### ISSUE TITLE
Layout Block: Check row actions padding

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#1010]
@AlexGStapleton Is the following happening for you?

![block](https://user-images.githubusercontent.com/789159/196522642-ae3de274-ace5-4a9a-8fed-6a2ae0625567.jpg)

**Comment by AlexGStapleton** [comment]
I can't replicate this. Did this maybe happen while testing the Row Colors addon? I ask because if that addons colors were completely cleared this could occur - [here's a PR to completely remove the spacing if that happens](https://github.com/siteorigin/siteorigin-panels/pull/1012).
