### ISSUE TITLE
check If page uses pagebuilder

### ISSUE THREAD

**Issue by Jursdotme** [siteorigin/siteorigin-panels#102]
On a page using pagebuilder for posts i have a lot of old posts not using pagebuilder.

Is there a way to check if a page uses pagebuilder and show the title and date only for the posts not using pagebuilder?

**Comment by boquiabierto** [comment]
I think checking for post’s panels_data postmeta will do
```
function has_pagebuilder( $post_id = null ){
  global $post;
  if( !$post_id ){
    $post_id = $post->ID;
  }
  $panels_data = get_post_meta( $post_id, 'panels_data', false );
  if( !empty($panels_data) ){
    return true;
  }
}
```
Then use
```
<?php if ( !has_pagebuilder() ) : ?>
  <h1>Title only on posts build without PageBuilder</h1>
<?php endif; ?>
```

**Comment by richrd** [comment]
Nice, looks good! I think I might use this some time :+1:
