### ISSUE TITLE
Page builder for WordPress 6.1.1 not template compatible

### ISSUE THREAD

**Issue by ValentinGratz** [siteorigin/siteorigin-panels#1029]
Hello,
I wanted to use your plugin on the latest version of WordPress 6.1.1, except the templates are not displayed completely, if at all.

I tested with a template on my personal site, and I just had a red line that appeared.

I just tried again on a demo site with two templates, concerning the "gym" template, it remains in "Loading prebuilt layout" as you can see:

![msedge_KefY5bMBcF](https://user-images.githubusercontent.com/39189263/208851572-c91b7158-7ad9-4924-8dbd-dbaf28a850eb.gif)

I succeeded after two or three attempts.

On the other hand, it is not the only problem, to believe that the templates are not compatible any more, because I do not have all the template.

![msedge_GtdzpwYC4m](https://user-images.githubusercontent.com/39189263/208851738-f840a09f-9f60-41a6-af64-437960730e39.png)

![msedge_qzWdtXuMQE](https://user-images.githubusercontent.com/39189263/208851713-e9970003-a8de-4be4-9e86-6c1f8fa10754.gif)

Finally, here is how the editor is also sometimes displayed on WordPress:

![affichage vide](https://user-images.githubusercontent.com/39189263/208851813-8bcf9252-50b1-4a14-a321-3f09fef579bb.png)

The WordPress configuration used:

``
### wp-core ###

version: 6.1.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/veyebuhoha8949/web/linkbio.instawp.xyz/public_html
wordpress_size: 49.46 MB (51861559 bytes)
uploads_path: /home/veyebuhoha8949/web/linkbio.instawp.xyz/public_html/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /home/veyebuhoha8949/web/linkbio.instawp.xyz/public_html/wp-content/themes
themes_size: 12.35 MB (12951088 bytes)
plugins_path: /home/veyebuhoha8949/web/linkbio.instawp.xyz/public_html/wp-content/plugins
plugins_size: 1.63 MB (1705195 bytes)
database_size: 2.16 MB (2260992 bytes)
total_size: 65.59 MB (68778834 bytes)

### wp-active-theme ###

name: Twenty Twenty-Three (twentytwentythree)
version: 1.0
author: the WordPress team
author_website: https://wordpress.org
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, block-templates, widgets-block-editor
theme_path: /home/veyebuhoha8949/web/linkbio.instawp.xyz/public_html/wp-content/themes/twentytwentythree

### wp-themes-inactive (2) ###

Twenty Twenty-One: version: 1.7, author: the WordPress team
Twenty Twenty-Two: version: 1.3, author: the WordPress team

### wp-plugins-active (1) ###

Page Builder by SiteOrigin: version: 2.20.1, author: SiteOrigin

### wp-plugins-inactive (2) ###

Akismet Anti-Spam: version: 5.0.2, author: Automattic
Hello Dolly: version: 1.7.2, author: Matt Mullenweg

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.4.0-135-generic x86_64
httpd_software: Apache/2.4.54 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
php_version: 7.4.33 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.6.11-MariaDB-1:10.6.11+maria~ubu2004
client_version: mysqlnd 7.4.33
max_allowed_packet: 33554432
max_connections: 200

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/veyebuhoha8949/web/linkbio.instawp.xyz/public_html/wp-content
WP_PLUGIN_DIR: /home/veyebuhoha8949/web/linkbio.instawp.xyz/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 256M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

``

**Comment by AlexGStapleton** [comment]
Hi Valentin,

Sorry for the delay - somehow we missed this one. I've had a look at the provided information and you don't have the [SiteOrigin Widgets Bundle](https://wordpress.org/plugins/so-widgets-bundle/) installed. This plugin is heavily used by our Layout Directory and I suspect its absence is causing the import issues you're facing. I can confirm it's why the layout isn't appearing as expected.

Kind regards,
Alex

**Comment by ValentinGratz** [comment]
Thank you for your comeback.
What I find unfortunate is that you cannot "merge" the two extensions into one.

And then, that doesn't solve everything. I retested with the GYM theme as shown, and I only have the text parts like this: (instead of having the complete page).

![Capture web_5-1-2023_125612_ot-pursuit-huda instawp xyz](https://user-images.githubusercontent.com/39189263/210774911-705598bd-9376-4d9e-90b5-7a15fd761d5a.jpeg)

While on the builder it shows me all the parts, so is it to be completed (does the builder no longer provide the shapes or the images? )

![Capture web_5-1-2023_125753_ot-pursuit-huda instawp xyz](https://user-images.githubusercontent.com/39189263/210775226-38a76e2d-939b-4992-8f57-ef8a8734b650.jpeg)

**Comment by AlexGStapleton** [comment]
Hi Valentin,

By the looks of your screenshot, the Hero and Headline widgets aren't active. Saving the page should activate them automatically but if it doesn't, navigate to **Plugins > SiteOrigin Widgets** and activate them.

> What I find unfortunate is that you cannot "merge" the two extensions into one.
SiteOrigin Widgets Bundles is with and without Page Builder so merging these two plugins together would require certain users to have Page Builder present when they don't wish to use it.

Kind regards,
Alex

**Comment by ValentinGratz** [comment]
Hello,

I have both extensions enabled:
- Page Builder by SiteOrigin
- SiteOrigin Widgets Bundle

And when I try to edit one of the "Missing Widget'" parts in red (in the screenshot above) I get this error:

`The widget SiteOrigin_Widget_Hero_Widget is not available. Please try locate and install the missing plugin. Post on the support forums if you need help.
`

Out, I don't really see what other extension activated to solve this.
![msedge_WQMjNSzIB7](https://user-images.githubusercontent.com/39189263/211364446-4ed52abd-b7ff-42bc-b979-963c7ca54241.gif)

**Comment by AlexGStapleton** [comment]
Hi Valentin,

SiteOrigin Widgets Bundle allows you to enable and disable widgets selectively. Please navigate to **Plugins > SiteOrgin Widgets** and you'll be able to activate the Hero and Headline widgets. No further plugin installs are requried.

Kind regards,
Alex
