### ISSUE TITLE
Images Break Out of Container in FireFox 34

### ISSUE THREAD

**Issue by eddyerburgh** [siteorigin/siteorigin-panels#108]
Firefox ignores max-width:100%;

Fixed on my theme by adding 
img.wpb_single_image {
	width: 100%;
}

**Comment by gregpriday** [comment]
I wasn't aware of this. According to this [StackOverflow question](http://stackoverflow.com/questions/2923710/why-do-firefox-and-opera-ignore-max-width-inside-of-display-table-cell), the issue only comes up in an element with `display: table-cell`. Nothing from SiteOrigin should be adding this to any wrappers. Can you check if your theme is?

**Comment by eddyerburgh** [comment]
Thanks, it's from my theme.
