### ISSUE TITLE
Checkbox by default checked

### ISSUE THREAD

**Issue by NickHeurter** [siteorigin/siteorigin-panels#109]
I'm wondering if it's possible to make a checkbox checked by default. I've added the following field to the widget styling:

    $fields['responsive_tablet'] = array(
        'type' => 'checkbox',
        'label' => __('Tablet', 'siteorigin-panels'),
        'group' => 'dynamic_display',
        'priority' => 21,
        'default' => true,
    );

But it's not checked by default. So it seems like the 'default' => true, option isn't working.

**Comment by gregpriday** [comment]
So it turns out we weren't actually supporting default values in style fields. I've added support for this though. It'll be available in the next update.

https://github.com/siteorigin/siteorigin-panels/commit/6b27707fcdccf7956a2b80fe4096099974d9f1c6

**Comment by NickHeurter** [comment]
Thanks a lot Greg! Works great.
