### ISSUE TITLE
Bootstrap 3 Intergation

### ISSUE THREAD

**Issue by thongta** [siteorigin/siteorigin-panels#11]
Hi Greg,

I'm a theme developer who engaged with Twitter Bootstrap 3 (BS3) due to business issues.
Your SO PB is awesome, it would be more awesome if we find a way to integrate it with BS3.

I understand that we can use both SO & BS3 separately at the same time, but that will make some unnecessary CSS/JS resources. Please think about it and if you need some helps, I can give effort to sort it out.

Cheers,
Thong

**Comment by gregpriday** [comment]
Hi Thong

Similar idea applies to this issue as your other one. Hopefully someone in the Page Builder community will create this as a plugin. I'd be more than happy to help them out :)

https://github.com/siteorigin/siteorigin-panels/issues/13
