### ISSUE TITLE
Use Active Callback

### ISSUE THREAD

**Issue by NickHeurter** [siteorigin/siteorigin-panels#110]
I was wondering if it's possible to add a active_callback to a field. I want the field 'responsive_desktop' only to be displayed when the checkbox of field 'display_always' is unchecked. Is that possible? I've tried the following:

```
$fields['display_always'] = array(
    'name' => __('Display always', 'siteorigin-panels'),
    'type' => 'checkbox',
    'group' => 'dynamic_display',
    'description' => __('Always show block', 'siteorigin-panels'),
    'priority' => 5,
    'default' => true,
);

function always_callback( $fields ) {
    if ( $fields->manager->get_setting('display_always')->value() == '1' ) {
        return false;
    } else {
        return true;
    }
}

$fields['responsive_desktop'] = array(
    'name' => __('Responsive', 'siteorigin-panels'),
    'type' => 'checkbox',
    'label' => __('Desktop', 'siteorigin-panels'),
    'group' => 'dynamic_display',
    'priority' => 20,
    'active_callback' => 'always_callback',
);
```

**Comment by gregpriday** [comment]
I've implemented things like this in the past, but not for Page Builder row and widget style fields. In the widgets bundle we use something called [state emitters](https://siteorigin.com/docs/widgets-bundle/form-building/state-emitters/) - I'll see if I can get these working in Page Builder at some stage.

**Comment by NickHeurter** [comment]
That would be great @gregpriday, I noticed the [state emitters] (https://siteorigin.com/docs/widgets-bundle/form-building/state-emitters/) but found out this wasn't working. I hope you can get these working on row and widget style fields as well. Good luck!

**Comment by NickHeurter** [comment]
Hi @gregpriday, hope you are doing well. Do you've got any idea when you think this option will be available in the plugin?

**Comment by gregpriday** [comment]
Unfortunately I haven't quite been able to find the time for this feature yet. At least not going as far as implementing state emitters in Page Builder.

Something that we did before state emitters in the Widgets Bundle was write custom code for widgets that needed show/hide functionality. I'd imagine this would be possible at the moment in Page Builder style fields. Although it would be fairly complex to do though.

Sorry I don't have better news at the moment.

**Comment by AlexGStapleton** [comment]
It's now possible to indirectly do this using the [setup_style_fields event](https://github.com/siteorigin/siteorigin-panels/pull/916). It's not an active callback, but that event will allow you to set up events that'll allow you to effectively do the same thing. 

For example, if I had a checkbox field called `toggle_example` and another field called example, the following JS will `toggle_example` to control the visibility of the `example` field.

```
( function( $ ) {
	$( document ).on( 'setup_style_fields', function( e, view ) {
		var example = view.$el.find( '.so-field-example' );

		view.$el.find( '.so-field-toggle_example input[type="checkbox"]' ).on( 'change', function() {
			// If the toggle example field is checked, show the field.
			$( this ).is( ':checked' ) ? exampleField.show() : exampleField.hide();
		} ).trigger( 'change' );
} )( jQuery );
```

We would still like to introduce active callbacks but it's not something we currently have plans for. I'm going to close this for the time being, and we'll re-open it when it does.
