### ISSUE TITLE
TinyMCE shortcode button disappears

### ISSUE THREAD

**Issue by ehrig** [siteorigin/siteorigin-panels#112]
I am very much in love with the page builder, but for any post type I activate the page builder my TinyMCE shortcode dropdown button disappears. How to fix it? I can't use the page builder at all, if my shortcodes are not accissable via the TinyMCE dropdown button anymore, which works perfectly, without the page builder.

**Comment by braamgenis** [comment]
Hi @ehrig 

We've added support in the past for a couple of TinyMCE shortcode dropdown plugins, namely the WooCommerce shortcodes and WP Canvas Shortcodes. Please let us know which shortcodes plugin you're using and we'll see if we can add support for it.

**Comment by ehrig** [comment]
Thank you @braamgenis, but it's a custom built.

**Comment by gregpriday** [comment]
I've noticed quite a few plugins these days properly display their extra buttons without any compatibility code from our side. I'm not entirely sure what's changed, but maybe there's a more official way of registering these buttons now that makes them show up.

I'm going to close this issue for now. Unfortunately there's not much we can do in the way of adding support for custom plugins - but then again, maybe that's not necessary anymore. Which would be great news.
