### ISSUE TITLE
Request - Keeping the content when switching the editor mode

### ISSUE THREAD

**Issue by BeFiveINFO** [siteorigin/siteorigin-panels#113]
Please excuse me in advance to post a question that might be troublesome. And please forgive my approximate english. I am trying my best.

I am a WordPress theme developer who is trying to integrate your site origin page builder into our theme.

Is it possible for you to add an option (with php code) to allow the page content to be kept even if the editor mode is switched between Page Builder and WordPress default editor rather than trying to keep the entire content?

For example, when you have a brand new page added, you have a blank page. You write something, then you click on the "Page Builder" button, it switches to a blank page in the Page Builder mode without transferring any contents from the WordPress default editor. When you switch back again to the WordPress default, it shows the content before while keeping what you just edited in the Page Builder mode. This way user can retain both contents without destroying the layout or any other elements added in respective modes.

Thank you for your attention to this post in advance.

**Comment by braamgenis** [comment]
Hi @BeFiveINFO 

Page Builder already gives the user the option of keeping content when switching between the default editor and Page Builder. You should see an alert come up when switching between the two which asks whether you want to clear content or preserve it. Could you maybe give some more information on what you're trying to do? Maybe list your actions step by step and what you expect to see. Thanks!

**Comment by BeFiveINFO** [comment]
@braamgenis 

Thank you for a response!

> actions step by step and what you expect to see. 

Sorry but **now** I see why you have made it so.

If you let users to choose more choices at that point in switching the editor mode, it will inevitably become complicated not only to users but also developers. Rather than letting users have a few choices, it is less confusing to explicitly limit available choices and convenience.

For example, we currently have "keep content", "copy the content over" options when we switch the editing mode. Then adding "having different content data preserved for each editor mode" will obviously lead to even more questions asked by users / customers / clients like  "why can't I do that?" (it may be possible to do what the user wants but the users do not often think of making use of available options or the users do not often try to understand the prompt message) or "My content disappears! It doesn't work!". Besides maintaining the additional feature will add up more complexity to the plugin therefore burdens to maintainers and developers using the Page Builder.

I will instead think of writing FAQ: "Why can't I preserve the layout and widgets in switching between WordPress editor and Page Builder?"

Thank you for your attention and wish you a nice day.

**Comment by braamgenis** [comment]
Thanks for responding @BeFiveINFO 
We'll definitely look at adding that information to our docs.
Hope you have nice day too!
