### ISSUE TITLE
Row CSS Styles are duplicating

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-panels#118]
Edit > Row > Attributes > CSS Styles. Declarations added there are duplicated in the inline style tag. They are repeated.

**Comment by KevinTaron** [comment]
@gregpriday can't confirm that. Seems to be okay in my tests.

![single-inline](https://cloud.githubusercontent.com/assets/2236069/12167479/a067e4cc-b52c-11e5-9d81-70267bb56f94.png)

**Comment by gregpriday** [comment]
Thanks for checking @KevinTaron. @braamgenis also just confirmed this isn't an issue.

I copied this over from our old issue tracker, so not sure what the history was, but I'll close this for now.
