### ISSUE TITLE
Live Editor

### ISSUE THREAD

**Issue by egemenerd** [siteorigin/siteorigin-panels#12]
Hi,

Live editor is a great new feature but I think there is a bug. It is not waiting for "full" page load. For example; jQuery(window).load is not working properly. I mean if there is a slider or carousel etc. on the page and if it is triggered in a jQuery(window).load function, it simply doesn't work or it doesn't display correctly. Is there any solution for that?

**Comment by braamgenis** [comment]
Hi @egemenerd 

This issue appears to have been resolved. Please let us know if you still experience the problem and how we can reproduce it. Thanks!
