### ISSUE TITLE
Appearance > Home Page needs revision capabilities 

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#122]
SiteOrigin themes that add the Appearance > Home Page item are missing revisions that would be found if you edit the page via Pages > Home.

**Comment by gregpriday** [comment]
When that home interface is saved, we need to hack it to create a new revision for the page that it's using as the home page.

WordPress uses a custom post type as post revisions. It should be fairly easy to create a fake revision. We'd just need to add post meta `panels_data` to that and set the `post_content`. Once you're done, making changes in this appearance > Home Page interface should add revisions when you go to Edit as Page.
