### ISSUE TITLE
Add Jetpack Gallery widget support

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#123]
The Gallery Jetpack widget Add Media button doesn't work in PB. 

@gregpriday notes from FogBugz case
The JS for the gallery widget just isn't being enqueued. I'm going to change this task to encompass adding all Jetpack widget compatibility.

To get access to the JP Gallery widget, Tiled Galleries module must be activated.

**Comment by AlexGStapleton** [comment]
+1 Would love to see support for this introduced.

**Comment by gregpriday** [comment]
I gave it a fair shot, but there were a few issues that made it not possible. Maybe things have changed since last year, though.

**Comment by Misplon** [comment]
Gallery Widget (deprecated)
