### ISSUE TITLE
Page Builder widget forms not using in_widget_form

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-panels#124]
There's an action that gets called in the standard WordPress widgets interface that isn't being used when the widget forms are generated for Page Builder.

It should be easy enough to add support for [this action](https://developer.wordpress.org/reference/hooks/in_widget_form/).

The issue was reported on the SiteOrigin support forums. Lets try fix this up for Jeffrey.

https://siteorigin.com/thread/apply-in_widget_form-action-on-each-widgets/

**Comment by phpbits** [comment]
subscribed and I hope this will be added soon!

Thanks,
Jeffrey

**Comment by phpbits** [comment]
any news? Thanks!

**Comment by gregpriday** [comment]
We'll be sure to post here as soon as we're done or there's any news.

**Comment by jobil** [comment]
Looking forward to seeing this get implemented as well!

**Comment by phpbits** [comment]
at last :) Will check! Thank you very much ;)

**Comment by phpbits** [comment]
Any news on adding this changes to the .org update? Thanks!
