### ISSUE TITLE
SiteOrigin Design Suggestion! :)

### ISSUE THREAD

**Issue by Ansif** [siteorigin/siteorigin-panels#125]
Hi Everyone,

I've designed SiteOrigin Page Builder backend. Please let me know your thoughts to improve backend user interaction.

![visual-editor](https://cloud.githubusercontent.com/assets/5621180/11567026/129d163a-9a0b-11e5-8214-f31e0bd39d7f.png)

Current design is really looking old trend. Want to make changes so clean and concentrate on UX.

Regards,
Ansif

**Comment by gregpriday** [comment]
Hi Ansif

Thanks a really good looking design (reminds me a bit of the new Calypso design). For now, our main goal is to make Page Builder look as much like the default WordPress interface as possible. So if we make any design changes, it'll be about improving this consistency.

Perhaps we'll make a more Calypso-ish design in the future though :)

**Comment by badcat** [comment]
Hmm - I agree a bit of a refresh might be in order - however this feels a bit too Divi-ish? :)

Ansif, What does it look like when you have a more complex design?  Maybe all of the specific row and widget icons disappear until the user hovers over them?  How does it work on mobile?

**Comment by Ansif** [comment]
Thanks, @gregpriday and @badcat!

Yes, it's more like Calypso & Divi-ish look. But it's a common design format and standard. Now a days we can't make page builder without Duplicate, Delete, Add and Settings button. These all are core features. That's how design standards too. :)

We can able to design based on that side or top and bottom design alignments.

For a complex design : I just though if design looks in current trend like in other page builder. Then SiteOrigin page builder also looking good with comparing them in our market. :)

Thanks for this awesome plugin! :)

**Comment by KevinTaron** [comment]
@Ansif maybe you can create a plugin like "Pagebuilder Calypso Design Addon" or something like that. 
If someone want your design he can install it and its overrides the main design ;)
