### ISSUE TITLE
Add a bottom limit for mobile width

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#126]
Settings > Page Builder > Layout > Mobile Width needs a bottom limit of 480.

**Comment by braamgenis** [comment]
@Misplon We've since added a tablet layout and tablet width option in Page Builder settings. Does that cover this requirement?

**Comment by Misplon** [comment]
@braamgenis Sorry man, not sure how I missed this.

We can choose to leave this for now but the issue I raised is still there. You can set the breakpoint for tablet and desktop to 0 which means responsive behaviour won't work. Users can unknowingly do this, not fully understanding what this setting is for. We've seen it a lot with the Vantage mobile menu breakpoint setting. In my ideal world, these settings wouldn't let you set a value that can't work. But ya, I'm also fine to leave this for now if our settings field don't have this lower limit/range ability.

**Comment by braamgenis** [comment]
Ah, ok. Got it. Cool, yeah. Will leave the issue open and get to it as soon as there's a gap.
