### ISSUE TITLE
Widget Styles > Layout: more options

### ISSUE THREAD

**Issue by thongta** [siteorigin/siteorigin-panels#13]
In this area, we have only padding option for the whole 4 directions. In many cases, we will need different padding for each directions (top, right, bottom, left) and it would be much helpful to have 4 options for particular padding-directions.

**Comment by gregpriday** [comment]
Hi Thongta

I know I've already chatted to you via email about this, but I thought I'd just reply here too for public record. So with these sorts of additional features, we're trying to encourage developers to create plugins that introduce these features. Page Builder uses several hooks to implement row styles, so it would be easy enough to add a few custom row and widget styling options.

Our goal is to keep the core as light, powerful and developer friendly as possible.

If one of these plugins proves very popular, then, with your permision, we'll add it to the core of Page Builder.
