### ISSUE TITLE
WPML different langs in different folders stops PB widgets loading

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#130]
When using WPML navigate to WPML > Settings and see the section: Language URL format. Select the setting: Different languages in directories ((http://localhost/siteorigin/ - English, http://localhost/siteorigin/de/ - German)).

Now navigate to a page, switch to its translation (not the primary lang) and try add a widget. Dependencies aren't being loaded because of the new URL structure.

<img width="979" alt="wpml-diff-lang-in-folders" src="https://cloud.githubusercontent.com/assets/789159/11851616/6045a6a4-a3e8-11e5-9214-a2ea3644c077.png">

<img width="1424" alt="cant-find-dependencies" src="https://cloud.githubusercontent.com/assets/789159/11851621/64b818fc-a3e8-11e5-849e-43a6f8c8bcd9.png">

**Comment by gregpriday** [comment]
@Misplon - is this the issue that WPML recently fixed? Can we close this issue?

**Comment by AlexGStapleton** [comment]
Just tried this - I can't seem to replicate this. Although, this could be due to different overall settings.

**Comment by gregpriday** [comment]
It might have been resolved by WPML at some point. If we haven't seen any recent reports of this, then we can close.

**Comment by AlexGStapleton** [comment]
This is honestly the first time I've heard of this issue so I would say it's quite likely this has been fixed.
