### ISSUE TITLE
Auto oEmbed not working on custom post types in WP 4.4

### ISSUE THREAD

**Issue by richardtape** [siteorigin/siteorigin-panels#131]
This has taken a little while to track down. But;

On a fresh install of WP `4.3.1` with _just_ the SiteOrigin Panels plugin activated, default theme, with a very basic custom post type added to the functions.php auto oEmbeds work. i.e. pasting in a youTube/Vimeo/collegehumor url (both SSL and non-SSL) auto converts into the relevant media in the normal WordPress post editor. (I've added the new CPT to the list of post types that panels works on)

However, upon updating to `4.4`, there is no auto conversion in the custom post type. The URL remains as-is. Things work as expected in the normal post/page editor screens (with and without Panels plugin active)

Panels version: 2.2.2

I'm currently trying to track down exactly why this is happening, but coming up blank so far. If you've got any pointers, they'd be greatly appreciated.

**Comment by gregpriday** [comment]
Hi @richardtape - thanks for letting us know. I'll investigate this now.

**Comment by gregpriday** [comment]
I can't seem to recreate this on my side. Embeds appear to be working properly on my development install which is WordPress 4.4. I tested with the current version and version 2.2.2.

Are you still getting the issue?

**Comment by richardtape** [comment]
Happy holidays, @gregpriday 

Yes. How did you register your CPT? I just used a boilerplate example with all the defaults. I'm on multisite, but I doubt that would make a difference. I'm running no other plugins and 2015 theme.

**Comment by gregpriday** [comment]
Thanks @richardtape! To you too - I hope you've been taking a little time off :)

I just pasted in some really simple CPT registration code from the WordPress developer docs.

```php
function siteorigin_test_custom_post_type(){
	register_post_type( 'acme_product',
		array(
			'labels' => array(
				'name' => __( 'Products' ),
				'singular_name' => __( 'Product' )
			),
			'public' => true,
			'has_archive' => true,
		)
	);
}
add_action( 'init', 'siteorigin_test_custom_post_type' );
```

Can you give me a few of the oEmbed URLs you're testing with?

**Comment by gregpriday** [comment]
I'm going to close this for now. Unfortunately, I'm still unable to recreate it. @richardtape, if you or anyone else comes across this please feel free to post it It's possible that its been resolved with newer versions of WordPress.
