### ISSUE TITLE
Use JSON for bundling prebuilt layouts

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-panels#135]
Using JSON files instead of PHP based data dumps would be a far better experience for developers. Ideally we should give them a way to register prebuilt layouts and their associated JSON file.

https://siteorigin.com/docs/page-builder/bundling-prebuilt/

Adding the option to specify a screenshot to give a look and feel more similar to the prebuilt layouts directory would also be a good idea.

**Comment by gregpriday** [comment]
Resolved via https://github.com/siteorigin/siteorigin-panels/commit/0f8307d496c63cf9ba54618bf950f377a85b0ce5

**Comment by suganyaselvakumar** [comment]
how to register  JSON files to  a pre-built layout?

**Comment by suganyaselvakumar** [comment]
function mytheme_prebuilt_layouts($layouts){
    $layouts['home-page'] = array(
        // We'll add a title field
        'name' => __('Default Home', 'vantage'),    // Required
        'description' => __('Default Home Description', 'vantage'),    // Optional
        'screenshot' => plugin_dir_url( __FILE__ ) . 'images/layout-screenshot.png',    // Optional
        'filename' => get_template_directory()  . '/jsonfile.json', 
    );
    return $layouts;

}
add_filter('siteorigin_panels_prebuilt_layouts','mytheme_prebuilt_layouts');
