### ISSUE TITLE
Widget class of page builder and widget bundle plugin css conflict with theme widget css

### ISSUE THREAD

**Issue by amanjaswalia** [siteorigin/siteorigin-panels#136]
Widget class of page builder and widget bundle in plugin css conflict with theme widget css. Need to replace class widget with other name. Like : if in theme  class widget style with background and border that effect also with page builder dynamic style.

**Comment by gregpriday** [comment]
Hi @amanjaswalia, if the .widget class is conflicting with your theme then you can turn this off by navigating to `Settings > Page Builder`, under the `Widgets` tab, disable `Add Widget Class`.

**Comment by amanjaswalia** [comment]
Thanks for reply.
If i disable "Add Widget Class" Live Editor Not working. I think Live Editor works with .widget class on page builder.
