### ISSUE TITLE
Fix compatibility with Yoast SEO

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-panels#139]
Yoast SEO version 3.x doesn't work with Page Builder anymore. This probably has something to do with the way Yoast is live-updating scores.

**Comment by GDBillBlack** [comment]
Hi Greg,
Sorry if this is a dumb question, but is the intention to resolve the incompatibility with Yoast and will updates be posted to this page?

**Comment by gregpriday** [comment]
That's the intention yeah. @braamgenis has had a look at this already and he's been able to isolate what's causing the SEO scores to not update.

Unfortunately the issue is that Yoast doesn't update SEO scores when the TinyMCE editor is hidden, so this might be difficult for us to fix without some changes on their side.

@braamgenis: wouldn't one possibility be to temporarily show the TinyMCE editor just before we update it, then hide it again?

**Comment by GDBillBlack** [comment]
Thanks for that. Hope they’re amenable to a bit of cross-company cooperation. It’s good for everyone, after all.

**Comment by gregpriday** [comment]
Fixed in https://github.com/siteorigin/siteorigin-panels/commit/9cdb4f0c449f1e287894071e4f5cfc1cc470d838
