### ISSUE TITLE
Plugin conflict with Leaflet Maps Marker / Maps Marker Pro

### ISSUE THREAD

**Issue by robertharm** [siteorigin/siteorigin-panels#14]
Hi,

I am the developer of the mapping plugin Leaflet Maps Marker (https://wordpress.org/extend/plugins/leaflet-maps-marker/) respectively Maps Marker Pro (https://www.mapsmarker.com).
A user has now reported an incompatibility with your plugin "Page Builder by SiteOrigin" v2.0.3, which results in maps not being displayed when a corresponding shortcode is used within a visual editor widget for example.

I could reproduce this issue on my server and guess found the reason for this issue: maps from my plugins are created via shortcodes, for example [mapsmarker marker="1"]. When that shortcode is parsed on a standard wordpress installation, also javascript gets added to the footer of the page (you can change that to inline javascript too).

What I now found is that for me it seems that once you enter a shortcode within a visual editor widget for example, your plugin pre-processes that shortcode and saves the output too (which can be seen by clicking on "switch to editor" / "text tab" after the content has been saved once. Anyway due to my plugin architecture, the parsing of shortcodes must not proceed in advance but on runtime, otherwise the map will be broken (as you can see on https://www.mapsmarker.com/dev/pro/2014/12/28/page-builder-test/)

I first thought I could prevent the "pre-parsing" of shortcodes through your plugin via your option "Copy Content" which is disabled. Unfortunately this did not have any effect.

Can you please help me find a solution as I would really like to get my plugin working in combination with yours. The best solution in my view would be that you add an option which "disabled pre-processing of shortcodes". I would then check within my plugin if your plugin is active and the option is disabled and if not, display a warning message.

Looking forward to hearing from you!

Robert

**Comment by robertharm** [comment]
Hi guys & ladies,
would be great if anyone could have a look at this issue - had another customer reporting that kind of incompatibility.
thx,
Robert

**Comment by gregpriday** [comment]
Hi Robert

Sorry for the late reply here. Yeah, the reason we added pre processing to Page Builder is to give widgets the chance to enqueue their scripts and styles before the header is finished. This allowed them to place everything in the header instead of the footer.

Another solution I'm planning on implementing is to use some filters to make Page Builder support the is_active_widget function. That way widgets could handle the early enqueueing themselves. This does seem to be the more standard way.

Would Leaflet Maps Marker work properly if I removed this pre-processing?

**Comment by robertharm** [comment]
Hi Greg,

thanks for getting back to me!

Within my plugins you can choose if javascripts should be enqueued in footer (default) or header (fallback for theme incompatibilities for example) - anyway chaning this setting didnt have any effect on the incompatibility with siteorigin.

The issue for both plugins (leaflet-maps-marker and leaflet-maps-marker-pro) is definitely the pro-processing.

It would be great if that pre-processing could be removed; if this cannot be done generally I would suggest the following approach:

1. check if one of my plugins is active:
if (is_plugin_active('leaflet-maps-marker-pro/leaflet-maps-marker.php') || is_plugin_active('leaflet-maps-marker/leaflet-maps-marker.php')) {...}

2. do not pre-process if active and mapsmarker-shortcode is used:
$leaflet_options = get_option( 'leafletmapsmarker_options' );
$leaflet_shortcode = $leaflet_options['shortcode'];

3. skip that shortcode from preprocessing

hope that approach would work for you.

**Comment by gregpriday** [comment]
Let me play around with removing pre-processing entirely. Apart from the single usecase of allowing widgets to enqueue their scripts, pre-processing feels unncessasry and a little dirty to be honest.

**Comment by robertharm** [comment]
ok, let me know if you need any input from my side...

**Comment by gregpriday** [comment]
Just letting you know we've started working on this change. We're essentially making Page Builder content appear to be a sidebar, along with providing `get_option('widget_*');`. You can keep track on the feature branch https://github.com/siteorigin/siteorigin-panels/tree/feature-support-for-is_active_widget.

**Comment by gregpriday** [comment]
Hi Robert

We've mostly finished off this feature. Would it be possible for you to check if it's working with Leaflet Maps Marker?

https://github.com/siteorigin/siteorigin-panels/tree/feature-support-for-is_active_widget

We're going to try merge this feature in by 2.1.

**Comment by robertharm** [comment]
Hi Greg,
thanks for the update - looks good: https://www.mapsmarker.com/dev/pro/2015/03/05/1105/ (created a map within a visual editor widget and one within a text widget) - both are displaying correctly.
Looking forward to the v2.1 release so that I can remove the compatibility warning within my plugin.
best,
Robert

**Comment by gregpriday** [comment]
Oh wow, that's awesome. Thanks for checking! I'll keep you posted on when
this fix goes out into the wild.

On Thu, Mar 5, 2015 at 9:10 PM, Robert Harm <notifications@github.com>
wrote:

> Hi Greg,
> thanks for the update - looks good:
> https://www.mapsmarker.com/dev/pro/2015/03/05/1105/ (created a map within
> a visual editor widget and one within a text widget) - both are displaying
> correctly.
> Looking forward to the v2.1 release so that I can remove the compatibility
> warning within my plugin.
> best,
> Robert
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/siteorigin/siteorigin-panels/issues/14#issuecomment-77430138>
> .
>



-- 
I make free WordPress themes
http://siteorigin.com

**Comment by robertharm** [comment]
v2.1 fixes this issue - many thanks again!
