### ISSUE TITLE
siteorigin_panels_row_cell_classes doesn't pass it's corresponding panels_data

### ISSUE THREAD

**Issue by binaykshrestha** [siteorigin/siteorigin-panels#140]
Hi Site Origin, 

First off, thanks a lot for this amazing page builder. 
I'm trying to use it for my premium theme. And i want it to use it with Bootstrap skeleton. I can easily achieve this through the filters you have provided but the problem is "siteorigin_panels_row_cell_classes" doesn't pass it's corresponding "panels_data" like "siteorigin_panels_row_classes" does. It is the only thing holding me back.

Can you please fix this in your next update? 
$cell_classes = apply_filters( 'siteorigin_panels_row_cell_classes', array('panel-grid-cell', $col), $panels_data['grid_cells'][$i++]);
where $i is not the cell index for the current grid but the total cell count :smiley: 

OR can you let us override function "siteorigin_panels_render" using function_exists('siteorigin_panels_render') while defining the function.

I don't know if i make any sense but i really want to see this grow better! you guys are doing a great job! (Y)

Thanks
Binay

**Comment by gregpriday** [comment]
Hi Binay

Thanks for the awesome feedback and very glad to hear you're integrating
with your premium theme!

If you submit a pull request with the changes you need I'll take a look. If
you can't get around to that, I'll look at adding this in my next round of
Page Builder development.

**Comment by gregpriday** [comment]
We have since added this. Page Builder 2.5 will include a filter that's passed the cell data like this - https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/renderer.php#L631-L635
