### ISSUE TITLE
Add hook to inject HTML before and after cell loop

### ISSUE THREAD

**Issue by ernilambar** [siteorigin/siteorigin-panels#147]
I am proposing here to add hook to add HTML before and after cell loop while rendering panels in `siteorigin_panels_render` function.

There are hooks to add HTML content before and after row. But I want to wrap all cells with a div to apply extra styling. Adding those hooks will be great. I am submitting patch later.

Thanks

**Comment by ehrig** [comment]
I would like to see @ernilambar hooks merged into master. It is essential for any custom row style that needs to add some HTML. Current workaround I see is people moving their row style divs around the DOM via JavaScript, see https://wordpress.org/plugins/video-backgrounds-for-siteorigin-page-builder/ which is less than ideal. Please consider adding the proposed hook.

**Comment by gregpriday** [comment]
This has been added, we'll release it in version 2.5 - https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/renderer.php#L637

There are a few other hooks worth looking at too, as well as some cell specific style settings.
