### ISSUE TITLE
Repeater within repeater field

### ISSUE THREAD

**Issue by mesunil2010** [siteorigin/siteorigin-panels#153]
HI guys,

I am trying to do this in my new theme to give users more building capacity but it looks a bit buggy now. The fields when expanded didn't work well in admin section. 

Let me know if its possible and even if not, i think we should make this happen. It will open doors to lots of possibilities.

Thanks

**Comment by gregpriday** [comment]
Hi Sunil

Repeaters inside repeaters should definitely be possible. What seems to be
going wrong for you?
