### ISSUE TITLE
Investigate WP not updating word counts

### ISSUE THREAD

**Issue by braamgenis** [siteorigin/siteorigin-panels#154]
It's probably similar to the Yoast SEO compatibility issue we had [here](https://github.com/siteorigin/siteorigin-panels/issues/139). See report here:
https://wordpress.org/support/topic/content-in-widgets-is-invisuble-for-seo#post-7962626

**Comment by gregpriday** [comment]
@braamgenis Can you check if this is still an issue? The word counts seem to be working for me. Closing for now, feel free to reopen if this is still an issue.

**Comment by braamgenis** [comment]
Yeah, seems to be fixed. :+1:
