### ISSUE TITLE
Empty panel-grid-cell causes white space on mobile view

### ISSUE THREAD

**Issue by daviedR** [siteorigin/siteorigin-panels#156]
Hi guys,

I tried to create a row with 3 columns. I want my widget to be on the middle column (2nd column), while the 1st and 3rd columns are only used as a horizontal spacer. Here is my set:

1st column: 15% - empty widgets
2nd column: 15% - there is widget here
3rd column: 15% - empty widgets

Everything looks fine when on desktop view, but not in the mobile view. The 1st and 3rd columns will have default `margin-bottom` and also `min-height: 1em` from the `panel-grid-cell` class. This causes a lot of white space on the mobile view. Is there something we can do to just make the empty grid cell has zero height and no margin?

I can't use the `:empty` pseudo class on custom CSS to remove the `margin-bottom` and `min-height`, because the `panel-grid-cell` is not empty, it's filled with `&nbsp;`.

I think this should be by default or something, since this is definitely a common problem.

Regards

**Comment by daviedR** [comment]
Hi guys,

I found a workaround for this. We could replace the empty cell `&nbsp;` using the `siteorigin_panels_render` filter.

```
function edit_siteorigin_panels_render( $html, $post_id, $post ) {
	$html = str_replace( '&nbsp;</div>', '</div>', $html );

	return $html;
}
add_filter( 'siteorigin_panels_render', 'edit_siteorigin_panels_render', 10, 3 );
```

After that, we could use the `:empty` pseudo class on CSS to set the height to zero or remove the margin bottom, or anything you like.

Cheers!

**Comment by gregpriday** [comment]
I'll check if there's a way we can handle empty cells better on mobile. It should be possible.

**Comment by gregpriday** [comment]
We actually resolved this in https://github.com/siteorigin/siteorigin-panels/commit/40ce64f1403edd591f810ca85e138aa02911e459
