### ISSUE TITLE
Option to disable parallax on mobile

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-panels#158]
We've heard from users getting issues with parallax on mobile. It would be useful to give them the option to disable it for mobile devices.

**Comment by Wachu91** [comment]
+1

**Comment by AlexGStapleton** [comment]
@Misplon Do you want this setting added to the general tab above/under Limit Parallax Motion, or on the layouts tab? If the latter, where about's do you want to add the setting?

How do this sound?
Setting: Disable Background Parallax On Mobile
Description: Disable row/widget background parallax when browser is smaller than the mobile width.

**Comment by Misplon** [comment]
Let's add this setting below the Limit Parallax Motion setting. Good to go with the suggested label and description, thanks.
