### ISSUE TITLE
Give widget styles action the widget class so these can be widget specific

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-panels#159]
We're giving plugins a way to add and remove style fields, but there isn't a way for a specific widget to add or remove style fields only for itself.

https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/styles.php#L40

**Comment by RajeebTheGreat** [comment]
Hi @gregpriday ,

Any update on this? We are developing theme with SiteOrigin Page Builder and would love to see this being implemented. 

Let me know if I can help on this on any way.
Regards!

**Comment by ehrig** [comment]
I would love to see this hook added as well. Any update on this one Greg?
