### ISSUE TITLE
Row ID feature confusing

### ISSUE THREAD

**Issue by live-mesh** [siteorigin/siteorigin-panels#166]
Further to my query in https://github.com/siteorigin/siteorigin-panels/pull/146, I find it a little odd that Row class gets applied to a different element, row style element, than the Row Id that is panel-grid parent for this style wrapper. At present, the way things are implemented, targeting a row in CSS via ID is different than targeting via class when applying styles like padding, background color, image etc. The row ID implementation broke styles in our theme that targeted using ID rather than class since the width of the parent element with ID is smaller than the child element when using 'Full Width' layout option. 

I am not clear on exact benefit of pushing the ID up to the panel grid topmost element while retaining all other attributes at lower level at panel-row-style wrapper level. Again, this is specially a problem when the layout is Full Width where the panel-row-style wrapper element is stretched while the panel-grid parent is within a container.

**Comment by live-mesh** [comment]
For now, I am trying to implement another Row ID using the style wrapper code mentioned in https://github.com/siteorigin/siteorigin-panels/pull/146. It seems to better suited to our major need of using Row ID for styling. 

We use Row IDs mainly for two purposes - for navigation from top menu and more so for targeting specific elements in CSS(hence for styling and there lies the issue). With the current implementation of Row ID by the plugin, we cannot reliably target the row for styling specially when custom padding is set for this element using Custom CSS. For example, with custom padding set for the element using Row ID, the features of the plugin like background color, image etc. breaks since all of the custom styling from the Layout/Design tab in Row edit window is targeted at the style wrapper. And we cannot target child row style wrapper using the ID (#row-id .row-style-wrapper) in Custom CSS since the style wrapper itself may not be created or can get deleted depending on the styling changes by the user in Layout/Design tab. 

The Row ID was probably implemented the way it is at present probably to avoid creating a style wrapper element when the user sets the Row ID. But if someone wants to use ID mainly for styling purposes, it makes more sense to set the ID at style wrapper level than one level above.

**Comment by gregpriday** [comment]
You're definitely right here. I was under the assumption that the class field was applied to the main div, no the style wrapper. Adding the custom ID to the style wrapper is actually significantly easier. So maybe I just felt like making things difficult for myself ;)

I'll relook at this in the next few days. My guess is that I'll probably land up moving the ID to the style wrapper. I can't think of a good reason to keep it where it is.

**Comment by live-mesh** [comment]
Wow - that is nice to hear. It will keep things simple as it always been with your awesome page builder. Thanks!
