### ISSUE TITLE
Parallax feature using CSS3 attributes and properties

### ISSUE THREAD

**Issue by live-mesh** [siteorigin/siteorigin-panels#167]
The present parallax feature is implemented using background-position property which is a performance lag. Will help if the feature implemented using CSS3 transforms or similar properties for smoother performance to avoid browser stuttering when parallax background is set.

**Comment by gregpriday** [comment]
I'll take a look to see if [Stellar](http://markdalgleish.com/projects/stellar.js/) has an option to use CSS3 transforms instead. Having a quick look through the code, I think it might be possible.

Do you by any chance know of any Parallax libraries that might work better than Stellar?

**Comment by live-mesh** [comment]
Stellar is probably your best bet unless you want to go for custom implementation. For couple of earlier themes, we used Stellar for parallax and then moved to custom code in later themes based on our study of sites that had parallax with no visible performance lag. We use this to implement parallax backgrounds for Hero Image widget in our plugin. You may want to take a look just in case it fits your needs. So far, it has been working well for our users.

**Comment by gregpriday** [comment]
I was also thinking of a custom solution. I'll take a look at your implementation. I'm all for a lighter brighter solution.

**Comment by gregpriday** [comment]
We resolved this with a custom Parallax library - https://github.com/siteorigin/siteorigin-panels/commit/c9fa3af5aa623594abfabfd44de0abe16cea6410

If there are still performance issues, please let us know. So far, the new implementation seems to be working quite well.
