### ISSUE TITLE
Add a filter to allow theme authors to remove the Switch to Editor button. 

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#168]
Allow theme authors to remove the Switch to Editor button in Page Builder. They can hide it in a child theme function now. Let's see if we can't provide a way to remove the button entirely.

**Comment by braamgenis** [comment]
We've already got this reported in GH-119.

**Comment by gregpriday** [comment]
Aaah right, my bad @Misplon.

**Comment by Misplon** [comment]
Nice catch @braamgenis. Thanks :)

**Comment by braamgenis** [comment]
All good. :smile:
