### ISSUE TITLE
Feature widget padding causes responsive issue (overlap, and cut off)

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#171]
[Reported in this thread.](https://siteorigin.com/thread/siteorigin-features-responsiveness-issue/)

The issue is caused due to large amount of padding (25px - both left and right) being applied to .sow-features-feature even at lower resolutions.

**Comment by gregpriday** [comment]
@AlexGStapleton: shouldn't this be an issue on the Widgets Bundle? If so, you can close this issue and reopen it there.

**Comment by AlexGStapleton** [comment]
Yes. Due to it being early days at the time of posting I likely thought the features widget was in page builder. :(
