### ISSUE TITLE
Allow setting a bottom margin on the last row

### ISSUE THREAD

**Issue by jordif** [siteorigin/siteorigin-panels#177]
I understand the last row should not get a bottom margin by default. However, if a user wants to add a margin using the Row Styles dialog, I think they should be allowed to. Right now if you enter a value for the last row, it won't work.

I have solved this by editing the following line:

https://github.com/siteorigin/siteorigin-panels/blob/develop/siteorigin-panels.php#L723

And changing it to:

    if($gi != count($panels_data['grids'])-1 || !empty($grid['style']['bottom_margin'])){

Do you think it would make sense adding this in the next version of the Page Builder?

Thanks!

Jordi

**Comment by braamgenis** [comment]
Fixed in GH-178
