### ISSUE TITLE
Add option to settings to automactially make new posts / pages page builder powered.

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#179]
[Suggested in this thread](https://siteorigin.com/thread/automaticaly-start-visual-editor/#comment-91039)

It would be a good idea to add an option in the SiteOrigin Page Editor settings to automatically make all new posts / pages to be page builder powered pages rather than standard WordPress pages.

While the referenced thread might be seen more of a bug (as it should obviously copy said data to show the correct interface), this still would be a decent feature to add.

**Comment by gregpriday** [comment]
Yeah, worthwhile enhancement.

**Comment by AlexGStapleton** [comment]
I don't know the exact version that this was introduced in, but this has been introduced.

**WP Admin > Settings > Page Builder**. Open the **General** tab and tick **Default To Page Builder Interface**
