### ISSUE TITLE
Can i fork it?

### ISSUE THREAD

**Issue by alessandrotesoro** [siteorigin/siteorigin-panels#18]
Hello,

First of all congratulations on such amazing plugin. Not sure wether i should have left this message on the wordpress.org forum or here on github. I was wondering if it would be possible for me to fork your plugin in order to create my personalized version of it. I'm not looking to create a competitor plugin nor publicly making it available on wordpress.org, i'd like to change/remove/add a few things around to make it fit my niche. Obviously i'll leave copyright and licensing in place unmodified. 

Regards,
Alessandro.

**Comment by gregpriday** [comment]
Hi Alessandro

You are well within your rights to fork (and GitHub makes that really easy), but I'd always suggest going the plugin route. It would be much easier for you not having to maintain the entire codebase - especially security and WordPress compatibility updates.

You can always add any hooks and filters you need in Page Builder using pull requests and add all the niche functionality using your plugin.
