### ISSUE TITLE
Post Loop Widget: Add ability to define when the more link is inserted

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#181]
You should be able to input a number, for instance 250 words, to tell Page Builder when to cut the text.

**Comment by braamgenis** [comment]
@AlexGStapleton Not sure we want to be adding stuff to the legacy PB widgets anymore. Perhaps we can add something like this to WB?

**Comment by AlexGStapleton** [comment]
I would be okay with that.

**Comment by AlexGStapleton** [comment]
Closing as this isn't a PB issue, and it's been introduced in WB anyway.
