### ISSUE TITLE
Previewing content inside Page Builder content layout.

### ISSUE THREAD

**Issue by paaljoachim** [siteorigin/siteorigin-panels#182]
Hey

One thing I really dislike about all the Page Builder plugins I have seen is that the content pages all have these generic looking blocks not showing the content which resides inside.

![screen shot 2016-03-08 at 19 11 10](https://cloud.githubusercontent.com/assets/5323259/13611220/a61ea9ea-e561-11e5-95b9-331ff668ff95.png)

I have noticed more and more plugins add a preview of a shortcode inside the content creation area.
Here is an example from Caldera Forms.

![screen shot 2016-03-08 at 19 14 44](https://cloud.githubusercontent.com/assets/5323259/13611286/15a54396-e562-11e5-94d1-2e1a0d3fce9f.png)

It shows a preview image of the inserted form. Having previews of content blocks inside the content creation area would make the experience more visual. A lot better then the generic looking blocks.

In regards to the first screenshot: One would be able to see the content of the example page, what the search form looks like, what items are in the custom menu, what the 4 columns of post content looks like. It sure would be great for a visual guy like myself.

**Comment by gregpriday** [comment]
The main thing we need to do to get a more visual editing experience going is improving the live editor. I like the idea of keeping a simple block based view as the main admin, and a completely visual experience in the live editor.

I've been experimenting with it for a little while now. I've more or less been able to nail down how I'd like a more advanced visual editor to work, so this is definitely where I'll be spending the bulk of my future Page Builder development time.

**Comment by paaljoachim** [comment]
Block based content editor view <-> live visual editor view.

I am thinking that there needs to be somekind of tighter switch between the two views.

Glad to hear that the visual editor is being worked on. Let me know when you want some outside thoughts on the direction your heading.

**Comment by SteveS123** [comment]
The ability to add rows/widgets in the live editor would be nice too.

**Comment by gregpriday** [comment]
This is where we're working on it - https://github.com/siteorigin/siteorigin-panels/tree/feature/new-live-editor

**Comment by SteveS123** [comment]
Oh very nice!

**Comment by gregpriday** [comment]
So the way I went ahead and implemented the new live editor makes it a lot more powerful. From a development and user perspective, the Live Editor just reuses the main builder interface and implements the communication between the builder and the preview iframe.

In future we could implement a lot more editability in the preview frame. So sortable elements and inline editing of widgets. There are a lot of potential issues with doing this, so it would be a much larger development undertaking. Think 4-6 months of dev time, rather than the ~2 weeks it took to implement this live editor.

https://github.com/siteorigin/siteorigin-panels/commit/aa8f94c79fc15cb46d1c1e609cf9f50e5aaad9a8

**Comment by paaljoachim** [comment]
It kinda brings it into a Customizer feel kind of thing which I find very interesting!
- One thing that would be nice to add is a trash icon for dragging and dropping widgets the user wants to remove. (Of course the other option is to right click.)

I will check into how things are done with using Site Origin themes.
