### ISSUE TITLE
Live Editor: Add ability to open live editor without having to open edit page

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#186]
[Suggestion in this thread](https://siteorigin.com/thread/add-live-editor-button-to-admin-toolbar-or-to-theme-file/).

You should be able to open the live editor directly, via a WP Admin bar link or even a hover context link in the edit posts screen.

**Comment by gregpriday** [comment]
We have this now.

![screen shot 2017-01-16 at 6 06 12 pm](https://cloud.githubusercontent.com/assets/1126859/21990179/79f4fec6-dc16-11e6-96a0-943af7b4b2fb.png)
