### ISSUE TITLE
Headline Widget - h3 always centered

### ISSUE THREAD

**Issue by KevinTaron** [siteorigin/siteorigin-panels#187]
Hi Guys,

don't know if that is a bug or a feature but in the Headline Widget some of my customers found a problem for them. 
If the headline is h3 and they don't use the subheadline the subheadline style is still applied. 

For example: Headline is H3 with text align left. They don't use Subheadline therefore the style is not changed. 
On the website the Headline is centered because default style of subheadline is applied mit text-align center. 

![h3bug](https://cloud.githubusercontent.com/assets/2236069/13808575/1ab37db6-eb67-11e5-9e90-e30965206518.png)

I think if the subheadline is empty the style should not be added.

**headline.php**
From: 
`189: if ( ! empty( $instance['sub_headline'] )  ) {`

To this:
`189: if ( ! empty( $instance['sub_headline'] ) && ! empty( $instance['sub_headline']['text'] ) ) {`

Should i add an pull request for this?

**Comment by braamgenis** [comment]
Hi @KevinTaron The Headline widget is part of the [Widgets Bundle](https://github.com/siteorigin/so-widgets-bundle). If you [open the issue](https://github.com/siteorigin/so-widgets-bundle/issues/new) there, I'll take a look as soon as I get a chance. Thanks!

**Comment by KevinTaron** [comment]
Hi @braamgenis yeah I already made an pull request there.
