### ISSUE TITLE
Can't add Vantage widgets

### ISSUE THREAD

**Issue by braamgenis** [siteorigin/siteorigin-panels#188]
JS errors when trying to add any Vantage widgets in Page Builder in WordPress 4.5 beta
![js errors pb vantage](https://cloud.githubusercontent.com/assets/3822928/13841200/0ff0d404-ec30-11e5-95b3-75d85c316330.png)

**Comment by gregpriday** [comment]
This could be a sign of a larger issue of how Page Builder is getting values from forms. Well worth getting a fix done soon. Although the current [release schedule](https://make.wordpress.org/core/version-4-5-project-schedule/) points to April 12th as the release date.

**Comment by braamgenis** [comment]
I can't reproduce this anymore. :confused: Lowering priority until it comes up again...

**Comment by gregpriday** [comment]
I haven't been able to recreate this in my testing. Reckon we can close and reopen if it comes up again. Might have been solved in another commit somewhere along the line.
