### ISSUE TITLE
Image: h3.widget-title output and then the image title is output with a h2

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#189]
The image widget will output an h3 with a widget-title class attached which will always be empty, and then it'll output the image title with an h2. This happens with the title position setting set to before, and after. Here's a screenshot of the markup:

![capture](https://cloud.githubusercontent.com/assets/17275120/13870903/b3358bfe-ed2b-11e5-8ecd-740e7ea6d2cc.PNG)

**Comment by gregpriday** [comment]
Is this with the **Image (PB)** widget, or the one in the Widgets Bundle?

**Comment by AlexGStapleton** [comment]
Whoops. Must have misclicked. I had meant to post it on the Widgets Bundle. Sorry!

[Correct Issue](https://github.com/siteorigin/so-widgets-bundle/issues/147)
