### ISSUE TITLE
Change "Switch to Editor" to "Revert to Editor"

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#194]
The number one reason I've found that people switch to the editor for the visual view, or to input text is due to the text, "Switch to Editor". It's somewhat misleading. Sure, there's a prompt after the fact but if your English is poor and the translation for your native tongue is spotty you're likely to proceed due to the more complicated text prompt. It would make more sense to change the word "switch" to say, revert. That way it's more obvious. 

I also find it odd that the word is Switch as that gives me the impression that I can always switch back. I'm not going to lie, I might not read the prompt if I consider myself an experienced WordPress user.

**Comment by gregpriday** [comment]
Aaah yeah, Revert is definitely a lot better. Quick and easy fix.
