### ISSUE TITLE
Widget Styles: Add checkbox, "Disable On Mobile" or breakpoint

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#195]
I've seen a lot of support requests about having set margin or CSS for a really nice desktop experience and then turning around and saying that it looks like crap due to the large amount of margin / padding they've added. You should be able to either disable it on mobile or adjust it for mobile users.

**Comment by braamgenis** [comment]
@AlexGStapleton I'm not following. There are a few places where it's possible to set margins or padding. Where would the "Disable on mobile" checkbox go and what setting should it disable? Could you perhaps link to a few of the support requests?

**Comment by AlexGStapleton** [comment]
Awkwardly, I didn't know that previously the padding option in the layout group was applied directly to the widget styles. As such, I've retitled the issue to be a little more direct.

The first one that comes to mind is: [Recent Support thread for CSS Attribute](https://siteorigin.com/thread/can-you-add-conditional-css-to-siteorigin-widget-attributes-css-section/) I'll link them as I come across them - I'm looking for them now, however.

An example though would be, say, [this layout](https://u.teknik.io/sl1O5.json) (exported layout). I've added 250px of padding to add really nice spacing for the text and image. It looks great on desktop!
![0ae695de1-35](https://cloud.githubusercontent.com/assets/17275120/14078289/ed7dac2e-f537-11e5-9cdd-bec5112c9dc1.png)

On mobile it's unusable.
![81880441d-36](https://cloud.githubusercontent.com/assets/17275120/14078310/1b4a475c-f538-11e5-8225-d09636b33411.png)

Now, obviously, this might not be the best way to do this. However, this use case is very common and people likely don't even realise they've ruined their websites responsiveness by adding the padding.

Let me know if this helps, or you would like a different explanation.

**Comment by AlexGStapleton** [comment]
A decent alternative suggestion would be to have a mobile version for styling. Take the following for example:

![edd75391d-37](https://cloud.githubusercontent.com/assets/17275120/14078388/c973f99a-f538-11e5-9bc3-46d18888d2b4.png)

**Comment by braamgenis** [comment]
Ah, ok. Yeah, this is a larger issue we definitely need to look into.

**Comment by gregpriday** [comment]
Since resolved using mobile specific padding settings.
