### ISSUE TITLE
Parallax background display (widget and row) requires another row on page to be a layout other than standard for it to work

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#198]
The Parallax background display setting requires a row layout set to something other than standard for it to work.

The row layout setting can be the containing row or any row on the page - there just has to be any row on the page with a nonstandard layout. Without a row that matches the criterion, it acts as a static background. This happens in every theme I've tested and is an overall Page Builder issue.

[Export of test layout](https://u.teknik.io/gn515.json).

**Comment by AlexGStapleton** [comment]
Why does it have to log every single title edit... :confused:

**Comment by gregpriday** [comment]
Nicely spotted! We've seen people saying parallax doesn't work - this was probably the reason why.
