### ISSUE TITLE
Nesting Layout Builder widgets doesn't work in the Customizer.

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-panels#199]
In both Page Builder and the standard Widgets interface, it's possible to add a Layout Builder widget inside another Layout Builder widget. In the Customizer though, the second level Layout Builder isn't initialized, so it just displays the **Open Builder** button.

![screen shot 2016-04-01 at 4 34 01 pm](https://cloud.githubusercontent.com/assets/1126859/14210084/bf507f78-f827-11e5-9236-f52a4ee9d4e5.png)

**Comment by gregpriday** [comment]
@braamgenis: Do you remember how our compatibility with the Layout Builder in the customizer works. This line seems to be breaking things.

https://github.com/siteorigin/siteorigin-panels/blob/develop/widgets/basic.php#L96

Removing the check `!jQuery('body').hasClass('wp-customizer')` fixes this issue, but then messes with existing Layout Builder widgets. Which is why I imagine it's there.

Do you have any ideas on how to fix this?

**Comment by braamgenis** [comment]
Yeah, a quick look didn't bring anything to mind. I'll have to take a deeper dive to see what's going on, when I get a chance.

**Comment by gregpriday** [comment]
Took another look. Super simple fix. Just needed an extra check to always run when inside a dialog.
