### ISSUE TITLE
Feature request - row background image opacity

### ISSUE THREAD

**Issue by ghost** [siteorigin/siteorigin-panels#2]
Hi Greg,

An awesome feature would be to have an extra field in the Row & panel style design tab for image opacity. This way we can use both the background colour and background image, then add opacity to the image. What this will do is allow for a filter type darkened background for text to overlay. 

In this scenario I would set the background colour as black, overlay an image, then set the opacity of the image as 0.8, which gives me a perfect dark background for nice type panels.

**Comment by gregpriday** [comment]
Sorry to have left this hanging @cmwwebfx. I'm going through older issues and came across it.

@AlexGStapleton - how often do you feel like the need for this comes up in customer support? It'd probably take ~3 hours to implement, so just want to get an idea of whether it's worth the time investment.

**Comment by AlexGStapleton** [comment]
This sort of request has honestly only come up a handful of times. It's not an ideal solution, but I typically recommend users use the SiteOrigin Hero widget in situations where they want this as that widget includes this functionality.

**Comment by AlexGStapleton** [comment]
We've decided to close this pending support by WordPress support. When support is added we'll implement this in a future PB update.
