### ISSUE TITLE
Multiple CSS styles per widget

### ISSUE THREAD

**Issue by Aitchy13** [siteorigin/siteorigin-panels#20]
Hi,

I've just started using the latest version of PageBuilder (looks great - has really moved on!) and noticed you can now add your own CSS to a widget.

When adding the following styles on separate lines, only the bottom one actually applied:

border-top: 1px solid #000;
border-bottom: 4px solid #000;
padding-bottom: 20px;

Perhaps I'm using this text box incorrectly, but I assumed I could add a style on each row as the description for that field says "CSS Styles, given as one per row."

Changing `inc/default-styles.php` on line 291 to `preg_match_all('/(.+?):(.+?)(;|\n|$)/', $args['widget_css'], $matches);` seems to do the trick.

This RegEx should separate CSS styles by `;`, and/or a new line (with or without `;`).

I've done a bit of testing, but you may want to double check this yourselves!

Thanks
James

**Comment by btilm305** [comment]
I made a pull request for a fix: https://github.com/siteorigin/siteorigin-panels/pull/22

**Comment by btilm305** [comment]
#22 has been merged and this issue is fixed
