### ISSUE TITLE
Option to disable "Would you like to copy this editor's existing content to Page Builder?" prompt/action

### ISSUE THREAD

**Issue by SteveS123** [siteorigin/siteorigin-panels#200]
If you don't have the WP_Widget_Text widget, Black Studio's Visual Editor widget or SiteOrigin's own Visual Editor widget registered, this prompt shouldn't come up as clicking "Ok" will do nothing.

**Comment by Misplon** [comment]
Thanks @SteveS123. We do have an enhancement request open here: https://github.com/siteorigin/siteorigin-panels/issues/119. However, I think we'll still need to check out the case of  `WP_Widget_Text` being unregistered so I'll leave this open. Appreciate your input.

**Comment by SteveS123** [comment]
My issue isn't with the ability to switch back and forth between PB and the Visual editor, the issue is PB attempting to copy the Visual editor content into a widget that may not exist. Thanks @Misplon!

**Comment by Misplon** [comment]
Hey @SteveS123, so right now if you have no Text, SO Editor or Black Studio Editor installed and click on the Page Builder tab, Page Builder will copy your content into a SiteOrigin Editor and ask you to install the Widgets Bundle. Can you think of a better way to handle this? We don't want to delete the existing content if a user clicks on the Page Builder tab so this seems like the best way to handle the transfer.

**Comment by SteveS123** [comment]
Ah I see, I have the Recommended Widgets option disabled in my setup as I have a fairly closed system.  So I get the prompt to copy but not the recommended widget afterward.    It'd be nice to have the option to disable this copy prompt even if it means they lose their content, but I get the no recommended widgets + no text/black studio widget combo is going to be pretty rare use case.  :^)

**Comment by Misplon** [comment]
It's an edge case but thanks for letting us know. We'll do our best to introduce a filter in the future that would let you have control over the copy prompt. Thanks for the feedback.

**Comment by gregpriday** [comment]
Fixed this. So now we also have a filter that allows you to specify a custom text widget. You can see how it's used in https://github.com/siteorigin/siteorigin-panels/commit/858674cc4279e7b756bdb5f461c25f25c417ea89

If no text widget is found, then the content copy doesn't happen.
