### ISSUE TITLE
Measurement field not saving values after 2.4

### ISSUE THREAD

**Issue by Jursdotme** [siteorigin/siteorigin-panels#201]
We have and extension plugin that adds som e additional fields to the row stylings. After updating to 2.4 measurement fields wont save anymore.

```php
$fields['heightMax'] = array(
		'name' => __('Maximum height (Fixed height)', 'secondthought_pagebuilder_bundle'),
		'type' => 'measurement',
		'group' => 'height',
		'description' => __('Maximum height of the row when using fixed height.', 'secondthought_pagebuilder_bundle'),
		'priority' => 13,
		'multiple' => false,
	);
```

If i change the type to text it save just fine.

**Comment by gregpriday** [comment]
Hi @Jursdotme - can you check if 2.4.2 resolves the issue? If not, I'll get to fixing it.

**Comment by Jursdotme** [comment]
The problem is also there with 2.4.2.

**Comment by AlexGStapleton** [comment]
Hi Jursdotme,

Could you send us a copy of your plugin so we can try and get a better idea of your overall setup? If you would like to keep the plugin private you can email it to us directly at support@siteorigin.com.

**Comment by Jursdotme** [comment]
For the time being i have changed the fields to regular text fields so it's no rush from here. But you can download the plugin [here](https://github.com/Jursdotme/secondthought-pagebuilder-bundle/releases) (You are gonna want the 1.14.8 release).

The fields i can't save are on the row styles in a custom group called "height".

**Comment by fingerprintweb** [comment]
I have the same problem, after last update measurement fields save and works, but whene edit they lost data.

**Comment by gregpriday** [comment]
Thanks for the details @Jursdotme. I'll be looking into this today.

**Comment by gregpriday** [comment]
Fixed this up. Turns out it was a mistake in transitioning to Underscore.js functions. Thanks for letting us know about this @Jursdotme. Much appreciated. I'll try get the update out today.

**Comment by Jursdotme** [comment]
Glad to help. Thanks for the quick response!
