### ISSUE TITLE
rich text editor : <br> added to newline in shortcodes' returned html

### ISSUE THREAD

**Issue by crmb** [siteorigin/siteorigin-panels#202]
For exemple, i use the formidable form plugin,
When i put the [formidable id="X"] to get the form html code, the newlines of the resulting html get additionals `<br>`.

The `<br>` are not added if the "automaticaly add paragraph" is unticked.

**Comment by braamgenis** [comment]
@crmb Thanks for reporting! This is probably an issue with the SiteOrigin Editor widget in the [Widgets Bundle](https://github.com/siteorigin/so-widgets-bundle) so I've created the issue there.
