### ISSUE TITLE
Update Bundled Translation

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#205]
There are outdated translations included with the plugin when compared to the translation project. French being a prime example.

it would also be a good idea to include a pot file so people can easily create their out translations without issue.

**Comment by gregpriday** [comment]
@AlexGStapleton: I'd lean heavily towards using Glotpress. Maybe we should just remove all the outdated translations from Page Builder's languages folder and just rely on Glotpress translations. I haven't looked into this too much. Would it be viable?

**Comment by AlexGStapleton** [comment]
Extremely. The relevant po/mo files would be automatically downloaded so there's no reason to include them. Plus, they can be updated independently of the plugin itself.

The only potential downside is that we have to rely on the translation team a little bit more so we can't exactly fast track translations if the need ever arises.
