### ISSUE TITLE
Post Loop widget: no longer allowing comma separation in Additional field

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#208]
Within the Query Builder in the Post Loop widget you could previously insert an argument as follows:

`cat=3,4`

After saving the Post Loop widget is changing this argument as follows:

`cat=3&4`

Replacing the comma with an ampersand incorrectly changes the query.

**Comment by AlexGStapleton** [comment]
This issue also occurs in the post carousel widget. Could this issue be related to the fix for so-widgets-bundle/#124

**Comment by braamgenis** [comment]
Yep, was indeed related. PB uses the posts selector from WB when it's installed. Should be fixed with [this commit](https://github.com/siteorigin/so-widgets-bundle/commit/3925ac76b0f51eebcc46e8a917208b2e2aad3b8a).

**Comment by Misplon** [comment]
Super, thanks :)
