### ISSUE TITLE
Trying to extend SO Panels and I'm missing a filter

### ISSUE THREAD

**Issue by jnhghy** [siteorigin/siteorigin-panels#209]
In the backend on the Edit Row Popup I need to change the number limits of "Set row layout". At this point its values are limited between 1 and 8, I need a filter that will allow me to change this limits.

I'm proposing the change in siteorigin-panels/tpl/js-templates.php on line 272:

```
$cells_field = '<input type="number" min="1" max="8" name="cells"  class="so-row-field" value="2" />';
```

changed to:

```
$cells_field = apply_filters('siteorigin_panels_row_columns',  '<input type="number" min="1" max="8" name="cells"  class="so-row-field" value="2" />');
```

Better solutions can be developed but this would be a minimum that will cover this part of the template.
If a pull request would help please let me know.

Thank you.

**Comment by AlexGStapleton** [comment]
It does seem kind of weird to restrict it and not provide the ability to override it via a filter. Maybe submit a pull request and Greg will take a look at it.

**Comment by gregpriday** [comment]
This limitation isn't only enforced by the input field, but by the row dialog code too. I've increased the limitation to 12 and implemented the filter that @stefan-meier added (with a slightly different name).

The limitation is mainly in place to stop Page Builder from completely crashing if the user enters a huge number. So this is a sort of sane maximum. I can't see a reason why many people would need more than 12, and anything higher than this is likely to start breaking the interface.
