### ISSUE TITLE
Compatibility issues with Admin Page Framework

### ISSUE THREAD

**Issue by vladkucherov** [siteorigin/siteorigin-panels#21]
Hello guys :raised_hand:

I created some widgets using [Admin Page Framework](https://github.com/michaeluno/admin-page-framework)
Some of those widgets are using the WYSIWYG Editor, but if I open it using the page builder, the editor won't load.
![image](https://cloud.githubusercontent.com/assets/4151984/5854536/9d6aebe2-a237-11e4-8be7-1ed18b1d436e.png)

I opened a case in APF, and I was referred to you guys.
https://github.com/michaeluno/admin-page-framework/issues/184

Many thanks!
Vlad.

**Comment by gregpriday** [comment]
Hi Vlad

I know that Black Studio TinyMCE does a little bit of magic to get the Visual Editor widget working properly in Page Builder. I've written up some docs on getting widgets compatible with Page Builder, but I'm still not sure how they're actually doing it.

I'll check with the APF guys if they'd be willing to emulate what Black Studio are doing with their widget.
