### ISSUE TITLE
Prevent .so-panels-icon font family change

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#212]
[Found in this thread](https://siteorigin.com/thread/lost-tool-graphic-on-buttons-when-editing-pages-in-wordpress/#comment-93553).
I've come across a plugin ([WebMan Amplifier](https://wordpress.org/plugins/webman-amplifier/)) that changes the font family for the icon. It doesn't directly target it but it does "take over" via a generic CSS selector (being font). We should set the font-family to important to prevent this plugin and other plugins like it from changing the fonts on the icon.

Reference Image:
![](https://i.imgur.com/hCMde5u.png)
![fcdec634d-67](https://cloud.githubusercontent.com/assets/17275120/14626504/6b388438-062f-11e6-8593-823fce366eb4.png)

**Comment by braamgenis** [comment]
I don't know about this. I generally don't like using `!important` as it makes future customisations more difficult. Really it's kindof heavy-footed of fontello to just assume any class starting with `icon-` belongs to them. :confused: Will look into it more when there's time and try find a way for everyone to play together nicely, hopefully without using `!important`.

**Comment by gregpriday** [comment]
That is rather sweeping. `[class*="icon-"]` mean that any element containing `icon-` (not just starting with) will have the fontello font family. We're already doing-the-right-thing by prefixing our own icons with `so-panels-icon-`. Not much more we can do. This is a bug with that plugin.

It is slightly odd that our icons aren't winning on specificity though. Our selector with font family is `.siteorigin-panels-builder .so-panels-icon {`.
