### ISSUE TITLE
Post Loop widget: Reset query after loop to prevent conflicts

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#214]
User recommends we add `wp_reset_query()` after our loop to prevent conflicts with other plugins following the loop. Test case was with Advanced Custom Fields: https://siteorigin.com/thread/acf-breaking-after-using-blog-grid-widget/

**Comment by gregpriday** [comment]
We're doing this already https://github.com/siteorigin/siteorigin-panels/blob/develop/widgets/basic.php#L295
