### ISSUE TITLE
Optimizer theme Customizer field data loss

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#217]
User reporting that, when using the Optimizer theme, that Customize > Front Page > Front Page Widgets is experiencing data loss at regular intervals when using the Layout Builder widget.

Theme: https://wordpress.org/themes/optimizer/

![field](https://cloud.githubusercontent.com/assets/789159/14781722/877e9d58-0ae4-11e6-8866-7e25715ad99d.png)

**Comment by gregpriday** [comment]
@Misplon Is that a custom interface? It looks different to the standard WordPress Customizer. Also, have you been able to recreate this issue? Have we heard more reports of it since?

**Comment by Misplon** [comment]
From what I remember it was a customised Customizer interface. No further
reports that I know of. Can lower or close.

**Comment by gregpriday** [comment]
I tested this and I cant seem to recreate the data loss. This theme is using a very custom Customizer interface. It's possible they've fixed something on their side.
