### ISSUE TITLE
Prebuilt layout: Add Hook to disable Layout Directory (retain clone functionality)

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#219]
Use case: I wish to restrict the layout directory to CUSTOM USER ROLE and currently I'm unable to do so.

**Comment by folsomchris** [comment]
+1. There are also instances where we would want to replace the layout directory with our own, rather than having the "theme bundled" and "directory" which could cause user confusion.

**Comment by gregpriday** [comment]
I'll take a look at adding this.

**Comment by gregpriday** [comment]
I've added both filters. The one allows you to change the Layouts Directory to a custom URL. I don't think we'll have the time to document implementing a custom server any time soon, but the option is at least there.
