### ISSUE TITLE
Easily export a single row to insert into to another page

### ISSUE THREAD

**Issue by crmb** [siteorigin/siteorigin-panels#220]
The code of others visual builder i have tried where full of shortcodes. I didn't really liked this, that's why i am happy with siteorigin. 
However it was "easy" to copy a part of a manually created layout and paste it to another page.

If we could have some sort of "export this row"..

**Comment by gregpriday** [comment]
Copy paste is something I've wanted to add for quite a while now. It's something we'll definitely be implementing as we get more developers on board to help work on Page Builder. You can keep track of any progress in this area [here](https://github.com/siteorigin/siteorigin-panels/issues/5).
