### ISSUE TITLE
Row Style Background Image

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#222]
When the SiteOrigin Widgets Bundle is detected it should replace the Background Image Url with the typical [media field](https://siteorigin.com/docs/widgets-bundle/form-building/form-fields/#heading-media).

For backwards compatibility, we should show the Background Image URL when it is not empty.

**Comment by gregpriday** [comment]
This is actually a Vantage specific issue. Vantage had these row styles before they were in the core styles of Page Builder. Unfortunately, they had to stick around for legacy reasons. If you check out the style fields when using a default WordPress theme or a newer theme like North, it has a far nicer media field.

That said, the latest develop version of Vantage has a fix for this where new pages use the default style fields.

**Comment by AlexGStapleton** [comment]
Oh. Awkward. :S
