### ISSUE TITLE
If new post has empty title page builder contents will not be saved when post is created

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#225]
This is an odd one that I managed to find. Add a random widget to a new post, leave the title blank and save the page. Not only will the widget not be saved, the entire page itself won't be treated as if Page Builder mode was even entered.

**Comment by gregpriday** [comment]
Nice edge case here. I think the issue is Page Builder isn't even given the chance to save unless there is something in the title or post content. I came across something similar with the Live Editor. I fixed it by adding a temporary title - so we could do the same here.

**Comment by AlexGStapleton** [comment]
This no longer seems to happen. @gregpriday did you fix this? Maybe I'm just lucky. :confused:

**Comment by gregpriday** [comment]
I don't think I've looked at it yet. It's possible a change in WordPress 4.6 fixes this?

**Comment by AlexGStapleton** [comment]
No, I was using 4.5.3 when I posted my reply. It could have been fixed as a result of a different change. Guess we'll wait for someone else to try and replicate it (no rush) and if they're not able, we might as well close this.

**Comment by gregpriday** [comment]
Just double checked, and this is no longer an issue.
