### ISSUE TITLE
Shortcode not working: Career Portfolio

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#226]
The [Career Portfolio](https://wordpress.org/plugins/portfolio-wp/) (4k) shortcode no longer works on the frontend. When the shortcode is added to the editor widget (this issue also happens in the text widget), the preview displays the portfolio as expected but the frontend outputs nothing.

**Comment by gregpriday** [comment]
This might also have something to do with the sidebars emulation change. I'll fix that up as soon as I get a chance.

**Comment by braamgenis** [comment]
@AlexGStapleton This works for me now. Could you please confirm?

**Comment by AlexGStapleton** [comment]
I'm unable to replicate this issue either.
