### ISSUE TITLE
Rename Prebuilt button to just Layout

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#229]
it seems odd to label it as prebuilt as it gives the user the impression its sole purpose is for the layouts directory, which is obviously _not_ the case. Labelling it as layouts, in my opinion , would convey that it has multiple purposes. Thoughts?

**Comment by gregpriday** [comment]
Yeah, I agree. We've definitely added a lot more functionality behind that button since we first introduced it.
