### ISSUE TITLE
add fields to widget edit not working 

### ISSUE THREAD

**Issue by sureshamk** [siteorigin/siteorigin-panels#23]
i try to append options to widget options but not affecting 
My code as follows 

function custom_Fields()
{
    $grid_aary = $b = array_combine(range(1, 12, 1), range(1, 12, 1));
    $fields['r-mobile'] = array(
        'name' => __('Mobile grid width out of 12', 'siteorigin-panels'),
        'type' => 'select',
        'group' => 'responsive',
        'options' => $grid_aary,
        'description' => __('Coulm Width', 'siteorigin-panels'),
        'priority' => 16,
    );
    // echo 1;
    return $fields;
}
if (has_filter('siteorigin_panels_widget_style_fields')) {
    apply_filters('siteorigin_panels_widget_style_fields', array('SiteOrigin_Panels_Default_Styling', 'widget_style_fields'), 'custom_Fields', 100);
}

**Comment by gregpriday** [comment]
Hi sureshamk

For help with these sorts of things you can take a look at our documentation and post on our support forum.

https://siteorigin.com/docs/page-builder/
https://siteorigin.com/thread/
