### ISSUE TITLE
UX: Row Ratio should be detected and displayed

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#230]
[Reference thread](https://siteorigin.com/thread/row-column-ratio-select-box/)

Set a row ratio outside of the default even. Save the page and then open the row you just adjusted. The row ratio will not be selected and it'll be "set" as even.

Set a row ratio outside of the default even. Reopen the row, and it'll display the previously selected ratio.

This could cause confusion and should be corrected if possible.

**Comment by gregpriday** [comment]
Agreed. I know it's caused a lot of confusion for people in the past.

**Comment by gregpriday** [comment]
Lowering priority slightly. This is more of a nice to have than a strict requirement.
