### ISSUE TITLE
Ability to disable "Revert to Editor" button via filter

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#233]
[Suggested in this thread](https://siteorigin.com/thread/add-ability-to-turn-off-revert-to-editor-link/#comment-95372)

It would be a good idea to allow web designers the ability to disable the revert to editor link so that clients who ignore warnings don't complain about broken pages. :disappointed: The ideal method of doing this would be a filter as any Page Builder setting could be changed.

**Comment by Misplon** [comment]
Thanks @AlexGStapleton, we have this open, just need the time: 
https://github.com/siteorigin/siteorigin-panels/issues/119
Definitely something we'd like to see.

**Comment by AlexGStapleton** [comment]
Oh... I have no idea how I missed that. :confused: Sorry about that!

**Comment by Misplon** [comment]
All good man, I only knew about #119 because I logged a duplicate myself earlier this year.

**Comment by gregpriday** [comment]
I've actually implemented something like this in the last update. I'll comment on #119 though.
