### ISSUE TITLE
Implement a JavaScript Solution to allow for equal column heights

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#234]
[Suggested in this thread](https://siteorigin.com/thread/vote-for-adding-equal-height-function-to-row-settings/)
This is a common support request and I think it would be a good idea to implement something in the base version. Obviously, doing this with CSS is a massive pain but with JavaScript, it'll automate and make it pretty easy for users. A quick Google search reveals there's a number of libraries out there that we could use if we don't want to take the custom route.

References:
[Equal Height Columns](https://wordpress.org/plugins/equal-height-columns/) ([source](https://github.com/MIGHTYminnow/equal-height-columns/blob/master/public/js/equal-height-columns-public.js))

**Comment by gregpriday** [comment]
Yeah, this would be easy enough to implement. We could add something to [styling.js](https://github.com/siteorigin/siteorigin-panels/blob/develop/js/styling.js).

**Comment by KevinTaron** [comment]
Yeah would love that feature but I would prefer a non Javascript Solution.
CSS with flexbox should render faster and is supported in all browsers.
http://caniuse.com/#feat=flexbox

**Comment by AlexGStapleton** [comment]
Flexbox is nice and I like it, but I've found it can be very unreliable on mobile devices. :(

**Comment by gregpriday** [comment]
We've implemented this using Flexbox. It'll be available in the Page Builder 2.5 update.
