### ISSUE TITLE
Row padding in default settings 

### ISSUE THREAD

**Issue by Pigrecolab** [siteorigin/siteorigin-panels#235]
If possible (I think so...), it would be good to have the row padding in default settings, so I can override it in my theme for all the future row...

**Comment by gregpriday** [comment]
There is currently an option to set the row padding on a row by row basis.

In your theme, you could use the `siteorigin_panels_row_attributes` filter to make changes to the default HTML attributes and add any padding you need. This is a slightly more complex route to take, though.
