### ISSUE TITLE
Compatibility issue with facetwp and Sidebar Emulation

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#236]
Our sidebar emulation functionality prevents [FacetWP](https://facetwp.com/) from working as expected. It fails at the register_widgets() point due to the usage of add_query_arg( false, false );

A workaround solution to this would be to have a hook added that would allow the user to disable sidebar emulation.  Obviously this isn't ideal for the average user but for an experienced user who is aware of the risks and the downsides of doing so might seem worth it.

**Comment by gregpriday** [comment]
A few widgets/plugins had issues that came up with a recent change I made to sidebar emulation. I might look at undoing that change.

Is this particular issue specific to the latest Page Builder update, or does it cause problems with older versions too?

**Comment by AlexGStapleton** [comment]
I'll need to run a few more tests to identify what versions are affected by this issue - I'll do them in the morning. It should be noted that [The Events Calendar](https://wordpress.org/plugins/the-events-calendar/) is apparently affected by [this issue](https://siteorigin.com/thread/page-builder-plugin-conflict-with-the-events-calendar/) also.

**Comment by gregpriday** [comment]
@AlexGStapleton: is this issue still an issue? If it is, I'll take a look at it, or we can just suggest users of those plugins disable sidebar emulation.

**Comment by AlexGStapleton** [comment]
I'm unsure about facetwp but The Events Calendar works now. I would presume it works now without issue.
