### ISSUE TITLE
Inclusion in theme

### ISSUE THREAD

**Issue by baljindersingh88** [siteorigin/siteorigin-panels#237]
Hi Can i include it in my theme(it's a free theme) ?

**Comment by Misplon** [comment]
@baljindersingh88 Thanks for your interest. We're constantly improving and updating Page Builder so we'd recommend you use a plugin like TGM to suggest users install Page Builder, that way they'll always have the most up to date version.

If you're interested, our developer docs are here: https://siteorigin.com/docs/page-builder/.

**Comment by baljindersingh88** [comment]
Great So quick response.
Keep up the good Job

**Comment by Misplon** [comment]
For sure :) All the best with your theme development.
