### ISSUE TITLE
Row Design: Add column background and border design settings

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#238]
You should be able to specify the column background and border via the row styles sidebar. Obviously setting the background or border via widget is fine but if you have multiple widgets it can look rather messy. This will also remove a lot of extra "CSS" work that has to be done for certain layouts specifically for column designs.

**Comment by gregpriday** [comment]
This is actually something I've wanted to add. I just can't figure out where it should go. We could make use of contextual menus to add column styling, without clogging up the interface too much.

It'll be a useful option, but it's surprisingly challenging to implement.

**Comment by AlexGStapleton** [comment]
Hm. I don't think a context menu should be the only method of handling this. Typically from what I've seen, very few people are actually aware of the context menus in SiteOrigin Page Builder.

#98 with a contextual option (as in more of a drop down, or settings group - inside the layout settings group) would be a good solution in my opinion as it takes up little room and is very visual. Hm, then again... yeah you're right, there's no clear-cut method of doing this.

**Comment by AlexGStapleton** [comment]
This has been introduced.
