### ISSUE TITLE
Layout options in Layout Builder Widget doesn't work

### ISSUE THREAD

**Issue by thongta** [siteorigin/siteorigin-panels#24]
The subject says it all :)

This is a major bug, please fix asap.

**Comment by primozcigler** [comment]
It works for me.

It would be good for authors if you provide some additional information. Otherwise use their [official support](https://siteorigin.com/thread/), not issues.

**Comment by gregpriday** [comment]
I can also confirm that the layout options are working in the Layout widget. Are there any specific options that aren't working for you? I haven't double checked all of them.

This might be a theme specific issue, in which case we'll be able to help you out on our support forums like Primoz said.
