### ISSUE TITLE
Prevent Page Builder outputting from the_content when not intended

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#240]
Look at possible solutions to prevent PB outputting through additional `the_content` functions that might be  on a page.

**Comment by gregpriday** [comment]
In what situations are these additional calls to `the_content` being made? What are they being used to display?

**Comment by Misplon** [comment]
Most often plugin scenarios.

**Comment by Misplon** [comment]
https://github.com/moderntribe/the-events-calendar/search?utf8=%E2%9C%93&q=the_content

**Comment by gregpriday** [comment]
This should be resolved with https://github.com/siteorigin/siteorigin-panels/commit/3c487d8fe67b9a6e0390b6d3f7191fb932722adf
