### ISSUE TITLE
Post update but no update to layout builder widget that contains widgets with namespaces causes missing widget

### ISSUE THREAD

**Issue by jordant1089** [siteorigin/siteorigin-panels#242]
I am using widgets with class names that have namespaces and when I update a post but don't make changes to the layout builder widget I have on the post, the widgets become missing widgets with the backslashes removed from the class name. If a change is made to the layout builder, the update widgets don't go missing. 

I did a bit of digging and I think I found the problem. It looks like when the the layout builder is updated, it has $widget['panels_info']['raw'] = true. This causes the siteorigin_panels_process_raw_widgets function to trigger the update on the widget and in turn call the siteorigin_panels_process_raw_widgets function again where the backslashes of the widgets inside of the layout builder are escaped. 

When $widget['panels_info']['raw'] is not set, which it isn't when there is nothing changed inside the  widget, the update function doesn't fire and the class names don't get escaped. They are then saved to the database without backslashes and when the post is loaded, the widget it references can't be found.

**Comment by gregpriday** [comment]
Thanks for reporting this @jordant1089. Does the problem only come up with the Layout Widget, or are you getting it with Page Builder in general?

**Comment by jordant1089** [comment]
Yes, the problem is only with the Layout Widget.

**Comment by gregpriday** [comment]
Great. Thanks for reporting. I'll look into it.
