### ISSUE TITLE
How to use Page Builder with Timber library?

### ISSUE THREAD

**Issue by jared83** [siteorigin/siteorigin-panels#243]
Calling (Twig template engine):
`{{ post.content }}`
for example rendered a video player widget which is in a central column of a row just fine, but the grid layout itself hasn't been rendered at all. Instead the video appeared inside a paragraph `<p>` tag.
I am guessing that I need to call some Page Builder function from the functions.php file, as well as add, say, `page-builder.css` stylesheet into my `base.twig` template?
Need some help here. No clue how to render it all properly using [Timber](http://upstatement.com/timber/).
As I inspect `{{ post | json_encode }}` in a console I can see two fields/objects created by Page Builder: panels_data_preview and panels_data, but not sure what to do with them. Do I need to write a parser/renderer which will create the grid layout from those fields? I would've thought you guys have already written one.
Also it would be nice if I could get Page Builder to work with an arbitrary custom field that is of wysiwyg editor type.
Thank you for your time.
Jared

**Comment by gregpriday** [comment]
Hi Jared

So I assume that `{{ post.content }}` is just requesting the `$post->post_content` value. Page Builder needs to be passed through `the_content()` so that all the proper WordPress filters can be applied.

My suggestion here would be to ask the developers of Timber how you can request the post content in a way that it's passed through all the proper WordPress filters.

**Comment by jared83** [comment]
Well, Timber's docs say that `{{ post.content }}` calls `the_content()` function, as opposed to 
`{{ post.post_content }}` which is the raw text stored in the database.
See it [here](http://timber.github.io/timber/#wp-integration)

**Comment by gregpriday** [comment]
I'm not sure in that case. As long as your theme has `{{wp_head}}`, `{{ post.content }}` and `{{wp_footer}}` - it should be working properly. I haven't used Timber before though, so I don't know how it compiles everything. Perhaps asking them how a Timber compiled theme would be different from a default WordPress theme like Twenty Sixteen (where Page Builder works).
