### ISSUE TITLE
It should be more apparent that users shouldn't be using legacy widgets

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#248]
I've seen a number of issues and feature requests pop up recently about legacy widgets. For example, using the Embedded Video widget and having videos stretch (due to FitVids.js) undesirably or the limited functionality of said widget.

Here are a few possible solutions to prevent new usage of legacy widgets:
- Hide legacy widgets from newly created pages
- Display a warning when a legacy widget is added to make the user aware that this widget is a legacy widget and thus not recommended.
- If applicable, suggest a more modern SiteOrigin widget as a replacement.

**Comment by gregpriday** [comment]
Yeah, I've often seen issues with the legacy widgets too.

I'm thinking at some point we actually remove legacy widgets entirely. Maybe we could bundle them into a separate plugin with a big warning not to use it. Just having that extra step of installing a plugin will discourage most users from installing it.

This will be an option for users who have built sites using the legacy widgets and don't want to migrate.

**Comment by AlexGStapleton** [comment]
That's a good idea. However, the people who haven't already switched (to non-legacy widgets) are the same people who will complain when there site "suddenly breaks!!!" if they're removed from the core plugin. :(
