### ISSUE TITLE
Prebuilt layout import fails because of an em-dash

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#249]
If a prebuilt layout’s cell contains an em-dash (a long dash character) it hangs when trying to apply a prebuilt layout to the page.

When this error happens, JavaScript console shows the following error:

`TypeError: e is null
[7]</t.exports<.loadSelectedLayout/<()
 siteorigin-panels-24.min.js:1
bound ()
 self-hosted:756
n.Callbacks/i()
 jquery.js:2
n.Callbacks/j.fireWith()
 jquery.js:2
y()
 jquery.js:4
.send/c()`

Full report and steps to recreate here: https://siteorigin.com/thread/prebuilt-layout-import-fails-because-of-an-em-dash/#comment-97206

**Comment by gregpriday** [comment]
@Misplon I don't seem to be getting the same issue. Can you recreate this?

**Comment by Misplon** [comment]
I didn't check at the time due to a backlog I was working on. If you can re-create then I'm happy to leave this for the moment. Cool?

**Comment by gregpriday** [comment]
Closing this issue for now. I can't seem to recreate. If its reported again, try get hold of the users layout JSON file so I can test.
