### ISSUE TITLE
CSS styles not applied correctly ??

### ISSUE THREAD

**Issue by SatishGandham** [siteorigin/siteorigin-panels#25]
I applied the following styles
```
background-position:100% 50%;
background-repeat:no-repeat;
background-size:50% 100%;
background-position:100% 50%
background-repeat:no-repeat
background-size:50% 100%
```
Your preg_match_all  `'/(.+?):(.+?);?$/'` is only capturing the last value

```
array (size=3)
  0 => 
    array (size=1)
      0 => string 'background-size:50% 100%' (length=24)
  1 => 
    array (size=1)
      0 => string 'background-size' (length=15)
  2 => 
    array (size=1)
      0 => string '50% 100%' (length=8)
```

Where as this matches the first three lines. `'/(.+):(.+);/'`

Is this really an issue or am I missing something here?

Also the above CSS is treated as a single string, so the $ sign has to be removed from regex

**Comment by gregpriday** [comment]
Thanks for the report Satish. This is currently fixed in the development branch. We'll be pushing an update soon.

https://github.com/siteorigin/siteorigin-panels/commit/09692467fe02e5d6d520b646b3e6e3173e73a3c7
