### ISSUE TITLE
Adding `widget_update_callback`

### ISSUE THREAD

**Issue by venkatraj** [siteorigin/siteorigin-panels#251]
Hello Greg Priday,

First of all thank you for this great plugin, I'm using this with all my themes.
It seems that when saving widgets in page builder, the `widget_update_callback` filter has not been applied. So, when i extend widgets using `in_widget_form` and `widget_update_callback` filters, the former works (extra fields renders), but latter fails (field value is not save)/

**Comment by gregpriday** [comment]
Hi @venkatraj 

We have an open issue for this at the moment. You can follow it there.

https://github.com/siteorigin/siteorigin-panels/issues/207

If you can, please post a link to your theme, as well as how I'd test your functionality. I'll use that in my testing.
