### ISSUE TITLE
Consider adding a row title option

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#254]
Consider adding a row title field. This has been coming up a fair bit. At the moment users are having to work around this using the Layout Builder and a Text widget or similar solution.

**Comment by AlexGStapleton** [comment]
To clarify, is this visible on the frontend? Or is it like a row note (as in what it does - purely for reference)?

**Comment by Misplon** [comment]
This request would be for a visible row title. 

What you've mentioned @AlexGStapleton is another kettle of fish, something I know we've been asked before.

**Comment by gregpriday** [comment]
Although this feature might be useful, it means Page Builder will start edging into the realm of content, while it should be focused on layout.

With the title field would come people asking for title styling. Even just the basic styling offered by the Editor widget would add a huge number of fields.
