### ISSUE TITLE
String i18n: "Clone %s"

### ISSUE THREAD

**Issue by pedro-mendonca** [siteorigin/siteorigin-panels#256]
The post type (Post/Page) isn't translated as it gets it's name from the core, as `esc_html( ucfirst( $post_type ) )` is not a Page Builder string.
https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/admin-actions.php#L114

The result is a multilanguage sentence "Clone Post" or "Clone Page".

**Comment by gregpriday** [comment]
Well spotted @pedro-mendonca - sorry for not fixing this up sooner. The translation will be up to date in the 2.5 update of Page Builder.
