### ISSUE TITLE
Crayon Syntax Highlighter: Doesn't work on Page Builder pages

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#259]
I've received a number of reports (which I've been able to confirm) about the [Crayon Syntax Highlighter](https://wordpress.org/plugins/crayon-syntax-highlighter/) (50,000) not working with Page Builder widgets. I suspect it relates to how we handle data and this seems to be a long-standing issue.

Basically, the highlighter won't show no matter what. Something that works in a normal post, won't for a Page Builder powered post.

**Comment by lijubjohn** [comment]
Is there any alternative for this ?

**Comment by gregpriday** [comment]
This might work with the new caching option - which maintains shortcodes and runs its filter earlier. This will be coming out in the 2.5 release.

**Comment by tskamath** [comment]
Guys,  Crayon Syntax Highlighter is very important plugin for many of us who post codes, Its been 2 Years now, no fixes. really disappointing.

**Comment by gregpriday** [comment]
At the moment, it seems like Crayon Syntax Highlighter isn't being maintained.

<img width="981" alt="screenshot 2019-02-10 at 22 39 34" src="https://user-images.githubusercontent.com/1126859/52539279-e4dafa80-2d84-11e9-874c-9a2043355116.png">

There are plenty of alternative syntax highlighters that should be compatible with Page Builder. This is a good option - https://wordpress.org/plugins/syntaxhighlighter/
