### ISSUE TITLE
Margin Bottom (Row Setting): negative values aren't possible

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#260]
The margin bottom field doesn't allow for the value to be negative. This was apparently allowed in this commit d481c91410274b070e7ec23f548748169abb76d3 but I've heard reports (and I've been able to replicate it) that this doesn't seem to be the case.

**Comment by gregpriday** [comment]
Okay, think I finally added this properly now. Tested and it seems to be working.
