### ISSUE TITLE
Full Width Stretch: Only apply negative numbers

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#262]
@Misplon came across a website where a user was experiencing a white gap at the side of their website at certain resolutions ([slack](https://siteorigin.slack.com/archives/support/p1469039225000030)). This issue was caused by the full width stretched margins becoming positive and was resolved by disabling them (setting it to 0) once it hit that point. To prevent this from ever happening again it would be a good idea to introduce a check to ensure only negative numbers are applied.

**Comment by AlexGStapleton** [comment]
This doesn't actually seem to be a problem in the latest version.

**Comment by Misplon** [comment]
Sweet.
