### ISSUE TITLE
Page Builder editor by default

### ISSUE THREAD

**Issue by boluda** [siteorigin/siteorigin-panels#263]
Quick question: Can I set up the Page Builder editor as the default editor? Than would be nice in some cases. A checkbox on the options page, or even a filter would be great :)

![screen shot 2016-07-26 at 09 58 06](https://cloud.githubusercontent.com/assets/4599915/17130192/97dda222-5317-11e6-9e90-e71f7dcbc2b2.png)

**Comment by AlexGStapleton** [comment]
This is unfortunately not possible at the moment but it is a good idea imo.

**Comment by boluda** [comment]
Yeah! I emailed Greg and he told me to open an issue. Lets see if we can make this one. I have some clients who only use the PB editor, so this would be helpful :)

**Comment by gregpriday** [comment]
All done @boluda, thanks for the suggestion. This will be available in the 2.5 update.

**Comment by boluda** [comment]
Cool!
