### ISSUE TITLE
siteorigin_panels_process_raw_widgets update should reference old instance of widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#266]
[Reported in this thread](https://siteorigin.com/thread/process-raw-widgets-that-have-come-from-the-page-builder-front-end/)

The [widget update](https://github.com/siteorigin/siteorigin-panels/blame/develop/siteorigin-panels.php#L648) in siteorigin_panels_process_raw_widgets doesn't reference the previous widget data.

**Comment by AlexGStapleton** [comment]
Is [this line](https://github.com/siteorigin/siteorigin-panels/blame/develop/siteorigin-panels.php#L1422) a similar issue?

**Comment by LoloIrie** [comment]
Thanks Alex for your help on this issue, really appreciated !!! :)

I don't think it's a similar issue, but developpers can check it to be sure of course. Don't forget I'm a newbie and know very well the full plugin... ^^

**Comment by AlexGStapleton** [comment]
Wait, it's not? Maybe I'm misunderstanding your initial issue. The main issue you were having is that the old instance of the widget wasn't present, correct?

**Comment by LoloIrie** [comment]
Maybe I wrong and that's the same issue. Not sure about so I prefer a dev look at this point !

But yes you're right about the old instance of the widget, but only when you are saving again widget data. Updating info...

Let me explain shortly the workflow again to reproduce this issue:

1. Editor activate a widget using the siteorigin panel ans set all parameters including a parameter like "Only me can update the title of this widget".
2 Second editor wants to update widget parameters but he won't be able to update the 'title' field.

Hope it's clear now, but if now I can try to explain it again... :)

Best regards

**Comment by AlexGStapleton** [comment]
Okay so based on what you just said, you're running a check on widget save to check if a user has the permissions to edit said widget based on a local setting, correct? If so, that does sound like this issue as if the old instance is present you won't be able to reference the previous value.

**Comment by LoloIrie** [comment]
Correct ! :)

**Comment by LoloIrie** [comment]
Up !

**Comment by LoloIrie** [comment]
Up !

**Comment by gregpriday** [comment]
@LoloIrie please don't bump issues. We get to everything when we can.

I'll take a look at this and see what I can do.

**Comment by gregpriday** [comment]
Where ever possible, I've added actual old widget data based on the widget ID we happened to be storing. There are still a few instances where we won't pass in the actual old instance, like the Live Editor, but whenever data gets saved to the database, update functions are given the old instance if its available.

This will go out in the Page Builder 2.5 update.
