### ISSUE TITLE
Hide empty columns on mobile

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#267]
Hide empty columns on mobile so when they stack they don't cause unwanted vertical space.  Just need to add a special class to empty columns and then add `display:none` on mobile.

Recommend hiding only if Page Builder responsive setting is enabled. Check first.

**Comment by AlexGStapleton** [comment]
Ah damn. Forgot to log this. :sob:

**Comment by Misplon** [comment]
For sure!

**Comment by AlexGStapleton** [comment]
This was done in 2.4.11, right?

**Comment by gregpriday** [comment]
Yup! Done :)

**Comment by Misplon** [comment]
Yoh, epic! Small but super leveraged change.
