### ISSUE TITLE
WP 4.6 - Layouts directory returns no results

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#271]
- Fresh install of WP 4.6 RC1
- Only SiteOrigin Page Builder enabled

Reference GIF:
![](https://i.imgur.com/3SYjYKf.gif)

Request:
GET /siteorigin/wordpress5.6/wp-admin/admin-ajax.php?_panelsnonce=008e466d28&action=so_panels_layouts_query&search=&page=3&type=directory 

Response:
{"title":"Layouts Directory","items":[]}

**Comment by AlexGStapleton** [comment]
Can confirm this happens in RC2.

**Comment by gregpriday** [comment]
Resolved with https://github.com/siteorigin/siteorigin-panels/commit/af5d12db43e3a6f8bc65e8ac8fe105452a13a640
