### ISSUE TITLE
When deleting a Layout Builder widget, the inner widgets delete as well.

### ISSUE THREAD

**Issue by rdytogokev** [siteorigin/siteorigin-panels#272]
# Prerequisites:
- WordPress 4.5.3
- SiteOrigin PageBuilder 2.4.10
- SiteOrigin Widget Bundle 1.6.4
# Steps to reproduce:
1. Create **new page** in WordPress
2. Switch to **PageBuilder**
3. Click **"Add Widget"**
4. Select **"Layout Builder"** widget
5. Click the Layout Builder widget's **"Edit"** link
6. From the Layout Builder's window dialog, click **"Add Widget"**
7. Select a **"SiteOrigin Editor"** widget
8. Click the SiteOrigin Editor widget's **"Edit"** link
9. From the SiteOrigin Editor's window dialog, **type some text**. (Example: "Text I do not want to lose")
10. Click **"Done"**
11. Click **"Done"**
12. Click the Layout Builder widget's **"Delete"** link
# Issue:

This is where the issue appears. The SiteOrigin Editor widget located inside the Layout Builder widget gets deleted as well. 
# Expectation:

My expectation is to have the inner widgets move out of the Layout Builder and into the row where the Layout builder was formerly located. I understand that they will not be arranged properly anymore, but I don't want to lose all the work I put into them.

Is this something we can get fixed? Maybe this calls for rethinking the "delete" button. Maybe there should be two delete buttons for Layout Builder widgets. One to delete the widget only and one to delete the widget and all the inner widgets.
# Video Walkthru:

I created a private YouTube screencast walking through this issue.
https://youtu.be/qDPJ8oh_uls

**Comment by gregpriday** [comment]
Sorry for the late reply here @rdytogokev. Yeah, this would be a really nice enhancement. The main issue is that even though the Layout Builder widget is bundled with Page Builder is bundled with Page Builder, it is an independent widget.

So far we've been able to keep Page Builder working without having any widget specific code in the main Backbone application. Ideally, I'd like to keep it this way. I would be open to giving widgets a way to register a deletion (and possibly insertion/move) handler and have the Layout Builder itself handle this move.

With the next release of Page Builder (2.5), we're adding a row copy/paste feature. This allows you to copy and paste rows from a Layout Builder widget, back into the main page. So this is a good work around until we can look at implementing something like this.

**Comment by rdytogokev** [comment]
Cool.  That helps. I appreciate your hard work on this project. Thanks.

**Comment by gregpriday** [comment]
Closing this issue because of the existing copy/paste feature. I also think changing the current behaviour at this late stage would be confusing for a lot of users.

For example, lets say you add a Layout Widget, then duplicate it a few times to check a specific design, then delete the duplicated Layout Widgets - you'll also be expected to delete the sub widgets one by one. This isn't a great experience.

Thanks for the suggestion though @rdytogokev. Sorry to have left it hanging for so long.
