### ISSUE TITLE
Cannot delete Icon on Button

### ISSUE THREAD

**Issue by badcat** [siteorigin/siteorigin-panels#274]
Once a user has chosen an Icon in the SiteOrigin Button, there's seemingly no way to delete the icon?  The only choice appears to be to recreate the button and not choose an icon.  Perhaps add a "clear" or none button here?
![button-icon](https://cloud.githubusercontent.com/assets/26096/17713170/76d3e74c-63c7-11e6-8a4f-9870aa5e6843.png)

Edit:
Hah - I figured out that you can "unselect" the same icon.  :(
Still...  it seems inconsistent with the UI to not have a way to clear it.

thanks.

**Comment by AlexGStapleton** [comment]
That's form field is actually in the SiteOrigin Widgets Bundle. It should be noted that [this has already been logged](https://github.com/siteorigin/so-widgets-bundle/issues/255) - It's just sadly just not high up on the priority list at the moment. :(

**Comment by badcat** [comment]
Hi Alex - sorry I did a search for "Button" before I posted   :(    Yup, Widgets.  It's increasingly easy for me to lose track of what's part of SO Panels core vs SO Widgets Bundle vs... Kinda wish the blue gear icon (seen when adding a widget) was also visible in the panel editor.  I guess that's something for a feature request.  thanks again!

**Comment by AlexGStapleton** [comment]
Don't worry about it mate - trust me, it happens to me often too. :smile: 

Awkwardly, that icon is an image based on the [dashicon generic icon](https://developer.wordpress.org/resource/dashicons/#admin-generic). Awkwardly, you can't select Dashicons so [I've logged that as a suggestion](https://github.com/siteorigin/so-widgets-bundle/issues/299).
