### ISSUE TITLE
Layout Export: Add ability to export images

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#278]
Users should be able to do a full export of a page which includes all media assets. This is to suggest that relying on third party images (read: external images) isn't always ideal. It works for our layout directory but it doesn't really work for a typical user.

It's quite a process to explain to a user how to move the images over manually and this will remove the need to do so.

**Comment by AlexGStapleton** [comment]
To clarify, an archive was the intention all along. Although if you wanted to stick with only the json export you could convert the images to base64 (although that doesn't seem like the best of ideas).

**Comment by gregpriday** [comment]
Yeah, this would be ideal. There are a lot of things to consider. Ideally, the import would have some concept of the original media field's attachment ID to prevent duplicate imports.

**Comment by Misplon** [comment]
We're closing this for the moment due to a lack of recent requests. Most media fields offer an external URL field, that's our recommendation at the moment.
