### ISSUE TITLE
Add new options to Row style panels

### ISSUE THREAD

**Issue by mimomedia** [siteorigin/siteorigin-panels#28]
Hi, congratulations for your great work. This is a great plugin. I was wondering if it is possible to add my own custom options to row style panels, let's say like a custom css classes dropdown where user can select some previously declared classes of a theme.

**Comment by mimothemes** [comment]
The perfect thjng would be to have the possibility to include a custom new panel with the theme specific options, can someone point me in the right direction.

Thank you very much

**Comment by mimothemes** [comment]
Done with this simple function:

if(function_exists('siteorigin_panels_init')):

function mm_panels_row_style_fields($fields) {

	$mm_behaviour = array(
            'parallax' => 'parallax',
            'fixed' => 'fixed',
            'static' => 'static'
            );
 
        return $fields;
}
add_filter('siteorigin_panels_row_style_fields', 'mm_panels_row_style_fields');
 
endif;

**Comment by mimothemes** [comment]
Hi, i need now to get this selected option and include it as a class in the row, is there any example i can use?

Thank you very much

**Comment by katart** [comment]
This worked for me:

```php
// Add Custom Class Options to SiteOrigin Rows
function custom_row_style_fields($fields) {
	$row_styles = array(
			'default-row-style' => 'Choose Style',
			'row-notification' => 'Notification'
		);
		
  $fields['row_styles'] = array(
  'name'        => __('Row Styles', 'siteorigin-panels'),
      'type'        => 'select',
	  'options' => $row_styles,
      'group'       => 'attributes',
      'description' => __('Choose a style option for this row of content', 'siteorigin-panels'),
      'priority'    => 1,
  );

  return $fields;
}

add_filter( 'siteorigin_panels_row_style_fields', 'custom_row_style_fields' );

function custom_row_style_attributes( $attributes, $args ) {
    if( $args['row_styles'] != 'default-row-style' ) {
        array_push($attributes['class'], $args['row_styles'] );
    }

    return $attributes;
}

add_filter('siteorigin_panels_row_style_attributes', 'custom_row_style_attributes', 10, 2);
```
I hope this helps.
