### ISSUE TITLE
Sidebar Emulator conflict with WooCommerce Layered Nav Filters

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-panels#280]
Issue reported [here](https://wordpress.org/support/topic/siteorigin_panels_sidebars_emulator). Still needs to be investigated.

**Comment by britner** [comment]
Hey, would love to see an update? how can help? It would also be nice to fix the Sidebar Emulator conflict with polylang too. I know it's been reported a lot so I'm not sure you guy's take on whether or not your wanting to fix? Let me know where you stand? whats the best way to help?

**Comment by gregpriday** [comment]
This should be fixed in the latest update.
