### ISSUE TITLE
Background image for call to action widget

### ISSUE THREAD

**Issue by sourcerer-mike** [siteorigin/siteorigin-panels#281]
https://siteorigin.com/widgets-bundle/call-action-widget/

Please allow an image as background.

Would be great if the one from "Design" (right menu) would be used.
So that if an background image is set, then there will be no color set.

Last one would be great in general.

**Comment by AlexGStapleton** [comment]
Decent suggestion. Could you please create a separate issue for the second suggestion? We'll be able to track it more easily that way.

**Comment by AlexGStapleton** [comment]
Oh actually. I forgot to say this in my last comment, but could you please repost this issue over at siteorigin/widgets-bundle? As the Widget Bundle has a separate repo.

**Comment by sourcerer-mike** [comment]
Hello,

it is absolutely okay if you go ahead. As someone from outside I just want to give the impulse to you. What and where it belongs is up to your structures which I don't need to understand for that. Anyway it is nice to know for next time. Thank you.

At last I've done so: https://github.com/siteorigin/so-widgets-bundle/issues/312
But please try a reply like "Wrong place, but I forwarded it to the {right place here}." linked etc.

Very user friendly and something I would love to see at more places.
But sorry if you're not part of the staff. In that case I guess you're there with me.

Cheers,

Mike
