### ISSUE TITLE
is_active_widget and the Layout Builder

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-panels#282]
is_active_widget does not cover widget's that are placed within the Layout Builder widget.

**Comment by gregpriday** [comment]
@braamgenis I know it's been a while since you built the sidebars emulator, but can you take a look at this? My guess is that we just need to add some sort of recursive component to the `register_widgets` function that checks inside Layout Builder widgets for more widgets.

**Comment by braamgenis** [comment]
Yeah, that sounds about right. Maybe add a filter for a widget to specify that it might contain other widgets that need to be registered.

**Comment by gregpriday** [comment]
I'm going to take a quick look at this. Even if it specifically works with the Layout Builder, that should be fine.

**Comment by gregpriday** [comment]
@braamgenis - think that should fix it. If you still remember the sidebars emulator stuff, then can you take a look over the commit and check if it all makes sense.
