### ISSUE TITLE
Live Editor UX: Force device view iframe at actual width rather than being responsive

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#284]
When using the live editor on an iPad (when in vertical orientation) all three views will look the same due to the iframe being responsive (max-width vs width). We should show the iframe at a static width rather than a dynamic one to provide a consistent preview overall. If this width exceeds the browser width, we should overflow scroll it.

**Comment by AlexGStapleton** [comment]
@Misplon I'm using the PB global tablet and mobile width settings for this, right? If not, what widths would you like to use for tihs?

**Comment by Misplon** [comment]
Using the global width values sound good. Thanks.
