### ISSUE TITLE
Integration with other content plugins

### ISSUE THREAD

**Issue by boquiabierto** [siteorigin/siteorigin-panels#285]
I have very specific issues integrating your styling and parallax scripts into the [Wherever Content](https://github.com/boquiabierto/wherever-content) plugin I’ve just released.

The plugin injects content wherever you specify and using it with your page builder is straightforward. But page builder only enqueues the registered styling and parallax scripts when they are needed by the current post (which is nice) and rightfully registered through 'wp_enqueue_scripts' but I need the scripts to be also available for content added by a custom query which is executed in the 'wp' hook which executes before 'wp_enqueue_scripts'. In other words, custom queries in a 'wp' hook won’t enqueue page-builder scripts registered in the 'wp_enqueue_scripts' hook.

So the only way I’ve found the scripts to enqueue with independence to the main query is to copy your scripts into the plugin and [register them before](https://github.com/boquiabierto/wherever-content/blob/master/includes/class-wherever.php#L196) the custom query in the 'wp' hook (which is ugly). 

This dependence to page-builder scripts is terrible and get even worse by your version dependent naming of the scripts which seems only to apply on .org’s plugin version. Must be part of your build process?

Hopefully you like the Wherever Content plugin and are willing to offer me some kind of solution so both plugins can live in peace together ;-) cheers!

**Comment by AlexGStapleton** [comment]
Hi @boquiabierto.

Very sorry for the delay.
Are you still having issues with this?If so, you should be able to do this by using [SiteOrigin_Panels::renderer()->generate_css( $post_id )](https://github.com/siteorigin/siteorigin-panels/blob/2.10.6/inc/renderer.php#L49). 

If that doesn't help,  can you please link me to the current version of class-whatever.php? I clicked the provided link but it's coming up as no longer existing. Was this code moved to a different file?

**Comment by AlexGStapleton** [comment]
Hi @boquiabierto,

I'm going to close this to ensure only active issues are open. Please feel free to re-open this if you would like to pick this back up.
