### ISSUE TITLE
Set row ID as purely a number and it'll be suddenly changed to false on save

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#286]
Create a row and then set the row as 1, and on save that row id will be changed to false.

**Comment by AlexGStapleton** [comment]
This doesn't appear to be a bug, [but intentional](https://github.com/siteorigin/siteorigin-panels/blob/develop/siteorigin-panels.php#L1591).

```
if( is_numeric($grid['style']['id']) ) {
	// Numeric IDs will cause problems, so we'll ignore them
	$grid['style']['id'] = false;
}
```

I'm not too sure why though. 😕

**Comment by gregpriday** [comment]
We can still investigate the reason and find a way of letting a user enter a numeric ID.

**Comment by AlexGStapleton** [comment]
Is it a good idea to completely remove the unique id check just for this? I really like the idea of a suffix if the ID isn't unique but it might not really be worth us worrying about. Hm. yeah, actually, I'm okay with this change.

**Comment by gregpriday** [comment]
It's best that the user gets the ID they expect. We also have ID settings for rows, cells and widgets now, so that's a lot of unique IDs to keep track of. Also, with the current implementation, this check is run on every page load. So if we were to reimplement this, I'd want it to happen on save.
