### ISSUE TITLE
If row has row id with a number at the start, Column CSS suddenly won't output

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#287]
Create a multi-column row with a row ID with a number first and then whatever else after that. Add any widgets into the columns (purely to provide output) and the .panel-grid-cell float CSS for this row won't be output, only the width will.

[Reference Layout](https://u.teknik.io/NeFDc.json)

**Comment by gregpriday** [comment]
@AlexGStapleton - can you check if this is still an issue? I just tested and it seems to be working fine. The fix might be from the changes where we moved custom row IDs from the row to the row styling element.

**Comment by AlexGStapleton** [comment]
It works now. This must have been indirectly fixed in a recent update.
