### ISSUE TITLE
Call in widget to the_excerpt() with no explicit excerpt causes PHP to timeout in live editor

### ISSUE THREAD

**Issue by emik** [siteorigin/siteorigin-panels#29]
I have a widget that calls get_posts and uses global $post. It loops through the posts calling setup_postdata($post). It is at the_excerpt() that the live editor fails to render properly. PHP times out and the content displayed is repeated and styled incorrectly. I traced the issue through to the call to siteorigin_panels_render(). I notice that it is a recursive function so that may have something to do with it. The content works fine on the actual rendered page, the issue is just with the live editor.

**Comment by gregpriday** [comment]
Hi Emik

Would it be possible to get a copy of this widget so I can check this issue out for myself?
