### ISSUE TITLE
Add NextPage (Pagination) quicktag functionality

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#290]
Look at supporting the `<!--nextpage-->` quicktag in Page Builder.

https://en.support.wordpress.com/nextpage/

**Comment by Misplon** [comment]
When the `<!--nextpage-->` is inserted into the Text tab, the page pagination does appear but content isn't separated by the tag, all content appears. Same situation in Black Studio. Would still be cool.

**Comment by Misplon** [comment]
A quick update. I've confirmed this is still a challenge. If we could get this core functionality working in the Editor widget, it would be awesome.

**Comment by braamgenis** [comment]
I don't think we can support this in a way that it will just work the same as WP Core pagination. The core pagination just splits page content wherever it finds the `<!--nextpage-->` tags. PB can't do it the same way as it would result in invalid HTML.

The simplest solution I can think of would require PB to handle this on a per editor widget basis and split each editor widget's content and load subsequent pages using AJAX.

The suggestion of splitting a whole layout is possible but would be complex. I would rather let users specify that they want paginated content and then create separate PB layout for each page to which they can link. The drawback to this approach is it would take quite a bit of work to figure out the admin UI for allowing pagination and multiple layouts for a single page.

**Comment by gregpriday** [comment]
We can call this a limitation. I've investigated it a couple times in the past and it's damn near impossible to get it working with a column layout.

If there's enough demand for it, we could probably modify the interface to allow explicitly adding page breaks. This would basically be a highly specific row. My guess is 20-40 hours to get that implemented.

**Comment by Misplon** [comment]
Super, thanks for the feedback. I'll add a limitations section to the documentation to make a note of this.
