### ISSUE TITLE
Text widget and WYSIWYG

### ISSUE THREAD

**Issue by fakeartist** [siteorigin/siteorigin-panels#293]
Hi. The content of the text widget is plain text. Is there any way, that one could use a WYSIWYG editor instead (or both, like in the WordPress editor)?

**Comment by AlexGStapleton** [comment]
No. You'll need to use a different widget. We recommend using the SiteOrigin Editor which you can get by installing the [SiteOrigin Widgets Bundle](https://wordpress.org/plugins/so-widgets-bundle/).
