### ISSUE TITLE
Black Studio TinyMCE: Live Editor and history error

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#294]
There's an issue with the [Black Studio TinyMCE](https://en-au.wordpress.org/plugins/black-studio-tinymce-widget/) that happens when using SiteOrigin Page Builder. Here's the [Black Studio TinyMCE  Widget issue](https://github.com/black-studio/black-studio-tinymce-widget/issues/42).

When you make a change to the visual editor widget and view the history or live editor, you'll be presented with nothing (or an error if you have WP_DEBUG enabled). 

Here's a reference gif of me recreating this issue:
![](https://i.imgur.com/sueAhzJ.gif)

Error:
> Fatal error: Call to undefined function is_plugin_active() in D:\wamp\www\siteorigin\wp-content\plugins\black-studio-tinymce-widget\includes\class-compatibility-plugins.php on line 90

PHP Stack Trace:

> [23-Sep-2016 04:05:39 UTC] PHP   1. {main}() D:\wamp\www\siteorigin\index.php:0
> [23-Sep-2016 04:05:39 UTC] PHP   2. require() D:\wamp\www\siteorigin\index.php:17
> [23-Sep-2016 04:05:39 UTC] PHP   3. require_once() D:\wamp\www\siteorigin\wp-blog-header.php:13
> [23-Sep-2016 04:05:39 UTC] PHP   4. require_once() D:\wamp\www\siteorigin\wp-load.php:39
> [23-Sep-2016 04:05:39 UTC] PHP   5. require_once() D:\wamp\www\siteorigin\wp-config.php:93
> [23-Sep-2016 04:05:39 UTC] PHP   6. do_action() D:\wamp\www\siteorigin\wp-settings.php:411
> [23-Sep-2016 04:05:39 UTC] PHP   7. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\plugin.php:524}() D:\wamp\www\siteorigin\wp-includes\plugin.php:524
> [23-Sep-2016 04:05:39 UTC] PHP   8. wp_widgets_init() D:\wamp\www\siteorigin\wp-includes\plugin.php:524
> [23-Sep-2016 04:05:39 UTC] PHP   9. do_action() D:\wamp\www\siteorigin\wp-includes\widgets.php:1474
> [23-Sep-2016 04:05:39 UTC] PHP  10. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\plugin.php:524}() D:\wamp\www\siteorigin\wp-includes\plugin.php:524
> [23-Sep-2016 04:05:39 UTC] PHP  11. SiteOrigin_Panels_Sidebars_Emulator->register_widgets() D:\wamp\www\siteorigin\wp-includes\plugin.php:524
> [23-Sep-2016 04:05:39 UTC] PHP  12. get_post_meta() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\sidebars-emulator.php:79
> [23-Sep-2016 04:05:39 UTC] PHP  13. get_metadata() D:\wamp\www\siteorigin\wp-includes\post.php:1661
> [23-Sep-2016 04:05:39 UTC] PHP  14. apply_filters() D:\wamp\www\siteorigin\wp-includes\meta.php:486
> [23-Sep-2016 04:05:39 UTC] PHP  15. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\plugin.php:235}() D:\wamp\www\siteorigin\wp-includes\plugin.php:235
> [23-Sep-2016 04:05:39 UTC] PHP  16. siteorigin_panels_live_editor() D:\wamp\www\siteorigin\wp-includes\plugin.php:235
> [23-Sep-2016 04:05:39 UTC] PHP  17. siteorigin_panels_process_raw_widgets() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\inc\live-editor.php:22
> [23-Sep-2016 04:05:39 UTC] PHP  18. WP_Widget_Black_Studio_TinyMCE->update() D:\wamp\www\siteorigin\wp-content\plugins\siteorigin-panels\siteorigin-panels.php:657
> [23-Sep-2016 04:05:39 UTC] PHP  19. apply_filters() D:\wamp\www\siteorigin\wp-content\plugins\black-studio-tinymce-widget\includes\class-widget.php:90
> [23-Sep-2016 04:05:39 UTC] PHP  20. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\plugin.php:235}() D:\wamp\www\siteorigin\wp-includes\plugin.php:235
> [23-Sep-2016 04:05:39 UTC] PHP  21. Black_Studio_TinyMCE_Compatibility_Plugins->wpml_widget_update() D:\wamp\www\siteorigin\wp-includes\plugin.php:235

Only the relevant plugins were active at the time of testing (SiteOrigin Page Builder and Black Studio TinyMCE Widget) and Twenty Sixteen was the active theme.

**Comment by marcochiesi** [comment]
Fixed on Black Studio TinyMCE widget v. 2.2.12.

**Comment by gregpriday** [comment]
Thanks @marcochiesi!
