### ISSUE TITLE
Background position and background size

### ISSUE THREAD

**Issue by daviedR** [siteorigin/siteorigin-panels#299]
Hi guys,

In row / widget settings, we can set a background image and choose how it is shown using the "Background Display" option, which is an merged option to set some background CSS property.

Can we make it more explicit that looks more representative to CSS? OR maybe even split it into 5 different options:
- background-position
- background-size
- background-repeat
- background-attachment
- background-parallax (True/False)

That way we can have more flexible background image options. What we have right now is very limited and need custom CSS in some cases.

For example:
Background display "Cover" doesn't have `background-position` option. If we have a landscape oriented image as the background, and we are on mobile device, the image would anchor on top left (the default background-position value). In most cases, we want to have it at center center. We need to add custom CSS to make it `center center`.

What do you think?

**Comment by gregpriday** [comment]
I'd like to avoid adding too many extra style settings. So having 5 settings for styling would be a bit too much, also migrating these settings would require a fair amount of effort.

The cover option should have a background size set to cover though, I've changed this.

Page Builder 2.5 also improves how custom CSS is handled. It's much easier to overwrite things like background positioning using a few CSS attributes. So for expert users who want more control, the option is there.

**Comment by gregpriday** [comment]
https://github.com/siteorigin/siteorigin-panels/commit/ccced0edda42daec40a9c647d7229a8e28554bb9
