### ISSUE TITLE
Overwrite jQuery css in Row to get parallax effect

### ISSUE THREAD

**Issue by mimomedia** [siteorigin/siteorigin-panels#30]
Hi i am trying to get a parallax effect in row, with its background image.

What i am doing is to insert some jQuery to make this happen on Document ready but i cannot overwrite the 'background-image' attr for the row, just declare it transparent.

I use this image to get the parallax effect with no problem, but need to make the row background transparent after loading, is this possible?

Have tried 

window.load
document.ready

with no luck

I am using this plugin 

https://github.com/pixelcog/parallax.js/

Thank you very much

**Comment by slifin** [comment]
I was able to integrate parallax using this plugin: https://github.com/pederan/Parallax-ImageScroll which essentially places the image over the row so you don't need to play with the row itself that much

I suggest having a play with it and if you get stuck post your issue here

**Comment by mimothemes** [comment]
Hi thank you very much for the info. I have finally done it using this jQuery function on Document Ready

function mmparallax(){
	jQuery('.panel-row-style-parallax').each(function() {
        var bg = jQuery(this).css('background-image');
        jQuery(this).css('background-image','');
        bg = bg.replace('url(','').replace(')','');
        jQuery(this).parallax({imageSrc:bg});
    });
}

Before it is needed to add the class 'parallax' to the row in row options

**Comment by mimothemes** [comment]
Hi again, i have seen the plugin you have posted. When firstly i was looking for one i saw this but also saw that it needs a very special html markup so that's why i choose the other.

Could you explain me how you do it with this plugin? You just create a new markup on the fly?

Thank you very much.

**Comment by slifin** [comment]
I modified the element to have data-image="<myimagehere>" attached to it, I did this with the siteorigin_panels_row_style_fields and siteorigin_panels_row_style_attributes filters, these allowed me to extend the controls so I could add parallax specific controls on the backend and move the background image to the data-image attribute of the row which is all that is really required to get that plugin working it doesn't require extra markup
