### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by paulgibbs** [siteorigin/siteorigin-panels#302]
In the bundled library, `siteorigin-panels/widgets/lib/lessc.inc.php`, there is code that is not PHP7. Please can you update siteorigin-panels to use a newer version of that script which ought to be compatible with PHP?

> 2500 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
> 2514 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
> 2645 | ERROR | 'string' is a reserved keyword introduced in PHP version 7.0 and cannot be invoked as a function (T_STRING)
> 2677 | ERROR | Function name, class name, namespace name or constant name can not be reserved keyword 'string' (since version 7.0)

**Comment by paulgibbs** [comment]
Same goes for the copy of the same file in the complementary `so-widgets-bundle` plugin.

**Comment by gregpriday** [comment]
I actually fixed this a few days ago, just pushed the changes to Github now https://github.com/siteorigin/siteorigin-panels/commit/959a0f9e3c73d6d581d0e9bb040219e955212aa6

Luckily this part of the code is only used for legacy widgets in Page Builder, so it shouldn't be too much of a problem. Oddly enough, even in our PHP7 testing of Widgets Bundle, it didn't cause a problem. I've still fixed it there too, though.

**Comment by paulgibbs** [comment]
Great, thanks @gregpriday!

**Comment by paulgibbs** [comment]
@gregpriday Do you know what release this is going to get into? And an ETA for that?
