### ISSUE TITLE
Layout Builder doesn't open correctly and causes toolbar duplication in other layout.

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#303]
Reported in [this thread](https://siteorigin.com/thread/layout-builder-broken/).

For whatever reason [this layout](https://u.teknik.io/Vx2LB.json) has issues with the last three layout builders in that this will happen when you try and open a second layout builder:

![](https://i.imgur.com/iJ88nNQ.png)

When you go back to the original layout builder it'll look like so:

![](https://i.imgur.com/7DgecVh.png)

Here are a couple of edited versions:
[This version](https://u.teknik.io/PlJ40.json) contains the last two rows and it won't work on import but if you save it will.

[This version](https://u.teknik.io/NXSh6.json) will continue to be broken on save. Only occurs to the last two rows. Removing any rows and saving will prevent the issue from occurring.

Here's a reference gif:
![](https://i.imgur.com/erPZmUR.gif)

**Comment by gregpriday** [comment]
I can recreate this issue on my side. I'll take a look. My first suggestion though would be to try educate users on how to properly use the Layout Builder widget. I can't quite see why those single-column rows with a single layout builder, aren't just normal 3 column rows.
