### ISSUE TITLE
Widgets not loading from parent theme

### ISSUE THREAD

**Issue by Jursdotme** [siteorigin/siteorigin-panels#306]
I have a theme that contains a widget. This theme is a parent theme with a child theme active.

The widget only shows up if the parent theme is active. If i activate the child theme the widget doesn't get loaded.

The child theme overrides a single template file and loads a stylesheet.

Do i somehow have to load the widgets from the child theme aswell?

**Comment by AlexGStapleton** [comment]
I can't seem to replicate this. Could you please send me a copy of your parent theme (or rather tell me the name) and a copy of your child theme so I can run a few tests?

**Comment by gregpriday** [comment]
I'm closing this issue for now, @Jursdotme. If you have any additional information, please let us know and I'll reopen it.
