### ISSUE TITLE
Is there a way to remove the SiteOrigin builder meta box from the Posts page?

### ISSUE THREAD

**Issue by orionthemes** [siteorigin/siteorigin-panels#307]
We need to resolve the HTML validation issues on a custom theme in order to get it accepted to ThemeForest. Validation issues are caused by SiteOrigin builder meta box which automatically loads on the blog page (the page defined in Reading Settings -> Posts page).
![screen shot 2016-11-05 at 08 22 46](https://cloud.githubusercontent.com/assets/23274206/20028454/3f6e7682-a332-11e6-9553-ea8f8125d1d8.png)
![screen shot 2016-11-05 at 08 23 51](https://cloud.githubusercontent.com/assets/23274206/20028455/41e0d5cc-a332-11e6-8bf7-de7e36be9964.png)
Thank you,
Timea

**Comment by Misplon** [comment]
Hi @orionthemes. I might get corrected by the team but I don't believe those two are related. `wp_footer` is used as a fallback when for some reason, styles can't be loaded in the normal hook in the head. What is the comment that's cut off in your screenshot? It's for a Layout Builder widget right?

**Comment by orionthemes** [comment]
The rest of the html reads: 
<style type="text/css" media="all" id="siteorigin-panels-grids-wp_footer">/ Layout 1110 / #pg-1110-0 , #pl-1110 .panel-grid-cell .so-panel , #pl-1110 .panel-grid-cell .so-panel:last-child { margin-bottom:0px } #pg-1110-0 .panel-grid-cell , #pg-1110-1 .panel-grid-cell { float:none } #pg-1110-0 , #pg-1110-1 { margin-left:-15px;margin-right:-15px } #pg-1110-0 .panel-grid-cell , #pg-1110-1 .panel-grid-cell { padding-left:15px;padding-right:15px } @media (max-width:780px){ #pg-1110-0 .panel-grid-cell , #pg-1110-1 .panel-grid-cell { float:none;width:auto } #pl-1110 .panel-grid , #pl-1110 .panel-grid-cell {  } #pl-1110 .panel-grid .panel-grid-cell-empty { display:none } #pl-1110 .panel-grid .panel-grid-cell-mobile-last { margin-bottom:0px }  } </style>

We are using the widget bundle with the theme, but we already had to remove all the Layout Builder widgets because of validation errors (review team is quite strict on this), the only validation issue remaining is on the blog page, where this widget loads automatically, if possible we would like to remove it overall from the blog page, since it is loading styles in the footer on the front-end even when empty.

Should I open the Issue on SiteOrigin Widget Bundle rep?

**Comment by Misplon** [comment]
The Page Builder tab shouldn't be activated by default on your Blog page. If you reset the options table in your database, is that still the case? I can replicate this issue but I need to go to Pages > Blog and click on the Page Builder tab, it isn't activated by default. The user would need to choose to move over to Page Builder.

**Comment by Misplon** [comment]
Sorry, not `options`. I was thinking of `postmeta` but that would negatively impact your demo site. Basically, on first install, is your Blog page automatically showing the Page Builder tab?

**Comment by orionthemes** [comment]
You are right, there is no such issue on the fresh installation, just on our demo import...
What should I look for in post meta table, to just delete this, not the whole table?
Creating a demo from scratch isn't really a good option.

Thank you very much for the great support.

**Comment by Misplon** [comment]
Please, try reverting back to the WP editor. Go to Pages > Blog, click Revert to Editor and then clear any remaining Page Builder grid HTML that is moved to the Text tab. Then, save. That should then be how a page looks before a user clicks on the Page Builder tab. Let us know how that goes.

**Comment by Misplon** [comment]
On another note, you could also look at supporting the Page Builder Post Loop widget which looks for templates as follows:

*-loop.php
loop-*.php

* is any string.

The assigned posts page has the disadvantage of not rendering content. Using the Post Loop widget is a way around this as the user can place content above, below or on the sides of the loop. You can see Vantage add loops in this pattern here: https://github.com/siteorigin/vantage/tree/develop/loops. 

This is not related to your question, just a general note while we are talking about Page Builder and the posts page.

**Comment by orionthemes** [comment]
We tried to revert back to editor several times and this is what keeps happening:
https://jumpshare.com/v/xXdA5tqOanBB3yMGLXNR

We will check out the Post Loop widget. Thanks.

**Comment by Misplon** [comment]
We're unsure why this is happening. Please, could you try some basic tests:

* Does this happen with all other plugins deactivated?
* Does this happen with another theme like Twenty Sixteen?

If all else fails, you could remove this action:

`add_action('wp_footer', 'siteorigin_panels_print_inline_css');`

from within `after_setup_theme`.

**Comment by gregpriday** [comment]
@orionthemes I'm going to close this issue for now. If you're still having problems, please feel free to reopen it.
