### ISSUE TITLE
the_excerpt() is not working on live editor

### ISSUE THREAD

**Issue by egemenerd** [siteorigin/siteorigin-panels#308]
First of all, thank you for your prompt response @AlexGStapleton ( https://github.com/siteorigin/siteorigin-panels/issues/180 )

This issue is related to the_excerpt() function because when I remove this function from the widget, everything is working properly. 

Also I'm sure it is not related to my plugin because I tried with other plugins which have used the_excerpt() function in the widgets and they are not working too. For example;

https://wordpress.org/plugins/livemesh-siteorigin-widgets/

https://wordpress.org/plugins/recent-posts-widget-extended/

https://wordpress.org/plugins/recent-posts-widget-with-thumbnails/

Please upload Livemesh siteorigin widgets plugin and try to display post excerpts below the post items. You will get an empty page like the following;

![ss1](https://cloud.githubusercontent.com/assets/7691382/20039640/df8d584a-a44f-11e6-86fe-cb86992223e7.png)

If I turn off the excerpts;

![ss2](https://cloud.githubusercontent.com/assets/7691382/20039655/228ca90c-a450-11e6-8e1c-3a20f01b36c8.png)

Everything is working properly;

![ss3](https://cloud.githubusercontent.com/assets/7691382/20039658/30cec7e8-a450-11e6-9e1e-985710ac7442.png)

My demo is in localhost (Mamp) and I only uploaded standard test data;

https://codex.wordpress.org/Theme_Unit_Test

**Comment by AlexGStapleton** [comment]
I'm able to replicate this with the two widgets I tried (livemesh and recent posts with thumbnails). I suspect it's due to the_content being called for whatever reason. My reasoning for thinking this are based on the second plugin.

**Comment by gregpriday** [comment]
Thanks for letting us know about this. I'll take a look as soon as I can.
