### ISSUE TITLE
Feature Request: Padding and margin in Rows, Columns and widgets

### ISSUE THREAD

**Issue by mimomedia** [siteorigin/siteorigin-panels#31]
Hi, just only if you have time this would be great i think.

Just add the top, left, bottom and right margin/padding separately as options for the three of the elements. Now columns don't have this feature and Rows/Widgets have it but you need to give it a whole padding to all the row.

Thank you very much
Best Regards

**Comment by gregpriday** [comment]
Sorry I didn't reply here sooner. When I saw your suggestion come through, I did chat to the team and we've found a nice potential way to implement this. We have a lot of work to do on Page Builder at the moment, but we'll definitely look at this for a future release.

**Comment by gregpriday** [comment]
This has all been added. All these settings will also be available for cells in Page Builder 2.5
