### ISSUE TITLE
Layout import: browse button doesn't work in Edge

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#312]
Preface: Drop and drag works without issue.

The layout import button doesn't work in Edge. It's unclear (based on this [WordPress ticket](https://core.trac.wordpress.org/ticket/37039)) if this is an issue with Plupload or a general issue with Edge. It should be noted that WordPress [resolved this issue](https://core.trac.wordpress.org/ticket/37039) with their usage.

![](https://i.imgur.com/bxgerbM.gif)

References:
[Slack Chat](https://siteorigin.slack.com/archives/plugins/p1479314241000150)
This is the same issues that affected [WordPress](https://core.trac.wordpress.org/ticket/37039) and [BuddyPress](https://buddypress.trac.wordpress.org/ticket/6846).

**Comment by gregpriday** [comment]
@AlexGStapleton: can you confirm this is still an issue? If so, @braamgenis, do you have any way of testing with Edge? Can I assign this issue to you?

**Comment by AlexGStapleton** [comment]
Can confirm - still an issue.

**Comment by braamgenis** [comment]
Yeah, I recently setup dual booting with Win 10, would just need to get VVV etc going.

**Comment by gregpriday** [comment]
It seems like this is related to https://github.com/moxiecode/plupload/issues/1343

We need to call `uploader.refresh()` after we show the UI.

We're hiding the UI before initializing `uploader` https://github.com/siteorigin/siteorigin-panels/blob/develop/js/siteorigin-panels/dialog/prebuilt.js#L89

Then only showing it again `PostInit`, which I assume is after initializing - https://github.com/siteorigin/siteorigin-panels/blob/develop/js/siteorigin-panels/dialog/prebuilt.js#L118

**Comment by gregpriday** [comment]
This is addressed in https://github.com/siteorigin/siteorigin-panels/commit/dc54a36c4019a466a8e76344a09276358b165325. @AlexGStapleton, can you close this if the build I sent you resolves the issue.
