### ISSUE TITLE
Layout directory issues with encoded URL

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#314]
[As per slack chat](https://siteorigin.slack.com/archives/plugins/p1480088996000002)

This [add_query_arg()](https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/admin-actions.php#L93) can sometimes result in an encoded &, Oddly, when it doesn't the layout directory doesn't work as only the encoded version works.

http://layouts.siteorigin.com/wp-admin/admin-ajax.php?action=query_layouts&amp;page=3 < Works
http://layouts.siteorigin.com/wp-admin/admin-ajax.php?action=query_layouts&page=3 < Doesn't work

**Comment by AlexGStapleton** [comment]
[This came up on Slack](https://siteorigin.slack.com/archives/support/p1480410164000008)

**Comment by gregpriday** [comment]
I actually think it's the encoded version that's not working. The only reason `http://layouts.siteorigin.com/wp-admin/admin-ajax.php?action=query_layouts&amp;page=3` works is because `page` is being ignored. For the other URL, `page` is being taken into account and there aren't 3 pages of layouts yet.

**Comment by gregpriday** [comment]
How often does this come up? We don't really have control over the output of add_query_arg. There might be something we can hack on the layouts server, but this would be a last resort. Ideally, we want to just rely on the `$_GET` variables. Using the encoded `&` is messing with this.

**Comment by AlexGStapleton** [comment]
At the time of posting, it felt like every fresh install had this issue but now it rarely comes up. Not too sure what's changed.

**Comment by gregpriday** [comment]
Maybe it was a fix with add_query_arg in a recent update of WordPress. I'll close this for now because it's difficult to fix. If it comes up for a user, tell them to update WordPress. If that doesn't fix things, then we can reopen this issue and try hack a fix. I'd rather avoid that, though.
