### ISSUE TITLE
the_content priority

### ISSUE THREAD

**Issue by cartpauj** [siteorigin/siteorigin-panels#315]
Would you consider running your the_content filter at an earlier filter hook priority instead of the default 10?

This would be helpful so that plugins currently hooking in before yours has run would not have their additional content lost.

A priority of 9 even, would probably solve most of such issues.
`add_filter( 'the_content', 'siteorigin_panels_filter_content', 9 );`

**Comment by AlexGStapleton** [comment]
This is something I've brought up with Greg in the past and his response was:

> Yeah, I suppose it could. Hard to know if we want other plugins coming before or after.
([reference](https://siteorigin.slack.com/archives/plugins/p1475090302000055))

As a result of this, I've just submitted a PR for PB 3.0 for testing.

**Comment by cartpauj** [comment]
I'm using this workaround ATM as well

```PHP
function site_origin_priority() {
    remove_filter('the_content', 'siteorigin_panels_filter_content');
    add_filter('the_content', 'siteorigin_panels_filter_content', 9);
}
add_filter('init', 'site_origin_priority', 3);
```

**Comment by gregpriday** [comment]
For now, anyone wanting to change the priority will need to stick to the workaround method. The issue with running the filter earlier is that the post_content is run through wpautop, which seriously damages the layouts of a lot of widgets. This came up during my testing.

Although running our filter at `10` does cause us to miss out on some processing from other plugins, it also helps us avoid potentially damaging filters like wpautop and any others we aren't aware of.

**Comment by cartpauj** [comment]
For anyone looking to do this after the latest update.

```PHP
function site_origin_priority() {
    if(class_exists('SiteOrigin_Panels')) {
        $single = SiteOrigin_Panels::single(); //No reason $single static var shouldn't already exist
        remove_filter('the_content', array($single, 'generate_post_content'));
        add_filter('the_content', array($single, 'generate_post_content'), 9);
    }
}
add_filter('init', 'site_origin_priority', 3);
```

**Comment by gregpriday** [comment]
There's actually a new caching mechanism in Page Builder 2.5 that has the_content filter running at 1. This was done to help with compatibility with other plugins, but it's disabled by default incase it caused unforeseen issues with existing layouts.

Just navigate to Settings > Page Builder in your WordPress admin, and enable the Content Cache setting.
