### ISSUE TITLE
WooCommerce Shop Page: PB isn't able to run

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#318]
Due to how WooCommerce handles the shop page, Page Builder isn't actually able to run as the_content isn't used.

References:
[Shop description hook](https://docs.woocommerce.com/wc-apidocs/source-function-woocommerce_product_archive_description.html#599-614 )
[wc_format_content()](https://docs.woocommerce.com/wc-apidocs/source-function-wc_format_content.html#703-712)

**Comment by AlexGStapleton** [comment]
I can get Page Builder to run (see below - ignore the function name), but I can't get the styles / JavaScript to actually output. I'm likely missing something obvious. :/

```
function siteorigin_panels_woocommerce_shop_content( $content ){
	if( is_shop() ){
		$panels_data = get_post_meta( wc_get_page_id( 'shop' ), 'panels_data', true );
		if ( !empty( $panels_data ) ) {
			$panel_content = siteorigin_panels_render( wc_get_page_id( 'shop' ) );
			if ( !empty( $panel_content ) ) {
				$content = $panel_content;
			}
		}
	}

	return $content;
}
add_filter( 'woocommerce_format_content', 'siteorigin_panels_woocommerce_shop_content'  );
```

**Comment by knightknight** [comment]
Has there been anymore development with this, as being able to get Page Builder to render an output for a WooCommerce shop page would be great ?

I found a similar issue customising North and using the 'overlap content' option for all my pages, except WooCommerce's shop page nothing worked unless you hard code in the content to the woocommerce.php template.

**Comment by AlexGStapleton** [comment]
Unfortunately, no, there haven't been any additional development this. Sorry mate.
