### ISSUE TITLE
Plugin incompatibility: Gravity Forms + Yoast SEO

### ISSUE THREAD

**Issue by d--j** [siteorigin/siteorigin-panels#321]
### What did you expect to happen?

The Page Builder should work with the popular plugins [Gravity Forms](http://www.gravityforms.com/) and [Yoast SEO](https://wordpress.org/plugins/wordpress-seo/).

If all three plugins are activated there should be no JavaScript errors and the Gravity Forms CSS should be enqueued.

### What happened instead?

When a Gravity Form is included on a page via the SiteOrigin Page Builder and Yoast SEO is active the jQuery library does not get enqueued – resulting in "jQuery is not defined" JavaScript errors.
Also the Gravity Forms CSS files do not get enqueued.

If you deactivate the Yoast SEO plugin the page loads without errors.

### How can we reproduce this behavior?

Install Gravity Forms, SiteOrigin Page Builder and Yoast SEO and add a page where the Page Builder is active and Gravity Form widget gets included.

Here is a test page:
https://yoast.test-umgebung.de/page-with-pagebuilder/

Here is a page where the form is included without the Page Builder (there the error does not occur):
https://yoast.test-umgebung.de/page-whitout-pagebuilder/

### Technical info
* WordPress version: 4.7
* Yoast SEO version: 4.0
* Gravity Forms: 2.1.1.19
* Page Builder by SiteOrigin: 2.4.20
* Theme: Twenty Sixteen or Twenty Fifteen
* Webserver: nginx, php 7, MySQL 5.7, Linux

Contact me privately to get WordPress backend access and/or SFTP access to the test installation.

See: Yoast/wordpress-seo#6263

**Comment by Misplon** [comment]
Hi d--j 

Thanks for posting and for such a nicely formatted issue report. The team will take a look at this as soon as they're able.

From a non-technical perspective I wanted to quickly share with you my experience of this combination. You can see for example, Yoast, Gravity and PB in use [here](http://ctshipsuppliers.com/contact-us/). The workaround at that link is to use Gravity via a Text widget using the form shortcode. Perhaps you can try that and let me know if helps the problem, as a workaround that is.

**Comment by d--j** [comment]
Hi @Misplon,

yes looks like that workaround works: https://yoast.test-umgebung.de/form-as-shortcode/

**Comment by Misplon** [comment]
Super, thanks for testing and for logging this. Due to the backlog of Page Builder issues, this probably won't be attended to right away If you don't mind, it would be best to use the shortcode method so you can keep building and using the three plugins together. You can use the core Text widget, the Black Studio TinyMCE "Visual Editor" widget or the SiteOrigin Editor widget (contained in the SiteOrigin Widgets Bundle).

**Comment by d--j** [comment]
I used that workaround on one site but since it does not work on all sites. One site of mine has a CSS for the SiteOrigin Editor + Standard Text Widget  and this clashes with the Gravity Forms CSS.

On that site I used the following workaround:
```php

<?php
 
add_action('wp_enqueue_scripts', function(){
  wp_enqueue_script('jquery');

  gravity_form_enqueue_scripts(1, false);
  wp_enqueue_style( 'gforms_reset_css' );
  wp_enqueue_style( 'gforms_datepicker_css' );
  wp_enqueue_style( 'gforms_formsmain_css' );
  wp_enqueue_style( 'gforms_ready_class_css' );
  wp_enqueue_style( 'gforms_browsers_css' );
}, 999);

```

**Comment by Misplon** [comment]
Looks good. Thanks for sharing that.

**Comment by gregpriday** [comment]
Does anyone have a copy of Gravity Forms to check if this is still an issue. Seems like the kind of thing that might have resolved itself after all these years, but worth looking into.

**Comment by Misplon** [comment]
Sending via Slack.

**Comment by AlexGStapleton** [comment]
I can confirm this issue still occurs after adding the Form widget and selecting then form. This issue doesn't occur if you tick `Disable script output` though so that's a possible workaround. I don't see any visual differences by ticking that setting but I suspect it's effectively doing the same thing as the PHP @d--j provided.

![](https://vgy.me/Px7wIn.png)

**Comment by gregpriday** [comment]
Thanks for checking @AlexGStapleton. We'll keep this open and look into it ASAP.

**Comment by AlexGStapleton** [comment]
I looked into how **Disable script output** works. Gravity Forms has provided a filter called [gform_disable_print_form_scripts](https://docs.gravityforms.com/gform_disable_print_form_scripts/) that  we can use to automatically do what that setting does. Not too sure when we would do that though.

**Comment by Misplon** [comment]
What scripts are being disabled?

**Comment by AlexGStapleton** [comment]
It doesn't appear to not be outputting anything. It's just not using [wp_print_styles](https://developer.wordpress.org/reference/functions/wp_print_styles/) to output scripts and instead using [wp_enqueue_script](https://developer.wordpress.org/reference/functions/wp_enqueue_script/).

**Comment by Misplon** [comment]
This seems like the summary: https://wordpress.stackexchange.com/questions/188510/use-wp-enqueue-scripts-not-wp-print-styles.

**Comment by Misplon** [comment]
Hi all. Alex and I took a look at this issue via https://github.com/siteorigin/siteorigin-panels/pull/806. At the moment, we aren't able to replicate the issue. We'd be happy to circle back if anyone would like us to and can send steps to replicate. Thanks for your contributions.
