### ISSUE TITLE
Sensei Issues

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#324]
I have a premium user who's reported a couple of issues (which I've been able to replicate on a separate install) with SiteOrigin page Builder and [Sensei](https://woocommerce.com/products/sensei/).

- Complex layouts will not save when applied to a lesson and instead, the page will revert to a non-page builder form.

The easiest way to replicate this is to import a layout from the layout directory - any layout will cause this issue.

- Quiz causes page builder to repeat

**Comment by gregpriday** [comment]
@AlexGStapleton Has this come up again? Is it still an issue?

**Comment by AlexGStapleton** [comment]
This hasn't been reported since. I don't actually have a copy of Sensei to verify if this is happening anymore but due to lack of reports and the popularity of Sensei and our plugins, I think we should close this until it's reported by another user.

**Comment by gregpriday** [comment]
I agree.
