### ISSUE TITLE
Post Loop Widget: Add a hook to allow scripts to be enqueued 

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#326]
Add a hook to the Post Loop widget to allow scripts that might be required for a loop to be enqueued.

**Comment by Misplon** [comment]
We're working around this at the moment: https://github.com/siteorigin/siteorigin-unwind/blob/develop/loops/loop-blog-masonry.php#L10. Having a hook would still be useful.

**Comment by gregpriday** [comment]
Easy enough to add, but the current solution isn't too bad.

**Comment by Misplon** [comment]
Yeah, would be nice to have but no issues (that I'm aware of) with the current solution.
