### ISSUE TITLE
Negative padding is reset to positive

### ISSUE THREAD

**Issue by LittleHamster** [siteorigin/siteorigin-panels#327]
In the widget layout if you set the padding to a negative number and save it, then it rests to a positive value. For example padding top is set to `-20px` but when saved, it is `20px`. Is this a bug?

**Comment by AlexGStapleton** [comment]
Okay so this is related to #260, but ignoring that issue - padding doesn't allow for negative numbers. If you used a negative number, the padding wouldn't work as you would have a syntax error. Sorry mate. :(
