### ISSUE TITLE
Layout builder prevents custom widget to load scripts when widget is active

### ISSUE THREAD

**Issue by romosamatya** [siteorigin/siteorigin-panels#331]
While creating widget I have used `is_active_widget( false, false, 'themename_test_widget', false ) )` to load the scripts only on front-end page if and only that particular widget is active but it fails if nested inside Layout Builder and is OK if used inside Layout Builder.

**Comment by gregpriday** [comment]
The best way for us to solve this would be to have the sidebars emulator check inside Layout Builder widgets.

**Comment by gregpriday** [comment]
Actually already reported here https://github.com/siteorigin/siteorigin-panels/issues/282

**Comment by shivapoudel** [comment]
What is the solution to do that check then?

**Comment by gregpriday** [comment]
There is no solution currently. This is something we'll fix internally. You can keep track of this issue's progress here: https://github.com/siteorigin/siteorigin-panels/issues/282
