### ISSUE TITLE
the_content() with $strip_teaser doesn't work

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#332]
[the_content()](https://developer.wordpress.org/reference/functions/the_content/#parameters) with $strip_teaser enabled will remove everything before the manual more. This functionality doesn't work when Page Builder is enabled.

**Comment by gregpriday** [comment]
Unfortunately, WordPress doesn't give us access to this variable from the_content filter, so there's no way for us to fix this.

https://github.com/WordPress/WordPress/blob/master/wp-includes/post-template.php#L240
