### ISSUE TITLE
Only load front.css when needed.

### ISSUE THREAD

**Issue by Horttcore** [siteorigin/siteorigin-panels#333]
Hello,

couldn't find any older ticket about this, but it would add some performance if the front.css is only loaded if the pagebuilder module is used.

Cheers Ralf

**Comment by gregpriday** [comment]
This is the default behaviour of Page Builder. This script is only enqueued when the Page Builder render function is called.

https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/renderer.php#L237

So generally, if front.css is being enqueued on every page, then it might be a plugin calling `siteorigin_panels_render` for pages other than the page currently being viewed.
