### ISSUE TITLE
adding an page with php

### ISSUE THREAD

**Issue by mrqaidi** [siteorigin/siteorigin-panels#334]
hello i am trying add homepage via php  but its not working  here is my code

    $post_id = wp_insert_post(array(		
        'post_content'   => '',
		'post_name'      => __('Homepage','aq_qmovies'),
		'post_title'     => __('Homepage','aq_qmovies'),
		'post_status'    => 'publish',
		'post_type'      => 'page',
		'ping_status'    => 'closed',
		'post_date'      => date('Y-m-d H:i:s'),
		'post_date_gmt'  => date('Y-m-d H:i:s'),
		'comment_status' => 'closed',
		'post_content'  => ''
		));
        
    update_post_meta($post_id,'panels_data','a:3:{s:7:"widgets";a:5:{i:0;a:10:{s:5:"title";s:0:"";s:10:"aq_content";s:6:"movies";s:10:"aq_orderby";s:6:"recent";s:5:"posts";s:2:"10";s:8:"Featured";s:3:"yes";s:10:"item_slide";s:1:"3";s:8:"autoplay";s:4:"true";s:11:"stopOnHover";s:4:"true";s:10:"pagination";s:4:"true";s:11:"panels_info";a:7:{s:5:"class";s:27:"AQ_Widget_Slideshow_content";s:3:"raw";b:0;s:4:"grid";i:0;s:4:"cell";i:0;s:2:"id";i:0;s:9:"widget_id";s:36:"a0f92c8b-e5ff-438b-a2e1-d7f9e67d4a83";s:5:"style";a:1:{s:18:"background_display";s:4:"tile";}}}i:1;a:4:{s:5:"title";s:13:"Recent movies";s:5:"items";s:6:"movies";s:5:"posts";s:2:"15";s:11:"panels_info";a:7:{s:5:"class";s:20:"AQ_Widget_List_items";s:3:"raw";b:0;s:4:"grid";i:1;s:4:"cell";i:0;s:2:"id";i:1;s:9:"widget_id";s:36:"bcbcdbf2-5c50-4481-bdab-abccbab3b5c9";s:5:"style";a:1:{s:18:"background_display";s:4:"tile";}}}i:2;a:8:{s:5:"title";s:13:"Random Movies";s:5:"items";s:6:"movies";s:5:"posts";s:2:"10";s:7:"orderby";s:6:"random";s:10:"item_slide";s:1:"4";s:8:"autoplay";s:4:"true";s:11:"stopOnHover";s:4:"true";s:11:"panels_info";a:7:{s:5:"class";s:21:"AQ_Widget_Item_slider";s:3:"raw";b:0;s:4:"grid";i:1;s:4:"cell";i:0;s:2:"id";i:2;s:9:"widget_id";s:36:"fb27be9b-2520-4e10-9748-b0a67e04ecd8";s:5:"style";a:1:{s:18:"background_display";s:4:"tile";}}}i:3;a:3:{s:5:"title";s:6:"Genres";s:9:"scrolling";s:4:"true";s:11:"panels_info";a:7:{s:5:"class";s:16:"AQ_Widget_Genres";s:3:"raw";b:0;s:4:"grid";i:1;s:4:"cell";i:1;s:2:"id";i:3;s:9:"widget_id";s:36:"598ae36f-107d-4562-a63a-9008785952c5";s:5:"style";a:1:{s:18:"background_display";s:4:"tile";}}}i:4;a:3:{s:5:"title";s:14:"Released Years";s:9:"scrolling";s:4:"true";s:11:"panels_info";a:7:{s:5:"class";s:24:"AQ_Widget_Released_years";s:3:"raw";b:0;s:4:"grid";i:1;s:4:"cell";i:1;s:2:"id";i:4;s:9:"widget_id";s:36:"6ba03a20-9245-4312-ba47-8fb297701f4d";s:5:"style";a:1:{s:18:"background_display";s:4:"tile";}}}}s:5:"grids";a:2:{i:0;a:2:{s:5:"cells";i:1;s:5:"style";a:5:{s:13:"bottom_margin";s:3:"0px";s:6:"gutter";s:3:"0px";s:7:"padding";s:15:"0px 0px 0px 0px";s:11:"row_stretch";s:14:"full-stretched";s:18:"background_display";s:4:"tile";}}i:1;a:2:{s:5:"cells";i:2;s:5:"style";a:2:{s:11:"row_stretch";s:4:"full";s:18:"background_display";s:4:"tile";}}}s:10:"grid_cells";a:3:{i:0;a:2:{s:4:"grid";i:0;s:6:"weight";i:1;}i:1;a:2:{s:4:"grid";i:1;s:6:"weight";d:0.7845443702940000374468354493728838860988616943359375;}i:2;a:2:{s:4:"grid";i:1;s:6:"weight";d:0.2154556297059999903087401662560296244919300079345703125;}}}');
    update_post_meta($post_id,'_panels_data_preview','a:3:{s:7:"widgets";a:5:{i:0;a:10:{s:5:"title";s:0:"";s:10:"aq_content";s:6:"movies";s:10:"aq_orderby";s:6:"recent";s:5:"posts";s:2:"10";s:8:"Featured";s:3:"yes";s:10:"item_slide";s:1:"3";s:8:"autoplay";s:4:"true";s:11:"stopOnHover";s:4:"true";s:10:"pagination";s:4:"true";s:11:"panels_info";a:7:{s:5:"class";s:27:"AQ_Widget_Slideshow_content";s:3:"raw";b:0;s:4:"grid";i:0;s:4:"cell";i:0;s:2:"id";i:0;s:9:"widget_id";s:36:"a0f92c8b-e5ff-438b-a2e1-d7f9e67d4a83";s:5:"style";a:1:{s:18:"background_display";s:4:"tile";}}}i:1;a:4:{s:5:"title";s:13:"Recent movies";s:5:"items";s:6:"movies";s:5:"posts";s:2:"15";s:11:"panels_info";a:7:{s:5:"class";s:20:"AQ_Widget_List_items";s:3:"raw";b:0;s:4:"grid";i:1;s:4:"cell";i:0;s:2:"id";i:1;s:9:"widget_id";s:36:"bcbcdbf2-5c50-4481-bdab-abccbab3b5c9";s:5:"style";a:1:{s:18:"background_display";s:4:"tile";}}}i:2;a:8:{s:5:"title";s:13:"Random Movies";s:5:"items";s:6:"movies";s:5:"posts";s:2:"10";s:7:"orderby";s:6:"random";s:10:"item_slide";s:1:"4";s:8:"autoplay";s:4:"true";s:11:"stopOnHover";s:4:"true";s:11:"panels_info";a:7:{s:5:"class";s:21:"AQ_Widget_Item_slider";s:3:"raw";b:0;s:4:"grid";i:1;s:4:"cell";i:0;s:2:"id";i:2;s:9:"widget_id";s:36:"fb27be9b-2520-4e10-9748-b0a67e04ecd8";s:5:"style";a:1:{s:18:"background_display";s:4:"tile";}}}i:3;a:3:{s:5:"title";s:6:"Genres";s:9:"scrolling";s:4:"true";s:11:"panels_info";a:7:{s:5:"class";s:16:"AQ_Widget_Genres";s:3:"raw";b:0;s:4:"grid";i:1;s:4:"cell";i:1;s:2:"id";i:3;s:9:"widget_id";s:36:"598ae36f-107d-4562-a63a-9008785952c5";s:5:"style";a:1:{s:18:"background_display";s:4:"tile";}}}i:4;a:3:{s:5:"title";s:14:"Released Years";s:9:"scrolling";s:4:"true";s:11:"panels_info";a:7:{s:5:"class";s:24:"AQ_Widget_Released_years";s:3:"raw";b:0;s:4:"grid";i:1;s:4:"cell";i:1;s:2:"id";i:4;s:9:"widget_id";s:36:"6ba03a20-9245-4312-ba47-8fb297701f4d";s:5:"style";a:1:{s:18:"background_display";s:4:"tile";}}}}s:5:"grids";a:2:{i:0;a:2:{s:5:"cells";i:1;s:5:"style";a:5:{s:13:"bottom_margin";s:3:"0px";s:6:"gutter";s:3:"0px";s:7:"padding";s:15:"0px 0px 0px 0px";s:11:"row_stretch";s:14:"full-stretched";s:18:"background_display";s:4:"tile";}}i:1;a:2:{s:5:"cells";i:2;s:5:"style";a:2:{s:11:"row_stretch";s:4:"full";s:18:"background_display";s:4:"tile";}}}s:10:"grid_cells";a:3:{i:0;a:2:{s:4:"grid";i:0;s:6:"weight";i:1;}i:1;a:2:{s:4:"grid";i:1;s:6:"weight";d:0.7845443702940000374468354493728838860988616943359375;}i:2;a:2:{s:4:"grid";i:1;s:6:"weight";d:0.2154556297059999903087401662560296244919300079345703125;}}}');
    update_post_meta($post_id,'_wp_page_template','default');
        
    update_option( 'page_on_front', $post_id );
    update_option( 'show_on_front', 'page' );
    update_option( 'home_generated', true );

any idea ?

**Comment by mrqaidi** [comment]
found how to do it

    // layout json
 	$post_content = '{"widgets":[{"title":"","aq_content":"movies","aq_orderby":"recent","posts":"10","Featured":"yes","item_slide":"3","autoplay":"true","stopOnHover":"true","pagination":"true","panels_info":{"class":"AQ_Widget_Slideshow_content","raw":false,"grid":0,"cell":0,"id":0,"widget_id":"a0f92c8b-e5ff-438b-a2e1-d7f9e67d4a83","style":{"background_display":"tile"}}},{"title":"Recent movies","items":"movies","posts":"15","panels_info":{"class":"AQ_Widget_List_items","raw":false,"grid":1,"cell":0,"id":1,"widget_id":"bcbcdbf2-5c50-4481-bdab-abccbab3b5c9","style":{"background_display":"tile"}}},{"title":"Random Movies","items":"movies","posts":"10","orderby":"random","item_slide":"4","autoplay":"true","stopOnHover":"true","panels_info":{"class":"AQ_Widget_Item_slider","raw":false,"grid":1,"cell":0,"id":2,"widget_id":"fb27be9b-2520-4e10-9748-b0a67e04ecd8","style":{"background_display":"tile"}}},{"title":"Genres","scrolling":"true","panels_info":{"class":"AQ_Widget_Genres","raw":false,"grid":1,"cell":1,"id":3,"widget_id":"598ae36f-107d-4562-a63a-9008785952c5","style":{"background_display":"tile"}}},{"title":"Released Years","scrolling":"true","panels_info":{"class":"AQ_Widget_Released_years","raw":false,"grid":1,"cell":1,"id":4,"widget_id":"6ba03a20-9245-4312-ba47-8fb297701f4d","style":{"background_display":"tile"}}}],"grids":[{"cells":1,"style":{"bottom_margin":"0px","gutter":"0px","padding":"0px 0px 0px 0px","row_stretch":"full-stretched","background_display":"tile"}},{"cells":2,"style":{"row_stretch":"full","background_display":"tile"}}],"grid_cells":[{"grid":0,"weight":1},{"grid":1,"weight":0.784544370294},{"grid":1,"weight":0.215455629706}]}';
    // create page first
    $page_id = wp_insert_post(array(		
        'post_content'   => '',
		'post_name'      => __('Homepage','aq_qmovies'),
		'post_title'     => __('Homepage','aq_qmovies'),
		'post_status'    => 'publish',
		'post_type'      => 'page',
		'ping_status'    => 'closed',
		'post_date'      => date('Y-m-d H:i:s'),
		'post_date_gmt'  => date('Y-m-d H:i:s'),
		'comment_status' => 'closed',
		'post_content'  => $post_content
		));
        
	$page = get_post( $page_id );
	// set page data
	$panels_data = json_decode( wp_unslash( $post_content ), true);
	$panels_data['widgets'] = siteorigin_panels_process_raw_widgets($panels_data['widgets']);
	$panels_data = siteorigin_panels_styles_sanitize_all( $panels_data );
	$panels_data = apply_filters( 'siteorigin_panels_data_pre_save', $panels_data, $page, $page_id );

	update_post_meta( $page_id, 'panels_data', $panels_data );

codes token from siteorigin-panels.php

**Comment by gregpriday** [comment]
Hi @mrqaidi, glad to hear you were able to figure this out.
