### ISSUE TITLE
Live Editor and History: External script inclusion in page builder will get flagged as XSS in Chrome

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#338]
I'm unsure if this is something we can fix, but basically if you include some external JavaScript hosted on a third party server to a text widget and open the Live Editor, it won't be loaded. An example of this is a simple Pinterest board:

```
<a data-pin-do="embedBoard" data-pin-board-width="400" data-pin-scale-height="240" data-pin-scale-width="80" href="https://www.pinterest.com/pinterest/official-news/"></a>

<script async defer src="//assets.pinterest.com/js/pinit.js"></script>
```

Once the live editor is run (or history viewed), this will appear in the console (or something like that):
![](https://i.imgur.com/8jlkRoM.png)

**Comment by gregpriday** [comment]
Adding the `X-XSS-Protection: 0` header fixes this for both the Live Editor and History Browser. I made sure to only add this with a few checks - just in case.
