### ISSUE TITLE
Multiple widgets to a row padding issue

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#339]
A page (or layout Builder) with at least two rows with multiple widgets in a single column with different padding applied to both widgets will result in the padding that's meant to be applied to the second widget being applied to the first widget. The second widget won't get any padding applied.

[Reference layout](https://u.teknik.io/eK2nu.json)

![](https://i.imgur.com/VPxutb7.png)
![](https://i.imgur.com/w6j9D7t.png)

**Comment by daviedR** [comment]
I opened a support topic on WordPress site for this issue but no response until now.

https://wordpress.org/support/topic/padding-settings-issue-on-2-4-23/

This is a serious issue. Our clients are complaining their padding are totally gone after the update. Our quick fix for now is using Custom CSS, but it looks inconvenient to end users.

Please fix this asap.

**Comment by gregpriday** [comment]
I've fixed this with https://github.com/siteorigin/siteorigin-panels/commit/09d3ae26868a1de8886265b7cd57e438a351f2f0 - the update will be coming soon.
