### ISSUE TITLE
Filter to add custom widget field types under "Widget Styles"

### ISSUE THREAD

**Issue by ehrig** [siteorigin/siteorigin-panels#341]
Creating custom widget field types works great. But it looks like those aren't picked up by the "Widget Styles" groups. I have already created a custom widget field type "box-shadow" that I want to add to the "Widget Styles" group "Design". But I can't get my head around how.

As far as I can see all "Widget Styles" are run through `siteorigin_panels_render_style_field`, which has no filter that allows me to add my own custom field types to any of the "Widget Styles" groups, and there default ones are a but restrictive.

By looking through the code I also stumbed upon a bug/typo here: https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/styles.php#L227
`url` should be named `link`, as there is no widget field type `url` in the page builder.

**Comment by gregpriday** [comment]
Hi @ehrig - sorry for the late reply here. The Widget Styles is meant for creating generic widget styles that apply to all widgets in Page Builder. They're different from the fields in the Widgets Bundle, so `url` isn't really a typo. It's just an unused field type.

This also means you can't actually use Widgets Bundle custom fields as style fields. At this time you can only the field types we provide.

So the solution right now is to just include styling for your widget in the actual widget form. This is how we handle it for widgets in the Widgets Bundle.

**Comment by scottsawyer** [comment]
@gregpriday are you saying that if I wanted to add a field to the Widget Styles on the widget edit screen, I am currently unable to do so?

![screenshot-138 197 3 126-9090-2018 10 13-04-38-39](https://user-images.githubusercontent.com/577492/46903378-ee6d5800-cea1-11e8-944a-68d8c2d2faeb.png)
