### ISSUE TITLE
'Update' button in Live Editor

### ISSUE THREAD

**Issue by braamgenis** [siteorigin/siteorigin-panels#342]
Consider adding an 'Update' button in the Live Editor, so user doesn't have to click 'Done' _and_ 'Update' to save changes.

**Comment by Misplon** [comment]
There is some cross over with Alex's issue here: https://github.com/siteorigin/siteorigin-panels/issues/359 requesting that the Live Editor return to the website front-end page if the Live Editor was accessed from the toolbar.

**Comment by braamgenis** [comment]
Yeah, we should consider both cases when working on this.

**Comment by AlexGStapleton** [comment]
This was implemented in https://github.com/siteorigin/siteorigin-panels/commit/7a2c24b9fe24156b774ebabeeccaee0563aa50a5
