### ISSUE TITLE
siteorigin_panels_render() and live editor

### ISSUE THREAD

**Issue by komarovartem** [siteorigin/siteorigin-panels#343]
**The Issue.**
If you tried to output the panels data from the post for example in the header.php using the following code.

`$panels_data = get_post_meta(206, 'panels_data', true);
echo siteorigin_panels_render( 206, true, $panels_data );`

or

`echo siteorigin_panels_render(206);`

It works perfectly but not in a Live Editor. In the Live Editor, the content from the editing page is being copied to the header where supposed to be a custom data from a different post.

**Recreate the issue.**
Two pages with page builder content.
One for siteorigin_panels_render() function which you put in a header.php and one just for content.
And after you run a live editor the content from a page will be copied to the header.

**Comment by gregpriday** [comment]
Thanks for letting us know about this @komarovartem. I added a check to the Live Editor filter so it only filters for the post_id of the current post.
