### ISSUE TITLE
Widgets defined within namespace are not rendered in preview mode (live editor)

### ISSUE THREAD

**Issue by Talv** [siteorigin/siteorigin-panels#346]
I have few custom widgets that have its class located in a namespace, eg: ```Widgets\Foo```. In live mode they are not rendered at all. They are visible on the sidebar and I can edit them from there, but actual elements are not rendered on the website preview.

The problem is within ```siteorigin_panels_live_editor```, which then calls ```siteorigin_panels_process_raw_widgets```. Here we can find.. the evil line..
https://github.com/siteorigin/siteorigin-panels/blob/09d3ae26868a1de8886265b7cd57e438a351f2f0/siteorigin-panels.php#L666
```php
$info['class'] = addslashes( $info['class'] );
```
What messes things up, since classes are never unslashed after that, at least not in live mode.
For now i resorted to just commenting out call to ```siteorigin_panels_process_raw_widgets``` in live mode.. and it does seem to work without breaking other things.

Also, I've noticed that ```panels_data``` metadata keys owned by post revisions are totally stripped from slashes in ```class``` keys, they contain stuff like ```WidgetsFoo``` instead of ```Widgets\Foo```. I think it breaks the ability to restore older revisions.

WP version: 4.7.2
Plugin version: 2.4.25

**Comment by gregpriday** [comment]
Thanks for letting us know about this @Talv. Escaping class names is only important if the data is being saved to post_meta first (which unescapes it in the process of loading from the database). The Live Editor skips this step which is what was causing problems.

Fixed it by adding an option to not escape classes to the `process_raw_widgets` function.
