### ISSUE TITLE
Row padding not being applied - 2.5 Beta

### ISSUE THREAD

**Issue by Paul-Allen** [siteorigin/siteorigin-panels#347]
The row padding is no longer being applied after installing Page Builder 2.5 Beta.

I believe this is due to the .panel-grid div being moved inside the .panel-row-style div.

**Comment by andrejarh** [comment]
Confirming this bug on my test, row paddings are not working.

**Comment by gregpriday** [comment]
Thanks for reporting. Changing to flexbox meant that we needed to move the style wrapper up one level. I just changed how the row style is targetted for row padding.

https://github.com/siteorigin/siteorigin-panels/commit/81f89a2cc6149647c315c602925c6c605e8efaa4
