### ISSUE TITLE
 page builder 2.5 beta issue Flex box: Stretch

### ISSUE THREAD

**Issue by lgfstudio** [siteorigin/siteorigin-panels#350]
Hi guys

This does not work for me. Other Flex settings are OK.

**Comment by braamgenis** [comment]
Hi @lgfstudio This seems to work fine for me. Could you please provide more detail about what, exactly isn't working? Expected vs actual behaviour and steps to reproduce would help me track down the issue. Thanks!

**Comment by lgfstudio** [comment]
Maybe I misunderstand this function, but I was expecting having the 2 columns with the same high (Stretched)

![test](https://cloud.githubusercontent.com/assets/5370777/23755782/caabdc74-04e1-11e7-9e9d-6306da04eaa8.jpg)

**Comment by AlexGStapleton** [comment]
Ah. @braamgenis pretty sure the issue is that the background isn't stretched. Only panel-grid-cell is stretched, not .panel-cell-style
