### ISSUE TITLE
2.5: Live Editor doesn't update when you adjust ordering for rows/widgets

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#353]
If you reorder/reorganize rows/widgets in the live editor this isn't reflected until you either reload the live editor or make a content change.

[Reference GIF](https://i.imgur.com/139FhY1.gif) (5MB)

**Comment by gregpriday** [comment]
Mmm, that might be broken from when I brought in all the changes we were making for 3.0.

**Comment by gregpriday** [comment]
Resolved with https://github.com/siteorigin/siteorigin-panels/pull/354/commits/75c4c1be33fae3ce4ca6758ed8dd6a8e591a79c7
