### ISSUE TITLE
Filter rows

### ISSUE THREAD

**Issue by Jursdotme** [siteorigin/siteorigin-panels#357]
is is possible to filter the rendering of rows? I want to prevent the rendering of a row unless some condition is met.

Say for instance i want to show different rows on a page based on the userrole.

Any advice?

**Comment by gregpriday** [comment]
This is possible, but definitely wouldn't be easy. You'd need to filter the `panels_data` object to remove anything you don't want based on user role, but you'd also need to make changes to all the values to ensure it's still a valid `panels_data`.

This is the kind of thing we could add as a filter though.

**Comment by Jursdotme** [comment]
I actually tried to filter the panels_data array but couldnt get it to work.

(messy half-a-solution code)
```php
function my_process_panels_data( $panels_data ){

  if( !is_admin() ):
      return;
  endif;

  $userrole = wp_get_current_user()->roles;

  switch ($userrole[0]) {
    case 'administrator':
      $role = 'imanadmin';
      break;
    default:
      echo "Your favorite color is neither red, blue, nor green!";
  }

  // Extract layout content
  $widgets = $panels_data['widgets'];
  $rows = $panels_data['grids'];
  $grid_cells = $panels_data['grid_cells'];

  // Setup target arrays for filtered content
  $widgets_filtered = array();
  $rows_filtered = array();
  $grid_cells_filtered = array();
  $filtered_rows = array();
  $filtered_cells = array();

  // Unset original content array and reset it to an empty array awaiting filtered content.
  unset($panels_data);
  $panels_data = array();

  // Filter the rows.
  foreach ($rows as $index => $row ) {
    if ($row['style']['access'] = $role) {
      unset($row);
      array_push($filtered_rows, $index);
    } else {
      $rows_filtered[$index] = $row;
    }
  }

  // Filter the cells.
  foreach ($grid_cells as $index => $cell ) {
    if ( in_array($cell['grid'], $filtered_rows ) ) {
      unset($cell);
      array_push($filtered_cells, $index);
    } else {
      $grid_cells_filtered[$index] = $cell;
    }
  }


  // Filter the widgets.
  foreach ($widgets as $index => $widget ) {
    if ( !in_array($index, $filtered_cells ) ) {
      $widgets_filtered[$index] = $widget;
    }
  }

  // Map filtered content to original array.
  $panels_data['user_role'] = $role;
  $panels_data['filtered_cells'] = $filtered_cells;
  $panels_data['filtered_rows'] = $filtered_rows;
  $panels_data['widgets'] = $widgets_filtered;
  $panels_data['grids'] = $rows_filtered;
  $panels_data['grid_cells'] = $grid_cells_filtered;


  // Return original array with filterede content.
  return $panels_data;
}
add_filter( 'siteorigin_panels_data', 'my_process_panels_data', 1 );
```

There are hooks for before and after rows. If there is a row directly on the row one could pass it thought a simple `current_user_can()` function?

**Comment by gregpriday** [comment]
It would be a much better idea to either add a filter using a pull request or wait until I get a chance to look at it. Filtering panels_data is going to get pretty damn messy. A simple true/false filter to skip certain rows would be much easier to maintain.

**Comment by Jursdotme** [comment]
I may very well look into adding pull request. Thank you :-)

**Comment by Misplon** [comment]
Hi @Jursdotme thanks for reaching out. I'm to close this for the moment but if you'd ever like to submit a PR in the future, please, do so. Thanks again.
