### ISSUE TITLE
Live Editor: Add ability to save and return back to normal page view

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#359]
We should add the ability to save and return back to normal page view rather than WordPress editor when live editor opened via admin bar. It seems odd that the live editor still requires you to click done, and then save the page from there. By clicking done it should simply save and return the normal view of the page.

**Comment by Misplon** [comment]
This is still a good idea.

**Comment by AlexGStapleton** [comment]
Workflow:
- User Views page and click Live Editor Quick Link.
- User decides against editing, and clicks close OR user makes edits and then clicks Update to Save Changes
- Live Editor is closed.

New Setting added after the Live Editor Quick Link setting.
**Live Editor Quick Link: Close After Editing**
Requires Live Editor Quick Link to be enabled to be visible.
