### ISSUE TITLE
Copy Content: Add the ability to filter what's copied

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#361]
In certain instances, user's (or widgets) may not wish to have certain things included in the copied content.  Things the SiteOrigin Slider which will add the pagination numbers to the copied content. Another example is, say, a slider like Meta Slider. It adds a bunch of code that users will never want to be included in the excerpt or analyzed by plugins like Yoast.

**Comment by gregpriday** [comment]
I added a really basic function that other widgets can check to see if the content being rendered is for the database (in which case it shouldn't be processed). We could add more support to the Widgets Bundle to produce shortcodes instead of code for all non-text based widgets.
