### ISSUE TITLE
Copy Copy: Add ability to keep shortcodes intact when copied

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#362]
Follow up to #361. We should add the ability to keep shortcodes intact when copied rather than running them which can lead to a whole lot of undesired data appearing in the post. This normally is okay but it can prove to be problematic with plugins Yoast if invalid data is analyzed.

**Comment by gregpriday** [comment]
Yeah, mostly the same implementation as #361. Resolved by https://github.com/siteorigin/siteorigin-panels/commit/d181a2b455e29be391058343233138c8f72d3dad

**Comment by AlexGStapleton** [comment]
In hindsight, I was overthinking things. :/
