### ISSUE TITLE
Where can we download beta?

### ISSUE THREAD

**Issue by LittleHamster** [siteorigin/siteorigin-panels#368]
Where can we download the beta release? I checked both branches and release pages but there is no link to download the beta version. Is it just the develop branch? in few places people were talking about version 2.5 beta 1, I can't seem to find that :(

**Comment by AlexGStapleton** [comment]
Hi @LittleHamster!

At this point, Beta 1 is really quite out of date and we're quickly approaching the second Beta release (current ETA being next week). If you would like to get notified of this, please sign up to our [Developer Newsletter](https://siteorigin.com/docs/page-builder/) (there's a link in the sidebar).

If you would rather try it out now, pull develop and let me know how you go mate.

**Comment by LittleHamster** [comment]
@AlexGStapleton thanks
