### ISSUE TITLE
Issue in default template rows 

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [siteorigin/siteorigin-panels#373]
I am using wordpress verssion 4.7.3.
Theme: Twenty Seventeen

Page Builder by SiteOrigin Version 2.4.25
SiteOrigin Widgets Bundle Version 1.8.1
Ultimate Addons for SiteOrigin Version 2.4.1

I tested it by assigning Fitness Gym layout to a page and also got the same problem with We Love Design layout . I have added the screenshot please check it.

![siteorigin issue 2](https://cloud.githubusercontent.com/assets/2470646/24362821/91468468-132b-11e7-8d7a-38436d70f0d4.png)

![siteoriginissue](https://cloud.githubusercontent.com/assets/2470646/24362250/dab25e44-1329-11e7-9c28-0edcde1b1a93.png)

**Comment by AlexGStapleton** [comment]
Sadly, this is an issue with how Twenty Seventeen structures things and it's sadly not something we reliability fix. I would recommend reporting the off-centered columns to WordPress directory as it's not directly related to the usage of SiteOrigin Page Builder and more of a general theme issue. Sorry mate. :(

**Comment by PrafullaKumarSahu** [comment]
Hi Alex, thank you for your reply, I tried with [vantage](https://siteorigin.com/theme/vantage/) theme and having same issue sadly :( Can you give me more idea about this issue.

![same-issue-with-vantage-theme](https://cloud.githubusercontent.com/assets/2470646/24647814/14739d30-193f-11e7-894b-fe4fbf8b7b2e.png)

**Comment by AlexGStapleton** [comment]
Is the sidebar present?

**Comment by PrafullaKumarSahu** [comment]
@AlexGStapleton  thank you, that was causing the problem .

**Comment by PrafullaKumarSahu** [comment]
Removing Sidebar widgets solves problem for posts but not for pages.

**Comment by gregpriday** [comment]
You'd need to pick a page template that offers full width. Page Builder just occupies the entry-content space provided to it, so it's up to the theme to decide how to display this. You'd need to research creating full-width pages in Twenty Seventeen, or find a theme that supports this functionality out the box.

**Comment by PrafullaKumarSahu** [comment]
@gregpriday if a sidebar contains no widget in that case for post everything is working just expected and for page it is not working, which seems quite odd to me, yes, I can create a full width template and use it, I understood it, but I am using with vantage theme now. thank you for your reply.

**Comment by dustyadm** [comment]
This issue is with the theme itself for the warp, primary and panel content. You can disable this item in the template panel and they go back to normal. I know you closed this issue last year w/o resolution.
