### ISSUE TITLE
has_shortcode fails for content

### ISSUE THREAD

**Issue by LittleHamster** [siteorigin/siteorigin-panels#377]
When we place a shortcode inside a PageBuilder grid this check fails: 

```
global $post;
if( has_shortcode( $post->post_content, 'custom-shortcode') ) {
   echo "post has shortcode!";
}
```

can you guys test this and release a fix? thanks

**Comment by gregpriday** [comment]
This should all be working if you add the shortcode to a SiteOrigin Editor Widget using the latest Page Builder 2.5 beta and the recent update of the Widgets Bundle.

**Comment by LittleHamster** [comment]
@gregpriday oh okay, was testing on `2.4.25`, I guess 2.5 is going to be a major release, do you have a timeline when it is going to be released? thanks

**Comment by gregpriday** [comment]
I'm hoping for this week, but only once we're sure there aren't any major issues.

**Comment by LittleHamster** [comment]
@gregpriday cool, also do you have a zip file of the 2.5 beta to share? I downloaded the developer branch and when activating I get an error. Alex told me to sign up for a newsletter. thanks

**Comment by gregpriday** [comment]
I sent out a beta 3 to the newsletter this morning, but you can download it here: http://siteorigin.com/wp-content/uploads/2017/04/siteorigin-panels.beta3_.zip

**Comment by LittleHamster** [comment]
thanks @gregpriday :)

**Comment by LittleHamster** [comment]
@gregpriday the release got delayed?

**Comment by andrejarh** [comment]
Thumbs up for:  "A properly tested release is better than a rushed release."

Will there be another beta or RC for us to test or direct release?
