### ISSUE TITLE
Tags in widgets titles and SEO

### ISSUE THREAD

**Issue by dimitrov-adrian** [siteorigin/siteorigin-panels#38]
I think from SEO view of point widget titles shouldn't be h3 tags but div. Heading tags should be used only on article texts or kinda.

What do you think?

**Comment by gregpriday** [comment]
H3 tags do make sense to me. It's what most WordPress themes use for widget titles I would, however, like to give users the option of changing this. Even if it's only globally in the Page Builder settings.

**Comment by dimitrov-adrian** [comment]
OK, I agreed with it and with commit 46e3f94bf1e4112665e0fd907b34fc19eb40a55c

**Comment by gregpriday** [comment]
Our improved settings branch also adds a setting for widget title.

https://github.com/siteorigin/siteorigin-panels/tree/feature/feature-improved-settings-page
https://github.com/siteorigin/siteorigin-panels/commit/49efddfd13e1127f8951544c1c604aad1e95e452
