### ISSUE TITLE
Live Editor: Multiple SiteOrigin Panels on page break auto-scrolling

### ISSUE THREAD

**Issue by d--j** [siteorigin/siteorigin-panels#380]
If you have multiple SiteOrigin Panels on a Page (e.g. you use the Layout Builder in a widget area) then the auto-scrolling (hover over row/widget in the left area with mouse) scrolls to the last instance of SiteOrigin Panels (that is almost always the Layout Builder in the widget area.

Maybe changing
https://github.com/siteorigin/siteorigin-panels/blob/2.4.25/js/siteorigin-panels/view/live-editor.js#L170
to 
```js
		body.find( '#pl-' + $('post_ID').val() + ' .panel-grid .panel-grid-cell .so-panel' )
```
would fix this.

**Comment by gregpriday** [comment]
This is actually fixed in develop. There's a 2.5 release coming in the next few days.

https://github.com/siteorigin/siteorigin-panels/commit/6e5719915b35b90bb153b87e1a9fa03fec5302a6
