### ISSUE TITLE
beta 3 adding widgets bug

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#381]
I just noticed a weird bug in beta3.

If I add a row with two columns, then try to add a widget in the right column, it adds it to the column on the left instead.
Here is a demonstration: http://jmp.sh/tLSbKZJ

**Comment by gregpriday** [comment]
Well spotted @andrejarh! I'll get this fixed up.

**Comment by gregpriday** [comment]
There was just a small error in one of the checks. I fixed this up.
