### ISSUE TITLE
Flex Issue: SiteOrigin Post Carousel widget extends the page length when using FireFox

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#384]
With the new flex layout, the SiteOrigin Post Carouse widget extends the full length of the page when using FireFox

[Reference site](http://alex.siteorigin.net/siteorigin-post-carousel-widget-extends-the-page-length-when-using-firefox/)
[Reference layout](https://u.teknik.io/2ooT6.json)

Chrome:
![](https://i.imgur.com/uNKDss4.png)

FireFox:
![](https://i.imgur.com/tW1RmwJ.png)

I'm using FireFox 52.0.2.

**Comment by gregpriday** [comment]
@AlexGStapleton can you check this in the latest develop branch? Should be fixed. Do you have the build script all setup?

**Comment by AlexGStapleton** [comment]
Just tried it - all good mate.  👍

**Comment by gregpriday** [comment]
Feels good to win
