### ISSUE TITLE
beta 3 HTML validation issues

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#389]
Hi,
While building a new theme on latest beta, I tried validating the site with [W3C HTML validator](https://validator.w3.org).
This came out. 

I know it isn't a performance issue, as browsers know how to handle this, but such theme would get rejected for validation errors on WP.org or ThemeForest:

![screen shot 2017-04-14 at 18 25 35](https://cloud.githubusercontent.com/assets/10053621/25049081/36a28b06-2140-11e7-9edd-cbf5931d6872.png)

**Comment by gregpriday** [comment]
Well spotted. I fixed this up.
