### ISSUE TITLE
Max Mega Menu: Layout Builder can no longer be opened in Mega Menu editor Interface

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#394]
Since 2.5, user's are no longer able to edit the Layout Builder added to a [Max Mega Menu](https://en-au.wordpress.org/plugins/megamenu/) (100k). When the user clicks the Open Builder button, nothing happens. There's no direct reference to anything in the console, outside of Max Mega Menu reporting that the widget has been saved.

Once Max Mega Menu is installed, [please refer to this video](https://drive.google.com/a/siteorigin.com/uc?id=0BymU-6VMHHPfaWVFTk1fVzhhM1E) on how to replicate this issue.

It should be noted that SiteOrigin Widget Bundle widgets also appear to no longer work, although they have an error message. That may or may not be related. Let me know if you would like me to log that. For reference, the error message for those widgets is:

> This widget has scripts and styles that need to be loaded before you can use it. Please save and reload your current page.

**Comment by silentdude56k** [comment]
Seems to be fixed as of the June 7th 2.3.7.1 Max Mega Menu update. Running:

- WordPress 4.7.5
- Page Builder 2.5.4, 2.5.5 (2.4.25 continues to work too)
- Widgets Bundle 1.9.1
- Max Mega Menu 2.3.7.1

**Comment by AlexGStapleton** [comment]
According to the [change log for Max Mega Menu](https://en-au.wordpress.org/plugins/megamenu/#developers), this was fixed in 2.3.7.

**Comment by liquida** [comment]
Hello guys

I this plugin have been outdated for a while. It haven't importanted updates in the last year

Maybe you can try whit this new mega menu https://wordpress.org/plugins/quadmenu/

**Comment by AlexGStapleton** [comment]
The last update for Max Mega Menu was actually a month ago. Regardless, we'll make a note of your suggestion.

**Comment by AlexGStapleton** [comment]
This issue appears to be occurring again as of Max Mega Menu 2.5.
