### ISSUE TITLE
Legacy layout engine fails to detect older browsers

### ISSUE THREAD

**Issue by LittleHamster** [siteorigin/siteorigin-panels#396]
I set "Use Legacy Layout Engine" to "Detect Older Browsers" because of compatibility issues. I tested on Firefox 5 and 17 and it fails to detect and use floats instead of flex boxes. So everything is left aligned. I had to change it to "always" to get it working. 

I also use a cache plugin if that changes anything. Anyone else had this issue?

**Comment by gregpriday** [comment]
A caching plugin will more than likely break this feature. Have you tested with the caching plugin disabled? I'll investigate if caching plugins have a way of disabling cache in certain instances.

**Comment by LittleHamster** [comment]
@gregpriday I have not tested with caching disabled. I tried to test it with/without it and I can't install caching plugin on localhost. Just the live site where I set it to "always" and it is working.

**Comment by Misplon** [comment]
Hi @LittleHamster. Please, can you let us know which caching plugin you're using. If the plugin has settings to exclude files we can hopefully document how to avoid this issue.

**Comment by LittleHamster** [comment]
@Misplon 
sorry this issue was submitted almost a year ago 😁 
I no longer use this page builder

**Comment by Misplon** [comment]
Thanks for the quick reply, appreciate it. All the best :)
