### ISSUE TITLE
Advanced Custom Fields

### ISSUE THREAD

**Issue by vipii** [siteorigin/siteorigin-panels#397]
Hello,

I am using https://nl-be.wordpress.org/plugins/acf-page-builder-field/ on my WordPress.
But since the latest update I am getting this error:
Fatal error: Call to undefined function siteorigin_panels_generate_css() in /wp-content/plugins/ACF-Page-Builder-Field/acf-page-builder-field.php on line 268

How can this be fixed?
Line 268:

if( !isset($acf_siteorigin_panels_inline_css[$post_id]) ) {
            wp_enqueue_style('siteorigin-panels-front');

            $acf_siteorigin_panels_inline_css[$panel_id] = siteorigin_panels_generate_css($post_id, $panels_data);
        }

**Comment by vipii** [comment]
Full file:
https://pastebin.com/b3BV7zTh

Where does it needs to be updated and into what?

**Comment by gregpriday** [comment]
Thanks for letting us know about this. It looks like that plugin was relying on a function that we removed in a refactor. I've readded it, so everything should be working properly in the next update. Keep an eye out for 2.4.3.

https://github.com/siteorigin/siteorigin-panels/commit/c8da173f270c797980774cbbe4eb144d847daa63

**Comment by vipii** [comment]
Can you confirm that the rest of the code will work also?
Like "siteorigin_panels_start_style_wrapper"?

Thanks!

**Comment by AlexGStapleton** [comment]
It looks like the developers are working on 2.5 support Angrycreative/ACF-Page-Builder-Field#11

**Comment by bullpillaren** [comment]
Hi! Yes, we are working on support for 2.5. It's just a hotfix thoug,. we'll probably do a rewrite of the plugin sometime soon.

Anyway, the hotfix will probably be released sometime today.

**Comment by AlexGStapleton** [comment]
@bullpillaren Awesome! :) Let me know if you run into any issues with any of the code changes in SiteOrigin Page Builder.

**Comment by vipii** [comment]
We have updated the plugin and it looks like most of the issue's are gone.
Still this one is showing:

Warning: explode() expects parameter 2 to be string, array given in /home/cheopsbe/public_html/wp-content/plugins/siteorigin-panels/inc/styles.php on line 337

Warning: array_merge(): Argument #2 is not an array in /home/cheopsbe/public_html/wp-content/plugins/siteorigin-panels/inc/styles.php on line 337

**Comment by bullpillaren** [comment]
@vipii Have been working on a fix for this [here](https://github.com/Angrycreative/ACF-Page-Builder-Field/tree/PB-2.5-fix). You're more than welcome to test it out!
