### ISSUE TITLE
SiteOrigin IE Support

### ISSUE THREAD

**Issue by vipii** [siteorigin/siteorigin-panels#401]
When will there IE support?
Because the pages look really terrible in IE made with this plugin :/

**Comment by vipii** [comment]
After the update our pages are like this:
https://www.cheops.be/onze-aanpak/

**Comment by gregpriday** [comment]
We've tested with IE, all the way back to version 8 using Browser Stack. Can you give more specific examples of how it's not rendering properly for you? Are you having issues with layouts or the widgets placed in layouts?
