### ISSUE TITLE
Warning: explode() expects parameter 2 to be string, array given in /home/cheopsbe/public_html/wp-content/plugins/siteorigin-panels/inc/styles.php

### ISSUE THREAD

**Issue by vipii** [siteorigin/siteorigin-panels#402]
Need a hotfix for this issue:

Warning: explode() expects parameter 2 to be string, array given in /home/cheopsbe/public_html/wp-content/plugins/siteorigin-panels/inc/styles.php on line 337

Warning: array_merge(): Argument #2 is not an array in /home/cheopsbe/public_html/wp-content/plugins/siteorigin-panels/inc/styles.php on line 337

Being displayed on:
https://www.cheops.be/over-cheops/

Can't have this error live for long.

**Comment by AlexGStapleton** [comment]
This is related to #397

Based on [the plugin's forums](https://wordpress.org/support/topic/latest-site-orgins-update-causes-fatal-error/) this is likely related to their implementation and not related to SiteOrgin Page Builder specifically.

**Comment by gregpriday** [comment]
It seems like this error is related to improper arguments coming into the `general_style_attributes` function. As @AlexGStapleton pointed out, these arguments are coming from outside Page Builder. Page Builder gets the value of `$style[ 'class' ]` from a string input field, so it'll always be a string.

These are just warnings, you can disable error reporting on your site to get rid of them. This is recommended for production sites.

I'll add some error checking to handle incorrectly formatted arguments.
