### ISSUE TITLE
Saving Previews will actually save page

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#404]
Making a change via Page Builder and then previewing said change will actually save the page. This was previously not the case. This issue is not related to the content cache.

**Comment by perkaby** [comment]
Hi, 

Any news on this? We had this problem with WP 4.7.5 and Page Builder 2.5.7 and still have the problem after upgrading to WP 4.8 and Page Builder 2.5.8. 

The issue is that when you click Preview on a page with Page Builder, the page gets saved and published. This must be a major issue?
