### ISSUE TITLE
Legacy Layout: Collapse Order doesn't work

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#406]
The Legacy Layout doesn't currently allow for the collapse order to be changed. This is problematic as certain layouts need to be displayed in a certain order on mobile devices to look correctly.

**Comment by braamgenis** [comment]
Is this still an issue? If so could you please post steps to reproduce.

**Comment by AlexGStapleton** [comment]
This is still an issue. Please navigate to **WP Admin > Settings > Page Builder** and open the **Layout** tab. Set **Use Legacy Layout Engine** to **Always** and then save. Create/open a page and add a new row. Set the **Collapse Order** to **Right on Top**.

Add a basic widget (I used an archive and categories) to each column and then view them on mobile. The first column will appear on top when the right column should be on top.
