### ISSUE TITLE
live editor js error

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#408]
While working with live editor, I occasionally get this error:
![screen shot 2017-05-04 at 14 58 07](https://cloud.githubusercontent.com/assets/10053621/25704849/70625bdc-30db-11e7-9a00-686ea76076a1.png)

I don't know how why exactly it appears or how to replicate it. If I notice some logic why this error is appearing, I will send more info.

**Comment by andrejarh** [comment]
Also, while we're at it, not an error, but still:

![screen shot 2017-05-04 at 16 13 50](https://cloud.githubusercontent.com/assets/10053621/25707833/0a31acbe-30e5-11e7-8827-1bb5c145c07e.png)

**Comment by andrejarh** [comment]
additional errors (live editor)
![screen shot 2017-05-04 at 16 36 20](https://cloud.githubusercontent.com/assets/10053621/25708917/3165ffa8-30e8-11e7-9c23-38b0af9c2ef7.png)

**Comment by Misplon** [comment]
Hi @andrejarh Sorry we weren't able to reply sooner. Do you know if this bug is still occurring? We aren't currently able to replicate which is why we ask. Thanks.

**Comment by andrejarh** [comment]
Currently I don't see it. But if I see it again, I will report it.

**Comment by Misplon** [comment]
Super, thanks for taking a look.
