### ISSUE TITLE
Add new filters to print custom HTML inside of the row element

### ISSUE THREAD

**Issue by ste93cry** [siteorigin/siteorigin-panels#412]
I'm raising this issue because I found out some difficulties in adapting the builder to print a custom structure. In particular, I would like to add custom HTML after the opening tag of a row and obviously before the closing tag. Currently there is a filter called `siteorigin_panels_before_row` that can print HTML, but as the name says it's executed too early, and the same applies to the `siteorigin_panels_after_row` filter. It would be great if there was another filter or, even better, add a generic filter that's triggered in the `render_element` function of the `SiteOrigin_Panels_Renderer` class. This way we could even personalize the tag itself that's printed (for example I would like to print a `section` tag instead of a simple `div` tag).

**Comment by AlexGStapleton** [comment]
This PR is resolved by https://github.com/siteorigin/siteorigin-panels/commit/89c7c7a74ef27b471c5f78b45bcaa74fafb74aa6 which introduced siteorigin_panels_inside_row/cell_before/after filters. That commit was included in the 2.12.0 Page Builder update. Here is the pending documentation for these filters:

https://github.com/siteorigin/docs/pull/100
