### ISSUE TITLE
Is there $widget['panels_info']['cell_index'] removed from version2.5.0?

### ISSUE THREAD

**Issue by suganyaselvakumar** [siteorigin/siteorigin-panels#413]
Hi,

I am using your pagebuilder for about 2 and half years now. It helped us a lot and build there own layouts. Thanks & Very nice and brilliant job.

Is there $widget['panels_info']['cell_index'] removed from version2.5.0?

I customized page builder using filter "siteorigin_panels_css_object".(e.x)
 /* Widget text decoration */
foreach ($panels_data['widgets'] as $widget_id => $widget) { 

  if (!empty($widget['panels_info']['style']['link_text_decoration']) ) {

    $selector = '#pg-'. $post_id . '-' . $widget['panels_info']['grid'] .' #panel-' . $post_id . '-' . $widget['panels_info']['grid'] . '-' . $widget['panels_info']['cell'] . '-' . $widget['panels_info']['cell_index'] . ' a';
    $css->add_css( $selector, array(
      'text-decoration' => $widget['panels_info']['style']['link_text_decoration']
    ) );
  }           
}

but after update the v2.5.0. cell_index is missing and it inducing  "Undefined index: cell_index" notice.

Is there any way to rectify this problem?

**Comment by gregpriday** [comment]
It wasn't intentionally removed - it's still being generated [here](https://github.com/siteorigin/siteorigin-panels/blob/develop/siteorigin-panels.php#L456). Maybe there's a situation where it's not available though. Which action or filter are you using to trigger your code?

**Comment by suganyaselvakumar** [comment]
Hi,

Thanks for the quick response.
I used "siteorigin_panels_css_object" filter and for your reference attached the file here.
[example-code.txt](https://github.com/siteorigin/siteorigin-panels/files/998338/example-code.txt)

Thanks @gregpriday

**Comment by suganyaselvakumar** [comment]
Page Builder Data doesn’t show up in HTML source

After update the v.2.5.0 ,
the problem is that it isn’t showing the Page Builder Data in the HTML Source, even when I put the two lines in my wp-config,php to enable the debug mode:
define('SITEORIGIN_PANELS_NOCACHE', true);
define('SITEORIGIN_PANELS_DEV', true);

less than v.2.5.0 is working fine.
