### ISSUE TITLE
outdated FontAwesome

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#415]
Hi,
I just noticed pagebuilder still uses version 4.6.3 of FontAwesome.
Currently version if FA is 4.7.0  where 41 new icons were added.
![screen shot 2017-05-13 at 11 20 05](https://cloud.githubusercontent.com/assets/10053621/26024243/2f9c05a4-37ce-11e7-9d87-be6839d31c06.png)

**Comment by AlexGStapleton** [comment]
Hi @andrejarh,

To confirm, are you refering to the icons included with the SiteOrigin Widgets Bundle? If so, the latest icons will be included in the next WB update. Reference: siteorigin/so-widgets-bundle#474

**Comment by andrejarh** [comment]
Great!
Yes, I was referring to the bundle... sorry for confusion.

**Comment by Misplon** [comment]
Thanks for your feedback @andrejarh. I'll close this for now. If there are any issues with the Widgets Bundle update, please, open an issue there and we'll attend ASAP. Cheers :)
