### ISSUE TITLE
Content Cache: Password Protected pages don't work

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#418]
When the content cache setting is enabled, password protected pages display nothing rather than the password form.

You can see this issue [here](http://alex.siteorigin.net/content-cache-password-protected-post-test/).

**Comment by gregpriday** [comment]
Resolved by https://github.com/siteorigin/siteorigin-panels/commit/6457fba06aa647d4d3e5b79ecf72281520b10bb6
