### ISSUE TITLE
PHP Notice: Undefined index: row_styles

### ISSUE THREAD

**Issue by katart** [siteorigin/siteorigin-panels#419]
I've been using some custom code to add a Select field to add custom options to a Row Style. Here is the code:
```
// Add Custom Class Options to SiteOrigin Rows
add_filter( 'siteorigin_panels_row_style_fields', 'custom_row_style_fields' );
function custom_row_style_fields($fields) {
	$row_styles = array(
		'default-row-style' => 'Choose Style',
		'row-notification' => 'Notification'
	);
		
	$fields['row_styles'] = array(
		'name' => __('Row Styles', 'siteorigin-panels'),
		'type' => 'select',
		'options' => $row_styles,
		'group' => 'attributes',
		'description' => __('Choose a style option for this row of content', 'siteorigin-panels'),
		'priority' => 1,
	);

	return $fields;
}

add_filter('siteorigin_panels_row_style_attributes', 'custom_row_style_attributes', 10, 2);
function custom_row_style_attributes( $attributes, $args ) {
	if( $args['row_styles'] != 'default-row-style' ) {
		array_push($attributes['class'], $args['row_styles'] );
	}

	return $attributes;
}
```
This code is throwing the following error:

```
[01-May-2017 13:29:39 UTC] PHP Notice:  Undefined index: row_styles in /xx/xx/xx/wp-content/themes/edmond/functions.php on line 223
[01-May-2017 13:29:39 UTC] PHP Notice:  Undefined index: row_styles in /xx/xx/xx/wp-content/themes/edmond/functions.php on line 224
```

Line 223 is `if( $args['row_styles'] != 'default-row-style' ) {`
Line 224 is `array_push($attributes['class'], $args['row_styles'] );`

Any ideas why?

**Comment by AlexGStapleton** [comment]
That's happening as $args['row_styles'] doesn't exist. You should change line 223 to:

`if( ! isset( $args['row_styles'] ) || $args['row_styles'] != 'default-row-style' ) {`

Change line 224 to something other than array_push. Maybe something simple like:
`$args['row_styles'] = $attributes['class'];`

**Comment by katart** [comment]
Thanks for the tip @AlexGStapleton.

If I don't use `array_push()` then only the selected option would be the class set for that element. I want to add a new class to the element without removing the default classes inserted by the Site Origin plugin. Is that correct?

**Comment by katart** [comment]
@AlexGStapleton I'm still getting the PHP Notice with your modified code. 

The code works fine (the selected row_styles class is being inserted into the element, but PHP Notice is still being written to the debug.log.

**Comment by AlexGStapleton** [comment]
Ah. I see what you mean now. Replace line 223 to:

`if(  isset( $args['row_styles'] ) && $args['row_styles'] != 'default-row-style' ) {`

Replace 224 with:
`$attributes['class'][] =$args['row_styles'];`

Oh. I, for whatever reason had thought you wanted to replace the classes. Replace the array_push line with:

**Comment by katart** [comment]
Thanks for the help @AlexGStapleton That fixed it!
