### ISSUE TITLE
Unable to use Page Builder on Event pages powered by Events Manager

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#421]
Since the 2.5 release, you're unable to use SiteOrigin Page Builder on event pages by Events Manager (100k). Upon saving a page, all page builder related data is lost (bar exception to copied content data). This will happen for new and existing events.

**Comment by Misplon** [comment]
Confirmed. Looked at this today.

Previously, it was also possible to use Page Builder with:

ACF
ACF Pro
[ACF Page Builder Field](https://github.com/Angrycreative/ACF-Page-Builder-Field)

The Builder in ACF Page Builder Field no longer opens. Doubt this is related but means this workaround option is gone for the moment.

**Comment by AlexGStapleton** [comment]
Hold up - that last one should be resolved after #397 and a number of compatibility patches from them (they implemented a custom renderer which broke due to the recode in 2.5). Is it not working again? :(

**Comment by Misplon** [comment]
Working fine in pages, not working in custom post types like events.

**Comment by AlexGStapleton** [comment]
Are you talking about the events manager plugin or ACF Page Builder Field? Just to clarify, I was talking about the latter (I'm sorry if I wasn't very clear!).

**Comment by Misplon** [comment]
I'm talking about the ACF Page Builder Field. From what I can tell, at the moment, it won't open in an event but will open in a page. CPT, not working, pages look like they're working.

**Comment by Misplon** [comment]
Can test locally tomorrow to confirm this.

**Comment by AlexGStapleton** [comment]
ah. Gotcha.

**Comment by Misplon** [comment]
Ok, just the main issue then. The issue I was having, not being to open  the ACF Page Builder Field was because Page Builder wasn't enabled for the CPT. Page Builder needs to be enabled for the CPT for the Open Builder button from the ACF Page Builder Field plugin to work.

**Comment by braamgenis** [comment]
@AlexGStapleton So this is being caused by the Events Manager plugin changing and overwriting `panels_data` post meta. It worked previously because their code was running before ours, but now when copy content is enabled we trigger another `save_post` which then causes their code to run again and overwrite our saved post meta with incorrectly serialized data. I think this should be up to them to fix and it may be as simple as them just making sure they don't run `save_post` filters more than once.

**Comment by AlexGStapleton** [comment]
I'm confused. Previously (as in, pre 2.5) wasn't Copy Content also triggering a save_post? If so, why didn't this issue occur then? I may be overthinking things though.

**Comment by braamgenis** [comment]
There was no copy content pre 2.5. :smile: Even if there was, the fact remains that their code is making changes to post meta fields without first verifying whether those fields were set by them.

**Comment by AlexGStapleton** [comment]
You're thinking of the content cache. Copy Content was introduced before 2.3 (that's the earliest I can see reference to it in the change log).

Okay, that's fine - just wanted to be sure before I passed the news on. Thanks for looking into this!

**Comment by braamgenis** [comment]
I think you may be right.  ¯\_(ツ)_/¯
