### ISSUE TITLE
Additional Collapse Behaviour options

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#422]
We should expand the recently introduced Collapse Behavior settings with additional options. Here are a few possible options:

- Collapse on tablet (only shows if tablet layout isn't enabled)
- Don't collapse on tablet (only shows if tablet is enabled)

Suggestions are more than welcome.

**Comment by andrejarh** [comment]
Not sure if it helps, but this is how we implemented it in our Dentalia theme:
<img width="279" alt="screen shot 2017-05-25 at 22 20 30" src="https://cloud.githubusercontent.com/assets/10053621/26468960/a8b400bc-4198-11e7-93c8-c265b4baae7c.png">

**Comment by AlexGStapleton** [comment]
Hm. I like that system more overall. @gregpriday Thoughts?
