### ISSUE TITLE
Attributes: Custom CSS stopping responsive CSS from outputting correctly

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#423]
Row level Custom CSS is stopping responsive grid CSS from outputting as required, thereby breaking responsive behaviour.

Reminder: @gregpriday we looked at this in Slack with a users JSON layout.

_Generating this code `@media (max-width: 768px){;font-size: 0.5em }`_

**Comment by gregpriday** [comment]
So the actual reason for this issue is the layout has the following entered under CSS styles for a widget.

```
@media (max-width: 768px){
font-size: 0.5em;
}
```

That field doesn't support media queries, but we do have mobile CSS so they can use `font-size: 0.5em;` in the mobile CSS field.

I'll add some better error checking.

**Comment by Misplon** [comment]
Ahhh!!!
