### ISSUE TITLE
Row ID and Class Improvements

### ISSUE THREAD

**Issue by ingageco** [siteorigin/siteorigin-panels#426]
Hey team - 

I find the Row ID feature to not be as powerful, IMO, as it should be due to the fact that it's applied to a wrapper inside the actual row. 

For instance, here's the case of a row that I have:
#pg-2-0 (div generated as a true row)
#pg-2-0 > .custom-class or #row-id 
#pg-2-0 > .custom-class or #row-id > individual columns

It seems to me that it would be much more flexible for styling if the row-id or custom class was applied at the top level div - allowing for styling ALL elements within that row. 

This would allow for keeping content contained while extending the background full-width - a common style in many sites. 

With the current setup, you could achieve this by styling the #pg-2-0 as the background and putting a max-width, margin-left/right: auto on the "style div". But what happens if this row is moved up or down in the page row order? In my experience, #pg-2-0 would be rewritten, negating all style applied. 

Is there any possibility you would consider adding an entire-container class/id option for the main root div for a row? Maybe this option exists and I'm missing it?

**Comment by AlexGStapleton** [comment]
Row IDs aren't really intended to be used for custom styling and are more designed page builder using them row structure and the like (which is why they're able to change by row movement). Ideally, you should either apply a custom row id or row class and apply styling via that. Custom row ids/classes are applied to the row's container class - panel-row-style.

For reference, you can apply a row id or class by opening a row and heading over to the row styles sidebar. Open the Attribute Settings group and set the row id or class as desired.

It should be noted that your example use case is possible without CSS. Simply set the row layout to full width and set a background image as desired. The full width row layout is the full width of the page with a content container.

**Comment by ingageco** [comment]
I understand that the current row IDs are used for the page builder's function - but again, there is no way for us to target that via CSS with reliability since the IDs change. Im aware that the custom row-ids/classes are applied to panel-row-style - but that's the issue - it's limiting. We could easily target that div if custom IDs/classes were added to the root builder Row div. 

I checked out the full width row layout - but it's still the same limitation. I know the case I mentioned is possible without CSS - but the point is other options that are only available with css. Say I wanted to apply padding to #pg-0-1 (because i have a different padding on the panel-row-style div, or even a different background) - but then move it around after it's in place. That's missing. 

It would be much less limiting if Row ID and Custom Class were actually applied to the row and not to the inner wrapper (panel-row-style) class. Then we could use that ID to target EVERYTHING to do with that row. We can't do that now - we can only target the wrapper holds the columns. And if I target #pg-0-1 - it's going to change if I move it. 

Can you help me understand why this would not be an option? Or not be considered? Is there a good case for NOT having this option? This option would save time for us in that we could have CSS pre-built for the entire block, and when the row-id or class is applied, we can move it around without a problem. 

BTW - i'm a big fan of the builder. Just trying to improve it through feedback.

**Comment by ingageco** [comment]
I guess what I'm saying is there are two places the custom Row Id / class can be applied: 

- The root row div, which gives control over the entirety of the block
- where you have it currently, which makes the root div unreachable using that field. 

It doesn't seem feasible that most would not want it on the root div if given the option.

Id just like to see some sort of option - a filter, a setting - some option to make that apply to the root div for even greater control.

**Comment by AlexGStapleton** [comment]
I'm really not sure of a possible use case that can't be accomplished with a custom row id or class. If you're looking to apply padding to the row, why couldn't you just apply it directly to the row itself (without CSS)? If you're looking to apply spacing outside of a border or something like that, you could use margin (you can still have it be full width and centered by setting the row layout). I'm all for making a change but I really can't think of an actual limitation of the current system (as in, something you literally can't do).

Regardless, there is a filter that will allow you to do this - [siteorigin_panels_row_attributes]([url](https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/renderer.php#L632)). Example usage can be seen [here](https://gist.github.com/AlexGStapleton/e2adc03741fafe47e2539ee4a73c825b).

**Comment by ingageco** [comment]
Alex - Say i want to control :before and :after attributes - there's one case. The main point I'm trying to make is code automation. 

I know i can achieve adding a background color to the root div  _using the builder properties_ - but the goal here is code automation and style automation. If I have a CSS file, say generated via Sass, where i change colors, etc, i can't control the root div's color via CSS without using the page builder's controls. With the current setup, if I added a row ID of #videos and wanted the root row - the #pg-0-2 div to be the one with a gray background, and the inner container (currently panel-row-style) to have a white background **just from adding a class** , I cannot do that.  And in my opinion, that's a valid use case for a custom row ID or class ID - to be able to control the entire row - not just the inner content of the row. 

#pg-0-1#custom -- orange bg
#pg-0-1#custom .panel-row-style -- white bg
#pg-0-1#custom .panel-row-style .widget -- another bg color

Does that make sense?

Will that filter allow me to globally move the custom row ID or class to the root div rather than the .panel-row-style div? If so, that would be great.

**Comment by AlexGStapleton** [comment]
Okay, yeah, I can see that as a possible use case. Although, it's a very obscure one. It's up to @gregpriday if this gets changed but due to the workarounds due to filters and the intentional reluctance to change the structure, it's unlikely to happen (changing structure will absolutely cause design issues for people), I don't think it'll change.

> Will that filter allow me to globally move the custom row ID or class to the root div rather than the .panel-row-style div? If so, that would be great.
No, you'll need to use an additional filter for that - [siteorigin_panels_row_style_attributes](https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/renderer.php#L313) or [siteorigin_panels_row_style_classes](https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/renderer.php#L344). Filter for the class and remove it based on the row class.

**Comment by ingageco** [comment]
If the current setup is working for you guys, great. All I'd like is an option - even via a filter - that would allow me to state for it to be applied to the root div instead of the style div. Maybe like: 

apply_filter('siteorigin_panels_style_root_div', 'apply_to_root' );

function apply_to_root($var){
return true;
}

All this would do is move the custom row ID / class to the root (#pg-0-1) div instead of the style div globally for all rows.

What I love about SO Panels is that it's simple and lightweight, but powerful. Its a builder I can use within our current processes and not have to completely commit to the "build a site with a builder" mentality (as a developer, that's extremely hard, but i need systems for our sites). Im sure many others might feel the same way.

I appreciate your consideration of this @gregpriday  -- I feel that if this option was available and other devs knew about it, they might use it as well.

**Comment by gregpriday** [comment]
Thanks for your awesome feedback @ingageco - yeah, keeping things light weight is exactly what we're going for. I've never thought about it that way, but your line:

> Its a builder I can use within our current processes and not have to completely commit to the "build a site with a builder" mentality

Is exactly what we're going for.

As for the row IDs - this is actually how the custom ID feature used to work, but it was a little bit of a headache because we then had to output the correct IDs in our generated CSS. Any addon plugins also needed to check for the ID field rather than using the more implicitly generated IDs.

I'd be more than happy to add a few filters to make this functionality possible though. Knowing what I know from the previous implementation though, this is rather tricky.

**Comment by ingageco** [comment]
@gregpriday The ID isn't really what is needed - it's just a way to apply a custom class to that div. That's all I want :)

My recommendation would be just to allow a custom class to be added at that level. If you didn't allow divs at that level because of the ordering, that would make total sense as a limitation because of your style generation from the back-end.

**Comment by gregpriday** [comment]
Aaah right, sorry, I should have got the run down from @AlexGStapleton before replying. Yeah, adding classes is significantly easier.

**Comment by ingageco** [comment]
Hey Guys - here is the perfect illustration of the limitation I described in this issue:

See the blue row in this screenshot: https://cl.ly/2x411l3u3Q3C

This is what is desired - not possible with row configuration: https://cl.ly/3L3G3i011H2W

The only way to achieve a blue background WITH the content remaining in the middle "container" area (see the white row below) is to use CSS to style this outer row (that has the ID of #pg-2-1) as a blue background. But if this row is removed, #pg-2-1 will be the next row down, adding the blue background to it. 

The ability to apply custom class to the outer row would solve this, allowing for more CSS control and customization of a specific row. 

This is exactly the scenario I was describing previously, so i wanted to add it here for a better reference to the context. Thanks!

**Comment by AlexGStapleton** [comment]
You should be able to accomplish that setup by setting the `row layout` to `full width`. To clarify, the full width row layout is a row with a content container. This allows you to set a full width background and still have the content centered like in your desired screenshot.

**Comment by Corbyj1** [comment]
Hi, 

I'm having similar issues after developing a clients site based on how the site ID's _used_ to behave. You can find the issue logged here - [here](https://siteorigin.com/?post_type=thread&p=60895)

My use-case was more that I had a max-width applied to root level of each individual row and certain ID's/classes excluded this max-width. Now the site is completely broken design wise (which you mention changing to the old system would cause many design issues - rather ironic considering this update caused the exact issue your wanting to now avoid). 

I agree that there are definitely use-case scenarios for the old ID/class layout system to work the way it previously did, especially when many developers will have built sites around that system. Is there any update on a way around this? As currently I face the daunting task of checking through every single page on local/staging environments to determine what is broken and where I need to apply the new classes/ID's.

Any help would be greatly appreciated, thanks.

**Comment by petemolinero** [comment]
If you'd like to move all custom classes from the style wrapper to the top-level row div, you can do it with the following filters:

```php
/**
 * Add custom classes to the row itself
 *
 * @param    array   $row_classes   the current row classes
 * @param    array   $row           the row data
 * @return   array                  the modified row classes
 */
function custom_so_add_row_parent_classes( $row_classes, $row )
{
    $classes = ( isset( $row[ 'style' ][ 'class' ] ) )
        ? explode( ' ', $row[ 'style' ][ 'class' ] )
        : array();

    $merged = array_merge( $row_classes, $classes );
    return $merged;
}
add_filter( 'siteorigin_panels_row_classes', 'custom_so_add_row_parent_classes', 10, 2 );

/**
 * Remove custom classes from the row style wrapper
 *
 * @param    array   $attrs    the current row attributes
 * @param    array   $style         the row style data
 * @return   array                  the modified row attributes
 */
function custom_so_add_row_subdiv_classes( $attrs, $style )
{
    $attrs[ 'class' ] = array();
    return $attrs;
}
add_filter( 'siteorigin_panels_row_style_attributes', 'custom_so_add_row_subdiv_classes', 10, 2 );
```

**Comment by Misplon** [comment]
@petemolinero Thanks for posting your custom solution here.
