### ISSUE TITLE
Vertical alignment custom option causes error in CSS output.

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#427]
This issue is related to this pull request: 
https://github.com/siteorigin/siteorigin-panels/pull/417

Vertical alignment options are currently limited to flexbox and are not extendable beyond it.

**Comment by Misplon** [comment]
Hi Andre

Thanks for your efforts. I'm going to close this for the moment as the PR was closed. It looks like Braam had some feedback in the PR.
