### ISSUE TITLE
Unreadable widget titles

### ISSUE THREAD

**Issue by dimitrov-adrian** [siteorigin/siteorigin-panels#43]
In some cases where widget have long titles, the text could became unreadable.

![screen shot 2015-03-10 at 21 44 35](https://cloud.githubusercontent.com/assets/1009639/6584204/45420ada-c772-11e4-88fa-edc9e2d2b915.png)

I think (also have tested), the problem could be fixed if we set these list items to be **inline-block** instead of **list-item** which is default for <li /> elements

So possible fix here is

tpl/js-templates.php
```
<li class="widget-type" style="display:inline-block;">
```

and css/admin.css in rule
```
.so-panels-dialog.so-panels-dialog-add-widget .widget-type-list .widget-type
```
we could add ```vertical-align: top;``` to ensure they will be nicely arranged

**Comment by gregpriday** [comment]
This is something I've been meaning to fix for a while now. Turns out, it was actually fairly easy. I've committed to the develop branch of you want to take a look.

https://github.com/siteorigin/siteorigin-panels/commit/0be98717f979deb673f72fc4e19cef686e246b97

**Comment by gregpriday** [comment]
Something else I'd like to do is add some JS to match the height of all the widgets in a given row. Just to neaten things up a little bit.

**Comment by gregpriday** [comment]
Just added Javascript based height balancing. Still need to test this fully, but it's a decent start.

https://github.com/siteorigin/siteorigin-panels/commit/f25a0b1

![screen shot 2015-03-11 at 6 50 33 am](https://cloud.githubusercontent.com/assets/1126859/6590612/f6d53798-c7ba-11e4-8fa5-556d53f4dc38.png)

**Comment by cmwwebfx** [comment]
Stunning work @gregpriday 
Much nicer

**Comment by dimitrov-adrian** [comment]
Yeah, look better :) Unfortunately have no IE to test.

**Comment by tareiking** [comment]
@gregpriday Really like how the balancing is on a row basis vs. all blocks get the max. height applied - nice work.

@dimitrov-adrian You can test IE both remotely and locally via : http://www.browserstack.com/

**Comment by braamgenis** [comment]
Tested with IE9 (from [modern.ie](https://www.modern.ie/en-gb/virtualization-tools)) and IE11 and it looks like it's working well. Nicely done. @gregpriday
