### ISSUE TITLE
Make it easier for other plugins to embed a builder interface

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-panels#434]
At the moment, it's fairly complicated to embed for other plugins to embed a builder interface. It would be much easier if we had a single helper class available to other plugin developers.

The helper class should handle enqueuing and generating all the HTML necessary for the builder.

Once place we'd use it internally is for the Layout Widget.

https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/widgets/layout.php

**Comment by RajeebTheGreat** [comment]
Any update on this?

**Comment by Smartik89** [comment]
Yes, please. I was looking for solution on this. But I had no idea where to start.

**Comment by gregpriday** [comment]
Going to close this because it's not really essential. A helper class would be great, but I'd prefer to focus our resources on improving the core Page Builder experience.

The [Layout Widget](https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/widgets/layout.php) is a very stable implementation to use as a reference for anyone wanting to embed a Page Builder interface.
