### ISSUE TITLE
Panel grid cell styles ignored due to cell container

### ISSUE THREAD

**Issue by alenb** [siteorigin/siteorigin-panels#437]
Hey guys,

I've noticed that panel grid cell styles are ignored, because the cell itself is wrapped inside a cell container.

Here's a rough example:

```
<div class="panel-row-style panel-row-style-for-w5940bba937777-1">
    <div id="pgc-w5940bba937777-1-0" class="panel-grid-cell"> <!-- cell container -->
        <div class="hidden-sm hidden-xs panel-cell-style panel-cell-style-for-w5940bba937777-1-0"> <!-- actual cell -->
```
If I tell it to remove the margin, it ignores it, because there's a margin on the cell container.

![image](https://user-images.githubusercontent.com/659296/27115806-78982a2a-5110-11e7-9a59-308185cd8b1a.png)

**Comment by electrosick** [comment]
ads
