### ISSUE TITLE
Unable to enable WooCommerce Product Reviews

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#439]
Oddly, when SiteOrigin Page Builder is enabled for the Products post type, you're unable to enable reviews for a product as upon saving the checkbox is unset.

![](https://vgy.me/Sa82JK.png)

**Comment by AlexGStapleton** [comment]
I ran a version check - this has been happening since 2.5. 😿

**Comment by AlexGStapleton** [comment]
@braamgenis if you disable the content cache this issue doesn't occur. If the content cache is enabled and you disable this the [wp_update_post()](https://github.com/siteorigin/siteorigin-panels/blob/2.5.6/inc/admin.php#L204) it won't occur either.

**Comment by braamgenis** [comment]
This still happens for me with  content cache disabled.

**Comment by AlexGStapleton** [comment]
Oh! Sorry, I meant copy content.  Please try it _without_ copy content enabled.

**Comment by AlexGStapleton** [comment]
@braamgenis Awesome. :)
Does this technically also fix #416? In hindsight, this may be the exact same issue.
