### ISSUE TITLE
Redirect Custom Home Pages to standard Pages interface

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#441]
Redirect Appearance > Home Page to Pages > Home.

**Comment by AlexGStapleton** [comment]
I'm really happy about this. 👍

**Comment by gregpriday** [comment]
The main challenge will be how to handle creating new pages in the same way they were created in the home page interface. All easy enough though.

**Comment by gregpriday** [comment]
There are a few too many challenges here. It'll probably bring up more support issues by removing this from our themes as it would reduce by removing it. For now, we'll just make sure we don't use this in any future themes.
