### ISSUE TITLE
Widget Logic plugin doesn't work when used in page builder

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#442]
[Widget Logic](https://wordpress.org/plugins/widget-logic/) (300k) doesn't work on widgets added via SiteOrigin Page Builder. Content cache doesn't help so it doesn't appear to be a priority issue.

**Comment by braamgenis** [comment]
Their code uses sidebars to get widget instances and check whether they have any widget logic. When the widget logic determines that a widget shouldn't be displayed they simply unset the widget id from the sidebar. PB merely emulates a sidebar but isn't actually using the sidebar to determine whether or not widgets should be displayed. I'd be hesitant to allow the emulated sidebar to override PB's data as it could have unintended side-effects.

**Comment by AlexGStapleton** [comment]
If you don't think it's a good idea (which is totally fine), then I don't think we should worry about compatibility with this plugin. I'll try and find an alternative plugin.
