### ISSUE TITLE
Always Default to Visual Tab

### ISSUE THREAD

**Issue by maglio** [siteorigin/siteorigin-panels#444]
As of WordPress 4.8, SiteOrigin panels always default to the Visual tab.

Related: when selecting "Disable the visual editor when writing" from User profiles as a workaround, the Visual and Text tabs continue to show up.

**Comment by AlexGStapleton** [comment]
Unfortunately, I can't seem to disable this issue. To clarify, is the issue you're having related to the text widget? If so, that's sadly a general WordPress issue that occurred after the 4.8 text widget overhaul.

**Comment by maglio** [comment]
The issue is related to the Text widget. One solution is to use the SiteOrigin Editor instead.

**Comment by AlexGStapleton** [comment]
Closing this as this is a WordPress widget issue.
