### ISSUE TITLE
The plugin page builder does not enable the settings option of the ultimate post plugin 

### ISSUE THREAD

**Issue by sousajul** [siteorigin/siteorigin-panels#446]
When using the **ultimate post** plugin in the plugin **page builder**, the display, filter and order windows don't open to make the correct settings.

![image](https://user-images.githubusercontent.com/13439949/28320458-0260ecdc-6ba7-11e7-8be2-d1f31b95e7be.png)

![image](https://user-images.githubusercontent.com/13439949/28320207-58e20bdc-6ba6-11e7-9555-65444e862f89.png)

**Comment by AlexGStapleton** [comment]
This sort of issue is typically due to how the plugin includes its assets in the admin. I'll run a few tests but we may not be able to resolve this issue. I would recommend getting in contact with the developers to report this issue also.

**Comment by AlexGStapleton** [comment]
This is a general issue with the widget you're using. You'll need to get in contact with the developers of this widget about [improving SiteOrigin Page Builder compatibility](https://siteorigin.com/docs/page-builder/widget-compatibility/).
