### ISSUE TITLE
iPad: Unable to scroll widget settings

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#455]
[Reported in this thread](https://siteorigin.com/thread/ipad-text-editing-interface-problem/).

When using SiteOrigin Page Builder on iPad, you're unable to scroll any widget interfaces due the interface being (at least from the looks of it) to `overflow: hidden;`

![](https://vgy.me/lswqdd.png)

**Comment by gregpriday** [comment]
Just tested this on my iPad and it all seems to be working properly. I could scroll both the widget form on the left and the style fields on the right. Worked on both Chrome and Safari.
