### ISSUE TITLE
Renderer:  Prevent locale formatting with cell width

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#456]
[Reported in this thread](https://siteorigin.com/thread/page-builder-24/).

When a server has a locale setting that uses commas instead of periods (such as German) we'll incorrectly output the width of cells. This is due to the usage of [round()](https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/renderer.php#L86) which will output with decimal point based on locale.

**Comment by braamgenis** [comment]
I can't seem to get the locale settings to use a comma as the decimal separator no matter what I do. I even changed my whole systems settings, but nothing seems to affect PHP/WordPress. :confounded: I don't want to spend too much time on this unless it's quite a widespread problem.

**Comment by AlexGStapleton** [comment]
I wouldn't call it widespread so I would hold off on this for the moment. I'll reach out to the person in the initial thread and ask for a copy of their php.ini and any other information that may help us.

**Comment by vollyimnetz** [comment]
I got the problem too. It is not wordpress specific, rather php specific. I got
```
width: 33,3333%;
width: calc(33,3333% – ( 0,66666666666667 * 30px ) );
```

To reproduce add the following in the functions.php
```
setlocale(LC_ALL, 'de_DE');
```

To reproduce you **may** also need:
- a PHP-version with german locales (not sure if it is bundled in default installation).
- a wordpress with german locale installed

-------------------------

`setlocale(LC_NUMERIC, '');` will set float decimal seperation for numeric operations to normal. But i am unsure if the plugin should use/fix this. I think a check and warning would be the best option. Cause the using of `LC_ALL` is a very drastic change in the php-system (http://php.net/manual/de/function.setlocale.php).

Tip for programmers that only wants to format there dates in a proper way: **_use LC_TIME instead_**
```
setlocale(LC_TIME, 'de_DE');
```

**Comment by braamgenis** [comment]
Thanks for your help @vollyimnetz. I was able to reproduce the issue. It seems to occur already when unserializing the Page Builder data which we store in post metadata. Instead of changing locale settings I have just done a simple string replace to swap ',' with '.' when adding the column width CSS. That seems to be the only value affected by this issue for now.

**Comment by vollyimnetz** [comment]
Attention: this will only work for numbers lower than 1000!

Formated english number: 1,123,456.89
Formated german number:  1.213.456,89

Commas and points are directly reverse.

**Comment by braamgenis** [comment]
Hi @vollyimnetz That's ok. Like I said, this is only being done when adding the column width CSS. I.e. it's a percentage calculated from a weighting assigned when specifying column ratios. The number shouldn't be larger than 100, unless the weight is filtered and set to something larger than 1. In which case, if they happen to set it to 10 or more (resulting in >=1000%) they'll have some interesting, most likely broken, layouts. :)
