### ISSUE TITLE
Heading 4 Appears To Big Then Expected. 

### ISSUE THREAD

**Issue by codeslane** [siteorigin/siteorigin-panels#460]
Headings are messed up and appear too big.
https://www.knowurcodes.com/codes-languages/c-language/tokens-in-c/c-keywords/

here's the example URL.

**Comment by AlexGStapleton** [comment]
Unfortunately, this isn't as a result of SiteOrigin Page Builder and looks to be due to theme styling. I would recommend getting in contact with the theme developers for assistance with this issue.
