### ISSUE TITLE
Improve General Responsiveness of SiteOrigin Page Builder interface

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#461]
SiteOrigin Page Builder is honestly really hard to use on tablets and basically impossible on phones. We should improve the general interface so that it degrades better overall.

**Comment by gregpriday** [comment]
I'm down with this for a future feature release. Any specific ideas?

**Comment by AlexGStapleton** [comment]
Outside of general improvements (such as allowing for the edit modal to appear on phones), not really. It seems like, in general, sidebars in modals aren't responsive while the content itself may be.

**Comment by AlexGStapleton** [comment]
A user [has requested](https://siteorigin.com/thread/mobile-posting-problems/) the ability to disable the drag and drop on mobile. This does make sense but maybe instead of disabling it we look into making the ability to edit the widgets easier by always showing the edit links on top of the widget at all times on mobile.

(this is a general feedback comment on responsiveness)

**Comment by gregpriday** [comment]
@AlexGStapleton Looking over it again, this would be a fairly complex feature to implement. It wouldn't quite be a complete rebuild of the interface, but we would need to completely rethink how we're doing things.

I'm keen to fix any glaring issues with mobile functionality, but lets break those out into separate issues so we can assess how useful each one is on a case by case basis.

I totally get the use case for mobile usability, but I still imagine most of our users are on desktop. So unless there's a huge demand for a full mobile editing experience, we're going to stick to focusing on desktop.
