### ISSUE TITLE
Add the ability to disable inline styling CSS

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#466]
Before SiteOrigin Page Builder 2.5, you were able to disable the SiteOrigin Page Builder Inline CSS by simply removing its filters ([reference](https://siteorigin.com/thread/disable-inline-styling-of-the-layout/)).After 2.5 refactor, it's no longer possible to do this.

**Comment by chakzefir** [comment]
@AlexGStapleton could you confirm, am I correctly understand you ? You offer to create an option to disable inline styles in theme at all ?
For instance, as decision of current issue: create checkbox in Page Builder settings, and before printing inline styles check this option, and according to this, print or not the inline styles on page.
Am I right ?

**Comment by AlexGStapleton** [comment]
Unfourtantly, that's not currently possible due to this issue which prevents the removal of the inline CSS.

It should, however, be noted that we wouldn't add a setting to disable Page Builder styling to the page builder settings as it can cause major confusion if a user accidentally disables it. Once this is fixed, we'll offer a filter that developers can use to do this.

**Comment by jakebellacera** [comment]
:+1: if we can get filters shipped then I would be willing to switch all of my customer's sites to use this plugin.

**Comment by braamgenis** [comment]
The above PR, when merged, will allow third party devs to modify or remove inline styles, if desired.

It should be noted that the previous method of disabling inline styles is possible in the currently released version, it's just slightly altered. It should now look like this:
```
function siteorigin_panels_remove_inline_css(){
	$renderer = SiteOrigin_Panels_Renderer::single();
	remove_action( 'wp_head', array( $renderer, 'print_inline_css' ), 12 );
	remove_action( 'wp_footer', array( $renderer, 'print_inline_css' ) );
}

add_action( 'wp_enqueue_scripts', 'siteorigin_panels_remove_inline_css', 11 );
```
