### ISSUE TITLE
Color Inputs On Rows..

### ISSUE THREAD

**Issue by sagive** [siteorigin/siteorigin-panels#467]
I am using the latest version - Recently i notices the color selector - background color for rows and font color ext. are not active. I can manully enter a hex color into that field but the smart color picker doesnt work.

Added Image:
![image](https://user-images.githubusercontent.com/1174968/30247902-26e3d35e-9626-11e7-9dc9-b7cf307928d4.png)

Tried it on a new installation with Twenty Seventeen Theme

**Comment by AlexGStapleton** [comment]
Unfortunately, I can't seem to replicate this issue. To confirm, SiteOrigin Page Builder is the only active plugin, correct? Are you able to replicate this issue on a different computer/server?

Would it be possible for you to send me an export for this widget? To do this open up the page with the widget and click Layout button in the Page Builder toolbar. Then click import/export and then click download. Please upload the export to a 3rd party file hosting site such as [teknik.io](https://upload.teknik.io/).

**Comment by sagive** [comment]
Had a problem with wordpress installation. Thanks for taking the time
