### ISSUE TITLE
front-flex.css - Allow for front-flex.css to be minified or minify it by default

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#470]
It's basically not possible for users to reliably minify front-flex.css and not face issues (read: the contents of the file simply won't work). As a result, we should either work on resolve the minify issues or minify the file by default.

[Reference](https://wordpress.org/support/topic/optimize-front-flex-css/)

**Comment by braamgenis** [comment]
This could be an issue with the minifier they're using, so we'd need to know which one that is to try reproduce and fix reliably. I'll try find which one it is that Google PageSpeed recommends.

**Comment by AlexGStapleton** [comment]
All good now.
