### ISSUE TITLE
Shortcodes breaks Page Builder

### ISSUE THREAD

**Issue by asayuki** [siteorigin/siteorigin-panels#474]
Everytime I try to use a Shortcode with attributes it breaks the builder and I get reverted back to the editor with a bunch of so/pb-htlm.
Shortcodes without attributes seems to work just fine.

Before save:
![screenshot from 2017-09-22 21-43-58](https://user-images.githubusercontent.com/999657/30761650-465e336a-9fdf-11e7-86a7-2ae4e97b25fd.png)
After save:
![screenshot from 2017-09-22 21-44-20](https://user-images.githubusercontent.com/999657/30761658-4cbd197e-9fdf-11e7-9f91-f345bdf8e29d.png)

I have updated both Wordpress and Siteorigin Panels to the latest versions and disabled all plugins except Page Builder and Widget Bundle.

**Comment by AlexGStapleton** [comment]
What plugin is adding that shortcode? I ask as this is very unusual for a shortcode to break the page builder. Please try a shortcode being added by a differnet plugin or a standard WordPress shortcode like [gallery](https://codex.wordpress.org/Gallery_Shortcode).

**Comment by asayuki** [comment]
It's just a shortcode I defined myself.
I tested the same on a clean install, seems to work there. So there is something on my end - probably in the theme maybe?

Thanks anyway :)
