### ISSUE TITLE
Revisions: Any semi-complicated layout is revision issues

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#475]
If you revert to a previous revision that has a semi-complicated layout (basically anything with a couple of rows and columns), the widgets will either be lost (if standard WordPress widgets) or reverted to SiteOrigin Editor widgets (if widgets from the SiteOrigin Widgets Bundle). This issue has likely only shown itself due to https://github.com/siteorigin/siteorigin-panels/commit/cc2474dd5d00dfc9f1ca429cc73c294ebb2133ba (that's definitely not the cause though) as Page Builder is never activated by upon restoring the revision and thus requires the conversion.

[Here's an example video](https://drive.google.com/a/siteorigin.com/uc?id=0BymU-6VMHHPfaXZrSnE0OXh6TUE).

**Comment by gregpriday** [comment]
Fixed by reverting https://github.com/siteorigin/siteorigin-panels/commit/4a117e607927ba992a34964894841b2eccce6854
