### ISSUE TITLE
builderType not always being set

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#482]
In some instances the [builderType](https://github.com/siteorigin/siteorigin-panels/blob/2.5.13/js/siteorigin-panels/main.jsL83) isn't being set. This makes detecting the context of a widget problematic.

This appears to only happen for widgets inside of a builder field. In all other instances, builderType is being set. I've got no idea how to word this without saying its a WB issue. I suspect [the builder type](https://github.com/siteorigin/siteorigin-panels/blob/2.5.13/js/siteorigin-panels/main.js#L102) isn't being set for the customs form.

The layout builder is working without issue.

([slack reference](https://siteorigin.slack.com/archives/C02SYBBH2/p1509524679000002))

**Comment by braamgenis** [comment]
Fixed in siteorigin/so-widgets-bundle@1662c34a0f05702b65e0da8bee621a1683c09806
