### ISSUE TITLE
How to hook to the actuall CSS printed to the head of the document

### ISSUE THREAD

**Issue by sagive** [siteorigin/siteorigin-panels#483]
I have created a small plugin to help me add slanted borders to rows.
However...

The best cross browser way to do that is to use a :before and :after tags in the css related
to the right row.

Using classes is easy but i want to do a dynamic solution where the angle and direction
could be set directly for each row.

Example image: 
https://ibb.co/ke9dhb

I got everything covered but...
**i dont know how to attach the needed CSS. The best place i could attach it is to the head of 
the document along with other css printed by SiteOrigin Page Builder**

But, I cant find any hook / documentation to do that.

Cant you point me to the right direction / share an example?

**Comment by sagive** [comment]
Hey again... after research i created this:
```
function slantedborder_panels_css_object($css, $panels_data, $post_id){

    foreach ( $panels_data as $panel ) {

		$current_grid = $panel['grid'];

		if( $panels_data['grids'][$current_grid]['slnborder_before'] == '1' || $panels_data['grids'][$current_grid]['slnborder_after'] == '1' ) {
			// RETURN HERE #ROW_ID:before {some css here}
		}

        // $css->add_row_css($post_id, $gi, '', array(
        //     'margin-left' => '-10px',
        //     'margin-right' => '-10px'
        // ));
	};
	
    return $css;
};
add_filter('siteorigin_panels_css_object', 'slantedborder_panels_css_object', 10, 3);
```

But, i still dont know how to add a :before attr to this hook.
Would apreaciate your help (or maybe i am totally off..)

**Comment by swinggraphics** [comment]
You might be better off adding a class name to the row:
https://siteorigin.com/docs/page-builder/hooks/custom-row-settings/#heading-adding-the-new-option-to-the-row-element

**Comment by sagive** [comment]
thats easy but not flexible to the website owner. Thats why i went trough all the trouble of building an addon. i cant make 100 classes for every angle variation.

**Comment by swinggraphics** [comment]
Your sample code only shows one option—a single checkbox. That implies you can make do with a single class name. Just have your addon add a class name to the row instead of trying to generate actual CSS. See the link in my previous response.

**Comment by sagive** [comment]
Its not only a checkbox... there are 2 other user input parameters right beneath it. i am asking a specific question and not how to apply a class which does not require any customization! Why are you diluting my question with shallow, unhelpfull responses?

**Comment by swinggraphics** [comment]
Looking at the source code, I see you can create your own selector and pass it with styles to $css->add_css.

`function slantedborder_panels_css_object( $css, $panels_data, $post_id ) {
    foreach ( $panels_data[ 'grids' ] as $gi => $grid ) {
        if( $grid[ 'slnborder_before' ] == '1' || $grid[ 'slnborder_after' ] == '1' ) {
            $selector = "#pg-$post_id-$gi:before"; // This applies to a specific row
            $attributes = array(
                'border-top-width' => $grid['slnborder_before_angle'], // or whatever
                'border-bottom-width' => $grid['slnborder_before_angle'],
            ) );
            $css->add_css( $selector, $attributes ); // optional $resolution as 3rd argument
        }
    };
    return $css;
};
add_filter( 'siteorigin_panels_css_object', 'slantedborder_panels_css_object', 10, 3 );`
This is totally untested, but maybe is on the right track?

**Comment by swinggraphics** [comment]
Thanks, Github, for removing the line breaks (◔_◔)
https://pastebin.com/9myCx3Ti

**Comment by sagive** [comment]
this looks awesome! thank you, going to test it now ;)
