### ISSUE TITLE
Error due to element style in the body

### ISSUE THREAD

**Issue by louisemb** [siteorigin/siteorigin-panels#491]
I'm having issues on my site, when the page refreshes after signing up for the newsletter through the mailchimp newsletter signup form in the footer, the page layout shifts to the left of the page. The code validator gives me an error that there is an element style in the body <style type="text/css" media="all" id="siteorigin-panels-layouts-footer">

Is this normal or might be the cause of my problem?

Thank you for your help!

**Comment by AlexGStapleton** [comment]
The mentioned tag is normal and present on all page builder powered pages - it's not causing this issue.

We're unable to provide support for these sort of issues over GitHub. Can you please post a thread on our [Support Forums](https://siteorigin.com/thread).
