### ISSUE TITLE
row padding does not work on full width stretched

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#492]
Hi,
Custom row paddings don't work when Row layout is set to Full Width Stretched:
**Row padding settings:**
![screen shot 2017-11-24 at 09 57 03](https://user-images.githubusercontent.com/10053621/33202813-2d74deb2-d0fe-11e7-92af-fe4b87fb1e75.png)
**Row layout settings:**
![screen shot 2017-11-24 at 09 58 25](https://user-images.githubusercontent.com/10053621/33202824-336225dc-d0fe-11e7-9809-9285c3b9a5c7.png)
**Result:**
![screen shot 2017-11-24 at 09 57 30](https://user-images.githubusercontent.com/10053621/33202873-5854ccdc-d0fe-11e7-8c39-1c74532d46b0.png)

I've committed a pull requests, which solves this issue. Please review it.
[https://github.com/siteorigin/siteorigin-panels/pull/490](https://github.com/siteorigin/siteorigin-panels/pull/490)

**Comment by gregpriday** [comment]
Hi @andrejarh - so we decided to fix this with an additional row layout option. Not the most elegant solution, I know, but we do need to think about legacy issues. There will be a significant number of users who designed their sites around the original behaviour - especially from when the padding value was just a single text field.
