### ISSUE TITLE
`apply_filters('the_content', $foo)` overrides `$foo`

### ISSUE THREAD

**Issue by ethanclevenger91** [siteorigin/siteorigin-panels#494]
From a template such as `taxonomy-cpt.php`, I can use `term_description()` to get the global term's description. This description may contain shortcodes or embeds, so it may sometimes make sense to do:

`apply_filters('the_content', term_description());`

However, with this plugin active, if there are posts with this taxonomy term, the content of the first post is returned rather than the filtered term description.

I have been able to confirm that the above code works as expected with this plugin inactive.

Thoughts?

**Comment by AlexGStapleton** [comment]
We'll make a note of this to see if this is something that can be avoided. In the meantime, I would recommend running [do_shortcode](https://developer.wordpress.org/reference/functions/do_shortcode/) against your term_description as that will directly avoid this issue and allow for the shortcodes to work without issue.

**Comment by gregpriday** [comment]
Unfortunately there's no real way for us to tell what's coming into `the_content` filter. As @AlexGStapleton suggested, the best option would be to use `do_shortcode`. I think it's safe to expect other plugins to only pass post content through `the_content` filter.

Another option is for you to add `add_filter('siteorigin_panels_filter_content_enabled', '__return_false')` before places where you want to disable the filter.
