### ISSUE TITLE
Updating to the newest version crashes the plugin

### ISSUE THREAD

**Issue by paulwillen** [siteorigin/siteorigin-panels#496]
When I install the newest version of Page Builder (2.5.16) It crashes...
I cannot activate the plugin anymore and my site is all messed up (obviously)...

I needed to go back to version 2.5.14 to be able to restore everything. What's the best wat to proceed?

**Comment by AlexGStapleton** [comment]
We're unable to replicate this issue so we suspect you may be experiencing a pretty major plugin conflict. Your best bet would be to disable all non-SiteOrigin plugins and change to a default theme before updating. Once updated slowly reactivate each plugin one by one until the issue reoccurs. Once it does, disable the last activated plugin and then skip to the plugin after that one and keep reactivating them. If no other issues arise, the conflicting plugin is the disabled plugin. What was the conflicting plugin?

If no issues occur during these tests, please restore the theme. If an issue occurs then, SiteOrigin Page Builder must be having issues with your theme. What theme are you using?

**Comment by paulwillen** [comment]
Thanks for your reply; 
I think I'll try to replicate this on a QA environment, since I don't want my site to be at risk anymore. Thanks for your proposed solution. I'll report back when I've tested things out..
