### ISSUE TITLE
admin.php : enqueue_admin_scripts : ob error

### ISSUE THREAD

**Issue by rogerlos** [siteorigin/siteorigin-panels#497]
At line 436 of `inc/admin.php`:
```php
ob_clean();
```
Should be:
```php
ob_end_clean();
```
 `ob_end_clean`: If you `var_dump( ob_get_level() );` before the `ob_start()`, you can see the object level increasing steadily as each trip through the loop opens a new buffer without ever closing them.

**Comment by braamgenis** [comment]
Thanks! This will be fixed in the next release. :+1:
