### ISSUE TITLE
Feature request - ROW Copy & Paste

### ISSUE THREAD

**Issue by Justin4Site** [siteorigin/siteorigin-panels#5]
Hi Greg,

I love Page Builder, what it does and what it can do!

This enhancement can save people a lot of time and make it easier to use & re-use developed work.

**ROW Copy & Paste**
- Function: **COPY entire row as is** (including all formatting & widgets)
- Function: **PASTE entire row copied** _to another Page/Site_
- Ideal would be able to _Copy & Paste from one site to another_
- But within a site would be helpful also

Benefits
- This will allow developers to have a **Page with Model Rows** configured to there developed liking
- Then they can just Copy & Paste rows into the Site/Pages they are developing!
- Big time saver & easily allows re-use.

Note ... It is up to the developer to ensure (relatively minor stuff for us) that
-  Widgets are available on site they are copying to
-  URLs are updated as needed
-  etc. 

The Way it is now ... It is All or Nothing!
- To add a row into a new page either you Create the row & widget configs from scratch
  
  -or-
- Clone a whole page in (from current site).

If you can do it, Please consider this.  I believe it will be a big boost & will make Page Builder even easier to use and more productive!

People will be able to **Develop a Row once**, **cherry pick Rows** as needed, then **tweak Rows** as necessary.  
And because developing sites will be even easier, Page Builder will more likely be chosen!

Thanks Greg ... Great job!
Justin

**Comment by jnhghy** [comment]
Hey, I'm not sure if I'm on the same page with Justin4Site but we are on the same boat, I too would love too see a solution for easily clone rows or widgets but I don't think I require using the clipboard to copy paste, if the widget can show a JSON version of itself that can be copy as text and inserted in a specific field ( can be a widget that accepts json and then transforms itself to the "imported/pasted" widget).

**Comment by gregpriday** [comment]
This might be possible using clipboard.js.

http://zenorocha.github.io/clipboard.js/

**Comment by designabyss** [comment]
@gregpriday 

Can't we go through a slightly different route that doesn't exactly copy rows but sort of makes it easy to replicate rows across different pages?

Suppose I create a row with 4 columns and each column has a *SiteOrigin Image* widget with each widget having it's own particular style attributes.

Would it be possible to save the entire row's configuration (basically only the rows styles and widget styles part) in db and then when similar structure is needed elsewhere you can load it from saved configs!?

Hope it makes sense...

**Comment by arieldiaz** [comment]
I know this is popular, but just adding another big vote of support for this feature - would make SO PageBuilder significantly more powerful!!

**Comment by tobada** [comment]
Hey, any news on the subject? And if not, is there a best practise workaround?

**Comment by gregpriday** [comment]
Support clipboard operations have actually become a lot more widely supported in browsers these days, and we should be able to have it gracefully degrade for older browsers. I'll take another look at this. Combined with the contextual menu that we added last year, it should actually be fairly easy to implement.

**Comment by gregpriday** [comment]
I've added some basic copy paste functionality. Rather than using the clipboard, which requires a rather heavy library and some hacks to use, I went with cookies. I might change this to use HTML5 storage instead of cookies.

https://github.com/siteorigin/siteorigin-panels/tree/feature/copy-paste

We'll probably have this included in the 2.5 release.

**Comment by Justin4Site** [comment]
Hey Greg, The way to go man! Thank you I appreciate the "Copy & Paste" very much!

**Comment by crmb** [comment]
Great i will try it ASAP

**Comment by gregpriday** [comment]
It's a pleasure @Justin4Site - it only took us like 2 and a quarter years ;)

**Comment by tobada** [comment]
Thank you for your quick work. Is there a date for the 2.5 release?
