### ISSUE TITLE
Data loss due to quotes in tag

### ISSUE THREAD

**Issue by SteveS123** [siteorigin/siteorigin-panels#50]
Add this to a (Black Studio) Visual Editor widget "Text"/source view-

```<h1 style="text-align:center">TEST</h1>```

Click "Done" and then "Update" to save the page.

Try to edit that same widget, the code above should be gone.

**Comment by gregpriday** [comment]
Can you quickly check if you're still getting the issue in the 2.1 release branch?

https://github.com/siteorigin/siteorigin-panels/tree/release/2.1

I can't recreate the issue on my side, but we did make some changes that improved how data is encoded. We did this to fix data loss in a few other situations, but it should fix this one too.

**Comment by SteveS123** [comment]
I uploaded 2.1 but same issue I'm afraid.  I've tried disabling all plugins but Black Studio's and Page Builder, but no dice.

This is in the source before I click "Edit" to trigger the bug that erases the editor:

```<script type="text/javascript">
		document.getElementById('panels-data-field-550ad31a73283').value = decodeURIComponent("%7B%22widgets%22%3A%5B%7B%22filter%22%3A%221%22%2C%22text%22%3A%22%3Ch1%20style%3D%5C%22text-align%3Acenter%5C%22%3ETEST%3C%5C%2Fh1%3E%22%2C%22title%22%3A%22%22%2C%22type%22%3A%22visual%22%2C%22panels_info%22%3A%7B%22class%22%3A%22WP_Widget_Black_Studio_TinyMCE%22%2C%22raw%22%3Afalse%2C%22grid%22%3A0%2C%22cell%22%3A0%2C%22id%22%3A0%7D%7D%5D%2C%22grids%22%3A%5B%7B%22cells%22%3A1%2C%22style%22%3A%5B%5D%7D%5D%2C%22grid_cells%22%3A%5B%7B%22grid%22%3A0%2C%22weight%22%3A1%7D%5D%7D");
	</script>```

So the content is there after the page is saved, it's clicking the widget's "Edit" that erases it.

**Comment by dimitrov-adrian** [comment]
Problem seems to occures only when have double quotes, and also it is not only to black studio visiual editor but and on standard wp text widget.

**Comment by gregpriday** [comment]
OK, I've managed to recreate the issue on my side. I'll get started on fixing this for the 2.1 release.

**Comment by gregpriday** [comment]
Working on this now. The issue doesn't seem to be there for version 2.0.7, so it's something that we added since then. Hopefully I'll have a fix soon. Thanks again for reporting this @SteveS123

**Comment by gregpriday** [comment]
Luckily this was a very simple fix. Turns out there was a strip_slashes that we didn't need since changing to using filter_input and filter_input_array instead of super globals ($_POST). WordPress automatically adds slashes to the super globals, which is why we needed to strip them before.

https://github.com/siteorigin/siteorigin-panels/commit/6c1e7990a57169028086e311ce5b933a76d0d5f1
