### ISSUE TITLE
Cannot export layout when it contains a "SiteOrigin Button"

### ISSUE THREAD

**Issue by MaxValue** [siteorigin/siteorigin-panels#503]
s.a.

I tried to export the layout as JSON via:

1. Go to "Appearance" > "Widgets"
2. "Header Widgets" > "Layout Builder" > "Open Builder"
3. "Layouts" > "Import/Export" > "Download Layout"

When this "Download Layout" button is clicked, it sends a request but the download window never pops up. When all "SiteOrigin Button"s are removed from the layout, it works as expected: The download prompt is shown and I can download the file.

**Comment by AlexGStapleton** [comment]
Unfourtantly, we're unable to replicate this issue. I _suspect_ the server you're on may be rejecting the data for some reason. Are you able to replicate this issue on another server?

**Comment by MaxValue** [comment]
Hmm that could be.

I now (stupid me that i didn't do that in the first place) looked at the browser console:

Turns out another plugin i have (Wordfence) is acting super paranoid and blocking the request.

All green on your plugin now. This was a false positive!

Thanks for helping finding the issue in any case!
