### ISSUE TITLE
Preview bugged for post creator when there is an autosave from another user

### ISSUE THREAD

**Issue by Sharsie** [siteorigin/siteorigin-panels#505]
If there are multiple users working on a post and one of them creates an autosave (and then for example closes the window so the lock expires), the other user (not sure if it is always the owner of the post) will always be presented with an autosave of the other user.

**How to reproduce:**
1) Create a post with user A, add site origin editor and add some content
2) Save draft, Log out, delete lock from DB in wp_postmeta (emulates user closing the window and lock expiring)
3) Log in as user B
4) Edit the post changing some of the contents, click Preview to generate an autosave
5) Log out, delete lock from DB
6) Log in as user A, edit the post
7) Change the contents
8) Click preview and you should be presented with the user B's version of the autosave

Even if you save the post as draft and then preview it, you will again be presented with B's autosave

**Possible solution:**
https://github.com/siteorigin/siteorigin-panels/blob/develop/siteorigin-panels.php#L279
```diff
		if ( $preview ) {
-			$preview_post = wp_get_post_autosave( $post_id );
+			$preview_post = wp_get_post_autosave( $post_id, get_current_user_id() );
			if ( ! empty( $preview_post ) ) {
				$post_id = $preview_post->ID;
			}
		}
```

Because there is a check in `wp_get_post_autosave` whether the autosave belongs to the user previewing the post, it will retrieve the first autosave entry no matter if it belongs to the current user or not. This post is then used inside the `generate_post_content` function and the content is generated from the autosave instead of the latest version

**Comment by Sharsie** [comment]
@braamgenis Hello Braam, could we please reopen this issue?
The solution in #510 did not really fix the issue, it just made it individual for each editor.

To better explain:
Before when one editor created an autosave, everyone was presented with this autosave version

Now this is delegated to individual editors creating their own autosave and then being presented with this autosave even if the post is later updated. So the core problem is not really fixed.

**Steps to reproduce:**
1) Create a post with user A
2) Edit the post with user B, make changes, click Preview (no need to save draft)
3) Edit the post with user A
3) Click the preview with user B without changing the contents (or just refresh preview page)

Now we have several editors and since each creates and then views their own autosave, we had 4 editors seeing 4 different versions of the same post in preview
So for now I will have to create a button for our editors which will invalidate the autosaves, but it's just a quick workaround for our website.

**Offered solutions:**

The offending line is still [this condition block](https://github.com/siteorigin/siteorigin-panels/commit/487ad46b1d8610dbd3e52c2625485bcb28789b4b) but I would like to discuss how this should be approached, because I am not really sure myself.

So far I came up with these
1) Deleting other user's autosaves when post is updated (in any case only one user is allowed to edit the post at the time, so once the post is updated and a new revision is created, the autosaves are in fact invalid most of the time); however I can see a use case where user B edits the post, creates an autosave, doesn't save it... then another user comes, edits the post and saves it... then user B comes back and can browse their autosave to retrieve some of their work.

2) When preview is viewed, check if there is an autosave and if it is in fact newer or older than the latest revision. If it is older, do not use it. I'm thinking that when the user edits the post and creates an autosave, it should always have the latest modified time. If it is not, then he probably does not want to see the autosave, but the latest revision instead. Is my assessment accurate?

3) Make sure new autosave is generated every time the preview is accessed. But is this safe? I'm not really sure how the autosaves work, in fact this might just create a new autosave from the latest revision which might not be what you want, but I really do not know what other consequences it might have.



I will be happy to create a PR, but first I would like to know which way is the proper one

**Comment by Sharsie** [comment]
@AlexGStapleton @gregpriday @Misplon 
Hello guys, following my previous comment, could we please have this issue reopened?

Does any of the offered solutions sound good to you? I haven't had time to further think on this, but so far I'm most inclined to solution 2. My reasoning is that the other solutions are out of scope for SiteOrigin (handling autosaves) instead of deciding if autosave should be used.

**Comment by AlexGStapleton** [comment]
@braamgenis will take a look at this when he gets a chance.

**Comment by Sharsie** [comment]
Hello guys, so far I am testing it with a filter hook outside of the plugin. It seems to do what we want for now:

```php
add_filter("siteorigin_panels_filter_content_enabled", function() {
        global $preview;
        if ($preview) {
            $previewPost = wp_get_post_autosave( get_the_ID(), get_current_user_id() );

            if (!empty($previewPost)) {
                $autosaveDate = \date_create($previewPost->post_modified_gmt);
                $parent = get_post($previewPost->post_parent);
                $parentDate = \date_create($parent->post_modified_gmt);

                if ($autosaveDate < $parentDate) {
                    \wp_delete_post($previewPost->ID);
                }
            }
        }

        return $status;
});
```

Something along these lines could be a solution (really needs a doublecheck and maybe optimalization, just wrote it without thinking really :)
The empty check for parent post might not be needed, not sure, needs testing (e.g. autosave of a new post)

```diff
		if ( $preview ) {
			$preview_post = wp_get_post_autosave( $post_id, get_current_user_id() );
			if ( ! empty( $preview_post ) ) {
+			    $parentPost = get_post($preview_post->post_parent);
+			    if ( ! empty( $parentPost ) ) {
+                                $autosaveDate = date_create($preview_post->post_modified_gmt);
+                                $parentDate = date_create($parentPost->post_modified_gmt);
+                                if ($parentDate && $autosaveDate && $autosaveDate > $parentDate) {
+                                     $post_id = $preview_post->ID;
+                                 }
+                             } else {
                                 $post_id = $preview_post->ID;
+                             }
			}
		}
```

**Comment by Misplon** [comment]
Super, thanks for the update. Glad to hear you've found something to resolve for the moment. Braam will take a look during his next Page Builder run. Thanks again :)

**Comment by braamgenis** [comment]
Hi @Sharsie

We are satisfied with the way things work now, with each user having their own version of an autosave which is displayed in the preview, and you seem to have a good custom solution which works for you. Unfortunately we can't dedicate more time to adding this functionality ourselves, but I'm sure if there is a big enough demand we may see something offered by WordPress that we can hook into.

Thanks again for the contribution!

**Comment by Sharsie** [comment]
Hello @braamgenis, it does not really work that way, in reality, the user is seeing the updated version in the administration, but clicking preview does not render this updated content. Instead it renders their old autosave from before.

But I understand if you do not have capacities to fix this, not really happy the issue is closed as this is a bug, but in the end the plugin is free and it's up to you guys :)

**Comment by braamgenis** [comment]
In my tests, if you just refresh the preview page, it will display outdated content. However clicking the preview button in the editor ensures the content is updated correctly. This same behaviour occurs when editing a page using the normal WordPress visual editor. It seems there is some processing that occurs in the back end when clicking the preview button which doesn't occur when just refreshing the page.

**Comment by Sharsie** [comment]
Hmm, I tried with a completely clean wordpress and it refreshes the preview [as can be seen in this screencast](https://imgur.com/a/zsZw1X1).

There is, however, one confusing functionality of wordpress... clicking twice on the preview button opens links with different parameters (for non authors):
?p=10&preview=true
?p=10&preview_id=10&preview_nonce=4d76f9461f&_thumbnail_id=-1&preview=true

The one with the nonce seems to sometimes render an old content when page builder is active, but I just can't reproduce this consistently.

I'll try to dig into this a bit deeper later on, if I manage to come up with a solution I will submit a PR.
