### ISSUE TITLE
When registering an instance of a class as a widget PageBuilder fails to load it

### ISSUE THREAD

**Issue by nsrosenqvist** [siteorigin/siteorigin-panels#509]
If I register a normal widget by supplying the WP method `register_widget` with an instance of a class then PageBuilder manages to list it and add it to the panel builder. But when opening to edit the widget's form then it just gives an error message and a long number instead of the class name of the widget in the error message. Everywhere else in WordPress it's supported to register instances for widgets but it doesn't work in PageBuilder.

**Comment by nsrosenqvist** [comment]
**More info:** When all the widgets are listed in the  "add widget" dialog the object hash is loaded as widget class. When the widget has been added and the form is opened it's done in a subsequent request and therefore the object hash of the instance is different and the widget can't be loaded.

**Comment by AlexGStapleton** [comment]
Hi nsrosenqvist

That's odd. Can you please send me a copy of the code you're working with so we can run some tests against it?

**Comment by nsrosenqvist** [comment]
Don't have the code anymore unfortunately, but it should be easy to test. Just create a widget instance, register the instance, try and add it from pagebuilder

**Comment by nsrosenqvist** [comment]
this happens since PB stores a hash of instances and that hash is unique for each request. So when the widgets are listed in page builder the hash is the reference to the widget to insert, but on the next request when it's inserted the instance has a new hash and the reference from the selection is now not matching any registered widgets

**Comment by AlexGStapleton** [comment]
To be honest, we're not really understanding what the actual issue is. This was the main reason why we asked for a copy of the code so that we could easily tell/replicate this issue. Can you please elaborate on what you're trying to do, what you expect to happen and what is actually happening? Ideally, please be as specific as possible. Sorry about this!

**Comment by nsrosenqvist** [comment]
I'd rather not have to set up an environment again just to provide a code sample for an issue that I reported over two months ago. I'm no longer using Page Builder for my project due to this bug. I'll try describe the issue again and if something still doesn't make sense please explain further what it is that you're not understanding.

**The issue**
Wordpress supports registering widgets either by supplying a class name or an instance of a class. The reference for the widget in the factory is a hash of the object when an instance is provided rather than the class name (see line 98 of [wp-includes/class-wp-widget-factory.php](https://developer.wordpress.org/reference/classes/wp_widget_factory/)). All good so far.

(note that this is a native Wordpress widget, so I'm registering it with the native function `register_widget`, and not `siteorigin_widget_register`. Not sure if siteorigin_widget_register does something different)

Now when editing a post, when you click to insert a widget in the page builder you get a list of all registered widgets, both WP_Widgets and SiteOrigin_Widgets. When you click one of these in order to insert it into the layout, the reference to it is sent in a request to the server. Normally this is simply a namespaced version of the class name but with instances a hash of the object is sent instead, since that is the reference to it stored in `WP_Widget_Factory::$widgets`. This is where it gets interesting.

Now the server is processing this on a subsequent AJAX request and the hashes of the objects are unique for every request (since it's an instance and you can't recreate the instance from the object hash). So now when we're attempting to insert the widget into the layout Page Builder can't create the widget, it expects that only class names are used. This means that Page Builder don't fully support regular Wordpress widgets since it's incompatible with the registration of widget instances.

One way this could be solved (haven't looked at the Page Builder source in a while so you'll have to excuse me if I'm way off) would be to serialize all widgets that are registered as instances and use another way of referencing the widget instead of the object hash. That way you can determine what widget the user is trying to insert and you recreate that instance on the next request.

Please let me know if anything in this issue description requires further explanation.

**Comment by abrain** [comment]
A user of my [plugin](https://wordpress.org/plugins/einsatzverwaltung/) just faced the same issue. For now, they have to stick to an older version of the plugin, which uses the registration by class name. Could you please consider this issue for upcoming bugfix releases?

**Comment by AlexGStapleton** [comment]
Very sorry for the delay. This got lost in a recent issue push.

Unfortunately, we don't currently support the alternative method of registering widgets at this time. This is something that will be supported in the future but due to lack of reports, it's currently not a high priority. Your best bet to ensure compatibility, for the time being, would be to use the original/main method of registering widgets.

I'm going to close this issue in favor of #578.

**Comment by AlexGStapleton** [comment]
Just writing to mention that #578 is fixed in the 2.10.0 update.

**Comment by abrain** [comment]
Awesome, thank you!
