### ISSUE TITLE
Live editor collision

### ISSUE THREAD

**Issue by dimitrov-adrian** [siteorigin/siteorigin-panels#51]
Looking at https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/live-editor.php and as see how live editor is working I think there could be a problem if in given page are loaded more than one page with panels.
May be the logic should be refined with passing the post_id of what we editing.
I will try to make a test case which could trigger the problem.

**Comment by gregpriday** [comment]
Yeah, that's definitely something we'll want to take a look at. Hadn't really thought of that situation.

I'm planning on largely overhauling the live editor for Page Builder 2.2, so I'll do some work on these edge cases then.

**Comment by gregpriday** [comment]
Just implemented this in https://github.com/siteorigin/siteorigin-panels/commit/1b44eea2da144928e6328510d0c9a0b0c4caf7bb to resolve another issue :)
