### ISSUE TITLE
layouts weird issue

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#511]
Hi guys,
I am not exactly sure why this happens and can't say how exactly to reproduce this issue, but the more I work with the site, the more times the clone [post type] options duplicate. This is an example of my local installation:
![screen shot 2018-02-16 at 11 05 01](https://user-images.githubusercontent.com/10053621/36302699-b9e8bbd2-1309-11e8-83e5-584d0c42b907.png)

I've noticed This issue in older versions as well but didn't report it yet. It is not really a high priority issue.

Best regards to the team!

**Comment by andrejarh** [comment]
Hi Alex,
Plugins on the site are:
- SO Page builder
- SO Widget Bundle 
- Contact form 7
- Revolution Slider

**Comment by AlexGStapleton** [comment]
To clarify, how are you adding the post types? Directly with PHP, or are you using a plugin/prebuilt solution?

Would it be possible for you to proceed us with access to a site where this is happening? If so, can you please email login details to support@siteorigin.com.

**Comment by andrejarh** [comment]
The post types are defined in php. 
Currently I have this page on localhost. If you want, I can send create a copy and send it over to you.

**Comment by AlexGStapleton** [comment]
We would really appreciate it if you could send us a copy of that site so we can run some tests against it. We recommend using [Duplicator](https://wordpress.org/plugins/duplicator/), but whatever you use should be more than fine.

**Comment by Misplon** [comment]
Hi @andrejarh Thanks for all of your effort, logging bugs and PR's, it's most appreciated. Do you want to dive into this deeper with Alex with a copy of the site or should we leave this for the moment?

**Comment by Misplon** [comment]
Closing for the moment, please let me know if you'd like to reopen. Thanks again for your support.
