### ISSUE TITLE
TinyMCE lost formating

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#514]
After update to 2.6.3. All widgets with TinyMCE form lost all formating.
Example: 
**Before:** 
![screen shot 2018-03-12 at 09 56 59](https://user-images.githubusercontent.com/10053621/37277989-9d0da712-25e6-11e8-9b4d-b2030dde48cc.png)
**After:** 
![screen shot 2018-03-12 at 09 58 18](https://user-images.githubusercontent.com/10053621/37277999-a87106bc-25e6-11e8-8ad0-249784959f90.png)

I think it might have something to do with this:

+= 2.6.3 - 6 March 2018 =
+* Removed special handling for retrieving data from TinyMCE editor fields. Just use the field value directly.

**Comment by Misplon** [comment]
Hi @andrejarh 

If possible, please, could you share the exact markup used in your test in the screenshot. We're working two related issues. I want to confirm if this is the same as one of those issues or a different problem.

Thanks and sorry about the hassle.

**Comment by andrejarh** [comment]
The exact markup from the example is:
`Integer ornare vulputate augue, ac finibus ante interdum dictum. Fusce gravida finibus turpis, eget tempor tortor facilisis in.

Mauris nisi felis, euismod sed est in, aliquam mollis velit. Duis hendrerit lorem vel quam rhoncus, finibus varius tellus fermentum. In feugiat, libero condimentum malesuada ultrices, purus quam dapibus nisl, vel volutpat enim mauris sed leo.
<ul class="list-arrow">
 	<li>Lorem ipsum</li>
 	<li>Lorem ipsum</li>
 	<li>Lorem ipsum</li>
</ul>`
this is a video recording of a related bug, where the same content was saved differently if the markup was saved in visual or in HTML mode: http://jmp.sh/jtASzEQ

**With the latest version of bundle and panels, this issue is resolved**:
http://jmp.sh/ccxwtwO

**Comment by Misplon** [comment]
Thanks for confirming. All the best.
