### ISSUE TITLE
Add filter to disable all row/widget styles 

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#527]
A premium user has requested the ability to disable widget styles (the entire sidebar) for a specific post type. They didn't have the ability to do this by simply removing all widget styles.

**Comment by braamgenis** [comment]
There is a small bug related to this but it's already possible using:

- `add_filter( 'siteorigin_panels_general_style_fields', '__return_false' ); // Remove style fields in all cases.`
- `add_filter( 'siteorigin_panels_' . $section . '_style_fields', '__return_false' ); // Remove style fields for the specified section which could be 'row', 'cell', or 'widget'.`

These will need a slightly higher priority if Premium is installed as it adds Animation style fields at priority 10.
