### ISSUE TITLE
How to check if current page uses siteorigin

### ISSUE THREAD

**Issue by kevinmamaqi** [siteorigin/siteorigin-panels#535]
Hello,
Is there a conditional to check if the current page or a page by id is using Siteorigin panels?

**Comment by AlexGStapleton** [comment]
You can use [siteorigin_panels_is_panel](https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/functions.php#L22) to find if the current page is powered by page builder or not.

**Comment by kevinmamaqi** [comment]
Thank you @AlexGStapleton
