### ISSUE TITLE
Investigate knock-on challenges of merging teaser widget fix

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#536]
Investigate https://github.com/siteorigin/siteorigin-panels/pull/451. Ensure we still have a way of introducing WB widgets as required. Merge 451 as soon as able.

**Comment by gregpriday** [comment]
So the only real challenge I can think of is that a user sees a few widgets, installs widgets bundle, then suddenly doesn't see the teaser widgets and wonders where they went.

Unless we come up with a clever solution though, we can't have it both ways.

One solution might be to only deactivate the teaser widgets once the user has viewed the Widgets Bundle widgets page at least once. Thoughts?

**Comment by braamgenis** [comment]
One thing that was nice about the way things were before #451 was that users could enable some disabled widgets without having to navigate to the Plugins > SiteOrigin Widgets settings page first.

**Comment by gregpriday** [comment]
And from a support perspective, we could just tell users to disable recommended widgets in Page Builder settings to get rid of them.

**Comment by Misplon** [comment]
That sounds perfect. As long as there is a manual step, which there is, I’m
happy to leave it.

**Comment by gregpriday** [comment]
@AlexGStapleton are you alright with leaving things how they were?

**Comment by AlexGStapleton** [comment]
I'm fine with that imo. To be honest, I had completely forgotten about teaser widgets so I honestly don't think this will come up very often.

**Comment by gregpriday** [comment]
Perfect. I'll revert the merge, and we can move on.
