### ISSUE TITLE
Widget ID (or Class ) in the admin area

### ISSUE THREAD

**Issue by LoloIrie** [siteorigin/siteorigin-panels#545]
Hi,

it would be nice to have the widget ID or class name attributes used in the admin panel for each widget:

It would allow something like that (identify each widget in the admin area to apply specific CSS/JS rules):
https://siteorigin.com/thread/process-raw-widgets-that-have-come-from-the-page-builder-front-end/#comment-98326

It was a (now closed) a very simple/easy PR:
https://github.com/siteorigin/siteorigin-panels/pull/246/files

Thanks for interest ;)

**Comment by gregpriday** [comment]
This should be a fairly simple, harmless addition.

**Comment by gregpriday** [comment]
Thanks @LoloIrie - I used [your original PR](https://github.com/siteorigin/siteorigin-panels/pull/246) as inspiration, but needed to make sure the code was in the right place and data was being escaped properly.

**Comment by LoloIrie** [comment]
Thanks to implement it. :)

You're welcome.
