### ISSUE TITLE
Duplicate post revisions and meta data

### ISSUE THREAD

**Issue by chrisbarnett1** [siteorigin/siteorigin-panels#549]
I've found a few bugs with how post/page revisions are handled with SiteOrigin's Page Builder plugin.

I discover the issues on a one of our websites but have also tested on a clean WordPress install using the twentyseventeen theme.

Here are the bug I found:

1. When a post/page is created using the page builder, a duplicate post revision is being created everytime i.e. there are 2 revision per update. The call to wp_update_post() in the save_post hook is causing this. The solution is to remove the WordPress hook that creates revisions before calling wp_update_post(). The hook then needs to be added back afterwards. Also see: https://wordpress.stackexchange.com/questions/3393/enable-disable-post-revisions-programmatically/3398
2. When viewing the contents of post revisions (i.e. browsing the revisions), the pl-{ID} attributes in the HTML matches the ID of the revision rather than the post. WordPress then highlights these as changes. I think it make more sense to save the revision content using the post ID rather than the revision.
3. Duplicate 'panels_data' is getting added to the postmeta table on preview and save of revisions. We have a page that is frequently updated/previewed and it had over 700 duplicates. The code causing this is in revision.php. The save_post hook was adding the postmeta to the duplicate revision created above (1) and also the initial revision 2 times per page preview. The is_preview() check doesn't work in the context of save_post (the hook is called before the WP_Query object is setup). Anyway with the fix to remove the duplicate revision (1) this hook becomes redundant and can be remove.

I have a pull request to fix these if you like:
https://github.com/siteorigin/siteorigin-panels/pull/548

**Comment by AlexGStapleton** [comment]
To confirm, does this PR completely disable revisions? I ask as revisions must remain as without a revision version of panels_data being created the WordPress revisions system doesn't work correctly - restoring a revision won't change any of the actual content.

1. Regarding the duplicate panel_data (one revision specific panels_data rather than two), I haven't run any tests to verify this but if that's happening that definitely needs to be fixed.

2. This isn't ideal, I agree.

3. As mentioned, a revision panels_data must be made or the revision system simply doesn't work. Your best bet to avoid having a lot of instances of this is to decrease the WP_POST_REVISIONS amount so that only x number of revisions are kept (rather than 700).

**Comment by chrisbarnett1** [comment]
No it doesn't disable revisions. I wouldn't want to do that as I need this feature.

1. With the code in develop, I'm seeing an extra revision being created in wp_posts for every update made to a page (i.e. an update creates two rows in wp_posts with a post_type of revision for a single update). If you save a post that is using the page builder and watch the number of revisions that are created in the "Publish" meta box of the page/post you are editing you should see what I mean. When WordPress saves a post it uses wp_update_post()/wp_insert_posts() which triggers the save_post hook. As wp_update_post() is called in the save_post hook WordPress is generating 2 revisions. The remove_action/add_action I've added around the wp_update_post() call fixes this (line 215 and 217).

2. Line 196, 198 get the correct post ID. Which I've called a layout ID (I think that term is used somewhere else in the code base). 201,202 and 210 then use this ID. If you create a new post, make a few updates then browse the revisions you should see what this fixes.

3. We have WP_POST_REVISIONS set to 20. The duplicates I've found about are in the wp_postmeta table. There are multiple panel_data objects for a single post ID (i.e. the same revision ID). In my case 1 specific revision has 700 panel_data rows in the database. The logic in revision.php isn't actually needed as the save_post hook in admin.php is already adding/updating a panel_data object for every revision as well as the origin post itself. The extra hook in revisions.php uses add_metadata which is adding an additional 2 'panel_data' objects to post meta. It does this on save and preview which is how I've got a so many objects for a single post revision.

**Comment by chrisbarnett1** [comment]
Hold off on the pull request I think I've found a bug (and maybe a need for the second save_post in revisions.php). 

Seem if you restore a revision, the revision WordPress creates (to record that the revision has been restored) doesn't have any panel_data. For this to be a problem you need to restore a revision, make more changes then restore to the point you restored.

**Comment by AlexGStapleton** [comment]
Sorry, I wasn't very clear. I meant, does this PR prevent the copy of panels_data to the revision? I ask as, without that copy, the revision won't have the page builder data.  Based on your last reply it looks like it doesn't which is why the revisions aren't working. panels_data isn't being added for the revision anymore with this PR, right?

**Comment by chrisbarnett1** [comment]
After more testing I found a specific use case where panels_data wasn't set. I'll see if I can get to the bottom of this and submit new PRs.

**Comment by chrisbarnett1** [comment]
I've submitted 2 new PR for the first 2 issues I raised

https://github.com/siteorigin/siteorigin-panels/pull/551
https://github.com/siteorigin/siteorigin-panels/pull/552

I've added some screenshot to show what I'm fixing with these.

I'm still working on the 3rd issue I raised (i.e. duplicate post meta). I need to get this fixed for our website that is using the page builder. I'll share once I have the fix.

**Comment by chrisbarnett1** [comment]
Here is the PR for the 3rd issue:
https://github.com/siteorigin/siteorigin-panels/pull/553

**Comment by AlexGStapleton** [comment]
I've assigned the mentioned PRs to @braamgenis and he'll take a look over them during the next update push.

**Comment by braamgenis** [comment]
Fixed by #552 and #553 .
@chrisbarnett1 Thanks for your fixes!
