### ISSUE TITLE
mod_security - Adding an emoji to a page will result in the page not saving correctly

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#550]
[Reported here](https://siteorigin.com/thread/updates-not-saving-pages-reverting-to-non-so-layout/)

If the users website has mod_security installed, adding an emoji to the page will result in the page not saving any changes - it'll also remove the emoji so any change after that point will be retained until the emoji is added again.

I've confirmed this on Bluehost (siteorigin.net) and the user has confirmed this on Siteground. This issue may be dependent on a specific mod_security filter so it may not happen on all websites with mod_security. This may not be something we can specifically fix, but I do this it's as a result of something we've changed as we haven't received (as far as I'm aware of) any similar reports.

**Comment by gregpriday** [comment]
This might be fixed by changes in https://github.com/siteorigin/siteorigin-panels/issues/639

**Comment by Misplon** [comment]
We haven't had reports of this recently. If the issue is reported again in the future, we'll re-open.
