### ISSUE TITLE
Margin top on widgets not working properly

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#554]
Hi guys,
The new margin functionality on widgets does not seem to work as expected. 
When top margin is added to the widget, the cell background should be visible above the widget.

![screen shot 2018-06-22 at 19 22 58](https://user-images.githubusercontent.com/10053621/41790494-087b6d38-7653-11e8-8cb8-f80637192f55.png)

I've added json export as a zip (github does not allow json attachments)
[row-test.json.zip](https://github.com/siteorigin/siteorigin-panels/files/2128581/row-test.json.zip)

This was tested on Twenty Seventeen theme, Page builder ver2.6.9

**Comment by Misplon** [comment]
Hi @andrejarh. I do perhaps see an issue but when I load this up in our Corp theme, the margin is not in white. Please, see below:

<img width="1680" alt="screen_shot_2018-06-22_at_13_19_45" src="https://user-images.githubusercontent.com/789159/41797499-19468744-761f-11e8-8da7-4e12807c8cfa.png">

**Comment by andrejarh** [comment]
Yes I see there is the bug also on your setup.
The margin on the widget pushes down the whole cell. This results in the missing cell background on top. 
The expected behaviour of the widget margin would be to leave the cell attached to the top of the row and move down only the widget (making cell background visible on top).

**Comment by braamgenis** [comment]
Hi @andrejarh While this appears to be a bug, it's actually expected CSS behaviour called margin collapsing. 😩 See [here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing). In that article you can see there are ways for us to hack around the margin collapsing rule, such as setting `overflow:hidden;` on the parent `div`, but that's not ideal either as it could have unintended consequences later.

A workaround to achieve the layout you're after is to remove the margin on widget styles and set the cell's padding to 30px instead. Hope that helps.
