### ISSUE TITLE
Feature to disable JS resizing

### ISSUE THREAD

**Issue by petemolinero** [siteorigin/siteorigin-panels#557]
I know this is a total feature request as opposed to a bug, but it would be **awesome** if there was an option to totally disable the JS resizing. While JS resizing is a nice feature for people who want a drop-in page builder for their theme, it's fairly janky for someone who is building their theme from the ground up. I've been able to disable the JS resizing with a bunch of filters and CSS changes, but it would be WAY better if there was a native option for it. It would ideally work like this:

- Disables all JS resizing, and rows just automatically go edge-to-edge of their container (so, if the page builder is used directly inside `body`, it would be edge to edge of `body`.
- Adds a `div.pb-container` element inside either `.panel-no-style` or `.panel-row-style` depending on which exists, so that users can set up the styles for their container, for non full-stretched rows.

For others interested, I've created a ghetto work-around in the time-being using the code below (of course, I had to do some CSS mods too). It's not ideal, though, since it requires that I move all the background stuff off of row-style, since I'm using row-style as the container.

```php
/**
 * Dequeue the SiteOrigin front-end script
 *
 * We don't want the JS based resizing, so we will de-register the script.
 *
 * @return   void
 */
function custom_so_dequeue_script() {
    wp_dequeue_script( 'siteorigin-panels-front-styles' );
}
add_action( 'wp_footer', 'custom_so_dequeue_script', 1 );

/**
 * Remove the background and border styles from the row subdiv
 *
 * Because we're using the style wrapper as the container, we now need to move the background
 * and borders to the outer div.
 *
 * @param    array   $css   the input css array
 * @return   array          the output css array
 */
function custom_so_remove_row_subdiv_styles( $css )
{
    foreach ( $css as $key => $style ) {
        if ( strpos( $key, 'background' ) !== false || strpos( $key, 'border' ) !== false ) {
            unset( $css[ $key ] );
        }
    }

    return $css;
}
add_filter( 'siteorigin_panels_row_style_css', 'custom_so_remove_row_subdiv_styles', 10, 1 );

/**
 * Add the background and border styles to the parent row div
 *
 * Since we removed some of the styles from the row style wrapper, we need to
 * re-add them to the parent div.
 *
 * @param    object   $css           the SiteOrigin CSS object
 * @param    array    $panels_data   the panel data
 * @param    int      $post_id       the post id
 * @param    array    $layout_data   the row data
 * @return   object                  the modified SiteOrigin CSS object
 */
function custom_so_add_row_parent_div_styles( $css, $panels_data, $post_id, $layout_data )
{
    foreach ( $layout_data as $ri => $row ) {
        $styles = SiteOrigin_Panels_Styles::general_style_css( array(), $row[ 'style' ] );

        // Remove non-bg
        foreach ( $styles as $key => $value ) {
            if ( strpos( $key, 'background' ) === false
                && strpos( $key, 'border' ) === false ) {
                unset( $styles[ $key ] );
            }
        }

        // Add the styles for the row
        $css->add_row_css( $post_id, $ri, '', $styles );
    }

    return $css;
}
add_filter( 'siteorigin_panels_css_object', 'custom_so_add_row_parent_div_styles', 10, 4 );

/**
 * Add custom classes to the row itself
 *
 * @param    array   $row_classes   the current row classes
 * @param    array   $row           the row data
 * @return   array                  the modified row classes
 */
function custom_so_add_row_parent_classes( $row_classes, $row )
{
    $classes = ( isset( $row[ 'style' ][ 'class' ] ) )
        ? explode( ' ', $row[ 'style' ][ 'class' ] )
        : array();

    $merged = array_merge( $row_classes, $classes );
    return $merged;
}
add_filter( 'siteorigin_panels_row_classes', 'custom_so_add_row_parent_classes', 10, 2 );

/**
 * Remove custom classes from the row style wrapper
 *
 * @param    array   $attrs    the current row attributes
 * @param    array   $style         the row style data
 * @return   array                  the modified row attributes
 */
function custom_so_add_row_subdiv_classes( $attrs, $style )
{
    $attrs[ 'class' ] = array();
    return $attrs;
}
add_filter( 'siteorigin_panels_row_style_attributes', 'custom_so_add_row_subdiv_classes', 10, 2 );

/**
 * Remove data parallax from row style wrapper attributes
 *
 * @param    array   $attrs    the current row attributes
 * @param    array   $style         the row style data
 * @return   array                  the modified row attributes
 */
function custom_so_remove_row_subdiv_parallax( $attrs, $style )
{
    if ( array_key_exists( 'data-siteorigin-parallax', $attrs ) ) {
        unset( $attrs[ 'data-siteorigin-parallax' ] );
    }

    return $attrs;
}
add_filter( 'siteorigin_panels_row_style_attributes', 'custom_so_remove_row_subdiv_parallax', 10, 2 );

/**
 * Add data parallax to row attributes
 *
 * @param    array   $attrs     the current row attributes
 * @param    array   $style     the row style data
 * @return   array              the modified row attributes
 */
function custom_so_add_row_parallax( $attrs, $row )
{
    $general_attrs = SiteOrigin_Panels_Styles::general_style_attributes( array( 'class' => array() ), $row[ 'style' ] );

    // Remove non-parallax attributes
    foreach ( $general_attrs as $key => $value ) {
        if ( strpos( $key, 'data-siteorigin-parallax' ) === false ) {
            unset( $general_attrs[ $key ] );
        }
    }

    return array_merge( $attrs, $general_attrs );
}
add_filter( 'siteorigin_panels_row_attributes', 'custom_so_add_row_parallax', 10, 2 );
```

**Comment by AlexGStapleton** [comment]
I don't see any issues with doing this, but I think this functionality should behind a hook rather than a general setting - that way theme developers can hook into it without issue and users who aren't aware of what the setting does won't enable it.

It might be a good idea for you to submit a [pull request](https://help.github.com/articles/about-pull-requests/) with the desired functionality as that will provide a solid foundation from someone who's designed a theme around these sort of changes. Is that something you're keen on?

**Comment by petemolinero** [comment]
I'd totally be open to doing a pull request, and hiding it behind a hook rather than a setting makes sense to me as well.

In my mind the only two things that really need to be done are:

**1. Have an way to predictably remove the JS resizing**
Is there any guarantee that the [siteorigin-panels-front-styles](https://github.com/siteorigin/siteorigin-panels/blob/9d92d6770eb440562aba828d2dd313deae100ab6/js/styling.js) JS file will only contain the resize code in the future? It does right now, but if there's any chance it might include something else in the future, I'd say that simply dequeuing it isn't a very reliable way to disable resizing.

**2. Add before/after filter hooks between row style wrappers and cells.**
I think the easiest way to do this would be to add before/after hooks between the row style wrapper and the cells. Do you see any issue with that?
https://github.com/siteorigin/siteorigin-panels/blob/ce3ae33b5713e89cce132bdfb4d1faa20143db7b/inc/renderer.php#L704-L722

**Comment by AlexGStapleton** [comment]
1. It's very unlikely this will change as we know people are specifically dequeuing to prevent the resize code from running so we know that if we were to add additional (and unrelated code) it could cause major issues for certain issues.

2. I don't have anything against this, but I'm not sure why this would be required. Is there anything stopping you from applying a custom class directly to the row (not the styles) itself?

**Comment by petemolinero** [comment]
1. Sounds good! Glad to hear it.
2. The most common problem with this is that it would make it impossible for a user to have a full width background image (or color) but have their content inside a container (e.g. the default behavior of the "Full-width" layout of the page builder). I'd also like to preserve the ability to do things like a border on the bottom of a full width row (with contained content), and things like that. Basically, the only way that I can think of to allow this behavior would be to add a container directly around the cells.

**Comment by AlexGStapleton** [comment]
Hi @petemolinero,

We're going through our issue lists and we've decided to close this due to lack of requests. We really appreciate your feedback and thoughts on this issue and as discussed, we're still open to a PR from you.

**Comment by ingageco** [comment]
@AlexGStapleton I apologize for resurrecting an old thread, but you mentioned being open to a PR. Are you open to a PR for adding filters after row open and before row close, as mentioned by the OP? If so, i'll submit ASAP.
