### ISSUE TITLE
Yoast: When PB is active, text calulation is incorrect

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#558]
When Page Builder is installed, the Yoast word count calculation is incorrect when a header is present (specifically an h2) - this happens when Page Builder isn't enabled.

For example, the following text should calculate to 4, but while Page Builder is active it'll calculate to 2.
```
Test1 Test

<h2>Example</h2>
Other
```

[Reference video](https://drive.google.com/a/siteorigin.com/uc?id=183jajaU-XrwQFN7GCcSkc5V-p6sY8UiU)

**Comment by gregpriday** [comment]
Resolved with https://github.com/siteorigin/siteorigin-panels/commit/b6e6e0746fe28726ffd4a2e83b2a2e33258f41d7
