### ISSUE TITLE
Feature Request - Tablet width option

### ISSUE THREAD

**Issue by chiedo** [siteorigin/siteorigin-panels#56]
Hey guys,
Great product! What would be the possibility of getting a tablet width option that defaulted to a 2 column layout as opposed to needing to go straight to the mobile option which defaults to a 1 column layout?

**Comment by chiedojohn** [comment]
Any follow up?

**Comment by braamgenis** [comment]
Hi @chiedo 

Apologies for taking so long to respond. This is definitely something we'll be looking into soon. Thanks for your input.

**Comment by chiedo** [comment]
No prob, 
Thanks for the follow up!

**Comment by gregpriday** [comment]
We've since added tablet collapse point.
