### ISSUE TITLE
Page Builder Data not dumped

### ISSUE THREAD

**Issue by bondansebastian** [siteorigin/siteorigin-panels#566]
Hi there, 
First of all thanks for making this wonderful plugin.

Currently i am experiencing problem with dumping Page Builder Data.
Followed https://siteorigin.com/docs/page-builder/bundling-prebuilt/ but no dump found, on edit, live editor, or view mode.

I have put code block below in my `wp-config.php`

    define('WP_DEBUG', true);
    define('SITEORIGIN_PANELS_NOCACHE', true);
    define('SITEORIGIN_PANELS_DEV', true);

Tried to dive into `siteorigin-panels` code, but i cannot find any usage of `SITEORIGIN_PANELS_DEV` constant inside.

Tried on Windows 10 Version	10.0.17134 Build 17134 OS with these browsers:

- Chrome 67.0.3396.99 (Official Build) (64-bit)
- Mozilla Firefox 61.0.1 (64-bit)

**Comment by Misplon** [comment]
Hi @bondansebastian 

Are you creating a pre-built layout? If so, you can export the JSON file rather and use the method seen here:

https://github.com/siteorigin/siteorigin-corp/blob/develop/inc/siteorigin-panels.php#L11-L18

https://github.com/siteorigin/siteorigin-corp/tree/develop/inc/layouts

**Comment by bondansebastian** [comment]
Hi @Misplon 
That's right, i'm trying to create a pre-built layout
Thanks for the links, works like a charm.

I think it would really help if the [documentation](https://siteorigin.com/docs/page-builder/bundling-prebuilt/) gets updated ;)

**Comment by Misplon** [comment]
Glad that helped. For sure, we'll get the docs updated ASAP, thanks for the reminder. All the best.
