### ISSUE TITLE
Margin between widgets in same row (2.1 beta)

### ISSUE THREAD

**Issue by Prelc** [siteorigin/siteorigin-panels#57]
Hi,

I start to testing new version of Page Builder (I really like the new settings pages :) ) and i found interesting conflict between version 2.0 and 2.1 beta.

In the version 2.0 we have 4 same widgets on under the another in the same row like that - http://awesomescreenshot.com/0e34qknfc2 Between all 4 widgets there is automatically added margin-bottom: 30px; in the class `.pg(or pl)-(some-number) .panel-grid-cell .panel {margin-bottom: 30px;}`

In the version 2.1 beta this is no longer the case and there is no more space between widgets: http://awesomescreenshot.com/0364qkph3b Is this now on purpose like that? Or it is just a bug which will be fixed until release? If it is not the bug and is meant to be like that, what would be the best way to fix it? (Since it is going for WordPress theme i don't like the idea for adding custom CSS with margin for each widget or something like that).

Thanks in advance for the answer.

**Comment by gregpriday** [comment]
Hi Prelc

We actually came across this issue and were able to fix it. Can you check if this is working for you in the 2.1 release?

https://github.com/siteorigin/siteorigin-panels/releases/tag/2.1

**Comment by Prelc** [comment]
Hi Greg,

It works perfect with the 2.1 release. Thanks for this great plugin.

**Comment by gregpriday** [comment]
Fantastic! And thanks for taking time to dive into the beta version. Very much appreciated :)
