### ISSUE TITLE
WP release 4.9.8 --> Gutenberg Plugin

### ISSUE THREAD

**Issue by PremalathaKumar** [siteorigin/siteorigin-panels#571]
Hi There,

We have used Site Origin Page Builder Free version. 
Now We updating the WP version to 4.9.8 and Installed Gutenberg Plugin. 
But the problem is When adding the New Page Gutenberg editor don't have any option for Page builder section. 
and I checked the Blocks. and Don't see any Site Origin widgets. 
Currently, I have Site Origin 2.8.1 version. 
Could you please help me. 
Thank you!

**Comment by AlexGStapleton** [comment]
While using the Gutenberg editing mode, SiteOrigin Page Builder acts as a block so you'll need to add the SiteOrigin Layout block to your page to be able to use SiteOrigin Page Builder. If you would rather SiteOrigin Page Builder to be the main focus while editing the page, consider using the [Classic Editor](https://wordpress.org/support/plugin/classic-editor) which will restore the previous editing functionality.

We should be releasing our Gutenberg SiteOrigin Widgets Bundle integration shortly.

For more information, please refer to [this article](https://siteorigin.com/gutenberg-compatibility-page-builder/).

**Comment by PremalathaKumar** [comment]
Hi Alex,

Thanks for the reply. 
I have seen the article before. 
and I have checked the plugin changelog. It said, Siteorigin Layout Gutenberg Block!. 
So I thought you guys have added the Site Origin Block. 
But I didn't see any block related to site Origin. 
So Only I raised the issue. 
Am I wrong?

**Comment by AlexGStapleton** [comment]
Ah, you're right. Regrettably, there's been a Gutenberg update and this update has changed how blocks are added. This means that the previously correct way we were adding our blocks is no longer valid so they won't appear. This will be fixed in a SiteOrigin Page Builder shortly.

I'm really sorry about this but as Gutenberg is still in beta, this sort of things are sadly to be expected.

**Comment by gregpriday** [comment]
Resolved in https://github.com/siteorigin/siteorigin-panels/commit/b1779f57c16038bc5b440e1b650ce5695ffba502
