### ISSUE TITLE
Yoast Analysis: Unable to pick up Tabs or Accordion widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#572]
The Yoast Analysis isn't able to pick up on text added to the SiteOrigin Tabs or SiteOrigin Accordion widgets.

[Test Layout](https://drive.google.com/a/siteorigin.com/uc?id=10ByKOwNafQWloKcwsS-f0LkSvtfvT_bI)

**Comment by gregpriday** [comment]
The solution here would be to add a custom Widget handler to our Yoast compat file https://github.com/siteorigin/siteorigin-panels/blob/develop/js/yoast-compat.js#L62

So just converting each widget into a heading tags and div tags with the tab/accordion content.
