### ISSUE TITLE
Widget row Issue

### ISSUE THREAD

**Issue by julianbianqui** [siteorigin/siteorigin-panels#577]
If there a way to set a widget inside a row and not move it?

**Comment by Misplon** [comment]
Hi @julianbianqui 

Thanks for reaching out. Please, could you post your question on the forum and let me know once that's done. https://siteorigin.com/thread. I'll escalate your question once it has been posted, thanks.

**Comment by Misplon** [comment]
Hi @julianbianqui 

Did you have a chance to post on our forum? Please, send me the link so I can escalate the thread for you. Thanks.

**Comment by Misplon** [comment]
Thanks :)
