### ISSUE TITLE
Fatal error when we use get_current_screen during Gutenberg post type status check

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#582]
[Reported here](https://wordpress.org/support/topic/php-fatal-error-151/)

[This line](https://github.com/siteorigin/siteorigin-panels/blob/2.8.2/inc/admin.php#L1190) can cause errors during Ajax. 
> 2018/09/17 09:54:36 [error] 26402#26402: *17754 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to undefined function get_current_screen() in /home/site3437823/public_html/wp-content/plugins/siteorigin-panels/inc/admin.php:1190

---

While on paper this looks to be a simple change, @braamgenis was concerned that this change may cause additional Gutenberg related issues if mishandled or if something was overlooked. Here's the related [Slack chat](https://siteorigin.slack.com/archives/C02SYBBH2/p1537804543000100).

**Comment by braamgenis** [comment]
Resolved in 4e320a77f7a84f9c479fbb081dadb436cfac06ee
