### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by fabianpimminger** [siteorigin/siteorigin-panels#59]
Hi,

I've thought about translating this plugin to german as I'm using it for a few german clients. What's the best way to do this? Would it be ok if I'll send you a pull request with the translation files?

Cheers, Fabian

**Comment by gregpriday** [comment]
Hi Fabian

That's awesome! We're actually working with a group of professional translators to translate Page Builder into 11 additional languages. So far, the German translation has been completed, but we still need to check it before it's ready to go live.

We're hoping to get all these translations in by the end of the week.

We're working on a collaborative platform. If you have a little time I'd really appreciate it if you could take a look at what we have so far and add your translations.

https://poeditor.com/join/project?hash=82847115cc12f5d35ec3d066495dca1a

**Comment by richrd** [comment]
Hi,

I often use PageBuilder for clients websites. Great work and thanks!
Seems like Finnish isn't one of the 11 languages listed.
I could volunteer to do a Finnish translation, since I speak Finnish and English natively.

What do you think?

**Comment by gregpriday** [comment]
I've just approved your request to join. I'm looking forward to getting Finnish
in Page Builder :)

On Tue, Apr 7, 2015 at 3:33 PM, Richard Lewis <notifications@github.com>
wrote:

> Hi,
>
> I often use PageBuilder for clients websites. Great work and thanks!
> Seems like Finnish isn't one of the 11 languages listed.
> I could volunteer to do a Finnish translation, since I speak Finnish and
> English natively.
>
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/siteorigin/siteorigin-panels/issues/59#issuecomment-90555706>
> .
>



-- 
I make free WordPress themes
http://siteorigin.com

**Comment by richrd** [comment]
Great, thanks! :+1:

**Comment by luizrw** [comment]
Hi,

Have you adopted me in the project. Already finished the translation of pt_BR. You have any idea when it will update with the new languages?

Sorry for my english.

**Comment by richrd** [comment]
Hi!
I've been busy and it took me a long time to get back to translating. The Finnish translation is now done.
Looking forward to seeing it added at some point :)
