### ISSUE TITLE
Gutenberg: Assess whether to add wide and full options to the SO Widget block

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#593]
Assess what the impacts might be of adding wide and full options to the layout block.

https://wordpress.org/gutenberg/handbook/block-api/#supports-optional

**Comment by braamgenis** [comment]
I think the same applies here as with siteorigin/so-widgets-bundle#755

**Comment by Misplon** [comment]
Totally. Thanks for closing.
