### ISSUE TITLE
Bug: CSS generated for styling cells uses class that's never assigned

### ISSUE THREAD

**Issue by Epixors** [siteorigin/siteorigin-panels#596]
Hey guys,

I'm currently using the Page Builder plugin in conjunction with ACF using ACF Page Builder Field. I'm extending the editor to allow for color overlays on a background image. I've successfully implemented this for rows, but I'm running into an issue with the cells.

Here is the code that sets up the hooks.

```php
function custom_cell_style_fields($fields) {
  global $customFields;

  $fields['background-color-overlay'] = $customFields['background-color-overlay'];

	$fields['background-color-overlay-opacity'] = $customFields['background-color-overlay-opacity'];

  return $fields;
}

add_filter( 'siteorigin_panels_cell_style_fields', 'custom_cell_style_fields' );

function custom_cell_style_css( $attributes, $args) {
		$hexColor = (!empty($args['background-color-overlay'])) ? $args['background-color-overlay'] : null;

		$opacity = (!empty($args['background-color-overlay-opacity'])) ? (is_numeric($args['background-color-overlay-opacity']) ? (int)$args['background-color-overlay-opacity']/100 : 0.75) : 0.75;
		$opacity = max(0.0, min(1.0, $opacity));

		if($hexColor != null){
			//Take RGB values from the hex color
			list($r, $g, $b) = sscanf($hexColor, "#%02x%02x%02x");
			$attributes['background'] = 'linear-gradient(rgba('. $r .', '. $g .', '. $b .', ' . $opacity . '), rgba('. $r .', '. $g .', '. $b .', ' . $opacity . '))';
			if( !empty($attributes['background-image'])){
				$attributes['background'] .= ', ' . $attributes['background-image'];
				unset($attributes['background-image']);
			}
		}

    return $attributes;
}

add_filter('siteorigin_panels_cell_style_css', 'custom_cell_style_css', 10, 2);
```

This will properly show the fields on the backend, and generate CSS according to the input. That's all fine. The issue here is that the rendered CSS has the following structure:

```css
#acfpbf_3ac864-pgc-114-5-0 > .panel-cell-style {
    background-image: url(some_link.jpg);
    background-position: center center;
    background-size: cover;
    padding: 0px 0px 0px 0px
}
```

This is targeting a descendant of the cell with the class .panel-cell-style. This class however is never assigned. The HTML structure is as follows:

```
<div class="panel-grid-cell " id="acfpbf_3ac864-pgc-114-5-0">
    <div id="panel-114-5-0-0" class="so-panel widget widget_text panel-first-child panel-last-child" data-index="0">
        <div class="textwidget">
            <p>1</p>
            <p>2</p>
            <p>3</p>
            <p>4</p>
            <p>5</p>
            <p>&nbsp;</p>
        </div>
    </div>
</div>
```

The .panel-cell-style should be applied to the div with id panel-114-5-0-0, but it never happens.

Note: The $customFields variable is assigned elsewhere so it can be shared among different extension files. This is the relevant content.

```php
$customFields["background-color-overlay"] = array(
  'name'        => __('Background Color Overlay', 'siteorigin-panels'),
  'type'        => 'color',
  'group'       => 'design',
  'description' => __('If a color is chosen, overlays this color on the selected background (image)', 'siteorigin-panels'),
  'priority'    => 8,
);

$customFields["background-color-overlay-opacity"] = array(
  'name'        => __('Background Color Overlay Opacity', 'siteorigin-panels'),
  'type'        => 'text',
  'group'       => 'design',
  'description' => __('Sets opacity for the color overlay. 0 is fully transparent, 100 is fully opaque. Defaults to 75.', 'siteorigin-panels'),
  'priority'    => 8,
);
```

Is this an issue with the Page Builder renderer, or a conflict between the plugins I'm using?

**Comment by Epixors** [comment]
**Update**
Worked around it for now by adding the following

```php
function custom_widget_classes($classes, $widget_class, $instance, $widget_info){
  array_push($classes, "panel-cell-style");
  return $classes;
}

add_filter( 'siteorigin_panels_widget_classes', 'custom_widget_classes', 10, 4);
```

but this obviously creates a lot of bloat, and shouldn't really be needed.

**Comment by Epixors** [comment]
Advanced Custom Fields with the compatibility plugin for Page Builder will edit the structure (changes IDs), so in a way affects cell styles, though the CSS seems to change properly accordingly.

What do you mean with the settings for the cell styles values? In terms of the field settings it's the same as the version you posted. On the backend it'll properly show, and it will properly generate the CSS according to the provided hex color and opacity value (0-100). It just doesn't end up actually rendering because the panel-cell-style class is never applied anywhere.

**Comment by AlexGStapleton** [comment]
By cell style values, I mean the literal values you selected in the SiteOrigin Page Builder interface. Would it be possible for you to send me an export of the test page you're working on? To do this please open up the page in the editor and click the Layout button in the Page Builder toolbar. Then click import/export and then click download. Please upload the export to a 3rd party file hosting site such as <a href="https://wetransfer.com/">WeTransfer</a>.

To confirm, do you have any other SiteOrigin Page Builder focused code that affects the structure of rows, cells, or even widgets? If so, can you please temporarily disable it? I ask as I'm trying to rule out unrelated code that I don't have as that may be the reason why the markup isn't outputting for you correctly.

**Comment by AlexGStapleton** [comment]
Thanks. The provided values work without issue for me. Can you please create a test page? Sorry about this!

Also, can you plase confirm the following:

> do you have any other SiteOrigin Page Builder focused code that affects the structure of rows, cells, or even widgets? If so, can you please temporarily disable it? I ask as I'm trying to rule out unrelated code that I don't have as that may be the reason why the markup isn't outputting for you correctly.

**Comment by Epixors** [comment]
As I've mentioned before the only thing affecting the structure is ACF. I'll try to set up a demo page without it ASAP.

**Comment by Epixors** [comment]
Hey, have been out of office for a bit. I'm currently reworking the way I'm extending the options in Page Builder. If I end up running into the same issue I'll reopen it, for now this can get closed. Sorry to be a bother 😅

**Comment by Epixors** [comment]
Update: Found out where the compatibility issue lies. It's specifically the ACF Page Builder Field plugin. 

https://github.com/Angrycreative/ACF-Page-Builder-Field/blob/master/acf-page-builder-field.php

I wasn't using the 'siteorigin_panels_cell_style_attributes' hook, so $attributes was always empty, and it would never get to the part where it adds the panel-cell-style class. I should be able to restructure so this works without a dirty workaround, thanks for the help 👍

**Comment by AlexGStapleton** [comment]
Great to hear you managed to find a solution to this issue. Thanks for letting us know the cause and your solution! :)
