### ISSUE TITLE
Gutenberg: Context menu not appearing inside of WB Builder field when added using a SiteOrigin Layout Block

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#597]
Right clicking a widget or row inside of a builder field will result in the standard browser window appearing. 

[Video](https://drive.google.com/a/siteorigin.com/uc?id=13H2b_iMEtDmUMV39Vh933x8ujjo0iy3w) (excuse the mouse placement - it's an issue with the software used)

**Comment by AlexGStapleton** [comment]
I received a report of this sort of issue happening with the layout builder in general. Would this fix that?

**Comment by braamgenis** [comment]
Yes, the issue wasn't specific to the block editor.
