### ISSUE TITLE
Sidebars Emulator changes caused Master Slider shortcode to no longer work

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#600]
[Reported here](https://siteorigin.com/thread/invalid-slider-id-master-slider-id-must-be-a-valid-number/).

The recent Sidebars Emulator changes have broken the compatibility of the [Master Slider](https://wordpress.org/plugins/search/master+slider/) (100k) shortcodes. Previously, the slider would display without issue. Now, the user will receive an error message stating:

> Invalid slider id. Master Slider ID must be a valid number

Master Slider works without issue when the Sidebar Emulator functionality is disabled.

**Comment by andrejarh** [comment]
I am getting an error with Sidebars Emulator in the change log:
```
Undefined index: id in /home/orionthemes/ut.orionthemes.com/gaia/wp-content/plugins/siteorigin-panels/inc/sidebars-emulator.php on line 50
[11-Dec-2018 10:30:24 UTC] PHP Notice:  Undefined offset: 1 in /home/orionthemes/ut.orionthemes.com/gaia/wp-content/plugins/siteorigin-panels/inc/sidebars-emulator.php on line 51
```
I am not using the Master slider, but just reporting in case if it is connected.

**Comment by AlexGStapleton** [comment]
The issue also occurs for [SportsPress](https://en-au.wordpress.org/plugins/sportspress/) (20k) Events List plugin.

**Comment by braamgenis** [comment]
@AlexGStapleton I can't seem to reproduce the issue with Master Slider. Could you give some more specific steps to reproduce?

* Create slider.
* Insert slider shortcode in Editor Widget in a Page Builder page.
* Save and View Page
* Seems to work as expected.

**Comment by AlexGStapleton** [comment]
I can't seem to replicate this issue anymore but I would give SportsPress a try - that's really simple to replicate and likely the same issue.

- Install SportsPress
- Add a Calendar 
- Add an Events List widget to the page and select the newly created Calendar 
- The calendar setting will be reset back to all on save
