### ISSUE TITLE
Yoast Analysis: Unable to pick up widgets inside of a Layout Builder

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#601]
This issue is similar to #572.

Widgets added to a Layout Builder widget are unable to be picked up on by Yoast and will be completely ignored.

**Comment by braamgenis** [comment]
Is this still happening for you? If so please give some more speficic steps to reproduce.

**Comment by AlexGStapleton** [comment]
I'm no longer able to replicate this.
