### ISSUE TITLE
Inefficient CSS generation

### ISSUE THREAD

**Issue by MichaelPote** [siteorigin/siteorigin-panels#603]
If the global Row Gutter setting in the Page Builder options menu is set to 0, the page builder will still try to write out a CSS calc() statement for each column, even though it can be simplified to reduce the computation load on browsers.

```
#pgc-11-0-1 {
	width: 34%;
	width: calc(34% - ( 0.66 * 0px ) );
}
```

Should be simplified to:
```
#pgc-11-0-1 {
	width: 34%;
}
```

**Comment by Misplon** [comment]
Thanks for posting.
