### ISSUE TITLE
Problem with sidebar_admin_setup

### ISSUE THREAD

**Issue by mbrammer** [siteorigin/siteorigin-panels#61]
I figured out that the call of "do_action( 'sidebar_admin_setup' );" in siteorigin-panels.php#337 causes an error which breaks the WP theme customizer.
After commenting the line out of the plugin code, the customizer works again.

Another thing I figured out is that the problem can be solved when I delete the templates widgets from the footer.
I'm not sure what the problem is with the sidebar and/or the widgets, but here a code example that you know what I#m talking about.

```
if ( ! function_exists( 'foobar_widgets_init' ) ):
	function foobar_widgets_init() {
		register_sidebar( array(
			'name'          => __( 'Footer (center)', 'foobar' ),
			'id'            => 'footer-center',
			'description'   => __( 'Add widgets here to appear in the middle of the footer.', 'foobar' ),
			'before_widget' => '<div id="%1$s" class="%2$s">',
			'after_widget'  => '</div>',
			'before_title'  => '<h4>',
			'after_title'   => '</h4>',
		) );
		register_sidebar( array(
			'name'          => __( 'Footer (right)', 'foobar' ),
			'id'            => 'footer-right',
			'description'   => __( 'Add widgets here to appear on the right of the footer.', 'foobar' ),
			'before_widget' => '<div id="%1$s" class="%2$s">',
			'after_widget'  => '</div>',
			'before_title'  => '<h4>',
			'after_title'   => '</h4>',
		) );
	}
	add_action( 'widgets_init', 'foobar_widgets_init' );
endif;
```

I tested some free templates from the WordPress community. You can reproduce it for example with the theme "i-excel".
If you add a widget to the "Main Widget Area" sidebar, the theme customizer at http://yourdomain.com/wp-admin/customize.php?theme=i-excel will not work anymore.

**Comment by gregpriday** [comment]
Aaah, this was a bit of an oversight. The conditional that comes before that do_action should have been checking for the customizer interface too.

https://github.com/siteorigin/siteorigin-panels/blob/develop/siteorigin-panels.php#L365

Hopefully this is as easy as adding an extra check. I'm looking into this now.

**Comment by mbrammer** [comment]
Wow, that was a fast reply :+1: 
Thanks for that!

**Comment by gregpriday** [comment]
I couldn't quite recreate the issue, but would you mind trying out the current develop branch and see if it fixes the issue?

https://github.com/siteorigin/siteorigin-panels/commit/ee21e3a

**Comment by mbrammer** [comment]
This works perfectly! Thanks for that quick solution!

**Comment by gregpriday** [comment]
It's an absolute pleasure. Thanks for letting us know about this issue -
please keep the bug reports coming :)

On Thu, Apr 9, 2015 at 1:59 PM, Mischa Brammer <notifications@github.com>
wrote:

> This works perfectly! Thanks for that quick solution!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/siteorigin/siteorigin-panels/issues/61#issuecomment-91209120>
> .
>



-- 
I make free WordPress themes
http://siteorigin.com
