### ISSUE TITLE
Import layout problems in 2.9.x in combination with ReduxFramework when `ini_set('display_errors',1);

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#613]
I am experiencing import layout issues when updated to 2.9.x version. While it works perfectly in 2.8.

Here is an example import file: https://drive.google.com/open?id=123L8QLllZ_SaPMpL5eIVC5ycRzUPehPJ

The error is here: 
![screenshot 2018-12-11 at 13 02 44](https://user-images.githubusercontent.com/10053621/49799762-064c4580-fd46-11e8-85e1-af04f5f3ca72.png)

The import consists of custom widget built with siteOrigin widget bundle.  

When I add the json export to https://jsonlint.com/ it says the json is valid.

**Comment by AlexGStapleton** [comment]
I've tried the provided layout and it imports without issue for me. To clarify, are you importing into the full SiteOrigin Page Builder Classic Editor interface or into a block (SiteOrigin Layout)?

**Comment by andrejarh** [comment]
Thank you Alex for checking this out. I was using the classic editor.

I did some further testing and found out that the Page Builder is not causing this issue by itself, but it is somehow connected with https://github.com/reduxframework/redux-framework.
When I disabled the Redux framework, I was able to import json successfully without issues. 

I changed the title of this issue, to make it more specific. I will do some further testing. If I pinpoint the reason for this issue or find out how it can be easily reproduced, I will let you know.

**Comment by AlexGStapleton** [comment]
Thank you for letting me know about the conflicting plugin. Let me know how you go with the additional tests.

**Comment by andrejarh** [comment]
Hi,
So I managed to pinpoint the changes which caused this in  SO Panels.
In the file inc/admin-layouts.php, the action_import_layout() has changed
this lines were added 
**2.8.x version:**
```
		if ( ! empty( $_FILES['panels_import_data']['tmp_name'] ) ) {
			header( 'content-type:application/json' );
			$json = file_get_contents( $_FILES['panels_import_data']['tmp_name'] );
			@unlink( $_FILES['panels_import_data']['tmp_name'] );
			echo $json;
		}
```
**2.8.x version:**
```
		if ( ! empty( $_FILES['panels_import_data']['tmp_name'] ) ) {
			header( 'content-type:application/json' );
			$json = file_get_contents( $_FILES['panels_import_data']['tmp_name'] );
			$panels_data = json_decode( $json, true );
			$panels_data = apply_filters( 'siteorigin_panels_data', $panels_data, false );
			$panels_data['widgets'] = SiteOrigin_Panels_Admin::single()->process_raw_widgets( $panels_data['widgets'], array(), true, true );
			$json = json_encode( $panels_data );
			@unlink( $_FILES['panels_import_data']['tmp_name'] );
			echo $json;
		}
```
When I reverted just this change in latest SO Page builder, the import started working again.
For debugging purposes, I then printed the original json version and the new json version into the error log:
```
		if ( ! empty( $_FILES['panels_import_data']['tmp_name'] ) ) {
			header( 'content-type:application/json' );

			$json = file_get_contents( $_FILES['panels_import_data']['tmp_name'] );
			
			$panels_data = json_decode( $json, true );
			**error_log(print_r('$json1: '.json_encode($json),true));**
			$panels_data = apply_filters( 'siteorigin_panels_data', $panels_data, false );
			$panels_data['widgets'] = SiteOrigin_Panels_Admin::single()->process_raw_widgets( $panels_data['widgets'], array(), true, true );
			$json = json_encode( $panels_data );
			**error_log(print_r('$json2: '.$json,true));**
			@unlink( $_FILES['panels_import_data']['tmp_name'] );
			echo $json;
		}
```
There is quite a lot of difference between the two json files. The [diff can be seen here ](https://www.diffchecker.com/IXvc3QQk) The whole error log I got is accessible here: https://drive.google.com/open?id=1diw-HNMF6jQ-3CeruyogrZf1Aty5gipc
There are also PHP warnings inside like this one:
`[12-Dec-2018 08:53:54 UTC] PHP Warning:  json_decode() expects parameter 1 to be string, array given in /Users/andrej/Documents/webdev/gaiatheme/wordpress/wp-content/plugins/so-widgets-bundle/base/inc/fields/builder.class.php on line 58
`
If you have any further ideas what to test, please let me know.
Thanks

**Comment by AlexGStapleton** [comment]
The highlighted section was changed to resovle #556.

To clarify, in the combined code, which line is line 58? This one?

`$panels_data = json_decode( $json, true );
`

Regarding the diffs, which is which? Is red the old import code and the green is the new import code?
Does the PHP warning occur when the Redux Framework is disabled?

**Comment by andrejarh** [comment]
Hi, 
Yes I can confirm that this is the line 58. 
DIFF: The first one (red) is before the second one(green) is the new one.
PHP json warning is not present also when the plugin which uses the redux framework is disabled.

Also what I found out is 
1. The problem with the import appears only if reporting is turned on:
`ini_set('display_errors',1);
ini_set('display_startup_errors',1);
error_reporting(-1);`
Removing this imports everything just fine.

And only if there is an error somewhere else on the site (ie: caused by another plugin). 

2. The issue does not appear solely by installing latest version of Redux F. I couldn't reproduce it on a fresh installation with the latest redux version.


You guys are doing a great job. SiteOrigin is still the most resource friendly builder (source: https://pagely.com/blog/wordpress-page-builders/ ). 
Are there any plans for SO "blocks" bundle, which could make it easier to build Gutenberg blocks? :)

In production people don't have the error reporting on and it is highly unlikely that this issue would be relevant for many other users. 

**This issue isn't caused by the SiteOrigin panels, but by external factors, so I am closing it.**

**Comment by AlexGStapleton** [comment]
> Are there any plans for SO "blocks" bundle, which could make it easier to build Gutenberg blocks? :)

That's something I would definitely like to see long-term. I know it's not 100% ideal, but the SiteOrigin Widget Block will allow your users to use any widgets created using the SiteOrigin Widgets Bundle.
