### ISSUE TITLE
SiteOrigin Premium CPTB: Remove Gutenberg Add New Option

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#614]
As the SiteOrigin Premium CPTB functionality intentionally doesn't allow for Gutenberg, we should remove this option.

![](https://vgy.me/ZaYKy5.png)

**Comment by braamgenis** [comment]
Should be fixed in the latest. Let me know if it's not working for you.

**Comment by AlexGStapleton** [comment]
I can confirm this is working. 👍
