### ISSUE TITLE
Correct Syntax: Warning: "continue" targeting switch is equivalent to "break".

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#618]
Resolve the following warning:

`Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /wp-content/plugins/siteorigin-panels/inc/styles-admin.php on line 392`

**Comment by petitours** [comment]
always the warning with WP 5.02

**Comment by Misplon** [comment]
Hi @petitours, thanks for reaching out. The issue has been resolved [here](https://github.com/siteorigin/siteorigin-panels/commit/f93a76d23e2e4d337ed1453580523581a40d4dcc) and will be included in the next release.

**Comment by Misplon** [comment]
For the moment, the best solution would be downgrade to PHP 7.2 or similar. This is possible with all hosts.
