### ISSUE TITLE
Sanitize HTML before inserting with DangerouslySetInnerHTML

### ISSUE THREAD

**Issue by jeremeylduvall** [siteorigin/siteorigin-panels#619]
Flagging this for review. Currently, the plugin is using `dangerouslySetInnerHTML` to output HTML to the page here:

https://github.com/siteorigin/siteorigin-panels/blob/master/compat/js/siteorigin-panels-layout-block.js#L201

It doesn't appear as though this content is sanitized prior to being output. Should this be wrapped with `DOMPurify.sanitize()` or something similar?

**Comment by braamgenis** [comment]
The user input is being appropriately sanitized and the server-side rendered HTML escaped on the server before it's returned to the front-end and added to the DOM. It's a dynamic block for legacy reasons and was done this way before the `ServerSideRender` component was added to the block editor, but it's effectively the same.

**Comment by jeremeylduvall** [comment]
@braamgenis - thanks for the reply! I understand that the current implementation and use case is properly handled. The concern would be future use cases for the component. Since the component accepts a prop and passes it directly to `dangerouslySetInnerHTML` without sanitizing, another dev could accidentally create something new utilizing this component and pass it an unsafe prop value.

**Comment by braamgenis** [comment]
@jeremeylduvall Thanks for your concern! Ah, I see you mean the `previewHtml` state prop. That is set using the `withState` higher-order component to store the server-side rendered HTML and avoid having to refetch it on every render. As such it's meant to be for internal use only and shouldn't allow another dev to accidentally pass it anything, safe or unsafe. If `withState` is indeed allowing it's state props to be overridden, then it seems like there might be a flaw in it's implementation.

**Comment by jeremeylduvall** [comment]
Thanks Braam. I understand that the current use-case doesn’t necessitate the use of `DOMPurify`, and that the intention is for the block to be used in a specific manner. The suggestion is more for future precaution. If you’re not currently able to add sanitization to the use of `dangerouslySetInnerHTML`, we may need to discourage the use of the plugin on VIP sites that require 100% secure code moving forward.

**Comment by braamgenis** [comment]
@jeremeylduvall I've converted the block to extend a React `Component` and use internal state to store the preview and renders it using the `RawHTML` component. I.e. it's no longer accepting a prop and directly passing it to `dangerouslySetInnerHTML`. This will go out with our next release.

**Comment by braamgenis** [comment]
This went out with release [2.10.1](https://github.com/siteorigin/siteorigin-panels/tree/2.10.1)
