### ISSUE TITLE
customisation: radio buttons in Row Styles

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#620]
Hi guys,
Currently it is only possible to use radio buttons in widgets (using the W. Bundle), but not row styles. 
This doesn't work out of the box for example:

```
<?php function custom_radio_fields($fields) {

	$fields['radio_option'] = array(
		'name'        => esc_html__( 'Name', 'textdomain' ),
		'type'        => 'radio',
		'group'       => 'design',
		'priority'    => 10,
		'options' => array(
			'1' => esc_html__( '1', 'textdomain' ),
			'2' => esc_html__( '2', 'textdomain' ),
			'3' => esc_html__( '3', 'textdomain' ),
		),
		'default'  => '1'
	);
	return $fields;
}
add_filter('siteorigin_panels_row_style_fields', 'custom_radio_fields', 10, 2);

```
Is there any filter that I can use to add radio button capability into the Page builder Row styles section?

**Comment by AlexGStapleton** [comment]
Unfortunately, it's not possible to add additional fields using PHP at this time. I've submitted #623 and that will allow you to use a radio.
