### ISSUE TITLE
Namespaced Widgets Incorrectly Show as Missing When Adding New Layout

### ISSUE THREAD

**Issue by zschuessler** [siteorigin/siteorigin-panels#621]
When you add a new layout, if it contains a namespaced widget it will show up as missing, when in fact it exists. In all other scenarios namespaced widgets work great, seemingly.

This is because the class name is escaped, and the check fails here:
https://github.com/siteorigin/siteorigin-panels/blob/23ca4d4520c1b4048b11460bcd6625b616a15b6e/js/siteorigin-panels/model/widget.js#L31

```
initialize: function () {
		var widgetClass = this.get( 'class' );
		if ( _.isUndefined( panelsOptions.widgets[widgetClass] ) || ! panelsOptions.widgets[widgetClass].installed ) {
			this.set( 'missing', true );
		}
	},
```

A quick & dirty solution is to do this:

```
initialize: function () {
                var widgetClass = this.get( 'class' );
                widgetClass = widgetClass.split('\\\\').join('\\');
                this.set('class', widgetClass);

                if ( _.isUndefined( panelsOptions.widgets[widgetClass] ) || ! panelsOptions.widgets[widgetClass].installed ) {
                    this.set( 'missing', true );
                }
            },
```

This will convert the double slashes to single slashes. It's also important to set the class, as other parts of the javascript will depend on it as well.

In the mean time while a solution is found, is there a better way to make this change without an upgrade breaking my solution?

**Comment by zschuessler** [comment]
Closing this, I was able to get what I wanted by switching to Gutenburg + ACF's new Pro beta block setup.

**Comment by Misplon** [comment]
Hi Zachary, sorry we didn't reply at the time. I'm glad to hear you found a solution. All the best.
