### ISSUE TITLE
Show Add SiteOrigin Layout Block Button

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-panels#622]
At the moment, we're defaulting to using the classic editor for post types that are set to use Page Builder. While this is a good short term solution, in the long term we'd ideally take them to the block editor and only take them to the classic editor if they have the Classic Editor plugin installed.

One very easy way to achieve this is to include an "Add SiteOrigin Layout Block" button for any new pages created. This button should be displayed until other content is added to the block editor.

Here's a quick mockup of what that could look like:

![button-mockup](https://user-images.githubusercontent.com/1126859/50050703-b08fe880-010b-11e9-948f-c86f2b7024c7.png)

**Comment by braamgenis** [comment]
Done in #624
