### ISSUE TITLE
Since updating Social Media icons are broken 

### ISSUE THREAD

**Issue by frontenddevguy** [siteorigin/siteorigin-panels#629]
fb icon broken in ff dev ed, all icons not appearing in chrome.

This happens in footer and content (siteorigin social media buttons widget)

See: https://tictocsing.com/toc/

**Comment by Misplon** [comment]
Hi @frontenddevguy 

Are these the icons you're testing?

<img width="555" alt="toc_-_the_open_choir_-_tictoc_sing" src="https://user-images.githubusercontent.com/789159/50900818-f85e1300-141e-11e9-8362-fa25d7863818.png">

The WB update, updated Font Awesome 4 to 5 so there definitely could be browser caching issues.

**Comment by Misplon** [comment]
Above is Chrome, Firefox looks ok on my end too. Let me know what you find :)

**Comment by frontenddevguy** [comment]
It got fixed after updating core
