### ISSUE TITLE
Black Studio conflict with Page Builder in the Block Editor

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#632]
If Black Studio and Page Builder are both activated, the Block Editor isn't able to save the page. To recreate, activate Page Builder and Black Studio. Open a Block Editor page and try to save it.

[Reporting support thread](https://siteorigin.com/thread/pagebuilder-preventing-wordpress-block-editor-from-saving/).

**Comment by braamgenis** [comment]
@Misplon Does the page need any specific content? I installed and activated the [BS TinyMCE widget plugin](https://wordpress.org/plugins/black-studio-tinymce-widget/) and could save block editor pages without issue. Could you check whether this issue occurs for you when using the develop branch? It's possible that recent changes have fixed this issue.

**Comment by Misplon** [comment]
Sorry about this. The latest update of BS resolves. Really thought I had closed this. My bad.
