### ISSUE TITLE
Max Mega Menu widget doesn't work when added to the Layout Builder

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#633]
When you add a Max Mega Menu widget to a Layout Builder widget, the Max Mega Menu widget won't appear.

**Comment by gregpriday** [comment]
Do you have any steps to reproduce this @AlexGStapleton? I added 2 menus to my page. One inside a Layout Builder and one in a standard widget.

<img width="951" alt="screenshot 2019-02-12 at 08 55 44" src="https://user-images.githubusercontent.com/1126859/52617297-02eb4c80-2ea4-11e9-8ad7-72a1022f6a75.png">

It seems to be working as expected:

<img width="1206" alt="screenshot 2019-02-12 at 08 54 08" src="https://user-images.githubusercontent.com/1126859/52617251-dd5e4300-2ea3-11e9-9a71-f67202c0dca2.png">

**Comment by AlexGStapleton** [comment]
Sorry! I neglected to mention that this issue only affects widget areas.

**Comment by gregpriday** [comment]
Cool, I'll take a look.

**Comment by gregpriday** [comment]
That's working for me too. Added a layout widget to the footer of Corp, made 2 columns, added some text and a MMM. Everything working as expected.

<img width="1315" alt="screenshot 2019-02-13 at 09 41 19" src="https://user-images.githubusercontent.com/1126859/52694798-8cb61b00-2f73-11e9-8149-ac89e318c6ff.png">

Can you check if there's a more specific instance where this is happening?

**Comment by AlexGStapleton** [comment]
Oddly, I can't seem to replicate this issue anymore. Not too sure what changed. 😕 
Going to close this and re-open it if I find a reliable way to replicate it.

**Comment by Misplon** [comment]
Looks good for me too. I remember initially replicating this. Glad it's ok for the moment. Nice to keep compatibility with MMM when able, Tom's plugin and a free mega menu plugin.

**Comment by gregpriday** [comment]
Maybe it's something they fixed somewhere along the lines. Epic.

**Comment by gregpriday** [comment]
From their release note for version 2.3.7 [06/07/17]
> Fix: Compatiblity with SiteOrigin Page Builder Layout builder

**Comment by Misplon** [comment]
Epic! Nice find.
