### ISSUE TITLE
Create a welcome page

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#638]
Create a welcome page to be displayed on the first activation. This template will also be used for the Widgets Bundle and SO CSS. Initially populate with [Lorem](https://www.lipsum.com/feed/html).

**Comment by gregpriday** [comment]
I don't want to go too overboard and add it to all our plugins, but having this in PB will be great.

**Comment by Misplon** [comment]
Right on!

**Comment by gregpriday** [comment]
Here's the basics of what you're dealing with https://github.com/siteorigin/siteorigin-panels/tree/feature/welcome-page

For now it's fairly simple, but we can add anything else we need.

**Comment by Misplon** [comment]
Epic, will hit this tomorrow.

**Comment by Misplon** [comment]
Awaiting review at https://github.com/siteorigin/siteorigin-panels/issues/638.
