### ISSUE TITLE
Mod Security: prevent rule flagging certain post content

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#639]
We've started receiving more mod_security related reports lately. It's pretty easy for them to avoid this issue but I suspect a popular tool people are using to automate rule sets has added a rule that's triggering this. We should identify the offending rule(s) and come up with a solution to avoid it as best as we can.

One user did provide me with follow error log:

`[Tue Jan 15 19:11:36.917347 2019] [:error] [pid 3585794] [client 185.6.154.36:52155] [client 185.6.154.36] ModSecurity: Warning. Pattern match "(?i)<[^\\\\w<>]*(?:[^<>\\"'\\\\s]*:)?[^\\\\w<>]*(?:\\\\W*?s\\\\W*?c\\\\W*?r\\\\W*?i\\\\W*?p\\\\W*?t|\\\\W*?f\\\\W*?o\\\\W*?r\\\\W*?m|\\\\W*?s\\\\W*?t\\\\W*?y\\\\W*?l\\\\W*?e|\\\\W*?s\\\\W*?v\\\\W*?g|\\\\W*?m\\\\W*?a\\\\W*?r\\\\W*?q\\\\W*?u\\\\W*?e\\\\W*?e|(?:\\\\W*?l\\\\W*?i\\\\W*?n\\\\W*?k|\\\\W*?o\\\\W*?b\\\\W*?j\\\\W*?e\\ ..." at ARGS:instance. [file "/etc/apache2/conf.d/modsec_vendor_configs/OWASP/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "74"] [id "941160"] [rev "2"] [msg "NoScript XSS InjectionChecker: HTML Injection"] [data "Matched Data: \\x22title\\x22:\\x22\\x22,\\x22text\\x22:\\x22<h2 style=\\x22text-align: center;\\x22><span style=\\x22font-family: helvetica, arial, sans-serif;\\x22>\\x22Your brand is what other people say about you when you\\x19re not in the room\\x22- Jeff Bezos</span></h2>\\x0a<h2 style=\\x22text-align: center;\\x22></h2>\\x0a<p style=\\x22text-align: center;\\x22><span style=\\x22font-family: helvetica, arial, sans-serif; font-size: 14pt;\\x22>If branding was the association and perception in the customers mind, then bra..."] [severit [hostname "http://designs351.com/"] [uri "/wp-admin/admin-ajax.php"] [unique_id "XD4waLpRDKT1IFpV2g-dCwAAAB8"], referer: HTTPS://URL-TO-WEBSITE.TLD/post.php?post=20&action=edit&so_live_editor=1`

It seems to point to [this file](https://documentation.cpanel.net/display/CKB/OWASP+ModSecurity+CRS#OWASPModSecurityCRS-REQUEST-941-APPLICATION-ATTACK-XSS).

**Comment by gregpriday** [comment]
Some evidence of similar false positives on other sites - https://serverfault.com/questions/931856/modsecurity-false-positive-941100-and-941160-when-saving-wordpress-page

I can't seem to find an easy way of installing mod_security so @braamgenis is going to investigate. He's already got a VM setup going.

**Comment by gregpriday** [comment]
@AlexGStapleton do you have somewhere you could test this? I have an idea for a small change that might fix things. I could send you a build to test.

I'm thinking that if we load the HTML we're receiving from the server [here](https://github.com/siteorigin/siteorigin-panels/blob/develop/js/siteorigin-panels/dialog/widget.js#L173-L178) and load that into a jQuery object, we could split off CSS and JS files and manually inject them into the body. This might look less suspicious to `mod_security`.

**Comment by gregpriday** [comment]
[siteorigin-panels.dev-mod-security-fix.zip](https://github.com/siteorigin/siteorigin-panels/files/2854267/siteorigin-panels.dev-mod-security-fix.zip)

@AlexGStapleton here's a wild attempt at a quick fix. If it doesn't work, then @braamgenis will need to setup an environment to figure it out. ModSecurity seems to just not like us injecting JS/HTML, but there must be a way we can add scripts in a way it trusts.

If this does work, we'll just need to do some testing with a few popular widgets to make sure the change doesn't break anything.

**Comment by gregpriday** [comment]
I see this fix actually breaks the Layout Widget, so it'll definitely need some tweaks. Worth investigating if we're on the right track though.

**Comment by AlexGStapleton** [comment]
I don't actually have a method of testing mod_security. If you're confident the above file won't cause the site to fall over due to a fatal error, I'll ask the next person who reports this if they can try the above file.

**Comment by gregpriday** [comment]
It looks like I can create an EC2 instance pretty easily with mod_security. I'll test things there.

**Comment by gregpriday** [comment]
I can't seen to recreate this issue. Testing with the latest released version of Page Builder.

I have an EC2 instance running with mod_security installed. Have verified it's installed.

```
bitnami@ip-172-26-13-148:~$ sudo cat /opt/bitnami/apache2/logs/error_log | grep ModSecurity
[Tue Feb 12 16:12:24.248469 2019] [:notice] [pid 8915:tid 140578976581376] ModSecurity for Apache/2.6.7 (http://www.modsecurity.org/) configured.
[Tue Feb 12 16:12:24.248490 2019] [:notice] [pid 8915:tid 140578976581376] ModSecurity: APR compiled version="1.6.2"; loaded version="1.6.2"
[Tue Feb 12 16:12:24.248496 2019] [:notice] [pid 8915:tid 140578976581376] ModSecurity: PCRE compiled version="8.40 "; loaded version="8.40 2017-01-11"
[Tue Feb 12 16:12:24.248501 2019] [:notice] [pid 8915:tid 140578976581376] ModSecurity: LIBXML compiled version="2.9.4"
```

All widget forms are loading perfectly for me. Is there anything I'm missing?

I think ModSecurity also allows you to install custom rules. Is it possible that people getting these issues are running some custom rules?

**Comment by gregpriday** [comment]
Can we try get hold of some JSON exports for the pages where these issues are happening? Could be related to content in the widgets.

**Comment by AlexGStapleton** [comment]
I don't know which widget people are using that causes this issue - I'll start asking. With that said, with Wordfence, typically the SiteOrigin Button and SiteOrigin Hero widget causes the request to get rejected.

> Is it possible that people getting these issues are running some custom rules?

Yes. The posted error appears is being triggered by [OWASP ModSecurity CRS](https://modsecurity.org/crs/). This is implemented with cPanel so it's a very commonly used rule set. The specific rules that triggered the error was a rule from the [REQUEST-941-APPLICATION-ATTACK-XSS.conf](https://documentation.cpanel.net/display/CKB/OWASP+ModSecurity+CRS#OWASPModSecurityCRS-REQUEST-941-APPLICATION-ATTACK-XSS) rule set.

The next time someone reports this issue I'll ask for a copy of their layout.

**Comment by gregpriday** [comment]
Aaah, I assumed those were core rules because they were called core rules. I'll take a look.

For reference, the decoded HTML that triggered this is:

```
<h2 style="text-align: center;"><span style="font-family: helvetica, arial, sans-serif;">"Your brand is what other people say about you when you\x19re not in the room"- Jeff Bezos</span></h2>\n<h2 style="text-align: center;"></h2>\n<p style="text-align: center;"><span style="font-family: helvetica, arial, sans-serif; font-size: 14pt;">If branding was the association and perception in the customers mind, then bra...
```

**Comment by gregpriday** [comment]
I installed those extra rules and tried the trigger text in a Text Widget and SiteOrigin Editor Widget. Still nothing. So my guess is that this issue isn't as wide spread, or serious as we thought.

I'm going to lower this to P2 for now and add in some code that *might* fix the issue. That'll go out in the next update so we can ask these users to update and see if it fixes things. If we can get more solid steps to recreate that implies this issue is wide-spread, then we can raise it back to P1.

The best option would be to [report the false positive](https://github.com/SpiderLabs/owasp-modsecurity-crs/issues). I see a few false positive reports there, so we could help them out by reporting this.

**Comment by Misplon** [comment]
@ twohumans has added feedback here: https://wordpress.org/support/topic/after-updating-i-cant-edit-any-content-in-any-of-pagebuilder-widgets/#post-11198779.

_Here is the error that came out of our ModSecurity. My admin removed 3 rules (they didn’t share what rules) and it now works._

```[Tue Feb 12 12:14:53.953849 2019] [:error] [pid 473184:tid 
140341851064064] [client 46.229.168.148:41234] [client 
46.229.168.148] ModSecurity: Access denied with code 406 (phase 2). 
Matched phrase "46.229.168.148" at REMOTE_ADDR. [file 
"/etc/apache2/conf.d/modsec/custom/00_funio_spamipban.conf"] [line 
"2"] [id "666001"] [rev "2"] [msg "IP Match: The IP address is on 
the anti-spam blacklist"] [severity "ERROR"] [hostname "xxxxxx.xxx"] 
[uri "/robots.txt"] [unique_id "XGL-DefuuMqtCtPAgOYBGgAAANQ"]

[Tue Feb 12 11:20:08.407477 2019] [:error] [pid 473184:tid 
140341997922048] [client 72.10.140.234:18068] [client 72.10.140.234] 
ModSecurity: Access denied with code 403 (phase 2). Pattern match 
"http://[a-zA-Z0-9._]{1,}?/.{0,}?\\\\.pdf\\\\b[^\\\\n\\\\r]{0,}#" at 
ARGS:panels_data. [file 
"/etc/apache2/conf.d/modsec_vendor_configs/comodo_apache/08_Global_O
ther.conf"] [line "21"] [id "211050"] [rev "1"] [msg "COMODO WAF: 
Universal PDF XSS URL Detected.||xxxxxx.xxx|F|2"] [severity 
"CRITICAL"] [tag "CWAF"] [tag "Other"] [hostname "xxxxxx.xxx"] [uri 
"/wp-admin/admin-ajax.php"] [unique_id 
"XGLyOOfuuMqtCtPAgOb3ewAAAMY"], referer: https://xxxxxx.xxx/wp-
admin/post.php?post=422&action=edit&lang=fr```

**Comment by gregpriday** [comment]
Just checking that thread on wp.org. Did this only start coming up after an update? What happens if users roll back to a previous version of Page Builder? If that fixes things, it'd help us diagnose what's going on.

**Comment by Misplon** [comment]
I'll try and locate a thread that hasn't resolved and ask if they can use WP Rollback.

**Comment by gregpriday** [comment]
> Here is the error that came out of our ModSecurity. My admin removed 3 rules (they didn’t share what rules) and it now works.

Checking over those rules, yeah, that's a typical false positive. Seems like the one rule was blocking any HTML content being injected that had a link to a PDF. All of these are to do with content users enter themselves in the editor widget. We can't limit that.

There's not going to be much we can do here, unless ModSecurity has a way of signing requests as valid, but I don't think that's likely. We'll keep this open for now, but I'm assuming these issues have started coming up as a result of ModSecurity being added to more hosts recently, not because of anything we've changed.

Best action will be to tell users to ask their hosts to disable offending rules and hope that message goes through to as many hosts as possible.

**Comment by gregpriday** [comment]
Closing this because there's no reliable way we're going to be able to "trick" ModSecurity.

**Comment by Misplon** [comment]
In the event users run into this issue, they can send the following help article to their hosts: 

https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/

This rule is working as expected but too aggressive for a WordPress site.

**Comment by Cyrille37** [comment]
Hello

I've got a problem too with ModSecurity.

The user has this error :
![image](https://user-images.githubusercontent.com/368965/73480193-bbeab580-4399-11ea-9a1e-18633478778b.png)

The only idea I found is perhaps those two simultaneous (too fast ?) http POST while opening a "SiteOrigin button" : 
![image](https://user-images.githubusercontent.com/368965/73480472-3e737500-439a-11ea-9851-5fac0ee8185f.png)

**Comment by Misplon** [comment]
Hi Cyrille37. Try reaching out to your hosts. Let them know you've experienced a 403 error which you believe to be a false positive. Ask them to check their logs, hopefully, they can adjust and resolve the challenge for you

**Comment by Cyrille37** [comment]
Hi Misplon. Thanks. I wrote to IT department to get some logs ...
