### ISSUE TITLE
WP 5.1 RC jshint.js 404 errors

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#643]
[Slack](https://siteorigin.slack.com/archives/C02SYBBH2/p1550442809004000)

I'm getting the following errors when I open either editor when using the [WordPress 5.1 Release Candidate](https://wordpress.org/news/2019/02/wordpress-5-1-release-candidate/). None of the errors occur while SiteOrigin Page Builder is disabled.

Block Editor:
`post.php?post=2&action=edit:1584 GET http://127.0.0.1/siteorigin/wp51/wp-includes/js/codemirror/jshint.js?ver=2.9.5.999 net::ERR_ABORTED 404 (Not Found)

`SiteOrigin Page Builder:
```
VM853 post.php:556 GET http://127.0.0.1/siteorigin/wp51/wp-includes/js/codemirror/jshint.js?ver=2.9.5.999 net::ERR_ABORTED 404 (Not Found)
post.php?post=5&action=edit:556 GET http://127.0.0.1/siteorigin/wp51/wp-includes/js/codemirror/jshint.js?ver=2.9.5.999 net::ERR_ABORTED 404 (Not Found)
```

**Comment by braamgenis** [comment]
Ok, so this isn't caused by PB, it also happens on the _Appearance > Widgets_ screen with all SO plugins deactivated. Looks like a missing/changed dependency in WP core and doesn't seem to be causing any issues other than showing a 404.

**Comment by AlexGStapleton** [comment]
Weird stuff. Wonder if they're going to let this one slide.

**Comment by gregpriday** [comment]
If this hasn’t been reported on WordPress tax already, it could be worth
reporting.

**Comment by AlexGStapleton** [comment]
I just checked the GitHub mirror and it appears the removal of jshint.js has been a long time coming.

https://github.com/WordPress/WordPress/commit/c4277abb33258d3eaea8a580a6a4783bc57a1f64

That was the last commit for any file in that directory but it looks like jshint.js was still being included for some reason and has only just now been removed. There's no direct reference to how it was removed.

5.1: https://github.com/WordPress/WordPress/tree/5.1-branch/wp-includes/js/codemirror
5.0.3: https://github.com/WordPress/WordPress/tree/5.0.3/wp-includes/js/codemirror
