### ISSUE TITLE
Cell selectors need to be more specific to prevent issues with users using multiple Layout Builder

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#646]
The cell selectors should be applied to a direct descent rather than all instances of `.panel-grid-cell` as that results in CSS being applied to _all_ child `.panel-grid-cell`. For example, this is a screenshot of a layout builder:
![](https://i.imgur.com/13enhA2.png)

Here's an extreme example for a row cell four layout builders deep:
![](https://i.imgur.com/Miqx2Kj.png)

This issue causes issues with the `Collapse Behaviour` and any other settings that affect cell styles.

**Comment by braamgenis** [comment]
@AlexGStapleton Do you have a sample layout which has these issues? I can't seem to reproduce.

**Comment by AlexGStapleton** [comment]
[Here's a test layout](https://drive.google.com/a/siteorigin.com/uc?id=1isniK6_kY13hVHvXVXt9BexQqGSeeGap). The issue is present in both rows but it's really present in the second row due to how many layout builders there are.

**Comment by braamgenis** [comment]
>The issue is present in both rows 

Could you be a bit more specific about what exactly "the issue" is? I see multiple styles being applied, but as far as I can tell, the correct styles for child layout builders always overrides the parent styles.

>This issue causes issues with the Collapse Behaviour 

_Collapse Behavior_ appears to work as intended for me. Which one of the rows/builders isn't collapsing according to the specified setting?

**Comment by AlexGStapleton** [comment]
An example of this issue occurring is with the cell widths of the rows inside of the Checkmark Item - Open the **Checkboxes** Layout Builder, open the **Halfs** Layout Builder and finally open the **Checkmark Item** Layout Builder. Due to the highlighted selectors in the issue issue, parent layout builders have more specific CSS which resulting in the widths being lost on mobile.

This is the cell CSS used to control the width:

```
#pgc-w5c9949ce23027-0-0 {
    width: 15%;
    width: calc(15% - ( 0.85 * 30px ) );
}

```
This is the CSS that's overriding the wdith due to a parent row due to having **Collapse Behavior** set to **Collapse**.:

```
@media (max-width: 780px)
#pg-w5c9949ce22ffb-0 .panel-grid-cell {
    width: 100%;
}
```

Does that make sense?

**Comment by braamgenis** [comment]
Ah, ok I see. I previously understood that the issue was with the collapse behaviour itself not working as expected. Cool. Will see what can be done about this. Unfortunately it's not as straightforward as just using `> .panel-grid-cell` everywhere.
