### ISSUE TITLE
Panel cell background-image defaults?

### ISSUE THREAD

**Issue by 128keaton** [siteorigin/siteorigin-panels#650]
I had an 'insecure content' notice on my page recently and I traced it back to the `siteorigin-panels-layouts-head` being generated. Notably, this element below has 'http://google.com' set as the background..
![screen shot 2019-03-04 at 3 12 09 pm](https://user-images.githubusercontent.com/1402918/53763265-ebdebf80-3e8f-11e9-85e5-0d01d65c3219.png)

```
#pgc-10-4-0> .panel-cell-style { 
   background-image:url(http://google.com);background-repeat:repeat
}
```

**Comment by AlexGStapleton** [comment]
Hi,

That's strange. I'm not too sure what's causing this. Does this happen on a new page or does this issue occur solely with this page? Would it be possible for you to send me an export of the pictured page? To export a page, please open up the page in the editor and click the Layout button in the Page Builder toolbar. Then click import/export and then click download. Please upload the export to a 3rd party file hosting site such as <a href="https://wetransfer.com/">WeTransfer</a>  (no email is required).

**Comment by 128keaton** [comment]
@AlexGStapleton I am out of town, not at work, until the 20th. I'll report back then. Thanks!

**Comment by AlexGStapleton** [comment]
No worries mate. :)

**Comment by Misplon** [comment]
Hi 128keaton, I'm going to close for the moment. If you have any follow-up questions, please feel free to re-open. Thanks :)
