### ISSUE TITLE
Alignment colums Knowledge Base/ Echo plugin 

### ISSUE THREAD

**Issue by WimSchol** [siteorigin/siteorigin-panels#654]
I have a problem with the allignment of coloms in Knowledge Base plugin. Below i get an answer on my mail to them. Would you check if it right? thx. After deactivating PageBuilder problem is solved....
Wim

Answer of Echoplugins/Knowledge Base

Hi Wim,
I am sorry for the trouble you are having. I had a look at your website and I discovered that something is injecting paragraph tags between our knowledge base code. This is caused usually by a poorly designed theme or another plugin like a page builder. It should not be injecting paragraph tags like this.

Please try to following.

    If it's in a page builder remove the page builder insert the kb shortcode into that page using the default editor. If it works correctly you will need to contact the other plugin author to turn off the paragraph injection. Or do not use the builder for this page.

    Also you can try deactivating all other plugins to see if a different plugin is causing this.

Here are the paragraph injections. There are many more.

    If it's not a plugin, try switching theme if the issue is gone , it's the theme causing this and you will need to contact the theme company.

Sorry I cannot assist further and some other third party software is causing this issue.

Before starting please back up your website.

Thank you,
Dave
Echo Plugins Team

What best describes your inquiry?   Technical Support Documentation Doc Read Confirmation   I have done everything that you suggested but I am still having issues. Your Knowledge Base Information Which add-ons, if any, do you have?   Elegant Layouts Multiple Knowledge Bases Widgets Advanced Search Links Editor Additional information ( Optional )   Provide more information Additional information ( Optional ) Which template are you using?   Current Theme Template Your Site Information Theme URL   https://siteorigin.com/theme/vantage/ Theme Name   Vantage v 1.9.1 Is your Knowledge Base Publicly visible?   Yes it is public URL of your Knowledge Base   https://www.bureauzelfstandigenfryslan.nl/informatie/ Type of Problem Type of Problems   Front End ( display issues ) Front End Screenshots   KB.JPG Summary   not the correct view Details   Hello, the view of the KB on the site is not correct unless i have configurred 3 colums.... could you help me with this? Thx Wim Section Break Name   Wim Scholte Email   What best describes your inquiry? |   | Technical Support | Documentation | Doc Read Confirmation |   | I have done everything that you suggested but I am still having issues. | Your Knowledge Base Information | Which add-ons, if any, do you have? |   | Elegant Layouts Multiple Knowledge Bases Widgets Advanced Search Links Editor | Additional information ( Optional ) |   | Provide more information | Additional information ( Optional ) | Which template are you using? |   | Current Theme Template | Your Site Information | Theme URL |   | https://siteorigin.com/theme/vantage/ | Theme Name |   | Vantage v 1.9.1 | Is your Knowledge Base Publicly visible? |   | Yes it is public | URL of your Knowledge Base |   | https://www.bureauzelfstandigenfryslan.nl/informatie/ | Type of Problem | Type of Problems |   | Front End ( display issues ) | Front End | Screenshots |   | KB.JPG | Summary |   | not the correct view | Details |   | Hello, the view of the KB on the site is not correct unless i have configurred 3 colums.... could you help me with this? Thx Wim | Section Break | Name |   | Wim Scholte | Email |   |
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
What best describes your inquiry?
  | Technical Support
Documentation
Doc Read Confirmation
  | I have done everything that you suggested but I am still having issues.
Your Knowledge Base Information
Which add-ons, if any, do you have?
  | Elegant Layouts Multiple Knowledge Bases Widgets Advanced Search Links Editor
Additional information ( Optional )
  | Provide more information
Additional information ( Optional )
Which template are you using?
  | Current Theme Template
Your Site Information
Theme URL
  | https://siteorigin.com/theme/vantage/
Theme Name
  | Vantage v 1.9.1
Is your Knowledge Base Publicly visible?
  | Yes it is public
URL of your Knowledge Base
  | https://www.bureauzelfstandigenfryslan.nl/informatie/
Type of Problem
Type of Problems
  | Front End ( display issues )
Front End
Screenshots
  | KB.JPG
Summary
  | not the correct view
Details
  | Hello, the view of the KB on the site is not correct unless i have configurred 3 colums.... could you help me with this? Thx Wim
Section Break
Name
  | Wim Scholte
Email

**Comment by Misplon** [comment]
Issue migrated to https://siteorigin.com/thread/problem-with-pagebuilder/.

Thanks
