### ISSUE TITLE
Please consider concatenating assets

### ISSUE THREAD

**Issue by frontenddevguy** [siteorigin/siteorigin-panels#656]
I've just spent a day looking over sites I built with SO themes, and they are all getting very poor load times and scores, mainly because of the number of render-blocking styles and scripts.
There's some more I can do with smush and image sizes, but having about 20 small css files all load before the DOM is not so good..

Minify / cache plugins are really like shooting in the dark, and extremely time-consuming to troubleshoot. I've tried BWP, Autoptimize and others but eventually given up trying to get assets to load in the correct order without breaking anything. I'm wondering why are files not combined in the correct order by default with these plugins?

Anyway, for Page Builder, could there be some option to provide themes with a gulpfile, or some option within the theme to concatenate (minification doesnt matter so much) files?

I like having SO as an option for building sites when I don't have time or budget to do a custom theme, but the performance is getting to be too much of an issue.

This question relates also to themes, but Page Builder is the main bottleneck for performance.

Thanks!

**Comment by Misplon** [comment]
Hi @frontenddevguy 

Thanks for reaching out. We've just completed work on making Page Builder and the Widgets Bundle fully compatible with Autoptimize. I'll publish a post on https://siteorigin.com/blog/ once the update has been released. I'm sure it'll help.

**Comment by Misplon** [comment]
Here is the release announcement: https://siteorigin.com/boost-siteorigin-plugin-performance-autoptimize/. Hope this helps :)
