### ISSUE TITLE
Live editor doesn't show changes.

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#660]
With the latest update, Live editor doesn't display changes until the page is saved.

How to reproduce:
1. Open existing page with Live editor
2. Go to row styles, change background color.
3. Row background color doesn't change.

Here is a quick video: https://jmp.sh/uL2nRsc

Stack trace:
**Plugins used:**

- Page Builder by SiteOrigin
- SiteOrigin Widgets Bundle
- Classic Editor

--
**Theme:** 

- Twenty Nineteen

**Comment by Misplon** [comment]
Thanks for the help :) The Live Editor looks to be updating when removing the background color but not when adding. We'll attend ASAP.

**Comment by andrejarh** [comment]
Thanks for giving it priority 1

Additionally duplicating rows and importing layouts doesn't work OK either.
https://jmp.sh/j4sUbVG

**Comment by Misplon** [comment]
Thanks. I confirm duplicating rows being an issue. Cloning pages seems to be ok my end. I'm not too worried about not confirming that item at this stage. Let's let Braam take a look. The issues might be related to single problem.
