### ISSUE TITLE
Hide Add New Editor Selector when Classic editor is installed

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#663]
When the Classic Editor is installed, SiteOrigin Page Builder still sets up the **Add New** Editor Selector with different editor options. All of the options do the same thing due to the Block Editor being disabled.

![](https://i.imgur.com/cFD59QJ.png)

**Comment by braamgenis** [comment]
The Class Editor plugin allows users to change settings to be able to use the block editor, so we might rather consider adding a third option here to go directly to classic editor mode.

**Comment by Misplon** [comment]
@braamgenis Have you perhaps given this any more thought? Should we put a plan together for this adjustment?

**Comment by braamgenis** [comment]
It will need to check which Classic Editor settings are being used to decide what to display there. Will take a look when I get to this.

**Comment by Misplon** [comment]
Super, thanks.

**Comment by AlexGStapleton** [comment]
Due to how the Classic Editor works these days, and the multiple reasons why you may wish to switch between the editors, I think it's actually preferred if this Add New drop down stays as is.
