### ISSUE TITLE
siteorigin_panels_render() not rendering anymore in Live editor

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#667]
I have a custom widget and a custom post type. 
The widget just renders the content of a (custom post-type) post. 

To display the content, the widget uses this line of code: 
echo siteorigin_panels_render($custom_post_id);

 **what does the widget do** 
The idea behind the widget is to simplify (repeatable) content updates.
Let's say that the same content (rows + widgets) is displayed on 1000 different pages, then you need to add a small change to it. If the content is edited on a specific custom post type post, You only need to change it there and the content automatically updates on all 1000 pages... 

**pinpointing the issue**
It works perfectly on the front end. However in the live editor, the siteorigin_panels_render() doesn't render anymore in the Live editor using the latest SO panels versions. 
I tested it on an old version 2.10.1, and can confirm it is still working there. Also on all older versions.

I tried to pinpoint the issue, so i compared the new and the old versions. I did not notice any  changes within the siteorigin_panels_render() or SiteOrigin_Panels::renderer() function. 
I don't quite understand why the content isn't displayed anymore.

**the question**
So my question is: Is there a way to display a specific post content within the live editor? Is there some other function than siteorigin_panels_render(), which I should use?

Thanks!

**Comment by AlexGStapleton** [comment]
Hi andrejarh.

There are two Live Editor specific changes that _may_ have caused this. They are::

https://github.com/siteorigin/siteorigin-panels/commit/897423141b65c278c784847ab5d2d40c2cf01307
https://github.com/siteorigin/siteorigin-panels/commit/be108fb2fcef21158b94d3924bf0376437e7c8ba

Perhapses try reverting/altering those to see if that helps.

**Comment by AlexGStapleton** [comment]
Hi andrejarh,

Thanks for running some tests to work out why your widget is having issues. I'm not personally familiar with this code so I can't directly comment on it. I've assigned Braam to this issue. Braam is pretty flat out at the moment so I'm not too sure when he'll be able to take a look at it, but it'll be on his list.

**Comment by andrejarh** [comment]
No pressure. It is not a critical issue and can be put on hold until it's time for it.
