### ISSUE TITLE
Editor Widget inconsistently rendering the title (Gutenberg)

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#668]
Hi guys!
HTML output of the Editor widget is loading inconsistently, depending on how the editor widget is added to Gutenberg. 
If it is added with layout builder, then it outputs the title tag HTML as it is set in the SiteOrigin settings:
![so-settings](https://user-images.githubusercontent.com/10053621/57850374-12996a80-77de-11e9-8f95-fcee999ffd2f.png)

However if it is added through the SiteOrigin widget option, then the title is rendered without heading tags. This was tested with twenty nineteen and latest SO panels. No other plugins were active. 
Here is the visual diff:
![editor-widget](https://user-images.githubusercontent.com/10053621/57850467-4bd1da80-77de-11e9-8050-b26610188895.jpg)

**Comment by Misplon** [comment]
Thanks for logging. I've confirmed. I'll ask Braam to attend as soon as he's able.

**Comment by Misplon** [comment]
Hi :) Thanks for the wait. 

Braam brought me up to speed on this one. Widget Title HTML is a Page Builder setting that controls widget titles output within Page Builder. The Widgets Bundle can be used on its own, this setting doesn't impact Widgets Bundle titles when used outside of Page Builder. To resolve the challenge, you could insert a Layout Block and insert widgets into an instance of Page Builder there. Or, if you're using a SiteOrigin Editor widget via the Widget Block, insert the heading directly into the editor. 

Thanks for reaching out. Sorry, I don't have better news on this one. Hopefully, the above helps to explain what's happening.

**Comment by andrejarh** [comment]
I understand, what you are saying, but there should probably be some kind of tag for the heading anyway, even if diffferent? 
The heading text is just dumped into the so-widget-sow-editor container without any HTML tag at all. So it can't even be targeted with CSS. This surely can't be right? Are you sure there isn't some escaping issue causing the HTML tag to not display?

**Comment by andrejarh** [comment]
I checked the code and found out the issue is in the Widget Bundle. so I opened the issue there and also posted the solution for it. 
Please check it and include it in the next update if possible. If you want, I can also submit a PR.
