### ISSUE TITLE
Missing "sowb" object in Gutenberg causes all widgets to "break" in backend

### ISSUE THREAD

**Issue by kallehauge** [siteorigin/siteorigin-panels#671]
The issue can be reproduced by doing the following:

* Create vanilla WordPress installation
* Download and enable latest SiteOrigin page-builder and SOW Bundle plugins
* Go to Page builder settings and disable `Use Classic Editor for new posts`
* Go to `Plugins > SiteOrigin Widgets` and disable all widgets except `Editor`
* Create new page and add a layout block with the Editor widget inside and publish/save page
* Refresh backend and the layout block will have encountered an error

The reason is that when using the Layout block on a Gutenberg page and all widgets that declares the `sowb` object have been disabled (all widgets that have JavaScript files that start with `var sowb = window.sowb || {};`), then the `sowb` object doesn't exist when SiteOrigin tries to execute the following code in `so-widgets-bundle/base/js/admin.js`:

`$( sowb ).trigger( 'setup_widgets', { preview: true } );`

---

Just as a FYI to the maintainers, then this issue explains my previous PR for the Widget bundle: https://github.com/siteorigin/so-widgets-bundle/pull/859

**Comment by braamgenis** [comment]
Hi @kallehauge Thanks for providing more info on the issue. I've managed to reproduce and fix. The upcoming Widgets Bundle update should resolve the issue.

**Comment by braamgenis** [comment]
Fixed in siteorigin/so-widgets-bundle@adca8c68e39022daf9c62634260cc8dfea320648
