### ISSUE TITLE
Classic Editor Plugin: Allow users to switch editors metabox removed

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#673]
Steps to reproduce:

1. Activate the Classic Editor plugin, deactivate Page Builder.
2. Go to Settings > Writing and enable: Allow users to switch editors. 
3. Go to a post, note the Editor metabox on the right.
4. Activate Page Builder by SiteOrigin. Edit a post, note the metabox is missing.

**Comment by braamgenis** [comment]
This seems to also have been resolved by 7ea17fac66e9a4c9d052ca9d9dc411257ef14dea. @Misplon Please confirm when you can.

**Comment by Misplon** [comment]
Looks good on my end.
