### ISSUE TITLE
Classic Editor Plugin: Allow Block Editor pages to remain in the Block Editor

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#674]
* With the Classic Editor plugin and Page Builder activated, go to Settings > Writing and change Default editor for all users to Block Editor. 

* Next, go to Pages > Add New. Create and save a Block Editor page. Once saved, go to Pages, view the pages list and edit the page you've just created. The page will have reverted to the Classic Editor.

The expected behavior is that a Block Editor page would remain in the Block Editor. This same issue is persisting without the Classic Editor plugin activated by going to Pages > Add New > New Block Editor page, save, navigate away then go to Pages, edit the page, the page will be in the Classic Editor.

**Comment by braamgenis** [comment]
I'm not able to reproduce this. A block editor page remains in the block editor for me. The only thing that might affect this behavior in PB is when an existing page has `panels_data` saved in it's post metadata.

**Comment by Misplon** [comment]
Update after chatting on Slack. “Allow users to switch editors” needs to be enabled to reproduce the issue.
