### ISSUE TITLE
Checkbox changing value automatically

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#678]
Hi,
When a checkbox is added to the page builder row, it is not saving/displaying correct value.

I created a twentynineteen child theme with the only function in functions.php beeing: 
```
function checkbox_test($fields) {
    $fields['checkbox_test'] = array(
      'label' => 'this setting changes automatically',
      'type'        => 'checkbox',
      'group'       => 'design',
      'default' => true,
      'priority'    => '1',
    );      
    return $fields;
}

add_filter( 'siteorigin_panels_row_style_fields', 'checkbox_test', 10, 2 );
```
No other plugin, except page builder and widget bundle were active.
it is a similar example, as on the form docs page:  https://siteorigin.com/docs/widgets-bundle/form-building/form-fields/#heading-checkbox

Note that the checkbox is set to true by default.
Now if I uncheck the checkbox, it will become checked automatically whenever the row options are edited.

Please see the video: https://jmp.sh/yQjdZdJ

**Comment by AlexGStapleton** [comment]
I've been able to replicate this issue. I've marked this as a bug.

**Comment by gregpriday** [comment]
Thanks for reporting @andrejarh!

**Comment by gregpriday** [comment]
I had to revert my original fix because it was causing problems with widgets that used isset to represent unchecked checkboxes. I'll add a solution that applies specifically to style fields after the next release.

**Comment by AlexGStapleton** [comment]
I've run some tests and this issue is no longer happening. It looks like it was resolved in a newer unreferenced PR.
Let me know if this issue is still happening for you @andrejarh and we'll reopen this.
