### ISSUE TITLE
Live-Editor not working when admin-panel is accessed via https

### ISSUE THREAD

**Issue by rjaeckel** [siteorigin/siteorigin-panels#69]
Firefox pops a security warning: 
`Although this page is encrypted, the information you have entered is to be sent over an unencrypted connection and could easily be read by a third party. Are you sure you want to continue sending this information? `

There is also a warning about this in the developer console: `Blocked loading mixed active content "http://mysite.org/?siteorigin_panels_live_editor=true" `

The left sidebar is visible but the content is left blank.

**Comment by gregpriday** [comment]
Can you check that your site URL is set properly (with https) in Settings > General. It's also possible that you're using a hosting environment that loads the backend using HTTPS and the frontend using standard HTTP. I think WP Engine gives you this option.

**Comment by rjaeckel** [comment]
Indeed.
>  It's also possible that you're using a hosting environment that loads the backend using HTTPS and the frontend using standard HTTP. I think WP Engine gives you this option.

We're forcing https for administrative interface. the frontend is using HTTP preferably. It's a flag in `wp-config.php`. We have a multisite installation with about 150 domains and about 1000 blogs. No way to change this situation here.

The bug seems to be situated somewhere in the javascript code that loads the page content into the editor.

I was able to hack the database to get the editor working by removing "http:" from the site's home and base-path in the options-table. I would prefer not to do this for every site.

**Comment by gregpriday** [comment]
I'll see if there's a way for me to force Page Builder to use https in the
live editor window if the admin is being accessed through https. It should
be a fairly easy fix.

On Tuesday, May 5, 2015, Robert Jäckel <notifications@github.com> wrote:

> Indeed.
>
> It's also possible that you're using a hosting environment that loads the
> backend using HTTPS and the frontend using standard HTTP. I think WP Engine
> gives you this option.
>
> We're forcing https for administrative interface. the frontend is using
> HTTP preferably. It's a flag in wp-config.php. We have a multisite
> installation with about 150 domains and about 1000 blogs. No way to change
> this situation here.
>
> The bug seems to be situated somewhere in the javascript code that loads
> the page content into the editor.
>
> I was able to hack the database to get the editor working by removing
> "http:" from the site's home and base-path in the options-table. I would
> prefer not to do this for every site.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/siteorigin/siteorigin-panels/issues/69#issuecomment-98993853>
> .
>


-- 
I make free WordPress themes
http://siteorigin.com

**Comment by rjaeckel** [comment]
Thank you very much.
