### ISSUE TITLE
Mobile Bottom Margin applies global default when Bottom Margin is applied

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#691]
The Mobile Bottom Margin setting is outputting the globally defined Row/Widget Bottom Margin when the user applies a custom bottom margin. If no Bottom Margin is set, the Mobile Bottom Margin doesn't output the global Bottom Margin. The Mobile Bottom Margin should only ever be output when a custom Mobile Bottom Margin has been applied.

**Comment by gregpriday** [comment]
@AlexGStapleton can you double check my fix solves everything? Once you confirm, I'll do a release.

**Comment by AlexGStapleton** [comment]
I'm no longer able to replicate this issue with the develop version.
