### ISSUE TITLE
SiteOrigin Post Carousel Navigation issue

### ISSUE THREAD

**Issue by sandy2609** [siteorigin/siteorigin-panels#697]
While using SiteOrigin Post Carousel, when we navigate the slider to the right with right arrow, after the last slide, the slider continues sliding and shows blank slides.
The left arrow is working fine, but the right one is having issue.

**Comment by AlexGStapleton** [comment]
Thank you for reaching out. The SiteOrigin Post Carousel widget is added by the SiteOrigin Widgets Bundle rather than SiteOrigin Page Builder. I've had a look at the existing issues and there's an existing issue for this: siteorigin/so-widgets-bundle#132.
