### ISSUE TITLE
Latest chrome version broke cell display styling in backend

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#698]
I noticed this (noncritical) bug, which is caused by latest chrome update (I think). 
The last widget in a cell is being displayed out of boundaries of its parent row.
![image](https://user-images.githubusercontent.com/10053621/64420717-2d029700-d0a0-11e9-8b53-3b5ade345ef0.png)

**Comment by Misplon** [comment]
@gregpriday I've bumped this one up to P1. Not a classic P1 but it's very visible so I think it's worth treating as such.

@andrejarh Thanks :)

**Comment by andrejarh** [comment]
Hi,
I found another styling issue:

![image](https://user-images.githubusercontent.com/10053621/65032052-b3419780-d942-11e9-94fb-08a12b8f4330.png)

![image](https://user-images.githubusercontent.com/10053621/65032023-a1f88b00-d942-11e9-9abc-04529717c42b.png)

**Comment by Misplon** [comment]
Thanks, @andrejarh, we'll attend to both in this issue. Appreciate the screenshots.

**Comment by gregpriday** [comment]
Thanks for reporting @andrejarh. I've fixed up both these issues. They'll be going out in the next update.
