### ISSUE TITLE
Row Full Width Stretched with Parallax doesn't work with external background URL

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#699]
To recreate this issue:

* Add a row, make it Full Width Stretched.
* Add an external background image, you can use the following URL:
https://demo.purothemes.com/polestar/wp-content/uploads/sites/4/2018/06/optimizing.jpg
* Set the Background Image Display to cover.
* Add any content to the row, a Text widget with dummy text will do.
* Save/Publish and note the row is functioning normally on the site front-end.
* Next, change the Background Image Display from Cover to Parallax. Note that we're no longer able to stretch the external background image.

* If we change the background URL to a locally hosted image, the issue isn't present.
* If we leave the URL as external but change the background image display to cover, the issue isn't present.

**Comment by gregpriday** [comment]
We might need to consider this a limitation. Parallax needs to know the exact size of the background image to function properly. We're doing that here - https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/styles.php#L393-L406

How often does this come up? It might be possible to fetch the external image, check its size, then cache that value.

**Comment by Misplon** [comment]
The use case for us would be our prebuilt layouts. Where I've seen parallax used, I've switched those rows over to fixed.

**Comment by Misplon** [comment]
Estimated 3-4 hours to make this work. Going to rely on fixed row backgrounds in prebuilt layouts with external images (where necessary) for the time being.
