### ISSUE TITLE
Android Chrome: Unable to open widgets

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#703]
A user reported that they aren't able to open widgets while using Chrome on Android, and I've been able to replicate this issue. It looks like the "drag and drop" code for the widgets kicks in as the widget "jumps" briefly after selection.

This cannot be replicated while using the Chrome DevTools Device Mode.

**Comment by Misplon** [comment]
Are there any console errors to report?

**Comment by AlexGStapleton** [comment]
Chrome has something called [Remote Debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging). Unfortunately, I'm not getting any error messages. :(

**Comment by Misplon** [comment]
Thanks

@braamgenis Are you able to replicate?

**Comment by Misplon** [comment]
@AlexGStapleton If you could try to take another briefish look, as discussed on Slack, that would be great. Thanks.

**Comment by Misplon** [comment]
@AlexGStapleton I forget if we spoke on Slack after this message above. Did we?

**Comment by AlexGStapleton** [comment]
I can't seem to find anything related to this, but I'll take a look at this very shortly.

**Comment by Misplon** [comment]
Thanks

**Comment by AlexGStapleton** [comment]
Unfortunately, I'm not seeing any potential causes. 😞

**Comment by Misplon** [comment]
Cool, thanks for checking again. Perhaps we'll ask Andrew Freeborn to take a look when there is time.
