### ISSUE TITLE
SO Layout Block: Adding A New Widget Will Prevent Prior Post Loop Wigets from Displaying Custom Taxonomy

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#705]
Steps to replicate:
- Add Post Loop widget to SiteOrigin Layout block
- Open Post Loop widget and select a valid taxonomy that will result in posts outputting.
- Save
- Close the Block Editor and open the page directly to confirm post loop is displaying correctly
- Re-open Block Editor and add any widget after the Post Loop widget
- Save
- Close the Block Editor and open the page directly to confirm post loop is displaying incorrectly

After replicating this issue, re-open the Post Loop widget settings and the taxonomies field will be empty. If you open the Post Loop widget after re-opening the Block Editor the first time, this issue won't occur.

We've created a sandbox page here:
https://demo.siteorigin.com/north/post-loop-settings-loss-issue/

On that page, the Post Loop widget was originally set to output posts in the Exploration category. After following the above-outlined steps to replicate this issue the taxonomy field was reset.

**Comment by AlexGStapleton** [comment]
Update: This issue appears to happen with _any_ widget rather than just Post Loop widgets. I was able to replicate it using just an Archives widget.

@Misplon Are you able to replicate this issue by adding widgets other than the post loop widget?

**Comment by AlexGStapleton** [comment]
@Misplon Are you able to replicate this issue? I'm having trouble replicating this issue. It's possible it may have been indirectly fixed at some point.

**Comment by Misplon** [comment]
@AlexGStapleton I can't currently recreate this issue. I'll close this issue, if we can recreate this in the future we can re-open. Thanks, mate.
