### ISSUE TITLE
WP 5.3: SiteOrigin Layout Block Has Larger Than Normal Widget Titles

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-panels#709]
The Widget Titles in the SiteOrigin Layout Block are much larger in 5.3-RC3-46639.

![](https://i.imgur.com/LYeo7sO.png)

**Comment by Misplon** [comment]
There is a `style` block being outputted into the `head`, that block includes the following rule

```
.editor-styles-wrapper h4 {
    font-size: 1.25em;
}
```

To resolve, we most likely need to add `font-size: 13px` to the following rule

```
.siteorigin-panels-builder .so-rows-container .so-row-container .so-cells .cell .widgets-container .so-widget h4 {
    display: block;
    cursor: pointer;
    margin: 0 15px 3px 0;
    font-weight: 600;
    line-height: 1.25em;
    color: #474747;
    text-shadow: 0 1px 0 #fff;
    white-space: nowrap;
}
```

**Comment by Misplon** [comment]
Resolved via https://github.com/siteorigin/so-widgets-bundle/commit/76ac79ca388a39e90e21b2d9babd72a28ef9d8e8.
