### ISSUE TITLE
Mobile: Difficult to reach widget action links

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#718]
It's quite difficult to get to the widget action (Edit - Duplicate - Delete) links on mobile. If you very carefully tap on the widget description you can view the links but tapping almost anywhere else just opens the widget. Should we perhaps make the action links always visible on mobile?

**Screencast:** 
[RPReplay_Final1578753901.mp4.zip](https://github.com/siteorigin/siteorigin-panels/files/4049432/RPReplay_Final1578753901.mp4.zip)

**Comment by Misplon** [comment]
@AlexGStapleton What do you reckon we do here? Perhaps make the action links always visible for mobile?

**Comment by AlexGStapleton** [comment]
That's definitely the way to go. 

https://i.imgur.com/7d92dbB.png

That looks okay. Hm. What are your thoughts on hiding the description and moving the action links there? Something like this:

https://i.imgur.com/5KTbaZL.png

Or with the actions centered so they're easier to click:

https://i.imgur.com/KqKT57I.png

**Comment by Misplon** [comment]
The last screenshot is a good usability idea but looks a little misaligned. Should we center the widget title?

**Comment by AlexGStapleton** [comment]
That would look like this:
https://i.imgur.com/KjTjtrG.png

We could also set the actions to space between:
https://i.imgur.com/HZVwdos.png

Space between wIth centered title:
https://i.imgur.com/URmFX1n.png

How does the vertical alignment look in those screenshots? Do you want to move the actions up/down?
I feel like https://i.imgur.com/URmFX1n.png is the way to go as it's spread out more.

I've made the changes locally and will commit them once we've confirmed if we're going to center the title/alignment.

**Comment by Misplon** [comment]
This is the one I think https://imgur.com/HZVwdos.
