### ISSUE TITLE
Mobile: Consider increasing the widget modal to 100%

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#719]
Widget editing is possible on mobile by switching your phone to landscape. That said, space is still in short supply. I think we should consider pushing the widget edit modal to 100% width and height. The top bar which contains the close icon is sticky so it's always at an easy to reach location.

![IMG_0179](https://user-images.githubusercontent.com/789159/72206243-090ef200-3494-11ea-8f49-4abac8c1e6f0.png)

@braamgenis Thoughts?

**Comment by braamgenis** [comment]
Sure. It's not a solution for all device sizes, but would at least help for some.

**Comment by Misplon** [comment]
I agree. Yeah, it just felt like a small change we could make that would slightly help editing on certain mobile devices.
