### ISSUE TITLE
Customise responsive behavior

### ISSUE THREAD

**Issue by daninmanchester** [siteorigin/siteorigin-panels#72]
When defining rows/columns it would be useful to be able to influence the way which they respond to mobile / desktop.

e.g. in a 12 column grid responsive framework you could tag up as follows :

class="columns small-12 medium-6 large-3"

as well as show / hide behaviour.

It would be great to have a drop down in the columns to enable the user to configure this behaviour.

**Comment by ww40** [comment]
+1

**Comment by richrd** [comment]
:+1:

**Comment by harryjamesuk** [comment]
Definitely **+1** this idea. My website currently looks awful on a mobile as a result of the single-column layout and I don't want to have to design pages again just for mobile displays *(It makes it a pain if I want to change something)*:

![Image showing PC and Mobile comparison](http://gyazo.com/bee4d3fb64f7f40226a81f6e6885378b.png)

**Comment by Jonathlee** [comment]
+1, definitely great features

**Comment by ste93cry** [comment]
:+1: absolutely needed feature

**Comment by MatthewEppelsheimer** [comment]
+1

**Comment by boquiabierto** [comment]
You can repeat the content and do breakpoint dependent row visibility, like
```
<div class="panel-grid"> widgets with 12 column width each</div>
<div class="panel-grid medium"> same widgets with 6 column widths each </div>
<div class="panel-grid large"> again but in 3 column manner </div>
```
A bloody mess, yeah! So, +1
A dropdown in the row-editor header with small, medium, large options or your siteorigin’s theme demo preview icons would be awesome!
