### ISSUE TITLE
Attributes: Background value inverted commas escaping issue

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#720]
To replicate the issue, try inserting a background image into a CSS Styles field:

`background-image: url("http://localhost/siteorigin/wp-content/uploads/2020/01/fallon-michael-QKFwrKZ3hyk-unsplash-scaled.jpg") !important`

<img width="444" alt="01" src="https://user-images.githubusercontent.com/789159/72352241-8f247600-36ea-11ea-810e-85fa49cfc0e2.png">

The result is:

`background-image: url(&quot;http://localhost/siteorigin/wp-content/uploads/2020/01/fallon-michael-QKFwrKZ3hyk-unsplash-scaled.jpg&quot;) !important;`

I'm unsure if the issue persists in all CSS Styles fields. In this example, I'm working in a cell and using Mobile Styles.

@AlexGStapleton Have you come across this before? The workaround would be to remove the inverted commas.

**Comment by AlexGStapleton** [comment]
I can confirm I've been able to replicate this. I haven't received any reports of this though - most users would use the dedicated background setting.

This is what the CSS looks like when I open it after saving:

https://i.imgur.com/AKQIE7K.png

**Comment by Misplon** [comment]
Thanks for checking. The issue arose in relation to a forum reply of yours where a user is looking to change a background image for mobile. I'll downgrade to P3 as you can remove the inverted commas and implement the declaration in that way.

**Comment by AlexGStapleton** [comment]
@Misplon Are you able to replicate this anymore? I just tried and quotes are now being removed rather than encoded.

**Comment by Misplon** [comment]
The situation appears to be the same.

**Comment by Misplon** [comment]
Here is what I insert:
`background-image: url("http://localhost/siteorigin/wp-content/uploads/2020/01/fallon-michael-QKFwrKZ3hyk-unsplash-scaled.jpg") !important`

Here is what is saved:
`background-image: url(\"http://localhost/siteorigin/wp-content/uploads/2020/01/fallon-michael-QKFwrKZ3hyk-unsplash-scaled.jpg\") !important`

And here is what is outputted:
`#pg-14-0> .panel-row-style {
    background-image: url(\&quot;http://localhost/siteorigin/wp-content/uploads/2020/01/fallon-michael-QKFwrKZ3hyk-unsplash-scaled.jpg\&quot;) !important;
}`

**Comment by AlexGStapleton** [comment]
Huh, strange. Just tried again and was able to replicate it. Not too sure why it previously worked for me.

**Comment by Misplon** [comment]
Ok cool, glad you're able to replicate. Hahaha, yeah, it would have been a win if this had self-resolved.
