### ISSUE TITLE
panels_data not available within Live editor - PHP Notice

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#733]
In backend, when using live editor
I am shown a notice instead of the content when trying to load panels data in the theme banner area. 

**"Notice: Undefined variable: panels_data in /home/wp-content/plugins/siteorigin-panels/inc/renderer.php on line 658"**

The theme banner area renders siteorigin content before the wp main query (just below header). It displays page builder panel data by using "echo siteorigin_panels_render()" function. 

So the notice is displayed for page builder content which is not part of currently editable post content and is outside the main WP loop.

![image](https://user-images.githubusercontent.com/10053621/77745130-0ba4d080-701b-11ea-8ef2-e7f3777b45b7.png)

On the front end, the banner area displays without problems. Only live editor displays the PHP notice.

Ideally the content should display in live editor as well, but should not be editable for the obvious reasons.

**Comment by AlexGStapleton** [comment]
Hi @andrejarh,

Can you please clarify which theme of yours this is happening with? This will allow me to run some tests using a setup that we know can result in this issue. 

Kind regards,
Alex

**Comment by andrejarh** [comment]
Hi Alex,
To isolate the issue without additional clutter, I created a Vantage child theme. 
The child theme creates a banner area in SiteOrigin Vantage theme, a special post type and a widget for displaying its content.

Please download the Vantage child theme here: https://github.com/andrejarh/vantage-test-child-theme.  Demo page import file is also available, to demonstrate the Live Editor issue.

The issue https://github.com/siteorigin/siteorigin-panels/issues/667 seem to also be connected to this one and can be observed on the demo as well.

Please check it out. All feedback is welcome.
Andrej

**Comment by AlexGStapleton** [comment]
Hi @andrejarh,

Thank you for the child theme. I've been able to replicate this issue and I've submitted a #734 that will resolve it. 

@Misplon In addition to the steps outlined in @andrejarh's child theme, you'll need to edit the Page called "A page with banner area" and update "test_static_block_meta_box" with the id of imported test page.

Kind regards,
Alex

**Comment by AlexGStapleton** [comment]
Resolved by https://github.com/siteorigin/siteorigin-panels/pull/734
