### ISSUE TITLE
No negative margin on single column row causing issue when background color set

### ISSUE THREAD

**Issue by ciar4n** [siteorigin/siteorigin-panels#74]
HI Greg

I hope all is well!

Unless I am mistaken there appears to be a slight alignment issue regarding single columns rows compared to multiple column rows. As single column rows have no negative left and right margins, although the content remains in line with multiple columns rows, its containing div does not. I understand that this is for the purpose of the grid and normally wouldn't be a problem however an issue becomes apparent if a background color is set for each row as the background color is applied to the same containing div.

Attached is a screenshot which will hopefully explain. The green been a single column row and the gold been a multiple column row.

![screen](https://cloud.githubusercontent.com/assets/2803503/8286151/e30e83b8-18ff-11e5-98e8-518dfae94851.png)

Hope I make even a little bit of sense :)

Ciarán

**Comment by gregpriday** [comment]
I think we actually resolved this since you posted the issue by treating single-cell rows in the same way as multi-cell rows. I just double checked, and the issue you posted seems to be fine now.
