### ISSUE TITLE
Siteorigin doesn't have the option to edit already created pages

### ISSUE THREAD

**Issue by RafidMuhymin** [siteorigin/siteorigin-panels#744]
I am using WordPress. I have SiteOrigin activated. But the problem is I don't see an option to edit my pages or posts. I can create a page using SiteOrigin by clicking on the 'SiteOrigin Classic Editor' button in the 'Add New' drop-down menu.

I see an edit button when editing via Elementor, Live Composer or other page builders. They show an "Edit with Elementor/Live Composer' button above the header when a page is loaded or in beside the edit, quick edit buttons. But I don't see an option to edit in SiteOrigin. 

I am using 'Starter Templates' from 'Brainstorm Force'.
WP Version: 5.4
SiteOrigin Version: 2.15
Theme: Astra(version 2.4)

**Comment by Misplon** [comment]
Hi, @RafidMuhymin 

Thanks for reaching out. 

On Classic Editor pages, if Page Builder hasn't been loaded, click the Page Builder tab next to the Visual and Text tabs. On Block Editor pages you can insert a SiteOrigin Layout Block or a SiteOrigin Widget Block.

If you have any support questions in the future, please, let us know out via our support forum at https://siteorigin.com/thread. Thanks.

**Comment by Misplon** [comment]
Hi, I'm to close this issue. If you have any questions in the future, feel free to open a support thread on our forum or reach out via email on support@siteorigin.com if you're using SiteOrigin Premium. Cheers for now :)
