### ISSUE TITLE
No longer recognizes post loops

### ISSUE THREAD

**Issue by quantegy** [siteorigin/siteorigin-panels#745]
Updated to Wordpress 5.4, and now Page Builders is reporting that the site has no post loops, that were previously working.

**Comment by Misplon** [comment]
Hi, thanks for reaching out.

The Post Loop looks for templates with your theme or plugin using the following patterns:

```
*-content.php
content-*.php
*-loop.php
loop-*.php
```

Which theme are you using?

**Comment by quantegy** [comment]
@Misplon I know I wrote the loops myself following your documentation. Those files and their locations did not change. When I updated both Wordpress and Panels, the loops no longer render on the frontend, and in the admin the block keeps reporting that the site contains no loops.
![Uploading Screen Shot 2020-05-04 at 9.48.08 AM.png…](Screensoht of my theme directory)

**Comment by Misplon** [comment]
Please, send a copy of your theme and we'll take a look.

**Comment by quantegy** [comment]
@Misplon https://github.com/quantegy/uciseventeen-child

**Comment by Misplon** [comment]
If I drop those loop files into SiteOrigin Coro theme, I can use them. If you'd like to send me a copy of the parent theme, I can test further for you.

**Comment by quantegy** [comment]
@Misplon here is the parent theme https://github.com/quantegy/uciseventeen.git

**Comment by Misplon** [comment]
Thanks. Are you perhaps able to send built copies of the parent and the child?

**Comment by quantegy** [comment]
@Misplon built? Do you mean composer distributions?

**Comment by Misplon** [comment]
ok

**Comment by Misplon** [comment]
I've installed composer globally, run the install in each theme and checked a Post Loop widget in the Classic Editor and all templates appear to be in place:

![Screenshot_2020-05-05_at_18_41_37](https://user-images.githubusercontent.com/789159/81092044-53fbbc00-8f00-11ea-9f22-1d003fa4c502.png)

I'm using WordPress 5.5-alpha-47761.

If you've already started troubleshooting, please, let us know the steps taken. If not, please try:

* Check for JS console errors when the issue occurs.
* Check for PHP errors with DEBUG enabled.
* Check to see the issue persists with all plugins not authored by SiteOrigin deactivated.

Thanks

**Comment by Misplon** [comment]
Hi Chris

A quick check-in to see if you've perhaps made progress on this one.

**Comment by Misplon** [comment]
Hi Chris, I've closed this issue for the time being. If you still need a hand, please, let us know. Cheers :)
