### ISSUE TITLE
Live editor bug (new pages)

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#748]
1. When a new page is created and opened with live editor (before publishing the page), The live editor does not work. Any changes to the site are not displayed. 

Also a thing I noticed is that WP Admin bar is displayed in the live editor, when editing drafts (which is not the case when editing already saved posts).

This was tested on a fresh installation with the latest official WP version, default Twentytwenty WP theme and Page builder version 2.10.16. No third party plugins were installed. 

2. Additionally when I installed the widget bundle, and added the Features widget. I got this error:

<img width="731" alt="Screenshot 2020-05-07 at 09 59 15" src="https://user-images.githubusercontent.com/10053621/81269716-068b6600-904a-11ea-8364-693ee1b487c4.png">

**Comment by Misplon** [comment]
Thanks, Andre, I'll ask Alex if he can recreate, I haven't been able to yet.

**Comment by Misplon** [comment]
Alex can recreate the issue. Thanks for reporting. We'll resolve this ASAP in an update.
