### ISSUE TITLE
Chrome update broke Live editor

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#757]
Live editor doesn't seem to work well with latest Chrome version.

When in live editor view, the rows don't get highlighted when scrolling, and clicking on a widget does not open the widget edit screen...

I am running Windows Chrome 83.0.4103.61 and Page builder version 2.10.17. The issue is present also on Mac OS.

**Comment by Misplon** [comment]
Thanks, @andrejarh. We received a few reports yesterday evening. Users have temporarily switched to Firefox as a hotfix. We'll investigate and update this issue as soon as we know more.
