### ISSUE TITLE
Modern Events Calendar - Black Studio conflict

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#763]
The Modern Events shortcodes page doesn't function normally with Page Builder and Black Studio TinyMCE Widget activated. Once the two plugins plus Page Builder are activated go to M.E. Calendar > Shortcodes to view the issue, deactivate either Page Builder or Black Studio and the issue resolves.

https://wordpress.org/plugins/modern-events-calendar-lite/
https://wordpress.org/plugins/black-studio-tinymce-widget/

**Comment by AlexGStapleton** [comment]
Is this issue still occurring? I installed both plugins and I've compared the shortcodes page with and without SiteOrigin Page Builder being active, and I'm not seeing any issues. I'm able to adjust fields, and changes are being saved.

**Comment by Misplon** [comment]
Separately, does activating Modern Events Calendar reduce the size of our SO Premium admin icons in the main left WP menu for you?

**Comment by Misplon** [comment]
@AlexGStapleton The main issue seems to be resolved. My SO Premium admin icons seem normally sized now. Can close when ready.
