### ISSUE TITLE
Redirections plugin is incompatible with Rank Math SEO

### ISSUE THREAD

**Issue by cheyennecuellar** [siteorigin/siteorigin-panels#764]
What do I do since these two plugins are incompatible but I need both?

**Comment by Misplon** [comment]
Hi, is Page Builder involved in the problem?

**Comment by cheyennecuellar** [comment]
I have Elementor installed as a plugin. But no plugins called Page Builder.

**Comment by Misplon** [comment]
Thanks for confirming. This is the GitHub repo for Page Builder by SiteOrigin. You'll need to raise the issue with one of the authors of the two plugins involved in the conflict.

**Comment by cheyennecuellar** [comment]
thank you

**Comment by Misplon** [comment]
Sure, no problem. Hopefully, you're able to resolve the problem soon. Cheers for now :)
