### ISSUE TITLE
PHP Notice appearing when fields hidden

### ISSUE THREAD

**Issue by bbceg** [siteorigin/siteorigin-panels#766]
Not a major problem but I think I've found a case where a notice appears in the error log when widget styles are hidden using the following:

`add_filter( 'siteorigin_panels_widget_style_fields',     '__return_false', 11 );`

As described [here](https://siteorigin.com/thread/disable-widget-styles/).

The notice is as follows: 
`PHP Notice:  Undefined index: type in ...plugins/siteorigin-panels/inc/styles-admin.php on line 153`

The same notice is output for line 183.

Looking back through the error logs I'm relatively confident that this is a new issue.

**Comment by bbceg** [comment]
Turns out these notices were appearing because I was filtering the field value in a child theme. Please ignore!

**Comment by Misplon** [comment]
No problem! Thanks for keeping the issue updated.
