### ISSUE TITLE
PHP class autoloading

### ISSUE THREAD

**Issue by szepeviktor** [siteorigin/siteorigin-panels#77]
Please consider implementing class autoloading instead of hard-coded `require` calls.

**Comment by szepeviktor** [comment]
For example
https://github.com/Yoast/wordpress-seo/blob/trunk/wp-seo-main.php#L31

**Comment by gregpriday** [comment]
This is a very good suggestion. We've started moving towards auto loading
in our other plugins, but it would be great to get it into Page Builder too.

**Comment by gregpriday** [comment]
We've moved over to autoloading for Page Builder 2.5

**Comment by szepeviktor** [comment]
Thanks. 


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!
