### ISSUE TITLE
No positive case support

### ISSUE THREAD

**Issue by tom-cichy-cityos** [siteorigin/siteorigin-panels#774]
https://github.com/siteorigin/siteorigin-panels/blob/65d97475d2cc29b244b45a0fa09d13c6b0ee86e0/js/siteorigin-panels/model/widget.js#L158

This is a real shame, cause as a dev I could use this setting to tell you exactly with input to use as a title instead of this function "makes most sense".

If I want a numerical values there is no way getTitle function will let me.

**Comment by AlexGStapleton** [comment]
Hi Tom,

Can you please provide me with an example widget that doesn't function correctly due to this line? Using the code you're having trouble with will allow me to see exactly what you're seeing which will give me a better overall understanding of your usercase.

Kind regards,
Alex

**Comment by AlexGStapleton** [comment]
Hi Tom,

Just reaching out to touch base. Do you still need help with this?

Kind regards,
Alex

**Comment by tom-cichy-cityos** [comment]
Hi. Thank you very much for following up! 

I actually worked around that issue. Let me explain the issue better.

**As a developer, I want to use numeric values as title of my widgets.**

I still think the logic is broken (or my logic, I might miss sth) 
the comment in the code says "// This means that the widget has told us which field it wants us to use as a title"
- YES, this is what I need.

but then it doesn't use widgetData.panels_title anywhere except for the false case.

The function should use the value of the field named in widgetData.panels_title and return it immidately.

Could maybe be like attached:
<img width="1152" alt="Screenshot 2020-07-12 at 19 09 11" src="https://user-images.githubusercontent.com/48678862/87252425-4704c700-c473-11ea-858b-0d8539a377cd.png">

**Comment by AlexGStapleton** [comment]
Hi Tom,

Thank you for clarifying. We don't currently allow for this. Can you please clarify what you're setting `panels_title` too? This will allow me to account for your use case while also accounting for the current usage. 

Kind regards,
Alex

**Comment by tom-cichy-cityos** [comment]
I wrote a widget that adds vertical height to help with more complicated layouts.
May be too specific to call that an issue. 

So panels_title = 'vertica_height' and consequently I would have <input name='vertical_vertica_height'> in the form function in the widget.  

Don't worry about that.

**Comment by AlexGStapleton** [comment]
Hi Tom,

Thank you for the additional information. I'm going to add a note about this and if this comes up again we'll look to implement changes to allow for this. Please let me know if anything else comes up.

Kind regards,
Alex
