### ISSUE TITLE
Append prebuilt layouts instead of replacing the content with them

### ISSUE THREAD

**Issue by h8every1** [siteorigin/siteorigin-panels#78]
It would be nice if it was possible to append prebuilt layouts instead of replacing the whole content with them.

I have some handy snippets in my Prebuilts. For example two column layout with WYSIWYG-editor in one column and image widget in the second. They have some CSS classes and styling applied.

If I already have some content, I can't insert this snippet, because I will lose all my content.

Maybe I'm missing something at is laready possible to achieve what I want?

**Comment by cmwwebfx** [comment]
So what i understand from this comment you would like to save row layouts for reuse on the site?

**Comment by h8every1** [comment]
Yes. And most important thing is that i want to be able to use several row
layouts in a post.

вторник, 21 июля 2015 г. пользователь Ciaran Whelan написал:

**Comment by brentjett** [comment]
+1  I don't currently use prebuilts because of this behavior. Would love to construct pages with pre defined rows.

**Comment by gregpriday** [comment]
I worked on this briefly a little while ago, but I'll give it another shot.

**Comment by danpilat** [comment]
+1 - we would love this!

**Comment by Sekoul** [comment]
+1 - ditto, would be great. Thank you!
