### ISSUE TITLE
get_categories didn't work in __construct

### ISSUE THREAD

**Issue by fingerprintweb** [siteorigin/siteorigin-panels#79]
In wordpress can't use get_categories() to creat list category for form options type 'select'

$fpwebargs = array(
          'taxonomy'     => 'product_cat',
          'orderby'      => 'name',
          'show_count'   => 0,
          'pad_counts'   => 0,
          'hierarchical' => 1,
          'title_li'     => "",
          'hide_empty'   => 0
        );
$categories = get_categories($fpwebargs);
foreach ($categories as $cat) {
  $cat_options[$cat->cat_ID] = $cat->name;
}

$form_options = array(
'fields' => array(
        'some_selection' => array(
        'type' => 'select',
        'label' => __( 'Choose a thing from a long list of things', 'widget-form-fields-text-domain' ),
        'default' => '',
        'options' => $cat_options
        )
);

get_categories() we can use in 
function form(){
...
}
But then we lost generate form in class SiteOrigin_Widget

I sugest add hook to form function in yours widget (before form and after form)
After this we can add text, data, javascript or custom form fields. 
Don't forget add to hook widget name.  

ps. I bypass this using add_filter('siteorigin_panels_widget_form', 'my_fix', 'Woo_Products_Widget');
But in this filter is missing widget name parameter like in filtersiteorigin_panels_missing_widget_form

**Comment by gregpriday** [comment]
Hi @fingerprintweb - sorry I missed this issue. If you switch to using get_widget_form instead, it's called much later so you should have access to things like `get_categories`. This is what we use in our own widgets:

https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/google-map/google-map.php#L31
