### ISSUE TITLE
Since update to 2.11.1 we are receiving "Notice: Undefined index: panels_info"

### ISSUE THREAD

**Issue by korridor** [siteorigin/siteorigin-panels#791]
The error occurs at:   
`/wp-content/plugins/siteorigin-panels/inc/widgets/post-loop.php` in `SiteOrigin_Panels_Widgets_PostLoop::widget` at line 153

**Comment by AlexGStapleton** [comment]
HI Korridor,

Thank you for reporting this warning. I've identified why this is happening and I've come up with a fix. https://github.com/siteorigin/siteorigin-panels/pull/792

Kind regards,
Alex

**Comment by korridor** [comment]
Thanks for the quick response and fix.

Best regards,
Korridor

**Comment by Misplon** [comment]
Hi @korridor 

Thanks for logging :) I'm going to close this issue, if there are any issues after the next release, please, let us know. We're working on the last PR's for the release this week. If you'd like a beta copy to use now, please, let me know. Thanks again.
