### ISSUE TITLE
Native WP import/export and Page Builder v2.0

### ISSUE THREAD

**Issue by primozcigler** [siteorigin/siteorigin-panels#8]
Hi Greg,

I was playing around today with new PB v2.0 and it seems like the content import/export is not working anymore as it used to in v1.x?

This feature was killer before, so it would be great that is works in v2.0 as well. When I import basically just the bare content is imported, no data about the rows and grids.

Can you confirm? Or I am doing something wrong?

Thanks!
Primoz

ps: I will be creating pull request in next days for new approach to handling BackboneJS events, now everything is in closure and nothing is triggered on global scope.

**Comment by primozcigler** [comment]
Hi Greg,

I have invested quite some time today to fix that issue. It seems like it is arising form the this filter and 2 associated functions: https://github.com/siteorigin/siteorigin-panels/blob/master/siteorigin-panels.php#L1144 .

I tried to comment out that filter and the import works quite OK then. I noticed that you use deprecated *e* modified in `preg_replace` as well as some kung fu with the new lines. I am not very sure why these lines are there at all, can you please clarify, so I try to fix it and hopefully not break for everyone else? Thank you! :smile:

**Comment by gregpriday** [comment]
Hi Primoz

That filter was a good old fashion hack to make sure everything worked with the import/export. As far as I remember, the issue there was that some content wasn't being exported properly.

I'll run a few tests on my side and see if this filter is still neccessary. It's possible they fixed something in the WordPress import/export plugin that made this hack no longer neccessary.

**Comment by primozcigler** [comment]
Hi Greg,

I noticed *Fixed import/export.* on the changelog of `2.0.4`. Did `2.0.4` fix this issue?

I didn't have time to check that yet locally, I will later on today and I will let you know if everything works fine now on my side.

**Comment by gregpriday** [comment]
I did as much testing as I could, and it seemed to fix the issue. All I did was remove the old hack. It didn't seem like this was neccessary anymore with the latest importer plugin.

It would be great if you could confirm.

**Comment by primozcigler** [comment]
Hi @gregpriday I am confirming this was fixed (sorry for waiting so long) :smile: 

Keep up the good work! :)
