### ISSUE TITLE
Mobile: Check the editing experience of the Layout Block

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#802]
@AlexGStapleton a user mentioned that the mobile experience in the Layout Block wasn't the same as in the Classic Editor. I don't think we checked the Layout Block in our recent work for mobile. I haven't checked yet or confirmed but thought I'd log this so we can come back to take a look when able. Thanks.

Task: Check the editing interface of Layout Block on mobile. Align where possible to the level of editing we have on mobile in the Classic Editor.

**Comment by AlexGStapleton** [comment]
I'm not seeing any real differences between the Classic Editor and SO Layout block. Did they mention any specific differences?
I do see differences in the simulated preview though. I don't however think that's what the user was referring too as that wasn't easily accessible at the time).

![Screenshot_2020-08-17 Edit Page ‹ SiteOrigin — WordPress](https://user-images.githubusercontent.com/17275120/90339302-4394ca80-e033-11ea-8ad1-7f4c1f70c84c.png)

The preview isn't in an iframe so our existing media queries aren't applicable. To improve how that looks we would need to conditionally add a class to the layout (as the Block Editor doesn't do this) and then write CSS that replicates the existing responsive CSS. Do you want me to proceed with that? I ask as this view isn't really for editing the block, it's for previewing the content so I'm not too sure if it's a worthwhile change.

**Comment by Misplon** [comment]
Sorry, mate. I should have researched this more before logging. I can't see any differences using Xcode Simulator. Everything looks the same.

**Classic**
<img width="425" alt="classic" src="https://user-images.githubusercontent.com/789159/90438281-00d6ff00-e0d4-11ea-818c-779df8315b18.png">

**Block**
![block-editor](https://user-images.githubusercontent.com/789159/90438306-09c7d080-e0d4-11ea-9b10-6295230d74c6.jpg)

**Comment by AlexGStapleton** [comment]
Yeah, that's what I'm getting also. The only difference I'm getting is when using the simulated device previews. Do you want to account for this? I ask as this view isn't really for editing, it's for previewing the actual widget.

![Screenshot_2020-08-18 Edit Page ‹ SiteOrigin — WordPress](https://user-images.githubusercontent.com/17275120/90459221-fd7b5c00-e143-11ea-8306-d7a60abe0044.png)

**Comment by Misplon** [comment]
Does the above screenshot exist on an actual mobile device? When I click Preview on Simulator, it opens a new tab in Safari and offers up the following:

![Uploading iPhone_11_—_13_3_and_Mobile__Check_the_editing_experience_of_the_Layout_Block_·_Issue__802_·_siteorigin_siteorigin-panels.jpg…]()

**Comment by AlexGStapleton** [comment]
It looks like the preview device menu is disabled while using an actual device. It's accessible while using a tablet, but the PB responsive CSS kicks in so the correct view is displayed while editing the block regardless of what mode the user selects.

**Comment by AlexGStapleton** [comment]
To confirm, do you want me to account for that and have the mobile editing options visible in the simulated view? I ask as I was suggesting the opposite.

**Comment by Misplon** [comment]
You're right, feel free to close once you've read this. Thanks.
