### ISSUE TITLE
Classic Editor: Yoast content analysis returning zero words with PB active but not used

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-panels#811]
Yoast is returning a zero word count. I haven't checked the Block Editor yet, just the Classic Editor.

**Comment by gregpriday** [comment]
Did this start happening with one of our updates of one of their's?

**Comment by Misplon** [comment]
Not sure. Will narrow it down shortly.

**Comment by Misplon** [comment]
The issue is only present in Yoast 14.9. Rolling back resolves the issue.

**Comment by Misplon** [comment]
The issue isn't consistent, the word count being returned is sometimes normal. We aren't yet sure why.
