### ISSUE TITLE
"Section" container addition

### ISSUE THREAD

**Issue by brentjett** [siteorigin/siteorigin-panels#82]
Hi, nice solid plugin. I'd love to see the addition of a "section" container element to optionally wrap around rows/columns. It's very common for multiple rows to share the same background and therefore need a containing element, likely which will span the full width of the page. For example:

![section-example](https://cloud.githubusercontent.com/assets/1790660/8945259/83ab9c04-354b-11e5-9e94-3a4a342227b9.jpg)

**Comment by Finetuned** [comment]
+!

**Comment by ste93cry** [comment]
:+1: I'm using this plugin for the first time and I'm missing this feature a lot!

**Comment by gregpriday** [comment]
This would be fairly easy to implement now using a Layout Widget inside a row with a standard Full Width layout.

**Comment by ste93cry** [comment]
It should be possible to specify the CSS classes for the container `div` in the backend, or at least with a filter

**Comment by brentjett** [comment]
It's no problem, I use Beaver Builder now 👍

**Comment by gregpriday** [comment]
@ste93cry Aaah, @AlexGStapleton let me know I misunderstood the request. It's essentially CSS column styling for text. This is the kind of thing we could add to the Editor Widget in the Widgets Bundle. I'll take a look at this.

@brentjett awesome, thanks for stopping by to let us know.
