### ISSUE TITLE
Use of file_get_contents

### ISSUE THREAD

**Issue by robneu** [siteorigin/siteorigin-panels#83]
I noticed that you guys are using PHP's `file_get_contents` in a [few parts](https://github.com/siteorigin/siteorigin-panels/search?utf8=%E2%9C%93&q=file_get_contents) of the plugin. As far as I know, this is considered to be bad practice in a WordPress plugin. It's [definitely not allowed in themes](https://github.com/Otto42/theme-check/blob/f3f9706a7997385250c5ade69930e7ad842af0cf/checks/malware.php#L9). It's much more secure and reliable to use the [WordPress Filesystem API](http://codex.wordpress.org/Filesystem_API) for local files and the [HTTP API](https://codex.wordpress.org/HTTP_API) for remote files.

It looks like the filesystem API is what's needed in this case. If you'd like, I can try to work up a PR to port these instances over to use that instead of `file_get_contents`. If nothing else, I figured it would be helpful to make a note of this. :smile:

**Comment by braamgenis** [comment]
Hi @robneu 

You're right, it probably is better to use the Filesystem API. Feel free to make the changes in a PR and we'll look over it as soon as we get a chance. Otherwise, if you don't get to it we'll look at implementing this ourselves when we have some time. Thanks for your contribution.

**Comment by gregpriday** [comment]
The main place we're using `file_get_contents`now is for layout importing. The WordPress filesystem is only really important when you're dealing with file permissions, which reading doesn't need to do.

For layout importing, we're only accessing, then deleting files in the system's temporary folder. So it's really not essential.

All the other places where we're using `file_get_contents` are due for removal in Page Builder 2.6.
