### ISSUE TITLE
Extending the Page Builder

### ISSUE THREAD

**Issue by paaljoachim** [siteorigin/siteorigin-panels#84]
I am working on Altitude Pro a Genesis child theme parallex theme. They use widgets for front page sections. Adding background images is pretty easy adding good looking content is not.
In their online manual they show how to add html to text widgets for the various front page sections.
Well there got to be a better way then having to code a good looking parallex layout... Forcing the customer to use html in a text widget to adjust is really not a good option.

So I thought about testing out the Site Origin Page Builder for this purpose. As I searched for siteorigin through the plugin screen and the first plugin that I noticed was the Ultimate Addons for SiteOrigin -  https://wordpress.org/plugins/addon-so-widgets-bundle/
Just from browing quickly through the addons my first impression (was these are very useful addons) what about incorporating this directly into your own Page Builder? 

- Perhaps having a Jetpack like interface turning widgets on or off would benefit the plugin.

Another thing...
I plan on creating a tutorial on how I setup the Genesis Altitude Pro using various tools (I am also using waypoints and animate.css) and hope that the Page Builder becomes one of them.

Have a great day!

Paal Joachim

http://easywebdesigntutorials.com/

**Comment by braamgenis** [comment]
Hi @paaljoachim The Ultimate Addons plugin is a third party plugin, based on our [Widgets Bundle plugin](https://wordpress.org/plugins/so-widgets-bundle/) which includes a number of well written and maintained widgets and an interface for switching widgets on and off. Hope that's what you were looking for.
