### ISSUE TITLE
PB not honouring the classname for the widget output

### ISSUE THREAD

**Issue by primozcigler** [siteorigin/siteorigin-panels#85]
Hi Greg,

A question: we noticed in our team that Page Builder is not honouring the `classname` if supplied to the [__construct function](https://developer.wordpress.org/reference/classes/wp_widget/__construct/) when defining a widget?

This code: https://github.com/siteorigin/siteorigin-panels/blob/develop/siteorigin-panels.php#L1134

It is always defining the HTML class name based on the `id_base` property, ignoring the optional classname.

I am wondering if there is any particular reason for that? If not, I would love to create a PR with that change.

(I am aware it would be possible to add that via filter `siteorigin_panels_widget_classes`, but I believe this should be fixed in the plugin itself.)

Thank you for the answer!

**Comment by primozcigler** [comment]
Hi @gregpriday, I will really appreciate an answer :)

Thanks!

**Comment by gregpriday** [comment]
Hi @primozcigler! Sorry for the late reply here - really bad of me. There's no good reason for Page Builder to be ignoring the classname attribute. This is just an oversight on my behalf.

If you submit a PR that fixes this, I'd be happy to merge it. I'll take a look at this myself if you can't find the time though.

**Comment by primozcigler** [comment]
Hi Greg,

I am GLAD to hear that! :smile: 

Expect the PR later today.
