### ISSUE TITLE
Some prebuilt layouts are not showing up.

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/siteorigin-panels#853]
Hi,
While adding prebuiIt layouts to the theme, I encountered a strange issue. 
Some of the layouts are not showing up.

So I've added the layout folder within a plugin like this:
```
function o_prebuilt_layouts_folder( $layout_folders ) {
    $layout_folders[] = plugin_dir_path( __FILE__ ) . '/layouts';
    return $layout_folders;
}
add_filter( 'siteorigin_panels_local_layouts_directories', 'o_prebuilt_layouts_folder' );
```

And added the layouts to the folder as seen on the screenshot
![layouts](https://user-images.githubusercontent.com/10053621/111745637-2ce67880-888d-11eb-9ec8-09a8c11c5b0f.jpg)

Most of the layouts work fine, but some of them are not showing up.
The ones missing are: hero-1, profile-3, services-1 and testimonials-2. 

There isn't any specific difference in how the layouts were made. They all contain custom widgets and custom settings. 
Do you have an idea, what could be the reason for some of the layouts not displaying? Do you have any suggestion on how to debug this issue?
Thanks!

**Comment by AlexGStapleton** [comment]
Hi andrejarh,

Are you able to import the layouts that aren't showing into Page Builder manually using the Import/Export, or does Page Builder reject them? If Page Builder rejects them, try re-exporting the layout to see if that helps.

If Page Builder doesn't reject the layouts and they import correctly, can you please provide me with the layouts you're having issues with and (for comparison) a few of the working layouts? This will allow me to run some tests against those layouts and see if I can spot any issues with them.

Kind regards,
Alex

**Comment by andrejarh** [comment]
Hi @AlexGStapleton 
The layouts import properly with manual import. They just don't show up on the (cpanel based) server. Interestingly enaugh they show up on my localhost on my WIN PC, but also not displaying on a macbook localhost, although they were exported on the same computer (macbook). 

I've set up a demo and send the login info to support [at] siteorigin.com
I will apreciate very much, if you can take a look.

Thanks
