### ISSUE TITLE
Layout Builder Widget Not Including WP Rocket Lazy Load Class

### ISSUE THREAD

**Issue by JoelLisenby** [siteorigin/siteorigin-panels#869]
It appears that the new WP Rocket Lazy Load class is not being added to Layout Builder Widget rows when they have a background image.

This is the particular class I am referring to:
https://github.com/siteorigin/siteorigin-panels/commit/d45adf62461e3188f9616ad886f8ea6856059ce3#diff-41ce281458f153d7e2bdfc95e5b4d8c2c951d7cdf1ada9db5a0fb6eed90f58bcR24-R27

The screenshot below shows that this row within a Layout Builder Widget with a background is not outputting the rocket-lazyload class.
![image](https://user-images.githubusercontent.com/428122/117883403-3aeac100-b260-11eb-983c-9148b974842c.png)

**Comment by AlexGStapleton** [comment]
Hi Joel,

I've run a few tests and I'm having trouble replicating this. Non-Layout Builder widgets and rows are outputting as expected for you, correct?

<img width="702" alt="2021-05-13_07-38-29-1476" src="https://user-images.githubusercontent.com/17275120/118047539-3e945a00-b3be-11eb-9109-2a2d0ceb98a9.png">

Kind regards,
Alex

**Comment by JoelLisenby** [comment]
Apologies, it is actually not outputting to either. I just tried disabling all plugins except WP Rocket and SiteOrigin Page Builder and I'm seeing the same effect, even after clearing all caches.

**Comment by AlexGStapleton** [comment]
Handling over email.

**Comment by JoelLisenby** [comment]
Just wanted to update here that there was confusion over the Lazy load source. We realized that the support added was for the separate WP Rocket Lazy Load plugin (https://wordpress.org/plugins/rocket-lazy-load/)-- not the built in Lazy Load. I was informed that support for the built in Lazy Load will be coming shortly.
