### ISSUE TITLE
CSS when loading content with ajax

### ISSUE THREAD

**Issue by YanikPei** [siteorigin/siteorigin-panels#87]
I'm trying to load the content of a post with ajax. Everything works, except that the css, which SiteOrigin prints out in the head-section, is not available. Is there a way to load or create the css dynamically, or is it possible to include it on every single page/post?

**Comment by gregpriday** [comment]
This would be a little difficult to achieve, but not impossible. You'd need to create a custom ajax request that calls `siteorigin_panels_generate_css` with the ID of the post you want the CSS for. Your JS would need to load this CSS and append it to the head at the same time that it's loading your post content.

Hopefully that points you in the right direction.

**Comment by boquiabierto** [comment]
As @gregpriday said:

Create the wp_ajax function:
```
function ajax_siteorigin_panels_generate_css(){
	$post_id = $_POST['post_id'];
	$css = siteorigin_panels_generate_css($post_id);	
	echo $css;
}
add_action('wp_ajax_siteorigin_post_panels_css', 'ajax_siteorigin_panels_generate_css', 10 );
add_action('wp_ajax_nopriv_siteorigin_post_panels_css', 'ajax_siteorigin_panels_generate_css', 10 );
```
Remember to setup the ajax url:
```
function scripts_and_styles() {
	
	$themeURL = get_template_directory_uri();

	wp_enqueue_script( 'script-js', $themeURL . '/js/script.js', array('jquery'), false, true );
	wp_localize_script('script-js', 'WP_AJAX', array( 'ajaxurl' => admin_url( 'admin-ajax.php' ), 'themeurl' => $themeURL));

}
add_action( 'wp_enqueue_scripts', 'scripts_and_styles' );
```

Create your nice little API with an injection function, something like:
```
(function($){

	var dom_head = $('head');
	
	var SiteOriginAPI = {

		injectPostPanelsCSS: function (postID){
			
			var data = {
					action: 'siteorigin_post_panels_css',
					post_id: postID
				};
			
			$.ajax({
				type: 'POST',
				url: WP_AJAX.ajaxurl,
				data: data, 
				success: function ( data ){ 
					var inlineCss = '<style type="text/css" media="all" id="siteorigin-panels-grid-' + postID + '">' + data + '</style>';
					dom_head.append(inlineCss);
				},
				dataType: 'text'
			});
						
		}
	};
	// Inject it, here with postID = 2
	SiteOriginAPI.injectPostPanelsCSS(2);
	
})(jQuery);
```

**Comment by YanikPei** [comment]
@boquiabierto: Awesome, that works perfectly! Thanks!
