### ISSUE TITLE
[Feature Request] Add CSS classes for each column in a row

### ISSUE THREAD

**Issue by ste93cry** [siteorigin/siteorigin-panels#88]
It would be great to have the ablity to specify custom classes for each columns of a row. Currently I can only specify classes that will be applied to all columns or none.

**Comment by ste93cry** [comment]
@gregpriday any plan for this feature? I'm findinf really limitating the absence of this feature because user doesn't have enough control over the single columns style.

**Comment by gregpriday** [comment]
Hi @ste93cry - I think the easiest way to get this in the short term would be to have a placeholder in the cell class that Page Builder would replace with the cell index. Would this work for you?

For example entering `my-column-{$i}` could give the first column a class of `my-column-0`, the second a class of `my-column-1`, etc.

To give more fine grained control over each cell/column class would require a substantial rethink of the interface.

**Comment by ste93cry** [comment]
Thank you for the reply, I appreciate the effort you put on this plugin so keep up the good work! At the moment my layout is simple enough to be able to workaround the problem by stylizing the template with all the columns of the same width and style. However, it would be nice if you could put this feature into the things to do as soon as possible because I think that other users like me could have the same problem. This is definitely a big issue for the pagebuilder, because currently there isn't enough flexibility. A double click on a column (as far as I see the single click is already used for another feature) could open a little popup with a few options like custom style and class attributes and maybe and ID too. I know I'm asking a lot of things, but I prefer that you take the time you need to make it instead of implementing some workarounds that are still limitating and takes you time that you could use better

**Comment by lance1572** [comment]
@gregpriday  - I would like to know how to implement your short term solution. Where would I input that  my-column-{$i}

Yes! Awesome plugin too! I appreciate all the effort and keeping it free!!! Thank you!!

**Comment by gregpriday** [comment]
We have added the ability to set cell IDs as well as filter cell classes. This will all be available in the 2.5 update.
