### ISSUE TITLE
Page Builder, Yoast SEO, The Events Calendar Pro conflict - breaking TEC Pro styling

### ISSUE THREAD

**Issue by tim-andes** [siteorigin/siteorigin-panels#880]
My company has SO Premium but I don't have login details to get the premium support email, so I'm posting here.

<img width="1288" alt="Screen Shot 2021-06-03 at 11 31 38 AM" src="https://user-images.githubusercontent.com/64085493/120706086-e6f58580-c475-11eb-9114-dd534f2b2cac.png">

### Please give us a description of what happened.

If Page Builder (PB) / Yoast SEO / The Events Calendar Pro (TEC Pro) are all active and you use The Events Calendar widget OR short code forms of loading the calendar into a page, you will find that the styling for TEC Pro events calendar is broken (see above screen shot).

This can be 'fixed' by performing the following:
- Deactivate Yoast SEO, but leave PB and TEC Pro (w/ widget or short code) as is
- Instead of using TEC's widget or short code to load in events, use the default Events List widget (PB and Yoast SEO can remain active and in use)
- Do not use PB on the events page--just use the text editor and load in the TEC Pro short code (and keep TEC Pro/Yoast SEO active)

We found that it is this particular linked stylesheet that is being blocked from feeding through: https://cloudup.com/cpJoqwz2atP

### Please describe what you expected to happen and why.

The three plugins should work together without conflict.

### How can we reproduce this behavior?
1. Spin up new site with just the Twenty Twenty theme (we also experienced the issue with SO Corp)
2. Install SO Page Builder, SO Widgets Bundle, Yoast SEO, The Events Calendar, The Events Calendar Pro, Classic Editor
3. Create a list of events
4. Create an events page WITH PageBuilder, link events calendar with [tribe_events] short code in an Editor widget (styling should be broke)
    a. Try deactivating Yoast SEO (styling should work)
    b. Reactivate Yoast, but replace the Editor widget and TEC short_code with an Events List widget (styling should work)
5. Create a 2nd events page WITHOUT PageBuilder, link events calendar with [tribe_events] short code in the normal text field (styling should work)

### Technical info

* If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [ ] Gutenberg
- [X] Classic Editor plugin

* Which browser is affected (or browsers): 
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

#### Used versions
* WordPress version: Version 5.7.2
* Yoast SEO version: Version 16.4
* Classic Editor plugin version: Version 1.6
* Tested with theme: SiteOrigin Corp, Twenty Twenty

I yanked this form from Yoast SEO's GitHub (see issue [here](https://github.com/Yoast/wordpress-seo/issues/17117)). They reviewed it and don't believe their backend-heavy plugin will affect any visual output.

**Comment by Misplon** [comment]
Hi Tim, thanks for posting. We'll dive into this ASAP on Monday, definitely sooner if we can. If you have an active license, please, email support@siteorigin.com any time you have queries or requests. We're there to lend a hand wherever we can.

**Comment by tim-andes** [comment]
Sounds good. Enjoy your weekends! Should I forego sending an email this time?

**Comment by Misplon** [comment]
Thanks :) Sure, we can shift this over to email. I'll close this issue. We have the info so if you can just reference it in your email, that'll be great. Thanks again.
