### ISSUE TITLE
Feature request: Filter to disable column resizing

### ISSUE THREAD

**Issue by MatthewEppelsheimer** [siteorigin/siteorigin-panels#91]
Would you entertain a PR with a filter to disable column resizing? I haven't started on this yet — I want to see if it would be welcome, first — so I'm not sure how feasible this would be.

**Comment by gregpriday** [comment]
Do you mean adding a filter that would force columns to be a fixed width in the frontend, or a filter that would prevent a user from editing column sizing in the backend?

**Comment by MatthewEppelsheimer** [comment]
I'd like to prevent a user from manually editing column sizing in the backend. They would only be able to select the number of columns per row, not adjust each column's width.

**Comment by ste93cry** [comment]
:+1:, it could be useful in some cases like the integration of the pagebuilder with a frontend framework like Bootstrap

**Comment by MatthewEppelsheimer** [comment]
Agreed. Also in cases where the friendly design department wants to draw bright lines for editors to color within. :smile:

**Comment by mesunil2010** [comment]
Yes this is important. Guys if there is a filter for this, I could make a plugin or fork the project to work in bootstrap grid system.

**Comment by jnhghy** [comment]
Why do you need an extra filter for this? there is already filters for ratio and you can always dequeue siteorigin panels styles or scripts that you don't need and enqueue your own.

**Comment by AlexGStapleton** [comment]
This is possible using the [Custom Post Type Builder](https://siteorigin.com/premium-documentation/plugin-addons/custom-post-type-builder/) functionality in [SiteOrigin Premium](https://siteorigin.com/downloads/premium/). With that said, We'll keep this in mind for future updates for the base version of SiteOrigin Page Builder.
