### ISSUE TITLE
Disable History button if post revisions are not enabled

### ISSUE THREAD

**Issue by ste93cry** [siteorigin/siteorigin-panels#96]
The History button should be disabled if the `wp_revisions_enabled` function returns `false`. That function will ensure that the check is done against not only the constant `WP_POST_REVISIONS` but even the post type support.

![siteorigin-history-button](https://cloud.githubusercontent.com/assets/1770485/9580704/46adc262-4ffb-11e5-9404-dff2847cd656.png)

**Comment by gregpriday** [comment]
Hi @ste93cry 

This feature actually works independently of WordPress post revisions. This is an in memory history that only goes as far back when the Page Builder interface is first loaded. Post revisions however, operate on a database level.

I'd be fine with adding an option for users to disable this feature, but I don't think it should be tied to the post revision setting.

**Comment by ste93cry** [comment]
This is strange, I have a custom post type with the builder enabled, and the history only shows the current version of the page. This is why I thought it was tied with the post revisions that I disabled.
