### ISSUE TITLE
PHP Warning in Widgets

### ISSUE THREAD

**Issue by MachineITSvcs** [siteorigin/siteorigin-panels#963]
I am getting the following PHP warning in error log:

`PHP message: PHP Warning:  include(/web/wp-content/plugins/siteorigin-panels/widgets//less/functions.php): failed to open stream: No such file or directory in /web/wp-content/plugins/siteorigin-panels/widgets/widgets.php on line 3PHP message: PHP Warning:  include(): Failed opening '/web/wp-content/plugins/siteorigin-panels/widgets//less/functions.php' for inclusion (include_path='.:/usr/share/php') in /web/wp-content/plugins/siteorigin-panels/widgets/widgets.php on line 3PHP message: PHP Fatal error:  Uncaught Error: Class 'SiteOrigin_Panels_Widget_Shortcode' not found in /web/wp-content/plugins/siteorigin-panels/siteorigin-panels.php:69\nStack trace:\n#0 /web/wp-content/plugins/siteorigin-panels/siteorigin-panels.php(92): SiteOrigin_Panels->__construct()\n#1 /web/wp-content/plugins/siteorigin-panels/siteorigin-panels.php(773): SiteOrigin_Panels::single()\n#2 /web/wp-settings.php(409): include_once('/var/www/client...')\n#3 /web/wp-config.php(163): require_once('/var/www/client...')\n#4 /web/wp-load.php(50): require_once('/var/www/client...')\n#5 /web/wp-content/mu-plugins/tools/external-resource.php(12): include_once('/var/www/client...')\n#6 {main}\n  thrown in /web/wp-content/plugins/siteorigin-panels/siteorigin-panels...`

Could this be a problem specific to my installation? I see the "include_path" environmental variable doesn't include the web directory path. Could that be why?

**Comment by AlexGStapleton** [comment]
Hi @MachineITSvcs,

Thank you for reaching out. The reported missing file siteorigin-panels/widgets/less/functions.php [is a valid file](https://github.com/siteorigin/siteorigin-panels/blob/develop/widgets/less/functions.php) and should be able to be included without issue. The included URL has an unexpected `/` but that shouldn't result in the file not being included correctly. The path is also fine. I recommend reinstalling SiteORigin Page Builder to see if that helps.

Beofre proceeding, do a backup.

Navigate to **Plugins > Installed Plugins** and deactivate Page Builder by SiteOrigin, and then delete it. Scroll to the top of the page and click Add New and search for Page Builder by SiteOrigin.

KInd regards,
Alex

**Comment by AlexGStapleton** [comment]
Hi @MachineITSvcs,

It's been a while since we heard from you. I'm going to close this to clear up the issue queue. Let me know if you're still facing this issue and we'll pick this back up. :)

KInd regards,
Alex
