### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by szepeviktor** [siteorigin/siteorigin-panels#99]
A very small hardware server generated the non-Page Builder front page in 266 ms.
After activating Page Builder: 277 ms (+11),
after activating Widgets Bundle: 302 ms (+25).

Could you reduce the code executed on the front-end?
Useful tool: https://wordpress.org/plugins/whats-running/

**Comment by AlexGStapleton** [comment]
With each update, we’re working on improving on general performance improvements/ optimizations in our codebase. Though as this isn’t a once off sort of feature, it’s an ongoing process. So to keep things clean and focused, we’re going to close this to make room for more issues

**Comment by szepeviktor** [comment]
@AlexGStapleton If you pursue performance take a look at the plugin structure of Yoast SEO and BEaver Builder.
